/etc/passwd fixes

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4660,6 +4660,7 @@ check_containeruser() {         # check container user and shared home folder (a
   }
   [ -z "$Containeruserpassword" ] && Containeruserpassword='sac19FwGGTx/A' # password: x11docker
 
+  storeinfo containeruser="$Containeruser"
   store_runoption env "USER=$Containeruser"
   debugnote "container user: $Containeruser $Containeruseruid:$Containerusergid $Containeruserhosthome"
 
@@ -4669,7 +4670,7 @@ check_containeruser() {         # check container user and shared home folder (a
         no)  store_runoption env "XDG_RUNTIME_DIR=/tmp" ;;
       esac
     ;;
-    host)    store_runoption env "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" ;;
+    host) ;;
   esac
   return 0
 }
@@ -4687,14 +4688,14 @@ create_backendcommand() {        ### create command to run docker
   --bind=/etc/host.conf \\
   --bind=/etc/nsswitch.conf \\
   --bind=/etc/resolv.conf \\
-  --bind=/dev/ptmx \\
-  --bind=/dev/pts \\
-  --bind=/dev/tty \\
   --bind=/proc \\
   --bind=/run/shm \\
-  --bind=/dev/shm \\
   --bind=/dev \\
-  --bind=/sys"
+  --bind=/sys" 
+#  --bind=/dev/ptmx \\
+#  --bind=/dev/pts \\
+#  --bind=/dev/tty \\
+#  --bind=/dev/shm \\
   
   Chrootcommand="chroot"
   
@@ -5587,10 +5588,8 @@ Exec=/usr/local/bin/x11docker-xrandr
   echo "Containersystem=\"\$(grep '^ID=' /etc/os-release 2>/dev/null | cut -d= -f2 || echo 'unknown')\""
   echo "verbose \"Container system ID: \$Containersystem\""
   echo ""
-
   echo "# Check container user"
   echo "Containeruser=\"\$(storeinfo dump containeruser)\""
-  echo "Containeruser=\"\${Containeruser:-$Containeruser}\""
   echo ""
   case $Createcontaineruser in
     yes)
@@ -5599,6 +5598,7 @@ Exec=/usr/local/bin/x11docker-xrandr
       # create container user
       echo "# Create user entry in /etc/passwd (and delete possibly existing same uid)"
       echo "cat /etc/passwd | grep -v ':$Containeruseruid:' > /tmp/passwd"             ### FIXME gids same as uid would be deleted, too
+      echo "cat /tmp/passwd | grep -v ':0:0:'               > /tmp/passwd"
       echo ""
       echo "# Disable possible /etc/shadow passwords for other users"
       echo "sed -i 's%:x:%:-:%' /tmp/passwd"
@@ -5606,7 +5606,7 @@ Exec=/usr/local/bin/x11docker-xrandr
         auto) echo "bash --version >/dev/null 2>&1 && Containerusershell=/bin/bash || Containerusershell=/bin/sh" ;;
         *)    echo "Containerusershell='$Containerusershell'" ;;
       esac
-      echo "Containeruserentry=\"$Containeruser:x:$Containeruseruid:$Containerusergid:$Containeruser,,,:$Containeruserhome:\$Containerusershell\""
+      echo "Containeruserentry=\"\$Containeruser:x:$Containeruseruid:$Containerusergid:\$Containeruser,,,:$Containeruserhome:\$Containerusershell\""
       echo 'debugnote "containerrootrc: $Containeruserentry"'
       echo 'echo "$Containeruserentry" >> /tmp/passwd'
       echo 'echo "root:x:0:0:root:/root:$Containerusershell" >> /tmp/passwd'
@@ -5616,7 +5616,7 @@ Exec=/usr/local/bin/x11docker-xrandr
       echo ""
       echo "# Create password entry for container user in /etc/shadow"
       echo "rm -f -v /etc/shadow || warning 'Cannot change /etc/shadow. That may be a security risk.'"
-      echo "echo \"$Containeruser:$Containeruserpassword:17293:0:99999:7:::\" > /etc/shadow"
+      echo "echo \"\$Containeruser:$Containeruserpassword:17293:0:99999:7:::\" > /etc/shadow"
       case $Sudouser in
         "")  echo "echo 'root:*:17219:0:99999:7:::' >> /etc/shadow" ;;
         *)   echo "echo 'root:$Containeruserpassword:17219:0:99999:7:::' >> /etc/shadow  # with option --sudouser, set root password 'x11docker'"
@@ -6503,7 +6503,16 @@ Timetosaygoodbyefile=$(convertpath share $Timetosaygoodbyefile)
 debugnote \"cmdrc: Running container command: 
   $Containerentrypoint $Containercommand\"
 "
-
+    case $Backend in
+      host|chroot)
+        echo "# close additional file descriptors"
+        echo "for i in 3 4 6 7 8 9; do"
+        echo "  { >&\$i ;} 2>/dev/null && exec >&\$i-"
+        echo "done"
+        echo ""
+      ;;
+    esac
+    
     case $Forwardstdin in
       yes) echo "$Containerentrypoint $Containercommand <$(convertpath share $Cmdstdinfifo)" ;;
       no)  echo "$Containerentrypoint $Containercommand" ;;
@@ -7113,8 +7122,8 @@ check_hostuser() {              # check for unprivileged host user
    to choose a host user different from user '$Startuser'."
   }
   getent passwd $Hostuser >/dev/null 2>&1 || {
-    [ -e /etc/passwd ] || warning "Your system misses /etc/passwd"
-    warning "Could not find user '$Hostuser' in /etc/passwd."
+    [ -f /etc/passwd ] || warning "Your system misses /etc/passwd"
+    error "Could not find user '$Hostuser' in /etc/passwd."
   }
   
   Hostuser=$(id -un $Hostuser)
