minor fixes

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="7.2.0-beta-2"
+Version="7.2.0-beta-3"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -3015,7 +3015,7 @@ check_xdepends() {              # check dependencies on host for X server option
     no)
       case "${1:-}" in
         --xpra2*)
-          $Message "${1:-} needs image $Xcontainerimage (option --xc)."
+          $Message "${1:-} needs image x11docker/xserver (option --xc)."
           Return=1
         ;;
       esac
@@ -3274,14 +3274,14 @@ check_xserver() {               # check chosen X server, auto-choose X server
       "")
         error "Did not find a possibility to provide a display.
   Recommendations:
-    Either pull image $Xcontainerimage that provides
+    Either pull image x11docker/xserver that provides
     almost everything that x11docker could use,
     or install 'xinit' and one or all of:
       Xephyr xpra nxagent
     To run with GPU acceleration, install:
       weston and Xwayland, optionally also: xpra and xdotool
     To run from TTY or within Wayland, install:
-      weston and Xwayland
+      Xorg, or weston and Xwayland
   $Wikipackagesimage
 
   These messages from internal dependency checks might be useful:
@@ -7706,19 +7706,19 @@ check_backend() {               # option --backend
       [ "$(id -u)" != "0" ] && Rootlessbackend="yes"
     ;;
   esac
-  
+
   case "$Backend" in
     docker|podman|nerdctl)
       # Check whether docker daemon is running, get docker info
-      Backendinfo="$($Backendbin info --format='{{json .}}' 2>>$Containerlogfile)" || error "'$Backend info' failed.
+      $Backendbin info 1>/dev/null 2>>$Containerlogfile || error "'$Backend info' failed.
   If using docker: Is docker daemon running at all?
   Try to start docker daemon with 'systemctl start docker'.
   Last lines of log:
 $(rmcr < "$Containerlogfile" | tail)"
+      Backendinfo="$($Backendbin info --format='{{json .}}' 2>>$Containerlogfile)"
       check_runtime
     ;;
   esac
-  
   case "$Backend" in
     docker|podman|nerdctl|proot|chroot)
       [ "${Imagename:0:1}" = "/" ] && {
