mkfolder(): new function to create user owned folder

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="7.2.0-beta-6"
+Version="7.2.0-beta-7"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -1031,6 +1031,7 @@ rmcr() {                        # remove carriage return to translate DOS/Window
 }
 timestamp() {                   # print HH:MM:SS,NNN
   date +%T,%N | cut -c1-12
+  return 0
 }
 unspecialstring() {             # replace special chars of $1 with -
   # Replace all characters except those described in "a-zA-Z0-9_" with a '-'.
@@ -1248,6 +1249,19 @@ mkfile() {                      # create file $1 owned by $Hostuser
     chmod "${2:-}" "${1:-}"     || return 1
   }
   return 0
+}
+mkfolder() {                    # create folder $1 owned by $Hostuser
+  local Step Path= Return=
+  for Step in $(tr '/' '\n' <<< "${1:-}" | grep .) ; do
+    Path="$Path/$Step"
+    [ -d "$Path" ] || {
+      unpriv "mkdir -p  '$Path'"  || Return=1
+      chmod "${2:-755}" "$Path"   || Return=1
+    }
+    [ "$Return" ] && break
+  done
+  return ${Return:-0}
+  #unpriv "mkdir -p  '${1:-}'"   || return 1
 }
 myrealpath() {                  # real path of possible symlink
   [ -z "$*" ] && return 1
@@ -1734,7 +1748,7 @@ set_password() {                # option --password: set container user password
     }
   }
   Password="$(perl -e "print crypt(\"$Password\", \"salt\")")"
-  mkdir -p "$(dirname "$Passwordfile")"
+  mkfolder -p "$(dirname "$Passwordfile")"
   echo "$Containeruserpassword" > "$Passwordfile"
   chmod 600                       "$Passwordfile"
   note "Option --password: Password changed, exiting."
@@ -1805,7 +1819,7 @@ check_windowmanager() {         # option --wm: search a host window manager
     cinnamon|cinnamon-session) Windowmanagercommand="cinnamon --sm-disable";;
     compiz) # if none, create minimal config to have usable window decoration and can move windows
       [ -e "$Hostuserhome/.config/compiz-1/compizconfig/Default.ini" ] || {
-        unpriv "mkdir -p '$Hostuserhome/.config/compiz-1/compizconfig'"
+        mkfolder "$Hostuserhome/.config/compiz-1/compizconfig"
         mkfile "$Hostuserhome/.config/compiz-1/compizconfig/Default.ini"
         echo '[core]
 s0_active_plugins = core;composite;opengl;decor;resize;move;
@@ -4995,8 +5009,8 @@ check_containerhome() {         # option --home: check HOME of container user.
     host)
       # if no home folder on host is specified (--home=DIR), create a standard one in ~/.local/share/x11docker
       [ -d "$Persistanthomevolume" ] || {
-        [ "$Startuser" = "root" ] && su "$Containeruser" -c "mkdir -p '$Persistanthomevolume'"
-        [ "$Containeruser" = "$Hostuser" ] && unpriv "mkdir -p '$Persistanthomevolume'" && {
+        #[ "$Startuser" = "root" ] && su "$Containeruser" -c "mkdir -p '$Persistanthomevolume'"
+        [ "$Containeruser" = "$Hostuser" ] && mkfolder "$Persistanthomevolume" && {
           # create symbolic link to ~/x11docker
           echo "$Persistanthomevolume" | grep -q .local/share/x11docker && [ ! -e "$Hostuserhome/x11docker" ] && unpriv "ln -s '$Hosthomebasefolder' '$Hostuserhome/x11docker'" ||:
         }
@@ -8069,7 +8083,7 @@ check_hostuser() {              # check for unprivileged host user
   [ -z "$Hostuserhome" ] && Hostuserhome=$(getent passwd "$Hostuser" 2>/dev/null | cut -d: -f6)
   [ -z "$Hostuserhome" ] && {
     Hostuserhome="/tmp/home/$Hostuser"
-    unpriv "mkdir -p '$Hostuserhome'"
+    mkfolder "$Hostuserhome"
     warning "Could not read your home directory from /etc/passwd for user '$Hostuser'.
   Please set \$HOME with a valid path.
   Fallback: setting HOME=$Hostuserhome"
@@ -8078,7 +8092,7 @@ check_hostuser() {              # check for unprivileged host user
   debugnote "host user: $Hostuser $Hostuseruid:$Hostusergid $Hostuserhome"
   
   Localsharedir="$Hostuserhome/.local/share/x11docker"
-  unpriv "mkdir -p '$Localsharedir'"
+  mkfolder "$Localsharedir"
   Mitshmlib="$Localsharedir/XlibNoSHM.so"
 
   [ "$Hostuser" = "root" ] && warning "Running as user root.
@@ -8197,8 +8211,7 @@ check_xdg_runtime_dir() {       # set up XDG_RUNTIME_DIR if needed
     --weston|--kwin|--weston-xwayland|--kwin-xwayland)
       [ -z "$XDG_RUNTIME_DIR" ] && {
         export XDG_RUNTIME_DIR="$Cachefolder/XDG_RUNTIME_DIR"
-        unpriv "mkdir -p  $XDG_RUNTIME_DIR"
-        unpriv "chmod 700 $XDG_RUNTIME_DIR"
+        mkfolder "$XDG_RUNTIME_DIR" 0700
       }
     ;;
   esac
@@ -8215,7 +8228,7 @@ create_cachefiles() {           # create empty cache files owned by unprivileged
         case "$Mobyvm" in
           yes)
             Cachebasefolder="$(convertpath subsystem "$(wincmd "echo %userprofile%")")/x11docker/cache"
-            unpriv "mkdir -p '$Hostuserhome/.cache/x11docker/symlink'"
+            mkfolder "$Hostuserhome/.cache/x11docker/symlink"
             [ -e "$Hostuserhome/.cache/x11docker/symlink" ] || ln -s -T "$Cachebasefolder" "$Hostuserhome/.cache/x11docker/symlink"
             mkfile "$Hostuserhome/.cache/x11docker/symlink/symlink.txt"
             echo "x11docker: With MobyVM x11docker cache in WSL is stored in
@@ -8239,7 +8252,7 @@ $Hostuserhome/.cache/x11docker/symlink
   Cachebasefolder="$(convertpath subsystem "$Cachebasefolder")"
   [ "$Cachebasefolder" != "${Cachebasefolder//" "/""}" ] && error "Cache root folder must not contain whitespaces.
   $Cachebasefolder"
-  unpriv "mkdir -p '$Cachebasefolder'"                   || error "Could not create cache folder
+  mkfolder "$Cachebasefolder"                            || error "Could not create cache folder
   $Cachebasefolder"
   writeaccess "$Hostuseruid" "$Cachebasefolder"          || error "User $Hostuser does not have write access to cache folder
   $Cachebasefolder"
@@ -8257,7 +8270,7 @@ $Hostuserhome/.cache/x11docker/symlink
     x11docker IMAGENAME  --  sh -c \"cd /etc && xterm\""
 
   Sharefolder="$Cachefolder/$Sharefolder"
-  unpriv "mkdir -p $Sharefolder"
+  mkfolder "$Sharefolder"
 
   # Files in $Cachefolder: host only access
   Backendcommandfile="$Cachefolder/$Backendcommandfile"             && mkfile $Backendcommandfile
@@ -8268,8 +8281,8 @@ $Hostuserhome/.cache/x11docker/symlink
   Watchpidfifo="$Cachefolder/$Watchpidfifo"
   Xservercookie="$Cachefolder/$Xservercookie"                       && mkfile $Xservercookie
   Xtermrc="$Cachefolder/$Xtermrc"                                   && mkfile $Xtermrc
-                                                             unpriv "mkdir -p $Cachefolder/tmp/.X11-unix"
-                                                         unpriv "mkdir -m 700 $Cachefolder/XDG_RUNTIME_DIR"
+                                                                       mkfolder "$Cachefolder/tmp/.X11-unix"
+                                                                       mkfolder "$Cachefolder/XDG_RUNTIME_DIR" 0700
 
   # Files in $Sharefolder: shared to /x11docker in container
   Clipboardrc="$Sharefolder/$Clipboardrc"                           && mkfile $Clipboardrc
@@ -8310,7 +8323,7 @@ $Hostuserhome/.cache/x11docker/symlink
 
   # Files in $Cachebasefolder
   Logfilebackup="$Cachebasefolder/x11docker.log"
-  Modelinefilebasepath="$Cachebasefolder/$Modelinefilebasepath"     && unpriv "mkdir -p $Modelinefilebasepath"
+  Modelinefilebasepath="$Cachebasefolder/$Modelinefilebasepath"     && mkfolder "$Modelinefilebasepath"
 
   # file to store display numbers in use today
   Numbersinusefile="$Cachebasefolder/$Numbersinusefile"
@@ -10516,7 +10529,7 @@ $(nl -ba <$Cmdrc)"
           Source="$(cut -d'|' -f1 <<< "$Line")"
           Target="$(cut -d'|' -f2 <<< "$Line")"
           [ -d "$Source" ] && {
-            mkdir -v -p "$Target"
+            mkfolder "$Target"
             mount --bind "$Source" "$Target" 2>> "$Containerlogfile" || error "--backend=$Backend: mount failed.
   Last lines of log:
 $(tail "$Containerlogfile")"
