`--xpra`, `--xpra-xwayland`: set to highest possible quality transfer

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -422,14 +422,14 @@ verbose() {             # show verbose messages
 debugnote() {           # show debug output $*
   [ "$Debugmode" = "yes" ] && {
     logentry "DEBUGNOTE: $*"
-    [ "$Verbose" = "no" ] && echo "${Colblue}DEBUGNOTE:${Colnorm} $*" >&3
+    [ "$Verbose" = "no" ] && echo "${Colblue}DEBUGNOTE:($(date +%T))${Colnorm} $*" >&3
   } ||:
 }
 logentry() {            # write into logfile
   [ "$Logfile" ] && echo "$*" >>$Logfile ||:
 }
 killpid() {             # kill PID $1 with codename $2 [and process name $3]
-  verbose -d "terminating ${1:-} (${2:-}) ${3:-}: $(ps --no-headers -p ${1:-})"
+  verbose -d "Terminating ${1:-} (${2:-}) ${3:-}: $(ps --no-headers -p ${1:-})"
   ps -p ${1:-} >/dev/null && {
     [ "${3:-}" ] && {
       ps -p ${1:-} | grep -q -E "${3:-}" && kill ${1:-} 2>/dev/null
@@ -440,7 +440,7 @@ killpid() {             # kill PID $1 with codename $2 [and process name $3]
 }
 finish_sigint() {       # trap SIGINT to activate debug mode on finish()
   Debugmode="yes"
-  verbose -d "received SIGINT"
+  verbose -d "Received SIGINT"
   finish
 }
 finish() {              # trap EXIT routine to clean up background processes and cache
@@ -449,8 +449,8 @@ finish() {              # trap EXIT routine to clean up background processes and
   #set -x
   Pid1pid=$(cat $Containerpid1pidfile 2>/dev/null)
 
-  verbose -d "terminating x11docker."
-  checkpid $Pid1pid && verbose -d "process tree of container:
+  verbose -d "Terminating x11docker."
+  checkpid $Pid1pid && verbose -d "Process tree of container:
 $(pstree -p $Pid1pid ||:)"
     
   debugnote "List of stored background processes:
@@ -463,7 +463,7 @@ $(cat $Bgpidfile 2>/dev/null)"
     while read -r Line ; do 
       Pid=$(echo $Line  | awk '{print $1}')
       Name=$(echo $Line | awk '{print $2}')
-      debugnote "checking: $Pid ($Name): $(ps -p $Pid --no-headers ||:)"
+      debugnote "Checking: $Pid ($Name): $(ps -p $Pid --no-headers ||:)"
       checkpid $Pid && {        
         case $Name in
           xinit)                  killpid $Pid $Name xinit ;;
@@ -596,7 +596,7 @@ watchpidlist() {        # watch list of important pids
     read -t1 Pid <&9 ||:
     [ "$Pid" ] && {
       Watchpidlist="$Watchpidlist $Pid"
-      debugnote "watching $(ps --no-headers -p $Pid)"
+      debugnote "Watching $(ps --no-headers -p $Pid)"
     }
     for Pid in $Watchpidlist; do
       [ -e /proc/$Pid ] || {
@@ -666,9 +666,9 @@ waitforfilecreation() { # similar to inotify-wait: wait up to 15s for file $1 to
   ${1:-}"
       return 1
     }
-    verbose "waiting since ${Dauer}s for ${1:-} to be created, will wait up to $Warten seconds."
+    verbose "Waiting since ${Dauer}s for ${1:-} to be created, will wait up to $Warten seconds."
     rocknroll || {
-      verbose -d "stopped waiting for ${1:-} due to terminating signal."
+      verbose -d "Stopped waiting for ${1:-} due to terminating signal."
       return 1
     }
   done
@@ -690,9 +690,9 @@ waitforfilecontent() {  # wait for file $1 to be not empty
     Dauer=$(( $(date +%s) - $Zeit ))
     sleep $(awk "BEGIN { print $Count * 0.1 }")
     [ $Warten -lt $Dauer ]  && return 1
-    verbose "waiting since ${Dauer}s for ${1:-} to have content, will wait up to $Warten seconds."
+    verbose "Waiting since ${Dauer}s for ${1:-} to have content, will wait up to $Warten seconds."
     rocknroll || {
-      verbose -d "stopped waiting for file content of ${1:-} due to terminating signal."
+      verbose -d "Stopped waiting for file content of ${1:-} due to terminating signal."
       return 1
     }  done
   verbose "Found file content in ${1:-}"
@@ -717,12 +717,12 @@ $(grep -i -E 'error|failed|fatal'  <"${2:-}")"
 
     Count=$(( Count + 1 ))
     Dauer=$(( $(date +%s) - $Zeit ))
-    verbose -d "waiting since ${Dauer}s for ${1:-} to be ready..."
+    verbose "Waiting since ${Dauer}s for ${1:-} to be ready..."
     sleep $(awk "BEGIN { print $Count * 0.1 }")
     [ $Warten -lt $Dauer ] && return 1
     
     rocknroll || {
-      verbose -d "stopped waiting for logentry in ${2:-} of ${1:-} due to terminating signal."
+      verbose -d "Stopped waiting for logentry in ${2:-} of ${1:-} due to terminating signal."
       return 1
     }
   done
@@ -735,7 +735,7 @@ storepid () {           # store pid $1 and name $2 of background process in file
   # for use on exit / with trap to clean up with background processes
   # this subroutine has a twin in xinitrc
   echo ${1:-} ${2:-} >> $Bgpidfile
-  verbose -d "stored background pid ${1:-} of ${2:-}"
+  verbose -d "Stored background pid ${1:-} of ${2:-}"
   disown ${1:-} 2>/dev/null ||:
 }
 checkpid() {            # check if PID $1 is active
@@ -859,7 +859,7 @@ depends() {             # check dependencies on host for X server option $1
     ;;
   esac
   
-  debugnote "dependency check for ${1:-}: ${Return:-0}"
+  debugnote "Dependency check for ${1:-}: ${Return:-0}"
   [ "$Return" = "1" ] && {
     $Message "${1:-} not possible: missing dependencies."
     Autochooseserver="yes"
@@ -2254,6 +2254,8 @@ $(cowsay "$Wisdom" 2>/dev/null || echo "Wanda the fish says: $Wisdom")"
       [ "$Desktopmode" = "no" ] && note "xpra startup is rather slow. For faster startup
   with seamless applications,   try --nxagent.
   If security is not a concern, try --hostdisplay."
+      [ "$Gpu" = "yes" ] && note "If performance of GPU acceleration with $Xserver
+  is not satisfying, you can try insecure '--hostdisplay --gpu'."
     ;;
     
     --xephyr) note "Xephyr is a quite stable nested X server.
@@ -3070,7 +3072,7 @@ fi
   case $Xserver in
     --nxagent)
       { [ "$Sharehostipc" = "yes" ] || [ "$X11dockermode" = "exe" ] ; } && Xserveroptions="$Xserveroptions -shmem -shpix" || Xserveroptions="$Xserveroptions -noshmem -noshpix"
-# fixes issues with e.g. enlightenment, causes issues with e.g. xfce4-terminal. Development in nx-libs is in progress.
+#      # fixes issues with e.g. enlightenment, causes issues with e.g. xfce4-terminal. Development in nx-libs is in progress.
 #      Xserveroptions="$Xserveroptions \\
 #  +extension Composite"
     ;;
@@ -3171,8 +3173,10 @@ fi
       [ -n "$Dpi" ] && verlt "$Xpraversion" "xpra v2.1-r16547" && ! verlt "$Xpraversion" "xpra v2.1" &&  Dpi=""
       # disable proxy for high versions
       verlt "$Xpraversion" "xpra v2.1" || Xpraoptions="$Xpraoptions --start-via-proxy=no"
-      # disable sound transfer, --pulseaudio works different
-      Xpraoptions="$Xpraoptions -z0 --no-speaker --no-pulseaudio"
+      # disable sound transfer, --pulseaudio and --alsa work different
+      Xpraoptions="$Xpraoptions --no-speaker --no-pulseaudio"
+      # no compression, best quality
+      Xpraoptions="$Xpraoptions -z0 --quality 100"
       # disable possibly leaking options
       Xpraoptions="$Xpraoptions --daemon=no --fake-xinerama=no --notifications=no --file-transfer=off --printing=no --html=off --systemd-run=no --mdns=no"
       [ "$Fullscreen" = "yes" ]  && Xpraoptions="$Xpraoptions --desktop-fullscreen=yes"
@@ -3299,7 +3303,7 @@ $(tail "$Compositorlogfile")"
     ;;
     
     --xpra-xwayland|--xdummy-xwayland)
-      Xcommand="$(command -v Xwayland) $Newdisplay \\
+      Xcommand="$(command -v Xwayland) $Newdisplay -rootless\\
   $Xserveroptions"
       [ -z "$Hostwaylandsocket" ] && Newwaylandsocket="wayland-$Newdisplaynumber" || {
         Newwaylandsocket="$Hostwaylandsocket"
@@ -4156,7 +4160,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "$Messagefifofuncs"
   echo "exec 3<>$Sharefolder/message.fifo"
   echo ""
-  echo "verbose -d 'running dockerrc'"
+  echo "verbose -d 'Running dockerrc'"
 
   [ "$Debugmode" = "yes" ] && {
     echo "PS4='$DebugPS4'"
@@ -4326,7 +4330,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
     echo "  echo '[ -z \"\$Dbus\" ] && Dbus=\"\$(dbus-run-session --help >/dev/null 2>&1 && echo dbus-run-session)\"'"
     echo "  echo '[ -z \"\$Dbus\" ] && warning \"Did not find dbus-launch or dbus-run-session. (option --dbus).\"'"
   } 
-  echo   "  echo 'verbose -d \"running dbus user session with: \${Dbus:-(none)}\"'"
+  echo   "  echo 'verbose -d \"Running dbus user session with: \${Dbus:-(none)}\"'"
   echo   "  echo ''"
   echo   '  echo "[ -e \"\$XDG_RUNTIME_DIR\" ] || {"'
   echo   "  echo '  export XDG_RUNTIME_DIR=/tmp/XDG_RUNTIME_DIR'"
@@ -4444,7 +4448,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   ##########################
 
   echo ""
-  echo "verbose -d \"container ID: \$Containerid\""
+  echo "verbose -d \"Container ID: \$Containerid\""
   echo "[ \"\$Containerid\" ] || error \"Startup of docker failed. Did not receive a container ID.
   
   Last lines of container log:
@@ -4467,15 +4471,15 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo ""
 
   echo "docker inspect --format '{{ .NetworkSettings.IPAddress }}' $Containername >> $Containeripfile"
-  echo "verbose -d \"container IP: \$(cat $Containeripfile)\""
+  echo "verbose -d \"Container IP: \$(cat $Containeripfile)\""
   echo ""
   echo "docker inspect --format '{{.State.Pid}}' $Containername >> $Containerpid1pidfile"
-  echo "verbose -d \"host PID of container PID 1: \$(cat $Containerpid1pidfile)\""
+  echo "verbose -d \"Host PID of container PID 1: \$(cat $Containerpid1pidfile)\""
   [ "$Showcontainerpid1pid" = "yes" ] && echo "stdout \"\$(cat $Containerpid1pidfile)\""
   echo ""
   echo "# get PID of container"
   echo "Containerpid=\$(ps ax | grep \$Containerid | grep -v grep | grep -v ' logs' | awk '{print \$1}')"
-  echo "verbose -d \"container PID: \$Containerpid\""
+  echo "verbose -d \"Container PID: \$Containerpid\""
   echo "echo \$Containerpid >> $Containerpidfile"
   echo ""
   # container.CMD.sh will wait until setup script is ready
@@ -4494,7 +4498,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "exec 3<>$Cshare/message.fifo"
   echo ""
 
-  echo "verbose -d 'setup as root in container'"
+  echo "verbose -d 'Running setup as root in container'"
   
   # check type of libc
   echo "ldd --version 2>&1 | grep -q 'musl libc' && Containerlibc='musl'"
@@ -4967,11 +4971,11 @@ exit 0' >> /etc/rc.local"
   echo "exec 3<>$Messagefifo"
   echo ""
   
-  echo "verbose -d 'running xinitrc'"
+  echo "verbose -d 'Running xinitrc'"
 
   [ "$Noxhost" = "yes" ] && [ -n "$Hostdisplay" ] && {  
     echo "export $Hostxenv"
-    echo 'verbose -d "option --no-xhost: disabling any access to host display $DISPLAY granted by xhost"'
+    echo 'verbose -d "Option --no-xhost: disabling any access to host display $DISPLAY granted by xhost"'
     echo "no_xhost"
   }
 
@@ -5118,14 +5122,15 @@ exit 0' >> /etc/rc.local"
       echo "xrandr --addmode \$Output $(echo $Modeline | cut -d " " -f1)"
       echo "xrandr --output  \$Output --mode $(echo $Modeline | cut -d " " -f1)"
       
-      
-      echo "for Ycount in 25 30 40 45 50 55 60 65 70 75 80 85 90 95 100; do"
-      echo "  for Xcount in 25 30 40 45 50 55 60 65 70 75 80 85 90 95 100; do"
-      echo "    Modeline=\$(cvt \$(awk -v a=$Maxxaxis -v b=\$Xcount 'BEGIN {print (a * b / 100)}') \$(awk -v a=$Maxyaxis -v b=\$Ycount 'BEGIN {print (a * b / 100)}') | tail -n1 | cut -d' ' -f2- | tr -d '\"')"
-      echo "    xrandr --newmode \$Modeline"
-      echo "    xrandr --addmode \$Output \$(echo \$Modeline | cut -d' ' -f1)"
-      echo "  done"
-      echo "done 2>&1 | uniq"
+      [ "$Desktopmode" = "yes" ] && ! command -v Xvfb >/dev/null && {
+        echo "for Ycount in 25 30 40 45 50 55 60 65 70 75 80 85 90 95 100; do"
+        echo "  for Xcount in 25 30 40 45 50 55 60 65 70 75 80 85 90 95 100; do"
+        echo "    Modeline=\$(cvt \$(awk -v a=$Maxxaxis -v b=\$Xcount 'BEGIN {print (a * b / 100)}') \$(awk -v a=$Maxyaxis -v b=\$Ycount 'BEGIN {print (a * b / 100)}') | tail -n1 | cut -d' ' -f2- | tr -d '\"')"
+        echo "    xrandr --newmode \$Modeline"
+        echo "    xrandr --addmode \$Output \$(echo \$Modeline | cut -d' ' -f1)"
+        echo "  done"
+        echo "done 2>&1 | uniq"
+      }
 
       ! verlt "$Xpraversion" "xpra v2.3" && verlt "$Xprarelease" "r19606" && {
         warning "Your xpra version has a cookie authentication issue.
@@ -5357,7 +5362,7 @@ Keywords=docker x11docker $(echo $Name | tr -c '[:alpha:][:digit:][:blank:]' ' '
   Zeit=$(date +%s)
   Count=0
   Dauer=0
-  verbose "Waiting for X server $Xserver to be ready."
+  verbose -d "Waiting for X server $Xserver to be ready."
   while [ ! -e "$Cachefolder/Xready" ] ; do
     Count=$(( Count + 1 ))
     Dauer=$(( $(date +%s) - $Zeit ))
@@ -5379,28 +5384,20 @@ $(tail $Compositorlogfile)")"
   mkfile "$Cachebasefolder/Xenv.latest"
   for Line in $Newxenv ; do echo $Line >> "$Cachebasefolder/Xenv.latest" ; done
   
-  # watch X server and/or Wayland compositor
-  Compositorpid=$(cat $Compositorpidfile)
+  # check and watch compositor
   case $Xserver in
-    --nothing|--hostwayland|--hostdisplay) ;;
-    --weston|--kwin)
-      {  # catch closing compositor window
-        sleep 1
-        checkpid $Compositorpid && setonwatchpidlist $Compositorpid || error "Startup of compositor failed.
+    --weston|--kwin|--weston-xwayland|--kwin-xwayland|--xpra-xwayland|--xdummy-xwayland)
+      Compositorpid=$(cat $Compositorpidfile)
+      checkpid $Compositorpid && setonwatchpidlist $Compositorpid || error "Startup of compositor failed.
   Last lines of compositor log:
 $(tail $Compositorlogfile)"
-      } && waitfortheend & storepid $! waitfortheend
+      storepid $Compositorpid compositor
     ;;
-    --weston-xwayland|--kwin-xwayland|--xpra-xwayland|--xdummy-xwayland)
-      {  # catch closing X server or compositor window
-        sleep 1
-        checkpid $Compositorpid && setonwatchpidlist $Compositorpid || error "Startup of compositor or X failed.
-  Last lines of compositor log:
-$(tail $Compositorlogfile)"
-      } && waitfortheend & storepid $! waitfortheend
-    ;;
-    *)
-      # catch closing X server
+  esac
+  
+  # check and watch X server
+  case $Xserver in
+    --xpra|--xephyr|--nxagent|--xvfb|--xdummy|--weston-xwayland|--kwin-xwayland|--xpra-xwayland|--xdummy-xwayland)
       Xinitpid="$(pgrep -a xinit | grep "xinit $Xinitrc" | awk '{print $1}')"
       [ "$Xinitpid" ] && setonwatchpidlist $Xinitpid && storepid $Xinitpid xinit
       echo $Xcommand | grep -q Xorgwrapper && Line="Xorg $Newdisplay" || Line=$Xcommand
@@ -5419,7 +5416,7 @@ $(tail $Compositorlogfile)"
       [ "$Desktopmode" = "yes" ] && Xpraservercommand="xpra start-desktop" || Xpraservercommand="xpra start"
       Xpraservercommand="$Xpraservercommand $Newdisplay --use-display $Xpraoptions"
       #Xpraservercommand="xpra start $Newdisplay --use-display --start-via-proxy=no --daemon=no"
-      Xpraclientcommand="xpra attach $Newdisplay $Xpraoptions --window-close=shutdown"
+      Xpraclientcommand="xpra attach $Newdisplay $Xpraoptions --window-close=shutdown --title '@title@ ($Imagename)'"
       #Xpraclientcommand="xpra attach $Newdisplay --start-via-proxy=no --window-close=shutdown"
       verbose "Xpra server command:
   $Xpraservercommand"
@@ -5459,21 +5456,18 @@ $(tail $Xpraserverlogfile)"
             notify-send "x11docker: xpra server crashed. Restarting xpra now."
             mkfile $Xpraserverlogfile   # clear logfile to remove "xpra is ready" message
           }
-          verbose -d "starting Xpra server"
+          verbose -d "Starting Xpra server"
           $Mksu "env $Newxenv XPRA_OPENGL_DOUBLE_BUFFERED=1 $Xpraservercommand" >> $Xpraserverlogfile 2>&1 &
           Xpraserverpid=$!
           storepid $Xpraserverpid xpraserver
           waitforlogentry "xpra server" $Xpraserverlogfile 'xpra is ready' && verbose "Xpra server is ready" || {
             [ -e "$Xpraserverlogfile" ] && error "Xpra server startup failed.
   Last lines of Xpra server log:
-$(tail $Xpraserverlogfile)
-
-  Last lines of docker log:
-$(tail $Containerlogfile)"
+$(tail $Xpraserverlogfile)"
           }
         }
         checkpid $Xpraclientpid && kill $Xpraclientpid
-        verbose -d "starting Xpra client"
+        verbose -d "Starting Xpra client"
         [ -n "$Xpraclientpid" ] && note "Restarting Xpra client."
         $Mksu "env $Hostxenv XPRA_PADDING_COLORS='0,0.2,1' $Xpraclientcommand" >> $Xpraclientlogfile 2>&1 &
         Xpraclientpid=$!
@@ -5566,7 +5560,7 @@ $(tail $Logfile)"
       [ "$Showcontainerpid1pid" = "yes" ] && echo $Hostexepid
       echo $Hostexepid >>$Containerpid1pidfile
 
-      debugnote "pstree of $Hostexe:
+      debugnote "Process tree of $Hostexe:
 $(pstree -p $Hostexepid)"
       
       storepid $Hostexepid hostexe
@@ -5602,7 +5596,6 @@ $(pstree -p $$)"
         waitforlogentry weston $Compositorlogfile "weston-desktop-shell"                       || error "Weston startup failed. Can not run $Xserver.
   Last lines of weston log:
 $(tail $Compositorlogfile)"
-        storepid $(cat $Compositorpidfile) compositor
         # hide weston window
         $Mksu "xdotool windowunmap 0x$(printf '%x\n' $(grep 'window id' $Compositorlogfile | rev | cut -d' ' -f1 | rev))"
       }
@@ -5614,7 +5607,6 @@ $(tail $Compositorlogfile)"
       waitforlogentry weston $Compositorlogfile "weston-desktop-shell"                         || error "Weston startup failed. Can not run $Xserver.
   Last lines of weston log:
 $(tail $Compositorlogfile)"
-      storepid $(cat $Compositorpidfile) compositor
       $Mksu "exec env WAYLAND_DISPLAY=$Newwaylandsocket   xinit $Xinitrc -- $Xcommand          >> $Xinitlogfile  2>&1 " 
     ;;
     --weston)
@@ -5623,7 +5615,6 @@ $(tail $Compositorlogfile)"
       waitforlogentry weston $Compositorlogfile "weston-desktop-shell"                         || error "Weston startup failed. Can not run $Xserver.
   Last lines of weston log:
 $(tail $Compositorlogfile)"
-      storepid $(cat $Compositorpidfile) compositor
       $Mksu "exec                                         bash  $Xinitrc                       >> $Xinitlogfile  2>&1" 
     ;;
     --kwin-xwayland)
@@ -5632,8 +5623,7 @@ $(tail $Compositorlogfile)"
       waitforlogentry kwin   $Compositorlogfile "X-Server"                                     || error "Kwin startup failed. Can not run $Xserver.
   Last lines of kwin log:
 $(tail $Compositorlogfile)"
-      storepid $(cat $Compositorpidfile) compositor
-      $Mksu "env WAYLAND_DISPLAY=$Newwaylandsocket        xinit $Xinitrc -- $Xcommand          >> $Xinitlogfile  2>&1 " 
+      $Mksu "exec env WAYLAND_DISPLAY=$Newwaylandsocket   xinit $Xinitrc -- $Xcommand          >> $Xinitlogfile  2>&1 " 
     ;;
     --kwin)
       $Mksu "dbus-launch $Compositorcommand                                                    >> $Compositorlogfile 2>&1 & echo \$! >>$Compositorpidfile"
@@ -5641,11 +5631,10 @@ $(tail $Compositorlogfile)"
       waitforlogentry kwin   $Compositorlogfile "X-Server"                                     || error "Kwin startup failed. Can not run $Xserver.
   Last lines of kwin log:
 $(tail $Compositorlogfile)"
-      storepid $(cat $Compositorpidfile) compositor
-      $Mksu                                              "bash  $Xinitrc                       >> $Xinitlogfile  2>&1 " 
+      $Mksu "exec                                         bash  $Xinitrc                       >> $Xinitlogfile  2>&1 " 
     ;;
     --nothing)
-      $Mksu                                              "bash  $Xinitrc                       >> $Xinitlogfile  2>&1 " 
+      $Mksu "exec                                         bash  $Xinitrc                       >> $Xinitlogfile  2>&1 " 
     ;;
   esac
   
