docker-for-win: adjustments for runx

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -55,8 +55,9 @@ Dependencies on host:
   It will check for them on startup and show messages if some are missing.
   Core list of recommended packages:
    * Recommended to allow security and convenience:
-       X servers: Xephyr xpra nxagent (on Windows: Cygwin/X or WSL with runx)
+       X servers: Xephyr xpra nxagent
        X tools:   xauth xclip xrandr xhost xinit
+       On MS Windows also install runx:  https://github.com/mviereck/runx
    * Advanced GPU support: weston Xwayland xpra xdotool
   See also: https://github.com/mviereck/x11docker/wiki/Dependencies
 
@@ -193,29 +194,29 @@ X and Wayland appearance options:
      --border[=COLOR]  Draw a colored border in windows from --xpra[-xwayland].
                        Optional COLOR can be e.g. 'orange' or '#F00'. Thickness
                        can be specified, too, e.g. 'red,3'. Default: 'blue,1'
+     --dpi N           dpi value (dots per inch) to submit to clients.
+                       Influences font size of some applications.
  -f, --fullscreen      Run in fullscreen mode.
-     --size XxY        Screen size of new X server (e.g. 800x600).
      --scale N         Scale/zoom factor N for xpra, Xorg or Weston.
                        Allowed for --xpra, --xorg --xpra-xwayland: 0.25...8.0.
                        Allowed for --weston and --weston-xwayland: 1...9.
                        (Mismatching font sizes can be adjusted with --dpi).
+     --size XxY        Screen size of new X server (e.g. 800x600).
+     --output-count N  Multiple virtual monitors for Weston, KWin or Xephyr.
      --rotate N        Rotate display (--xorg, --weston and --weston-xwayland)
                        Allowed values: 0, 90, 180, 270, flipped, flipped-90,
                        flipped-180, flipped-270.  (flipped means mirrored)
-     --dpi N           dpi value (dots per inch) to submit to clients.
-                       Influences font size of some applications.
-     --output-count N  Multiple virtual monitors for Weston, KWin or Xephyr.
      --xfishtank       Show fish tank on new X server.
 
-X and Wayland configuration:
-     --xhost STR       Set \"xhost STR\" on new X server (see 'man xhost').
-                       (Use with care. '--xhost +' allows access for everyone).
-     --no-auth         Allow access to X for everyone. Security risk!
+X and Wayland special configuration:
      --display N       Use display number N for new X server.
-     --vt N            Use vt / tty N (regarded by --xorg only).
      --keymap LAYOUT   Set keyboard layout for new X server, e.g. de, us, ru.
                        For possible LAYOUT look at /usr/share/X11/xkb/symbols.
+     --no-auth         Allow access to X for everyone. Security risk!
+     --vt N            Use vt / tty N (regarded by --xorg only).
      --westonini FILE  Custom weston.ini for --weston and --weston-xwayland.
+     --xhost STR       Set \"xhost STR\" on new X server (see 'man xhost').
+                       (Use with care. '--xhost +' allows access for everyone).
 
 User settings:
      --sudouser        Allow su and sudo for container user. Use with care,
@@ -227,7 +228,7 @@ User settings:
                        Special case: --user=RETAIN keeps image user settings.
      --hostuser USER   Run X (and container user) as user USER. Default is
                        result of \$(logname). (x11docker must run as root).
-     --group-add GROUP Additional group GROUP for container user.
+     --group-add GROUP Add container user to group GROUP.
 
 Init system and DBus daemon:
      --init[=INITSYSTEM]  Run an init system as PID 1 in container. Solves the
@@ -237,11 +238,11 @@ Init system and DBus daemon:
                        Special: systemd, sysvinit, runit, openrc, s6-overlay.
                        The special init systems include option --dbus-system.
      --sharecgroup     Share /sys/fs/cgroup. Allows elogind in container if
-                       used with --dbus-system or init options.
- -b, --dbus            Run DBus user session daemon for image command.
+                       used with --dbus-system or special --init options.
+     --dbus            Run DBus user session daemon for image command.
      --dbus-system     Run DBus system daemon in container (includes --dbus).
                        Rather use one of --init=systemd|openrc|sysvinit|runit
-     --hostdbus        Connect to DBus session from host.
+     --hostdbus        Connect to DBus user session from host.
 
 Container capabilities:
   Custom capabilities can be added with --cap-add=CAP after  --
@@ -778,7 +779,7 @@ rmcr() {                        # remove carriage return to translate DOS/Window
   # convert stdin if $1 is empty. Otherwise convert file $1.
   case "${1:-}" in
     "") sed    "s/$(printf "\r")//g" ;;
-    *)  sed -i "s/$(printf "\r")//g"  "${1:-}"
+    *)  sed -i "s/$(printf "\r")//g"  "${1:-}" ;;
   esac
 }
 download() {                    # download file at URL $1 and store it in file $2
@@ -1821,9 +1822,15 @@ check_xserver() {               # check chosen X server, auto-choose X server
     To run from TTY or within Wayland, install:
       weston and Xwayland" ;;
       CYGWIN)    error "Did not find a possibility to provide a display.
-  Please install XWin (xinit package) and xwininfo in Cygwin." ;;
-      MSYS2|WSL) error "Did not find a possibility to provide a display.
-  Please provide an X server with runx. https://github.com/mviereck/runx" ;;
+  Please install packages xinit, xauth and xwininfo in Cygwin." ;;
+      MSYS2|WSL) [ "$Hostdisplay" ] && {
+          error "Did not find a possibility to provide a nested display.
+  Please install xinit and one or all of:  nxagent Xephyr xpra"
+        } || {
+        error "Did not find a possibility to provide a display.
+  Please provide an X server with runx: https://github.com/mviereck/runx" 
+        }
+      ;;
     esac
   }
 
@@ -1966,9 +1973,9 @@ check_xdepends() {              # check dependencies on host for X server option
       [ "$Return" = "1" ] || {
         # check xpra version
         [ "$Xpraversion" ] || {
-          Xpraversion="$(xpra --version)"
+          Xpraversion="$(xpra --version 2>/dev/null)"
           Xprarelease="$(echo $Xpraversion | cut -s -d- -f2)"
-          verbose "Xpra version: $Xpraversion"
+          verbose "Xpra version: ${Xpraversion:-XPRA_NOT_FOUND}"
         }
         ! verlte "$Xprarelease" "r18663" && verlte $Xprarelease "r19519" && {
           [ "$Sharehostipc" = "no" ] && {
@@ -2017,7 +2024,6 @@ check_screensize() {            # check physical and virtual screen size (also o
       Maxyaxis=$(echo "$Line" | cut -dx -f2 | cut -d ' ' -f1)
     }
     [ -z "$Maxxaxis" ] && command -v xwininfo >/dev/null && {
-#      Line="$(xwininfo -root -stats | rmcr)"
       Line="$(xwininfo -root -stats)"
       Maxxaxis=$(echo "$Line" | grep Width  | rev | cut -d' ' -f1 | rev)
       Maxyaxis=$(echo "$Line" | grep Height | rev | cut -d' ' -f1 | rev)
@@ -2131,17 +2137,17 @@ disable_xhost() {               # remove any access to X server granted by xhost
   $Wikipackages"
     return 1
   }
-  xhost 2>&1 | rmcr | tail -n +2  /dev/stdin | while read -r Line ; do  # read all but the first line (header)
+  xhost 2>&1 | tail -n +2  /dev/stdin | while read -r Line ; do  # read all but the first line (header)
     verbose -d "xhost: Removing entry $Line"
-    xhost -$Line | rmcr                                  # disable every entry
+    xhost -$Line                                  # disable every entry
   done
-  xhost - | rmcr                                         # enable access control
-  [ "$(xhost 2>&1 | rmcr | wc -l)" -gt "1" ] && {
+  xhost -                                         # enable access control
+  [ "$(xhost 2>&1 | wc -l)" -gt "1" ] && {
     warning "Remaining xhost permissions found on display ${DISPLAY:-}
-$(xhost 2>&1 | rmcr)"
+$(xhost 2>&1 )"
     return 1
   }
-  xhost 2>&1 | rmcr | grep "access control disabled" && {
+  xhost 2>&1 | grep "access control disabled" && {
     warning "Failed to restrict xhost permissions.
   Access to display ${DISPLAY:-} is allowed for everyone." 
     return 1
@@ -2978,17 +2984,10 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
   echo ""
 
   echo "export PATH='${PATH:-}'"
+  echo "export $Newxenv"
 
   echo "verbose -d 'Running xinitrc'"
 
-  [ "$Noxhost" = "yes" ] && [ -n "$Hostdisplay" ] && {
-    echo "export $Hostxenv"
-    echo 'verbose -d "Option --no-xhost: disabling any access to host display $DISPLAY granted by xhost"'
-    echo 'disable_xhost || warning "Option --no-xhost failed. Output of xhost:'
-    echo '$(xhost 2>&1 | rmcr)"'
-  }
-
-  echo "export $Newxenv"
 
   case $Xserver in
     --weston|--kwin|--hostwayland) echo "unset DISPLAY XAUTHORITY" ;;
@@ -3012,7 +3011,7 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
             [ "$Trusted" = "yes" ] && Trusted="trusted" || Trusted="untrusted"
             [ "$Xserver" = "--hostdisplay" ] && {
               [ -s "$Hostxauthority" ] && echo "export XAUTHORITY=$Hostxauthority"
-              echo   "xhost | rmcr | grep -q 'SI:localuser:$Hostuser' || { xhost +SI:localuser:$Hostuser | rmcr ; Xhostentry='yes' ; }"
+              echo   "xhost | grep -q 'SI:localuser:$Hostuser' || { xhost +SI:localuser:$Hostuser ; Xhostentry='yes' ; }"
             }
             case "$Hostssh" in
               no)
@@ -3054,7 +3053,7 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
         echo         "cp $Xclientcookie $Xservercookie"
         echo         "[ -s '$Xclientcookie' ] || warning 'Cookie creation failed!'"
         echo         "chmod 644 $Xclientcookie"
-        [ "$Xserver" = "--hostdisplay" ] && echo "[ '\$Xhostentry' = 'yes' ] && env XAUTHORITY=$Hostxauthority xhost -SI:localuser:$Hostuser | rmcr"
+        [ "$Xserver" = "--hostdisplay" ] && echo "[ '\$Xhostentry' = 'yes' ] && env XAUTHORITY=$Hostxauthority xhost -SI:localuser:$Hostuser"
         [ "$Xserver" = "--nxagent" ]     && echo "rm $Xclientcookie.bak"
       }
       echo           "export XAUTHORITY=$Xclientcookie"
@@ -3062,7 +3061,7 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
 
       case "$Xserver" in
         --hostdisplay) ;;   # do not change host settings
-        --xwin) ;; # xhost does not work over tcp
+        --xwin) ;;          # xhost does not work over tcp (?)
         *)
           case $Xauthentication in
             yes)
@@ -3073,14 +3072,14 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
 
           [ -n "$Xhost" ] && {
             echo "verbose 'Custom xhost setting on $Newdisplay (option --xhost): $Xhost'"
-            echo "xhost $Xhost | rmcr"
+            echo "xhost $Xhost"
           }
 
           [ "$Initsystem" = "systemd" ] || [ "$Dbussystem" = "yes" ] && {
             echo "note 'Allowing xhost access for $Containeruser on display $Newdisplay"
             echo "  to avoid service issues with X access. (option --init=systemd or --dbus-system):"
             echo "    xhost +SI:localuser:$Containeruser'"
-            echo "xhost +SI:localuser:$Containeruser | rmcr"
+            echo "xhost +SI:localuser:$Containeruser"
           }
         ;;
       esac
@@ -3103,7 +3102,7 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
             echo "# set keyboard layout on $Newdisplay to same as on host"
             echo "echo 'x11docker: keyboard layout:'"
             echo "cat $Xkbkeymapfile"
-            echo "xkbcomp $Xkbkeymapfile $Newdisplay | rmcr"
+            echo "xkbcomp $Xkbkeymapfile $Newdisplay"
           }
         ;;
       esac
@@ -3154,7 +3153,7 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
   Recommended: Downgrade to xpra v2.2.5, upgrade to at least r19606,
   or use another X server option.
   Fallback: Setting 'xhost +SI:localuser:$Containeruser'"
-        echo "xhost +SI:localuser:$Containeruser | rmcr"
+        echo "xhost +SI:localuser:$Containeruser"
       } ;;
   esac
   
@@ -3378,7 +3377,7 @@ check_containerhome() {         # options --home, --homedir, --homebasedir: chec
   }
   [ "$Homebasefolder" ] || case $Winsubsystem in ### FIXME 
     "") Homebasefolder="$Containeruserhome/.local/share/x11docker" ;;
-    *)  Homebasefolder="$(convertpath --subsystem "$(cmd.exe /C "echo %userprofile%" | rmcr)")/x11docker/home" ;;
+    *)  Homebasefolder="$(convertpath --subsystem "$(wincmd '/C "echo %userprofile%"' | rmcr)")/x11docker/home" ;;
   esac
   
   [ "$Sharehosthome" = "yes" ] && {
@@ -3959,12 +3958,11 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
 
   echo "# check whether docker daemon is running, get docker info"
   echo "$Dockerexe info >>$Dockerinfofile 2>>$Containerlogfile  || {
-    rmcr '$Containerlogfile'
     error \"Calling docker daemon failed.
   Is docker daemon running at all?
   Try to start docker daemon with:   systemctl start docker
   Last lines of log:
-\$(tail $Containerlogfile)\"
+\$(rmcr < '$Containerlogfile' | tail)\"
 }"
   echo ""
 
@@ -4137,7 +4135,6 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
     echo "while read -r Line; do"
     echo "  echo export \$(escapestring \"\$Line\")      >> $Imagecommandscript"
     echo "done < <($Dockerexe run --rm --entrypoint env $Imagename env 2>>$Containerlogfile| rmcr)"
-    #echo "rmcr '$Containerlogfile'"
     echo "IFS=$' \t\n'"
     echo ""
   }
@@ -4361,11 +4358,10 @@ $Wmdockercommand"'
   echo ""
   echo "verbose -d \"Container ID: \$Containerid\""
   echo "[ \"\$Containerid\" ] || {
-    #rmcr '$Containerlogfile'
     error \"Startup of docker failed. Did not receive a container ID.
     
   Last lines of container log:
-\$(tail $Containerlogfile)\"
+\$(rmcr < $Containerlogfile | tail)\"
 }"
   echo "echo \$Containerid >> $Containeridfile"
   [ "$Showcontainerid" = "yes" ] && echo "stdout \"\$(cat $Containeridfile)\""
@@ -4392,7 +4388,7 @@ $Wmdockercommand"'
   echo "verbose -d \"Container IP: \$(cat $Containeripfile)\""
   echo ""
   
-  echo "Failure=\"\$(cat $Containerlogfile | rmcr | grep -v grep | grep -E 'Error response from daemon|OCI runtime exec' ||:)\""
+  echo "Failure=\"\$(rmcr < $Containerlogfile | grep -v grep | grep -E 'Error response from daemon|OCI runtime exec' ||:)\""
   echo "[ \"\$Failure\" ] && {"
   echo "  echo \"\$Failure\" >>$Containerlogfile"
   echo "  error \"Got error message from docker daemon:
@@ -5391,9 +5387,8 @@ $(tail $Compositorlogfile)"
 start_xserver() {               # start X server
   local Xserverpid= Tasklistnew= Tasklistold= 
   case $Xserver in
-    --xpra|--xephyr|--xdummy|--xvfb|--xwayland|--nxagent|--weston-xwayland|--kwin-xwayland|--xpra-xwayland|--xdummy-xwayland)
+    --xpra|--xephyr|--xdummy|--xvfb|--xwayland|--nxagent|--weston-xwayland|--kwin-xwayland|--xpra-xwayland|--xdummy-xwayland|--xwin)
       $Mksu "exec env WAYLAND_DISPLAY=$Newwaylandsocket      xinit $Xinitrc -- $Xcommand             >> $Xinitlogfile  2>&1 " ;;
-    --xwin) Xcommand="$(echo $Xcommand | sed 's/\\//g')" ;   xinit $Xinitrc -- $Xcommand             >> $Xinitlogfile  2>&1   ;;
     --xorg)
       case $Xlegacywrapper in
         yes) $Mksu   "exec                                   xinit $Xinitrc -- $Xcommand             >> $Xinitlogfile  2>&1 " ;;
@@ -5590,7 +5585,6 @@ check_hostxenv() {              # check environment variables for host X display
   [ -z "$XAUTHORITY" ]   && [ -e "$Hostuserhome/.Xauthority" ] && XAUTHORITY="$Hostuserhome/.Xauthority"
   [ "$Hostssh" = "yes" ] && [ -e "$Hostuserhome/.Xauthority" ] && XAUTHORITY="$Hostuserhome/.Xauthority"
   [ "${XAUTHORITY:-}" ]  && {
-#    $Mksu "xauth -i -f ${XAUTHORITY:-} nlist $Hostdisplay 2>/dev/null | rmcr | xauth -f $Hostxauthority nmerge - 2>/dev/null"
     $Mksu "xauth -i -f ${XAUTHORITY:-} nlist $Hostdisplay 2>/dev/null | xauth -f $Hostxauthority nmerge - 2>/dev/null"
     chown $Hostuser $Hostxauthority
     chmod 600 $Hostxauthority
@@ -6087,8 +6081,7 @@ check_option_interferences() {  # check multiple option interferences, change se
       Sharecgroup="no"
     }
     case $Xserver in
-      tty) ;;
-      *) note "Windows firewall settings can forbid application access
+      --xwin) note "Windows firewall settings can forbid application access
   to the X server. If no application window appears, but no obvious error
   is shown, please check your firewall settings. Compare issue #108 on github." ;;
     esac
@@ -6808,7 +6801,6 @@ declare_variables() {           # declare global variables
   # X authentication
   Xauthentication="yes"                           # option '--no-auth' use cookie authentication yes/no
   Trusted="yes"                                   # Create trusted or untrusted cookies,  --hostdisplay uses untrusted cookies
-  Noxhost="no"                                    # deprecated option '--no-xhost': if yes, disable all X server access granted by xhost
   Xhost=""                                        # option '--xhost': custom xhost setting on new X server
 
   # special options not starting X or docker
@@ -6882,7 +6874,7 @@ stdout() {
 }
 parse_options() {               # parse cli options
   local Shortoptions Longoptions Parsererror
-  Shortoptions="aAbcdDefgGhHiKl:mMnNopPqQrstTuv::w::WxXyY"
+  Shortoptions="aAcdDefgGhHiKl:mMnNopPqQrstTuv::w::WxXyY"
   Longoptions="auto,x,X,xpra,xephyr,x11,xorg,hostdisplay,xwayland,weston-xwayland,xpra-xwayland,nxagent,wayland"           # X servers
   Longoptions="$Longoptions,weston,hostwayland,kwin,kwin-xwayland,xdummy,xvfb,no-x,vcxsrv,xwin,tty"                        # more X/Wayland servers
   Longoptions="$Longoptions,wm::,desktop,exe,xonly"
@@ -7024,7 +7016,7 @@ ${2:-}"                ; shift ;;        # add custom root command in container 
          --init)       Initsystem="${2:-tini}" ; shift ;;  # init in container
          --sharecgroup)Sharecgroup="yes" ;;                # share /sys/fs/cgroup. default for --init=systemd, possible use with --init=openrc
          --dbus-system) Dbussystem="yes" ;;                # set up dbus system daemon
-      -b|--dbus)       Dbusrunsession="yes" ;;                 # run image command with dbus-launch or dbus-run-session
+         --dbus)       Dbusrunsession="yes" ;;                 # run image command with dbus-launch or dbus-run-session
          --hostdbus)   Sharehostdbus="yes" ;;              # connect to host DBus
 
        ## Environment
