--nxagent: regression fix keyboard layout

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1779,7 +1779,8 @@ stdout() {
                        Desktopmode="yes" ;;
       -W|--wayland)    Sharewayland="yes"                  # set up wayland environment, regards --desktop
                        Setwaylandenv="yes"
-                       Dbusdaemon="yes" ;;
+                       Dbusdaemon="yes" 
+                       Dbuslaunch="yes" ;;
 
      #### Appearance
       -f|--fullscreen) Fullscreen="yes"  ;;                # fullscreen mode for Xephyr and Weston
@@ -2126,7 +2127,7 @@ $(cowsay "$Wisdom" 2>/dev/null || echo "Wanda the fish says: $Wisdom")"
     [ "$Sharegpu" = "yes" ]                                      && Xserver="--xpra-xwayland"
     [ "$Xfishtank" = "yes" ]                                     && Xserver="--xephyr"
     [ "$Desktopmode" = "yes"  ]                                  && Xserver="--xephyr"
-    [ -z "$Imagename$Hostexebasename" ]                          && { Xserver="--xephyr" ; Desktopmode="yes" ; }
+    #[ -z "$Imagename$Hostexebasename" ]                          && { Xserver="--xephyr" ; Desktopmode="yes" ; }
     [ "$Xserver" = "--xephyr" ] && { depends --xephyr            || Xserver="--weston-xwayland" ; }
     [ "$Sharegpu" = "yes" ]     && [ "$Xserver" = "--xephyr" ]   && Xserver="--weston-xwayland"
     [ "$Outputcount" != "1" ]                                    && Xserver="--weston-xwayland"
@@ -5764,15 +5765,15 @@ exit 0' >> /etc/rc.local"
         echo     "verbose -d \"Created cookie: \$($Xauth -f Xclientcookie list 2>&1 | rmcr)\""
         echo     "chmod 644 $Xclientcookie"
         [ "$Xserver" = "--hostdisplay" ] && echo "[ '\$Xhostentry' = 'yes' ] && env XAUTHORITY=$Hostxauthority xhost -SI:localuser:$Hostuser | rmcr"
-        [ "$Xserver" = "--nxagent" ]     && echo "rm $Xclientcookie.bak" && echo "xhost -"
+        [ "$Xserver" = "--nxagent" ]     && echo "rm $Xclientcookie.bak"
       }
 
       echo "export XAUTHORITY=$Xclientcookie"
       echo "[ '$Xauthentication' = 'no' ] || [ ! -s '$Xclientcookie' ] && unset XAUTHORITY && warning '$Xserver: X server $Newdisplay runs without cookie authentication.'"
 
       case "$Xserver" in
-        --hostdisplay|--nxagent) ;;
-        --vcxsrv) ;; # xhost does not work over tcp
+        --hostdisplay) ;;   # do not change host settings
+        --vcxsrv|--xwin) ;; # xhost does not work over tcp
         *)
           case $Xauthentication in
             yes)
@@ -5792,6 +5793,11 @@ exit 0' >> /etc/rc.local"
             echo "    xhost +SI:localuser:$Benutzer'"
             echo "xhost +SI:localuser:$Benutzer | rmcr"
           }
+        ;;
+      esac
+      case $Xserver in
+        --hostdisplay|--vcxsrv|--xwin|--nxagent) ;;
+        *)
           # Keyboard layout
           command -v setxkbmap >/dev/null && {
             case "$Xkblayout" in
@@ -6207,6 +6213,9 @@ $(pstree -cp $Containerpid1 2>&1 ||:)"
         echo "storepid() {"
         echo "  echo \${1:-} \${2:-} >> $Bgpidfile"
         echo "}"
+        [ "$Dbuslaunch" = "yes" ]   && command -v dbus-launch >/dev/null      && echo "Dbus=dbus-launch" || {
+          [ "$Dbuslaunch" = "yes" ] && command -v dbus-run-session >/dev/null && echo "Dbus=dbus-run-session"
+        } || echo "Dbus="
         echo "export $Newxenv"
         [ "$Benutzerhosthome" = "yes" ] && {
           echo "export HOME='$Benutzerhosthomefolder'"
@@ -6217,7 +6226,7 @@ $(pstree -cp $Containerpid1 2>&1 ||:)"
         echo "for i in 3 4 6 7 8 9; do"
         echo "  { >&\$i ;} 2>/dev/null && exec >&\$i-"
         echo "done"
-        echo "$Hostexe $( [ "$Forwardstdin" = "yes" ] && echo "<$Cmdstdinfile") >>$Cmdstdoutlogfile 2>>$Cmdstderrlogfile &"
+        echo "\$Dbus $Hostexe $( [ "$Forwardstdin" = "yes" ] && echo "<$Cmdstdinfile") >>$Cmdstdoutlogfile 2>>$Cmdstderrlogfile &"
         echo "storepid \$! hostexe"
       } >> $Imagecommandscript
       nl -ba <$Imagecommandscript >> $Containerlogfile
@@ -6329,8 +6338,8 @@ $(tail $Compositorlogfile)")"
 }
 ######### ToDo notes for development
 todo() {
-# BUG: --nxagent runs with xhost +
-# x11docker/xwayland: where is the X socket ??
+# x11docker/xwayland nested: where is the X socket ??
+# --wayland on win: weston dbus-x11 qtwayland
 
 # MSYS2/Cygwin/WSL:
 #       needs test:
@@ -6348,9 +6357,7 @@ todo() {
 
 # --group-add: compare host and container GID? warn if group misses in container, or create it?
 # BUG x11docker/cde fails
-# jess/cathode fails with xcb error, needs bug report
-
-# BUG --pulseaudio=socket: PULSE_SERVER and PULSE_COOKIE: point to /x11docker for --exe
+# jess/cathode fails with xcb error. bug report: https://github.com/jessfraz/dockerfiles/issues/401
 
 # --dbus-system: give up restricted setup?
 # check xhost +localhost
