V3.9.3.2 --no-xtest: new option to disable XTEST. issue #23: openSUSE warning to use --no-init
# 01.03.2018  V3.9.3.2  --no-xtest: disable extension XTEST. Default for most options.
#                       openSUSE docker package misses init binary, show warnings for --tini, issue #23

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -12,6 +12,8 @@
 Version="3.9.3.1"
 
 changelog() {
+# 01.03.2018            --no-xtest: disable extension XTEST. Default for most options.
+#                       openSUSE docker package misses init binary, show warnings for --tini, issue #23
 # 01.03.2018 V3.9.3.1   fix XTEST warning messages
 # 01.03.2018 V3.9.3     --tini: show warning for outdated docker versions without option --init and fall back to --no-init, issue #23
 # 26.02.2018            --xtest: new option to enable X extension XTEST. Default for --xdummy, --xvfb, --xpra
@@ -187,6 +189,10 @@ todo() {
 # BUG --weston,--kwin: docker sometimes fails although socket exists: "stat /run/user/1000/wayland-607: no such file or directory"
 # BUG: --pulseaudio: stopping container with pulseaudio disables sound of other containers, too. Seems to be a pulseaudio bug.
 # further check of xpra server crashes with jess/atom and chromium. --mmap=no avoids the bug: xpra bug report?
+# --hostdisplay: default to --ipc --trusted --clipboard? Give a note about --untrusted?
+# --pulseaudio --net fallback: ALSA notes should be visible
+# --pulseaudio --net: other pulseaudio connection possible? try pax11publish?
+# minor BUG: warnings in dockerrc not visible in terminal if password prompt in xterm
 
 # check out possibilities to allow 'sudo docker' directly again.
 # check detached mode on mageia
@@ -430,6 +436,7 @@ X and Wayland configuration:
      --vt N            Use vt / tty N (affects --xorg, --xdummy, --xpra).
      --display N       Use display number N for new X server.
      --xtest           Enable XTEST. Default for --xvfb, --xdummy, --xpra.
+     --no-xtest        Disable XTEST. Default for most options.
      --westonini FILE  Custom weston.ini for --weston and --weston-xwayland.
 
 Container capabilities:
@@ -1076,7 +1083,7 @@ Nxagentoptions=""                               # options for nxagent
 Xephyroptions=""                                # options for Xephyr
 Xephyrglamor="yes"                              # former option '--glamor': enable Xephyr glamor 2D acceleration (deprecated, now always yes)
 Xfishtank="no"                                  # --fish: xfishtank on new X server
-Xtest="no"                                      # enable extension Xtest yes/no
+Xtest=""                                        # enable extension Xtest yes/no. If empty, yes for --xpra/--xdummy/--xvfb, otherwise no
 
 # Main X server options
 Autochooseserver="yes"                          # option '--auto': automated choosing server
@@ -1206,7 +1213,7 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
   Longoptions="$Longoptions,verbose,no-xhost,trusted,untrusted,dbus,waylandenv,pw:,no-internet"                            # advanced options
   Longoptions="$Longoptions,tini,no-init,systemd,runit,openrc,sys-admin,sharecgroup"                                       # init system options
   Longoptions="$Longoptions,starter,cleanup,license,licence,help,version,install,update,remove,wmlist"                     # special options without starting X server
-  Longoptions="$Longoptions,xhost:,no-auth,vt:,display:,xtest,env:,showenv,sharewayland,stdout,stderr,silent"              # developer options
+  Longoptions="$Longoptions,xhost:,no-auth,vt:,display:,xtest,no-xtest,env:,showenv,sharewayland,stdout,stderr,silent"     # developer options
   Longoptions="$Longoptions,ipc,net,ps,cache,cap-default,no-entrypoint,sudouser,hostuser:,dbusdaemon,dbus-daemon"          # developer options
   Longoptions="$Longoptions,cachedir:,homedir:,westonini:,sharedir:"                                                       # developer options
   Longoptions="$Longoptions,xsocket,tcp,tcpxsocket,virtualgl,glamor,volume:,xhost+,resizeable,orphaned,rw"                 # deprecated
@@ -1316,6 +1323,7 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
                        shift ;;
          --dbus-daemon|--dbusdaemon) Dbusdaemon="yes"; Dbuslaunch="yes" ;; # set up dbus system daemon and consolekit
          --xtest)      Xtest="yes" ;;                      # allow extension XTEST. default for xvfb, xdummy and xpra
+         --no-xtest)   Xtest="no" ;;                       # disable extension XTEST. default for most X server options
          
        ## X Authentication
          --xhost)      Xhost="xhost $2" ; shift ;;         # set 'xhost +' on both X servers
@@ -1574,6 +1582,9 @@ $(cat /proc/asound/cards | grep ':' | cut -d[ -f2 | cut -d] -f1)
   Fallback: disabling init system in container with x11docker optin --no-init."
       Initsystem="none"
     }
+    [ "$Hostsystem" = "opensuse" ] && warning "openSUSE is known to have a bug in its docker package.
+  It misses an init binary needed for docker run option --init.
+  If this startup fails, please try again with option --no-init."
   }
   
   [ "$Capdropall" = "no" ] && warning "Option --cap-default disables security hardening
@@ -2595,11 +2606,18 @@ fi
   [ "$Xauthentication" = "yes" ] && Xserveroptions="$Xserveroptions \\
   -auth $Xservercookie"
   
-  # exension XTEST
-  case $Xserver in
-    --xpra|--xpra-xwayland) Xtest="yes" ;;
-    --xdummy|--xdummy-xwayland|--xvfb) Xtest="yes" ;;
-  esac
+  # extension XTEST
+  [ -z "$Xtest" ] && {
+    case $Xserver in
+      --xpra|--xpra-xwayland) Xtest="yes" ;;
+      --xdummy|--xdummy-xwayland|--xvfb) 
+        Xtest="yes" 
+        note "Enabled X extension XTEST to allow custom access to new X server
+  with Xpra. You can disable XTEST with option --no-xtest."
+      ;;
+      *) Xtest="no" ;;
+    esac
+  }
   case "$Xtest" in
     yes) Xserveroptions="$Xserveroptions \\
   +extension XTEST" 
@@ -2612,7 +2630,11 @@ fi
   they may take control over your computer!"
       ;;
     no)  Xserveroptions="$Xserveroptions \\
-  -extension XTEST -tst" 
+  -extension XTEST -tst"
+      case $Xserver in
+        --xpra|--xpra-xwayland) warning "You have disabled extension XTEST with --no-xtest.
+  Xpra will not be able to provide keyboard and mouse." ;;
+      esac
     ;;
   esac
   
@@ -3701,9 +3723,11 @@ start() {
   echo '  echo Imagecommand="\"$Imagecommand\""'
   echo '  echo Entrypoint="\"$Entrypoint\""'
   echo "  echo ''"
-  echo "  echo '# Environment variables found in image'"
-  echo "  echo \"export \$Environment\""
-  echo "  echo ''"
+  echo "  [ \$Environment ] && {"
+  echo "    echo '# Environment variables found in image'"
+  echo "    echo \"export \$Environment\""
+  echo "  }"
+  echo "  echo '#'"
   echo "  echo export USER=$Benutzer"
   echo "  echo export HOME=\"\\\"$Benutzerhome\\\"\""
 
@@ -3770,6 +3794,14 @@ start() {
   echo "cat $Imagecommandscript | nl -ba >> $Dockerlogfile"
   echo ""
   
+  [ "$Initsystem" = "tini" ] && {
+    echo "docker info | grep 'Init Binary: docker-init' >/dev/null || warning 'Your docker installation does not have an init binary"
+    echo "  although option --init is listed in \"docker run --help\"."
+    echo "  Most probably docker startup will fail."
+    echo "  Use x11docker option --no-init to avoid a startup failure.'"
+    echo ""
+  }
+
   echo "read Containerid < <($Dockercommand)" # <- docker run is here!
   
   echo "[ -z \"\$Containerid\" ] && echo 'x11docker ERROR: Startup of docker failed.' && exit 1"
@@ -4069,6 +4101,7 @@ start() {
       verbose "Environment variables: 
   $Newxenv"
     }
+    verbose "Docker version: $(docker --version)"
     verbose "Image name: $Imagename"
     verbose "Image command: $Imagecommand"
     verbose "Users and terminal:
