V3.6.1.10 --showenv: wait for output until X is ready
# 27.08.2017 V3.6.1.10  --nothing: no check for successfull startup, avoids error message for short-timed cli commands
#                       --showenv: wait for output until X is ready

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -7,7 +7,7 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # https://github.com/mviereck/x11docker
 
-Version="3.6.1.9"
+Version="3.6.1.10"
 
 changelog() {
 #### ToDo:
@@ -36,6 +36,8 @@ changelog() {
 # BUG debian bug report lightdm/sddm contra gdm, dm can crash on tty switch if multiple graphical sessions are running
 
 #### x11docker changelog ####
+# 27.08.2017 V3.6.1.10  --nothing: no check for successfull startup, avoids error message for short-timed cli commands
+#                       --showenv: wait for output until X is ready
 # 25.08.2017 V3.6.1.9  bugfix: --home: remove debugging error message
 # 25.08.2017 V3.6.1.8  bugfix --orphaned: did not find cache folder
 #                      provide stdin to host exe, too (--exe)
@@ -1618,7 +1620,9 @@ Parsed options: $Parsedoptions"
       Weston-Xwayland) note "Weston does not work well with Xwayland in scaled mode.
   In summary, Xwayland does not get the right screen resolution from Weston.
   Try out if it works for you. Otherwise, you can combine 
-  --xpra-xwayland --desktop for better desktop scaling support." 
+  '--xpra-xwayland --desktop --scale $Scaling' for better desktop scaling support.
+  --scale for single applications works best with --xpra / --xpra-xwayland.
+  --scale in desktop mode works best with option --xorg." 
       ;;
       Xpra-Xwayland)
         [ "1" = "$(awk -v a="$Scaling" 'BEGIN {print (a < 1)}')" ] && {
@@ -1766,7 +1770,7 @@ Parsed options: $Parsedoptions"
   esac
 }
 
-{ #### part: check free display, create cache folder and cache files 
+{ #### part: check free display, create cache folder and cache files, catch stdin
   $Mksu "mkdir -p $Cacherootfolder" || error "Could not create cache folder
   $Cacherootfolder"
   writeaccess $Hostuseruid $Cacherootfolder || error "User $Hostuser does not have write access to
@@ -1847,11 +1851,12 @@ Parsed options: $Parsedoptions"
   Dockerip=$(echo $Dockeriprange | cut -d/ -f1)
   
   # catch stdin
-  IFS="" read -t 0.1 -rn 1 Byte
+  IFS="" read -t 0.1 -rn 5 Byte
   [ -n "$Byte" ] && {
     echo -n $Byte
     cat                          ### FIXME: If only one byte is submitted, cat will wait until end of world
   } >> $Cmdstdinfile
+  #cat <(cat - 2>/dev/null) >>$Cmdstdinfile
 }
 
 { #### part: check window manager (option --wm)
@@ -2403,9 +2408,6 @@ esac
 
   while read -r Line; do Newxenv="$Newxenv $Line" ;   done < <(echo -e $Customenvironment)
   while read -r Line; do Hostxenv="$Hostxenv $Line" ; done < <(echo -e $Customenvironment)
-
-  #   option '--showenv': show display infos on stdout
-  [ "$Showdisplayenvironment" = "yes" ] && echo $Newxenv
   
   # Host X enviroment
   [ -n "$Hostdisplay" ] && [ -e "$Hostxsocket" ] && {
@@ -3138,6 +3140,10 @@ Keywords=docker x11docker $(echo $Name | tr -c '[:alpha:][:digit:][:blank:]' ' '
     Compositorpid=$(cat $Compositorpidfile)
     ps -p $Compositorpid >/dev/null 2>&1 && storepid $Compositorpid compositor
   }
+  
+  #   option '--showenv': show display infos on stdout
+  [ "$Showdisplayenvironment" = "yes" ] && echo $Newxenv
+  
   case $Xserver in
     Nothing|Hostwayland) ;;
     Weston|Weston-Xwayland|Kwin|Kwin-Xwayland|Kwin-Native)
@@ -3169,7 +3175,7 @@ Keywords=docker x11docker $(echo $Name | tr -c '[:alpha:][:digit:][:blank:]' ' '
       
       [ -s "$Dockerpidfile" ] && { 
         Dockerpid=$(cat $Dockerpidfile)
-        ps -p $Dockerpid >/dev/null 2>&1 || error "Docker startup seems to have failed! 
+        ps -p $Dockerpid >/dev/null 2>&1 || [ "$Xserver" = "Nothing" ] || error "Docker startup seems to have failed! 
   Last lines of docker.log:
 $(tail $Dockerlogfile)"
         storepid $Dockerpid docker
