assert Unpriv is defined in some places where it is neeeded

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1371,6 +1371,7 @@ mkfile() {                      # create file $1 owned by $Hostuser
   return 0
 }
 mkfolder() {                    # create folder $1 owned by $Hostuser
+  assert_unpriv_defined
   local Step Path= Return=
   for Step in $(tr '/' '\n' <<< "${1:-}" | grep .) ; do
     Path="$Path/$Step"
@@ -11349,14 +11350,26 @@ experimental() {
   }
   return 1
 }
+assert_unpriv_defined() {
+  if [ -z "$Unpriv" ] ; then
+    # The error function doesn't seem to work correctly in the contexts where this is called, so echo and fail fast to be sure.
+    local unpriv_check_msg
+    unpriv_check_msg='Error: Variable Unpriv should have been set by now. This means check_hostuser needs to run earlier (maybe a bug).'
+    echo "$unpriv_check_msg"
+    echo "$unpriv_check_msg" >&2
+    exit 1
+  fi
+}
 unpriv() {                      # run a command as unprivileged user. Needed if x11docker was started by root or with sudo.
   # $Unpriv is declared in check_hostuser: 'eval' or 'su $Hostuser -c'
+  assert_unpriv_defined
   local Command
   Command="$(oneline "${1:-}")"
   $Unpriv "$Command"
   return $?
 }
 unpriv_backend() {              # run container backend rootful or rootless
+  assert_unpriv_defined
   local Command
   Command="$(oneline "${1:-}")"
   [ -z "$Backendbin" ] && {
@@ -11370,6 +11383,7 @@ unpriv_backend() {              # run container backend rootful or rootless
   return $?
 }
 unpriv_xcbackend() {            # run X container backend rootful or rootless
+  assert_unpriv_defined
   local Command
   Command="$(oneline "${1:-}")"
   case "${Xcrootless:-no}" in
