--lang: Argument is optional now. --ps: deprecated

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="5.5.0"
+Version="5.5.1-beta"
 
 usage() {                       # --help: show usage information
   echo "
@@ -46,7 +46,7 @@ Focus on security:
   
 Note that some applications might behave different than with a regular
 'docker run' command due to security restrictions set by x11docker.
-Unrestricted container setup is possible with: --cap-default --user=root
+Unrestricted container setup is possible with --cap-default and/or --user=root
 
 Dependencies on host:
   Depending on chosen options, x11docker needs some packages to be installed.
@@ -86,7 +86,7 @@ Basic settings: (especially influencing auto choosing X server)
                        Degrades container isolation. Container access to GPU.
  -w, --wm [=COMMAND]   Use host window manager COMMAND for single applications
                        in nested X server options like --xephyr.
-                       Without COMMAND autodetect a window manager.
+                       Without COMMAND autodetect a host window manager.
                        To set default autodetected window manager:
                            update-alternatives --config x-window-manager
 
@@ -109,10 +109,11 @@ Clipboard, sound, printer, language:
                        define a desired sound card with CARDNAME.
                        Get a list of available sound cards with: aplay -l
                        Degrades isolation, container access to sound hardware.
-     --lang LOCALE     Language setting: search for utf8 LOCALE in image and
-                       create it if missing. Needs package 'locale' im image.
+     --lang [=LOCALE]  Set language variable LANG=LOCALE in container.
+                       Without LOCALE host variable --lang=\$LANG is used.
+                       If LOCALE is missing in image, x11docker generates it
+                       with 'localedef' in container (needs 'locale' package).
                        LOCALE can be e.g. ru, en, de, zh_CN, cz, fr, fr_BE.
-                       Same as host: --lang=\$LANG.
      --printer         Share host printers through CUPS server.
      --webcam          Share host webcam device files.
 
@@ -126,7 +127,7 @@ Special options:
      --pull [=ask|yes|no|always]  Behaviour if image is missing on host.
                        ask: Ask in terminal, timeout after 60s (default).
                        yes: Allow docker pull (default for --pull).
-                       no: Do not run 'docker pull'
+                       no: Do not run or ask for 'docker pull'
                        always: Always run 'docker pull'. Download only if
                        newer image is available. Allows sort of auto-update.
      --pw FRONTEND     Choose frontend for password prompt. Possible FRONTEND:
@@ -287,7 +288,6 @@ Miscellaneous:
                        ~/.local/share/applications to get a menu entry.
      --cachebasedir DIR   Custom base folder for cache files.
      --license         Show license of x11docker (MIT) and exit.
-     --ps              Preserve container and cache files on exit.
      --cleanup         Clean up orphaned containers and cache files.
 
 Verbosity options:
@@ -309,7 +309,7 @@ Please report issues and get help at: https://github.com/mviereck/x11docker
 license() {                     # --license: show license (MIT)
 echo 'MIT License
 
-Copyright (c) 2015, 2016, 2017, 2018 Martin Viereck
+Copyright (c) 2015, 2016, 2017, 2018, 2019 Martin Viereck
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
@@ -2225,15 +2225,6 @@ check_newxenv() {               # find free display, create $Newxenv
         ;;
       esac
     ;;
-#    --vcxsrv|--xwin)
-#      Newdisplay="$Hostip:$Newdisplaynumber"
-#    ;;
-#    *)
-#      Newdisplay=":$Newdisplaynumber"
-#      Newxsocket="/tmp/.X11-unix/X$Newdisplaynumber"
-#      Newxlock="/tmp/.X$Newdisplaynumber-lock"
-#      [ -n "$(find $Newxsocket $Newxlock 2>/dev/null)" ] && error "Display $Newdisplay is already in use."
-#    ;;
   esac
   # set $Newwaylandsocket
   case $Xserver in
@@ -2322,7 +2313,7 @@ check_vt() {                    # option --xorg: find free vt / tty
 
   # try to find free tty with fgconsole. Fails in some cases within X.
   [ "$Newxvt" ] || Newxvt=$(fgconsole --next-available 2>/dev/null ||:)
-  [ "$Newxvt" ] || Newxvt=$(fgconsole --next-available 2>/dev/null </dev/tty$XDG_VTNR ||:)
+  [ "$Newxvt" ] || Newxvt=$(fgconsole --next-available 2>/dev/null </dev/tty${XDG_VTNR:-} ||:)
 
   # try to find free tty within range of 13..63
   [ "$Newxvt" ] || {
@@ -2333,8 +2324,8 @@ check_vt() {                    # option --xorg: find free vt / tty
 
   [ "$Newxvt" ] || error "Could not identify a free tty for --xorg."
 
-  [ "$XDG_VTNR" ] && [ "$Hostdisplay$Hostwaylandsocket" ] && note "Current X server $Hostdisplay runs on tty $XDG_VTNR.
-  Access it with [CTRL][ALT][F$XDG_VTNR]."
+  [ "${XDG_VTNR:-}" ] && [ "$Hostdisplay$Hostwaylandsocket" ] && note "Current X server $Hostdisplay runs on tty ${XDG_VTNR:-}.
+  Access it with [CTRL][ALT][F${XDG_VTNR:-}]."
 
   [ "${Newxvt:-999}" -gt "12" ] && {
     fgconsole --next-available 1>/dev/null 2>/dev/null || note "Could not check for a free tty below or equal to 12.
@@ -3877,7 +3868,7 @@ create_dockercommand() {        # create command to run docker
   
   # real entrypoint is checked in dockerrc
   Dockercommand="$Dockercommand \\
-  --entrypoint env"
+  --entrypoint /usr/bin/env"
   
   # add environment variables. Only needed here for possible 'docker exec'. Otherwise set in container.CMD.sh
   while read Line; do
@@ -4767,27 +4758,26 @@ exit 0\" >> /etc/rc.local"
     echo "Langland=\$(echo \$Langland | cut -d_ -f1 | tr '[:upper:]' '[:lower:]')_\$(echo \$Langland | cut -d_ -f2 | tr '[:lower:]' '[:upper:]')"
     echo "echo \"\$Locales\" | grep -q \$Langland.UTF-8 && Langcontainer=\$Langland.UTF-8"
     echo "echo \"\$Locales\" | grep -q \$Langland.utf8  && Langcontainer=\$Langland.utf8"
-    echo "echo $Langwunsch | grep -E 'C|C.UTF-8|C.utf8|POSIX' >/dev/null && Langcontainer=$Langwunsch"
     echo "[ -z \"\$Langcontainer\" ] && {"
-    echo "  [ -e /usr/share/i18n/SUPPORTED ] || warning \"/usr/share/i18n/SUPPORTED not found.
-  Please install locale package in image (belongs to glibc)\""
+    echo "  [ -e /usr/share/i18n/SUPPORTED ] || note \"Option --lang: /usr/share/i18n/SUPPORTED not found.
+  Please install 'locale' package in image (belongs to glibc)\""
     echo "  Langcontainer=\$Langland.utf8"
-    echo "  verbose \"Creating language locale \$Langcontainer\""
+    echo "  verbose -d \"Option --lang: Generating language locale \$Langcontainer\"."
     echo "  command -v localedef >/dev/null || note 'Command localedef not found in image.
   Need it for language locale creation (--lang).'"
     echo "  localedef --verbose --force -i \$Langland -f UTF-8 \$Langcontainer || verbose \"localedef exit code: \$?\""
     echo "  locale -a | grep -q \"\$Langcontainer\" || {"
-    echo "    warning \"Locale creation of \$Langcontainer failed.\""
+    echo "    note \"Option --lang: Generation of locale \$Langcontainer failed.\""
     echo "    Langcontainer=''"
     echo "  }"
     echo "} || {"
-    echo "  verbose \"Found locale in image: \$Langcontainer\""
+    echo "  verbose -d \"Option --lang: Found locale in image: \$Langcontainer\""
     echo "}"
     echo "[ \"\$Langcontainer\" ] && {"
     echo "  echo \"\$Langcontainer\" > /x11docker.LANG"
     echo "  echo \"LANG=\$Langcontainer\" > /etc/default/locale"
-    echo "} || warning 'Desired locale for '--lang=$Langwunsch' not found and not created.'"
-    echo "verbose \"Output of locale -a:"
+    echo "} || note 'Option --lang: Desired locale for '$Langwunsch' not found and not generated.'"
+    echo "verbose -d \"Output of locale -a:"
     echo "\$(locale -a)\""
     echo ""
   }
@@ -4947,6 +4937,7 @@ $(tail $Xpraserverlogfile)"
             rocknroll && error "Xpra server startup failed.
   Last lines of Xpra server log:
 $(tail $Xpraserverlogfile)"
+            return 1
           }
         }
 
@@ -6039,10 +6030,16 @@ option_messages() {             # some messages depending on options, but not ch
   [ "$Sharewebcam" = "yes" ] && warning "Option --webcam: Container applications might look 
   at you and also might take screenshots of your Desktop."
   
-  [ "$Customdockeroptions" ] && warning "Found custom DOCKER_RUN_OPTIONS.
+  [ "$Customdockeroptions" ] && {
+    warning "Found custom DOCKER_RUN_OPTIONS.
   x11docker will add them to 'docker run' command
   without a check for validity or security. Found options:
   $Customdockeroptions"
+    grep -- '--entrypoint' <<< "$Customdockeroptions" && warning "Found option --entrypoint
+  in custom docker run options. x11docker uses this option, too.
+  This setup will probably fail. Use x11docker option --no-entrypoint instead
+  and add desired command as image command after the image name."
+  }
   
   return 0
 }
@@ -6514,21 +6511,21 @@ stdout() {
 }
 parse_options() {               # parse cli options
   local Shortoptions Longoptions Parsererror
-  Shortoptions="aAbcdDefgGhHiKl:mMnNopPqQrstTuv::w:WxXyY"
+  Shortoptions="aAbcdDefgGhHiKl:mMnNopPqQrstTuv::w::WxXyY"
   Longoptions="auto,x,X,xpra,xephyr,x11,xorg,hostdisplay,xwayland,weston-xwayland,xpra-xwayland,nxagent,wayland"           # X servers
   Longoptions="$Longoptions,weston,hostwayland,kwin,kwin-xwayland,xdummy,xvfb,no-x,vcxsrv,xwin,tty"                        # more X/Wayland servers
   Longoptions="$Longoptions,wm::,desktop,exe,xonly"
   Longoptions="$Longoptions,fullscreen,size:,scale:,rotate:,dpi:,output-count:,gpu,xfishtank,border::"                     # X appearance options
   Longoptions="$Longoptions,xhost:,no-auth,vt:,display:,env:,showenv,showid,showpid1"                                      # X and environment options
-  Longoptions="$Longoptions,home,clipboard,pulseaudio::,alsa::,lang:,printer,webcam"                                       # comfort options
+  Longoptions="$Longoptions,home,clipboard,pulseaudio::,alsa::,lang::,printer,webcam"                                      # comfort options
   Longoptions="$Longoptions,no-xhost,pw:,no-internet,workdir:,sharessh,limit::,pull::"                                     # advanced options
   Longoptions="$Longoptions,init::,sys-admin,sharecgroup,dbus,dbus-system,hostdbus"                                        # advanced options
   Longoptions="$Longoptions,homedir:,sharedir:,cachebasedir:,homebasedir:"                                                 # host folders
   Longoptions="$Longoptions,launcher,cleanup,license,licence,help,version,install,update,update-master,remove,wmlist"      # special options without starting X or container
   Longoptions="$Longoptions,verbose::,quiet,debug,stdin"                                                                   # verbose options
-  Longoptions="$Longoptions,hostipc,hostnet,ps,cap-default,sudouser,hostuser:,user:,group-add:,name:"                      # capabilities, users
+  Longoptions="$Longoptions,hostipc,hostnet,cap-default,sudouser,hostuser:,user:,group-add:,name:"                         # capabilities, users
   Longoptions="$Longoptions,keymap:,name:,no-entrypoint,runfromhost:,runasroot:,westonini:,interactive"                    # developer options
-  Longoptions="$Longoptions,cachedir:,starter,trusted,untrusted,xtest,no-xtest,stdout,stderr,silent,nothing"               # deprecated
+  Longoptions="$Longoptions,cachedir:,starter,trusted,untrusted,xtest,no-xtest,stdout,stderr,silent,nothing,ps"            # deprecated
   Longoptions="$Longoptions,tini,no-init,systemd,runit,openrc,sysvinit"                                                    # deprecated
   Longoptions="$Longoptions,xtest,xcomposite"                                                                              # experimental
   
@@ -6580,11 +6577,16 @@ parse_options() {               # parse cli options
       -g|--gpu)        Sharegpu="yes" ;;                        # share files in /dev/dri, allow GPU usage
       -w|--wm)         case ${2:-} in                      # choose host window manager
                          "n"|"none")    Windowmanager="none" ;;
-                         ""|"m"|"auto") Windowmanager="auto" ;;
+                         "")            Windowmanager="auto" ;;
+                         "auto")        Windowmanager="auto" 
+                           note "Option -w, --wm: Use --wm without an option
+  instead of --wm=auto" ;;
+                         "m")           Windowmanager="auto" 
+                           note "Option -w, --wm: Use --wm without an option
+  instead of -wm" ;;
                          *)             Windowmanager=${2:-} ;;
                        esac
-                       shift
-                       Desktopmode="yes" ;;
+                       shift ; Desktopmode="yes" ;;
       -W|--wayland)    Sharewayland="yes"                  # set up wayland environment, regards --desktop
                        Setwaylandenv="yes" 
                        Dbusrunsession="yes" ;;
@@ -6598,6 +6600,7 @@ parse_options() {               # parse cli options
          --dpi)        Dpi=${2:-} ; shift ;;               # dots per inch / influences font size
          --output-count) Outputcount="${2:-}" ; shift ;;   # number of virtual outputs
          --xfishtank)   Xfishtank="yes" ;;                 # Run xfishtank on new X server
+         --westonini)  Customwestonini="${2:-}" ; shift ;; # custom weston.ini
 
      #### Options
       -c|--clipboard)  Shareclipboard="yes"  ;;            # share host clipboard with dockered applications (xpra only)
@@ -6606,7 +6609,9 @@ parse_options() {               # parse cli options
       -p)              Pulseaudiomode="auto" ;;            # enable pulseaudio sound
          --pulseaudio) Pulseaudiomode="${2:-}" ; shift     # enable pulseaudio sound
                        [ "$Pulseaudiomode" ] || Pulseaudiomode="auto" ;;
-         --lang)       Langwunsch=${2:-} ; shift ;;        # locale/language setting
+         --lang)       Langwunsch="${2:-${LANG:-}}" ; shift    # locale/language setting
+                       [ "$Langwunsch" ] || note "Option --lang: Environment variable \$LANG is empty.
+  Please specify desired language locale with w.g. --lang=en_US or --lang=zh_CN." ;;
          --printer)    Sharecups="yes" ;;                  # share printer (cups)
          --webcam)     Sharewebcam="yes" ;;                # share webcam
 
@@ -6706,11 +6711,7 @@ ${2:-}"                ; shift ;;        # add custom root command in container 
          --hostipc)    Sharehostipc="yes" ;;               # docker run option --ipc=host
          --hostnet)    Sharehostnet="yes" ;;               # docker run option --net=host
          --cap-default) Capdropall="no" ;;                 # don't use --cap-drop=ALL
-         --name)    Containername="${2:-}" ; shift ;;      # set container name
-
-       ## miscellaneous
-         --ps)         Preservecachefiles="yes"  ;;        # preserve container instead of removing it with 'docker run --rm'
-         --westonini)  Customwestonini="${2:-}" ; shift ;; # custom weston.ini
+         --name)       Containername="${2:-}" ; shift ;;   # set container name
 
      #### special options not starting X or docker
       --launcher|--starter) Createlauncher="yes" ;;        # create application launcher on desktop and exit
@@ -6719,6 +6720,8 @@ ${2:-}"                ; shift ;;        # add custom root command in container 
       --wmlist)        echo $Wm_all ; exit 0 ;;            # special option for x11docker-gui to retrieve list of window managers
       
      #### deprecated
+         --ps)         Preservecachefiles="yes"            # preserve container instead of removing it with 'docker run --rm'
+                       note "Option --ps is deprecated and has no replacement." ;;
          --trusted)    Shareclipboard="yes" 
                        warning "Option --trusted is deprecated.
   To allow trusted cookies for --hostdisplay use option --clipboard.
