drop some useless cache files depending on setup

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1459,9 +1459,7 @@ setup_gpu() {                   # option --gpu: share /dev/dri and check nvidia 
   otherwise for security reasons. Container security is reduced now.
   However, given capabilities are still within default Docker capabilities.
   You would not have this issue with free nouveau driver on host."
-  
-          Nvidiacontainerfile="$Cshare/$(basename "$Nvidiainstallerfile")"
-          
+            
         } || {
           Nvidiainstallerfile=""
           note "You are using proprietary closed source NVIDIA driver.
@@ -4061,7 +4059,7 @@ create_dockercommand() {        # create command to run docker
     ;;
     tini) 
       Dockercommand="$Dockercommand \\
-  --volume $(convertpath volume "$Tinibinaryfile:ro" "$Cshare/tini")" 
+  --volume $(convertpath volume "$Tinibinaryfile:ro" "$Tinicontainerpath")" 
     ;;
     systemd)
       Dockercommand="$Dockercommand \\
@@ -4215,12 +4213,13 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   
   echo "Bgpidfile='$Bgpidfile'"
   echo "Compositorlogfile='$Compositorlogfile'"
+  echo "Containercommand=\"$Containercommand\""
   echo "Hostuser='$Hostuser'"
   echo "Hostusergid='$Hostusergid'"
-  echo "Containercommand=\"$Containercommand\""
   echo "Imagename=\"$Imagename\""
   echo "Messagefile='$Messagefifo'"
   echo "Newxenv='$Newxenv'"
+  echo "export PATH='$PATH'"
   echo "Showdisplayenvironment='$Showdisplayenvironment'"
   echo "Timetosaygoodbye='$Timetosaygoodbye'"
   echo "Timetosaygoodbyefifo='$Timetosaygoodbyefifo'"
@@ -4230,7 +4229,6 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo "Xinitlogfile='$Xinitlogfile'"
   echo "Xserver='$Xserver'"
   echo "Workdir='$Workdir'"
-  echo "export PATH='$PATH'"
   echo ""
   echo "Containerid="
   echo "Dockerlogspid=''"
@@ -4352,7 +4350,7 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo "rocknroll || exit 64"
   echo ""
   
-  [ "$Tinibinaryfile" ] && [ "$Switchcontaineruser" = "no" ] && echo "Tini=\"$Cshare/tini --\"" || echo "Tini="
+  [ "$Tinibinaryfile" ] && [ "$Switchcontaineruser" = "no" ] && echo "Tini=\"$Tinicontainerpath --\"" || echo "Tini="
   echo ""
   
   echo "Inspect=\"\$($Dockerexe inspect $Imagename --format='{{.Config.Entrypoint}}{{.Config.Cmd}}[{{.Config.User}}][{{.Config.WorkingDir}}]')\""
@@ -4454,6 +4452,8 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo     "  echo '# Runs as unprivileged user in container.'"
   echo     "  echo ''"
 
+  
+  #echo     "  echo 'exec 6>&1 7>&2'"
   echo     "  echo 'exec >>$(convertpath share $Containerlogfile) 2>&1'"
   echo     "  echo ''"
 
@@ -4613,13 +4613,16 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo     "  echo \"debugnote \\\"$(basename $Containercommandscript): Running container command: 
   \$Tini \\\$Dbus \$Entrypoint \$Containercommand
   \\\"\""
+  echo     "  echo ''"
   
+  #echo     "  echo 'exec 1>&6 2>&7 6>&- 7>&-'"
   case $Interactive in
     no)
       echo "  echo \"\$Exec \$Tini \\\$Dbus \$Entrypoint \$Containercommand $( [ "$Forwardstdin" = "yes" ] && echo "<$(convertpath share $Cmdstdinfifo)") >>$(convertpath share $Cmdstdoutlogfile) 2>>$(convertpath share $Cmdstderrlogfile)\""
       echo "  echo \"echo \\\$? >> $(convertpath share $Cmdexitcodefile)\""
     ;;
     yes)
+      echo "  echo 'exec >/dev/stdout 2>/dev/stderr'"
       echo "  echo \"\$Exec \$Tini \\\$Dbus \$Entrypoint \$Containercommand\""
       echo "  echo \"echo \\\$? >> $(convertpath share $Cmdexitcodefile)\""
     ;;
@@ -5007,9 +5010,9 @@ create_containerrootrc() {      # create container root setup script: This scrip
     echo "  *)"
     echo "    Installationwillsucceed=maybe"
     echo '    case "$Containerlibc" in'
-    echo "      musl) note 'Installing NVIDIA driver in container systems"
-    echo "  based on musl libc like Alpine is not possible due to"
-    echo "  proprietary closed source policy of NVIDIA corporation.'"
+    echo "      musl) note 'Installing NVIDIA driver in container systems
+  based on musl libc like Alpine is not possible due to
+  proprietary closed source policy of NVIDIA corporation.'"
     echo "        Installationwillsucceed=no"
     echo "      ;;"
     echo "    esac"
@@ -5034,8 +5037,8 @@ create_containerrootrc() {      # create container root setup script: This scrip
     echo "      env TMPDIR=/tmp2 PATH=\"/tmp2:\$PATH\" sh $Nvidiacontainerfile -A | grep -q -- '--install-libglvnd'        && Nvidiaoptions=\"\$Nvidiaoptions --install-libglvnd\""
     echo "      env TMPDIR=/tmp2 PATH=\"/tmp2:\$PATH\" sh $Nvidiacontainerfile -A | grep -q -- '--no-nvidia-modprobe'      && Nvidiaoptions=\"\$Nvidiaoptions --no-nvidia-modprobe\""
     echo "      env TMPDIR=/tmp2 PATH=\"/tmp2:\$PATH\" sh $Nvidiacontainerfile -A | grep -q -- '--no-kernel-module-source' && Nvidiaoptions=\"\$Nvidiaoptions --no-kernel-module-source\""
-    echo "      env TMPDIR=/tmp2 PATH=\"/tmp2:\$PATH\" sh $Nvidiacontainerfile --tmpdir /tmp2 \$Nvidiaoptions || note 'ERROR: Installation of NVIDIA driver failed."
-    echo "  Run with option --verbose to see installer output.'"
+    echo "      env TMPDIR=/tmp2 PATH=\"/tmp2:\$PATH\" sh $Nvidiacontainerfile --tmpdir /tmp2 \$Nvidiaoptions || note 'ERROR: Installation of NVIDIA driver failed.
+  Run with option --verbose to see installer output.'"
     echo "      rm -R /tmp2 && unset TMPDIR"
     echo "    } || note 'Skipping installation of $Nvidiacontainerfile'"
     echo "  ;;"
@@ -5545,7 +5548,7 @@ reload() {
         echo "exec /usr/local/bin/x11docker-agetty"
       ;;
       tini)
-        echo "exec $Cshare/tini -- /usr/local/bin/x11docker-agetty"
+        echo "exec $Tinicontainerpath -- /usr/local/bin/x11docker-agetty"
       ;;
       sysvinit)
         echo "/usr/local/bin/x11docker-watch &"
@@ -6971,7 +6974,7 @@ create_cachefiles() {           # create empty cache files owned by unprivileged
 
   Sharefolder="$Cachefolder/$Sharefolder"
   unpriv "mkdir -p $Sharefolder"
-  export Cachefolder Sharefolder
+  #export Cachefolder Sharefolder
   
   # host only access
   Bgpidfile="$Cachefolder/$Bgpidfile"                               && mkfile $Bgpidfile
@@ -7002,14 +7005,12 @@ create_cachefiles() {           # create empty cache files owned by unprivileged
   Xtermrc="$Cachefolder/$Xtermrc"                                   && mkfile $Xtermrc
   
   # systemd files
-  [ "$Initsystem" = "systemd" ] && {
-    Systemdtarget=$Cachefolder/$Systemdtarget                       && mkfile $Systemdtarget
-    Systemdconsoleservice=$Cachefolder/$Systemdconsoleservice       && mkfile $Systemdconsoleservice
-    Systemdwatchservice=$Cachefolder/$Systemdwatchservice           && mkfile $Systemdwatchservice
-    Systemdjournalservice=$Cachefolder/$Systemdjournalservice       && mkfile $Systemdjournalservice
-    Systemdjournallogfile=$Sharefolder/$Systemdjournallogfile       && mkfile $Systemdjournallogfile
-    Systemdenvironment=$Cachefolder/$Systemdenvironment             && mkfile $Systemdenvironment
-  }
+  Systemdconsoleservice=$Cachefolder/$Systemdconsoleservice         && mkfile $Systemdconsoleservice
+  Systemdenvironment=$Cachefolder/$Systemdenvironment               && mkfile $Systemdenvironment
+  Systemdjournallogfile=$Sharefolder/$Systemdjournallogfile         && mkfile $Systemdjournallogfile
+  Systemdjournalservice=$Cachefolder/$Systemdjournalservice         && mkfile $Systemdjournalservice
+  Systemdtarget=$Cachefolder/$Systemdtarget                         && mkfile $Systemdtarget
+  Systemdwatchservice=$Cachefolder/$Systemdwatchservice             && mkfile $Systemdwatchservice
   
   # shared to /x11docker in container
   Cmdexitcodefile="$Sharefolder/$Cmdexitcodefile"                   && mkfile $Cmdexitcodefile
@@ -7037,6 +7038,40 @@ create_cachefiles() {           # create empty cache files owned by unprivileged
   [ -e "$Numbersinusefile" ] || mkfile "$Numbersinusefile"
   
   return 0
+}
+drop_cachefiles() {             # remove some cache files that are not needed in current setup
+  case $Initsystem in
+    systemd) ;;
+    *) rm $Systemdconsoleservice $Systemdenvironment $Systemdjournallogfile $Systemdjournalservice $Systemdtarget $Systemdwatchservice ;;
+  esac
+  case $Xserver in
+    --xpra|--xpra-xwayland) ;;
+    *) rm $Xpraclientlogfile $Xpraserverlogfile ;;
+  esac
+  case $Xserver in
+    --weston|--weston-xwayland|--kwin|--kwin-xwayland|--xpra-xwayland|--xdummy-xwayland) ;;
+    *) rm $Compositorlogfile $Compositorpidfile $Westonini ;;
+  esac
+  case $Xserver in
+    --weston|--kwin|--hostwayland|--tty) rm $Xclientcookie $Xservercookie ;;
+    *) [ "$Xauthentication" = "no" ]  && rm $Xclientcookie $Xservercookie ;;
+  esac
+  case $Pulseaudiomode in
+    "") rm $Pulseaudioconf ;;
+  esac
+  case $Xserver in
+    --xdummy) ;;
+    --xpra) [ "$Xpravfb" = "Xdummy" ] || rm $Xdummyconf $Xorgwrapper ;;
+    *) rm $Xdummyconf $Xorgwrapper ;;
+  esac
+  case $X11dockermode in
+    exe) rm $Containerrootrc $Dockercommandfile $Dockerinfofile $Dockerrc ;;
+  esac
+  case $Xserver in
+    --xephyr|--xorg|--xdummy|--xdummy-xwayland|--xvfb|--xwayland|--weston-xwayland) 
+      [ "$Shareclipboard" = "no" ] && rm $Shareclipboardscript ;;
+    *)                                rm $Shareclipboardscript ;;
+  esac
 }
 setup_fifo() {                  # set up fifo channels (also option --stdin)
   # setup fifos to allow messages from within container, dockerrc and xinitrc
@@ -7232,7 +7267,7 @@ declare_variables() {           # declare global variables
   Hostxauthority="$(unspecialstring "Xauthority-${DISPLAY:-host}")"   # File to store copy of $XAUTHORITY
   Hostxenv=""                                     # Collection of host X environment variables
   Hostxsocket=""                                  # Socket of DISPLAY in /tmp/.X11-unix
-  Nvidiacontainerfile=""                          # --gpu: Path to nvidia installer in container
+  Nvidiacontainerfile="/usr/local/bin/NVIDIA-installer.run"  # --gpu: Path to nvidia installer in container
   Nvidiaversion=""                                # --gpu: Proprietary nvidia driver version on host
   Nvidiainstallerfile=""                          # --gpu: Proprietary nvidia driver installer for container in [...]local/share/x11docker
   
@@ -7374,7 +7409,8 @@ declare_variables() {           # declare global variables
   Initsystem="tini"                               # --init: Init system in container
   Sharecgroup="no"                                # --sharecgroup, --init=systemd: share /sys/fs/cgroup. Also needed for elogind
   Sharehostdbus="no"                              # --hostdbus: Connect to DBus user daemon on host
-  Tinibinaryfile=""                               # --tini (default): Binary of tini; either /usr/bin/docker-exec or provided by user in [...]/share/x11docker
+  Tinibinaryfile=""                               # --init=tini (default): Binary of tini; either /usr/bin/docker-exec or provided by user in [...]/share/x11docker
+  Tinicontainerpath="/usr/local/bin/tini"         # --init=tini: Path of tini in container
   
   # Gaining root privileges to run docker
   Passwordcommand=""                              # --pw: Generated command for password prompt
@@ -7793,6 +7829,7 @@ Parsed options:    $Parsedoptions"
   }
   
   # some checks and setup
+  drop_cachefiles                # remove cachefiles not needed for current setup
   setup_verbosity                # create summary logfile, start verbose output  # --verbose, --stdout, --stderr
   setup_fifo                     # open message channels for container, dockerrc, xinitrc and watchpidlist()
   check_screensize               # size of host X and of new X server            # --size #time0,213
@@ -7922,6 +7959,7 @@ main "$@"
   
 #### ToDo notes for development
 todo() {
+  # BUG --interactive fails
   # Reduce number of files
   #  - Store container info like ID, PID etc in one file
 
