new options --group-add and --showid.

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1,16 +1,16 @@
 #! /bin/bash
 
 # x11docker
-# Run GUI applications and desktop environments in docker on a separate X server or Wayland compositor.
+# Run GUI applications and desktop environments in docker
 #
-# - Circumvents common X security leaks. 
-# - Improves container security restricting container capabilities
+# - Circumvents common X security leaks with additional X servers.
+# - Improves container security restricting container capabilities.
 # - Container user is same as host user to avoid root in container.
 #
 # Type 'x11docker --help' or scroll down to read usage information.
-# More documentation at   https://github.com/mviereck/x11docker
+# More documentation at:  https://github.com/mviereck/x11docker
 
-Version="4.1.2-beta"
+Version="4.2.0-beta-1"
 
 usage() {               # --help: show usage information
   echo "
@@ -108,6 +108,7 @@ Special options:
      --showenv         Echo new \$DISPLAY, \$XAUTHORITY and \$WAYLAND_DISPLAY.
                        For custom access to new X server. Get environment with:
                          read xenv < <(x11docker --showenv [...])
+     --showid          Echo container ID on stdout.
      --sudouser        Allow sudo and su for container user. Use with care,
                        severe reduction of default x11docker security!
                        Password:  x11docker
@@ -206,6 +207,7 @@ User settings:
                        You can specify a group id with N being 'user:gid'.
      --hostuser USER   Run X (and container user) as user USER. Default is
                        result of \$(logname). (x11docker must run as root).
+     --group-add GROUP Additional group GROUP for container user.
                          
 Init system and dbus daemon:
      --tini            Default: init system tini (built-in of docker).
@@ -359,14 +361,14 @@ error() {               # show error messages on stderr and exit
   # output to terminal
 echo -e "
 \033[41mx11docker ERROR:\033[49m $Message
-" >&2
+" >&3
   # output to X dialogbox
   [ -n "$Hostxenv" ] && export $Hostxenv
   [ -n "$Newxenv" ] && {
     [ "$Tty" = "yes" ] && export $Newxenv
     [ "$Xserver" = "--xorg" ] && export $Newxenv
   }
-  alertbox "x11docker ERROR" "$Message"
+  [ "$Silent" = "no" ] && alertbox "x11docker ERROR" "$Message"
 
   # output to logfile
   [ -e "$Logfile" ] && echo "x11docker ERROR: $Message
@@ -1003,7 +1005,6 @@ Sharevolumes=""                                 # option --volume: host folders 
 Sharevolumescount="0"                           # counts shared folders in array
 Shareclipboard="no"                             # option '-c, --clipboard' enable clipboard sharing
 Shareclipboardscript=clipboard.bash             #    "              "      script used for text clipboard sharing
-Showdisplayenvironment="no"                     # option -E, --env: Show environment variables of new display
 Customenvironment=""                            # option '--env': set custom environment variables 
 Pulseaudio="no"                                 #   "                    use pulseaudio yes/no
 Pulseserver=""
@@ -1021,6 +1022,8 @@ Verbose="no"                                    # option '-v, --verbose': if "ye
 Showstdout="no"                                 # option --stdout: show image command stdout
 Showstderr="no"                                 # option --stderr: show image command stderr
 Silent="no"                                     # option --silent: do not show messages
+Showdisplayenvironment="no"                     # option -E, --env: output of environment variables of new display on stdout
+Showcontainerid="no"                            # option --showid: output of container id on stdout
 Verbosecolors="yes"                             # colored output for --verbose and deleting some systemd error messages. currently without option.
 Debug="no"                                      # option --debug: Throw it all out
 DebugPS4='+ \033[32m${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}(): }\033[0m'
@@ -1092,9 +1095,9 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
   Longoptions="$Longoptions,no-xhost,trusted,untrusted,dbus,dbus-system,pw:,no-internet,workdir:"                          # advanced options
   Longoptions="$Longoptions,tini,no-init,systemd,runit,openrc,sysvinit,sys-admin,sharecgroup"                              # init system options
   Longoptions="$Longoptions,starter,cleanup,license,licence,help,version,install,update,update-master,remove,wmlist"       # special options without starting X server
-  Longoptions="$Longoptions,xhost:,no-auth,vt:,display:,xtest,no-xtest,env:,showenv"                                       # X and environment options
+  Longoptions="$Longoptions,xhost:,no-auth,vt:,display:,xtest,no-xtest,env:,showenv,showid"                                # X and environment options
   Longoptions="$Longoptions,verbose,stdout,stderr,silent,debug"                                                            # verbose options
-  Longoptions="$Longoptions,hostipc,hostnet,ps,cache,cap-default,no-entrypoint,sudouser,hostuser:"                         # capabilities, users
+  Longoptions="$Longoptions,hostipc,hostnet,ps,cache,cap-default,no-entrypoint,sudouser,hostuser:,group-add:"              # capabilities, users
   Longoptions="$Longoptions,cachedir:,homedir:,westonini:,sharedir:,keymap:,add:"                                          # developer options
   Longoptions="$Longoptions,xsocket,tcp,tcpxsocket,virtualgl,glamor,volume:,xhost+,resizeable,orphaned,rw"                 # deprecated
   Longoptions="$Longoptions,xpra-image,xpra-attach,xorg-image,xdummy-image,kwin-native,nopwd,no-password,root,sudo"        # deprecated
@@ -1181,15 +1184,9 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
      #### Developer options
        ## User settings
          --user)       Benutzer="${2:-}"  ; shift ;;       # set container user instead of host user
-         --hostuser)   Hostuser="${2:-0}"                  # set host user different from logged in user
-                       [ "$(echo $Hostuser | cut -c1)" = "-" ] && {  ### FIXME: fuzzy validation, not reliable
-                         warning "You are using --hostuser without an argument.
-  Maybe you are using it in deprecated form to have container user similar
-  to host user. That is default now. Now, option --hostuser expects an 
-  argument to specify a different user than default user $(logname)"
-                         Hostuser=""
-                       } || shift ;;
+         --hostuser)   Hostuser="${2:-}" ; shift ;;        # set host user different from logged in user
          --sudouser)   Sudouser="yes" ;;                   # give container user sudo without password
+         --group-add)  Groupadd="$Groupadd ${2:-}" ; shift ;; # additional groups for user
          
        ## init system
          --no-init)    Initsystem="none" ;;                # no init, image command is PID 1
@@ -1205,6 +1202,7 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
   Please use --dbus-system in future." ;;                  
          
        ## Environment
+         --showid)     Showcontainerid="yes" ;;            # output of container id on stdout
          --showenv)    Showdisplayenvironment="yes" ;;     # output of display number and cookie file on stdout. Catch with  ~$ read xdenv < <(x11docker --showenv)
          --env)        Customenvironment="$(escapestring "${2:-}")
 $Customenvironment"    ;  shift ;;                         # set custom environment variables
@@ -2152,7 +2150,8 @@ Parsed options: $Parsedoptions"
   
   Cmdstdinfile="$Sharefolder/$Cmdstdinfile"                 && mkfile $Cmdstdinfile
   Cmdstdoutlogfile="$Sharefolder/$Cmdstdoutlogfile"         && mkfile $Cmdstdoutlogfile 666
-  Cmdstderrlogfile="$Sharefolder/$Cmdstderrlogfile"         && mkfile $Cmdstderrlogfile 666 
+  Cmdstderrlogfile="$Sharefolder/$Cmdstderrlogfile"         && mkfile $Cmdstderrlogfile 666
+  mkfile "$Sharefolder/environment"
   
   # catch stdin (submitted in x11docker.CMD.sh)
   [ -t 0 ] || cat >> $Cmdstdinfile
@@ -3438,6 +3437,10 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   --group-add $Hostgidaudio"
         [ "$Hostgidvideo" ] && Dockercommand="$Dockercommand \\
   --group-add $Hostgidvideo"
+        for Line in $Groupadd; do
+          Dockercommand="$Dockercommand \\
+  --group-add $Line"
+        done
       }
       
       # especially needed for --systemd, but others, too
@@ -3596,6 +3599,8 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   [ "$Debug" = "yes" ] && echo "echo 'set -x'"
   echo "  echo '# created startscript for docker run: x11docker.CMD.sh'"
   echo "  echo '# runs as unprivileged user in container'"
+  echo "  echo 'echo x11docker: Running unprivileged user commands in container'"
+
   echo '  echo Imagecommand="\"$Imagecommand\""'
   echo '  echo Entrypoint="\"$Entrypoint\""'
   echo "  echo ''"
@@ -3700,12 +3705,13 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "  echo ''"
   
   echo "  echo 'echo x11docker: container environment:'"
-  echo "  echo 'env > $Cshare/environment'"
+  echo "  echo 'env >> $Cshare/environment'"
   echo "  echo 'sed -i \"/\(PWD=\|_=\)/d\" $Cshare/environment'"
   echo "  echo 'env | sort'"
   echo "  echo 'echo x11docker: copy of environment stored in $Cshare/environment'"
   echo "  echo ''"
 
+  echo "  echo \"echo x11docker: running image command: \\\$Dbus \$Entrypoint \$Imagecommand\""
   [ -s "$Cmdstdinfile" ] && echo "  echo \"cat $Cshare/stdin | \\\$Dbus \$Entrypoint \$Imagecommand >>$Cshare/stdout 2>>$Cshare/stderr\""
   [ -s "$Cmdstdinfile" ] || echo "  echo                \"exec \\\$Dbus \$Entrypoint \$Imagecommand >>$Cshare/stdout 2>>$Cshare/stderr\""
 
@@ -3751,11 +3757,10 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "read Containerid < <($Dockercommand)" # <- docker run is here!
   
   echo ""
-  echo "[ -z \"\$Containerid\" ] && echo 'x11docker ERROR: Startup of docker failed.' && exit 1"
+  echo "[ -z \"\$Containerid\" ] && echo 'x11docker ERROR: Startup of docker failed. >&2' && exit 1"
   echo "echo x11docker: container ID: \$Containerid"
   echo "echo \$Containerid >> $Containeridfile"
-  echo "note 'Container ID:'"
-  echo "notestdout \"\$(cat $Containeridfile)\""
+  [ "$Showcontainerid" = "yes" ] && echo "notestdout \"\$(cat $Containeridfile)\""
   echo "docker logs -f \$Containerid >> $Dockerlogfile 2>&1 &"
   echo ""
   echo "# wait for container to be ready"
@@ -3763,7 +3768,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "  sleep 0.2"
   echo "  docker exec $Containername sh -c : && { echo 'x11docker: container is up and running.' ; break ; } || echo \"x11docker: container not ready on \$Count. attempt, trying again.\" "
   echo "done"
-  echo "cat $Dockerlogfile | grep -E 'Error response from daemon|OCI runtime exec' ||:"  # repeat possible error message to make it visible in error() after verbose Count loop
+  echo "cat $Dockerlogfile | grep -E 'Error response from daemon|OCI runtime exec' && exit 1"  # repeat possible error message to make it visible in error() after verbose Count loop
   echo ""
 
   
@@ -3784,6 +3789,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "# set up docker container as root before ongoing in unprivileged x11docker.CMD.sh"
   echo "# commands in this script are executed as root in container"
   [ "$Debug" = "yes" ] && echo "set -x"
+  echo "echo x11docker: setup as root in container"
   echo ""
   echo "# create some system dirs with needed permissions"
   echo "mkdir -v -p /var/lib/dbus /var/run/dbus"
@@ -3825,7 +3831,10 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "[ \"\$Gidvideo\" ] || Gidvideo=\$(getent group | grep video: | cut -d: -f3)"
   echo "[ \"\$Gidaudio\" ] || Gidaudio=\$(getent group | grep audio: | cut -d: -f3)"
   echo "getent group | sed \"s/^video.*/video:x:\$Gidvideo:\$(getent group | grep video: | cut -d: -f4 ),$Benutzer/ ;"
-  echo "                     s/^audio.*/audio:x:\$Gidaudio:\$(getent group | grep audio: | cut -d: -f4 ),$Benutzer/ ;;"
+  echo "                     s/^audio.*/audio:x:\$Gidaudio:\$(getent group | grep audio: | cut -d: -f4 ),$Benutzer/ ;"
+  for Line in $Groupadd ; do
+    echo "                     s/^$Line.*/\0,$Benutzer/ ;"
+  done
   echo "                     s/^systemd-journal.*/\0,$Benutzer/ \" | sed 's/:,/:/' > /tmp/group"
   echo "cp /tmp/group /etc/group"
   echo ""
@@ -4682,6 +4691,8 @@ $(tail $Compositorlogfile)"
 
 ######### ToDo notes for development
 todo() {
+# ssh -X -- command fails. why?
+# --group-add: compare host and container GID? warn if group misses in container?
 # --fullscreen: --weston[-x] in weston crashes. Use X backend if DISPLAY is available.
 # work on traperror(). 'set -u' possible without a stop?
 # --update: regard possible location in /opt
