--gpu: NVIDIA note for wiki article

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -2282,6 +2282,7 @@ setup_gpu() {                   # option --gpu: share /dev/dri and check nvidia 
     [ "$Containersetup" = "no" ] && {
       note "Options --no-setup --gpu: Cannot install NVIDIA driver
   with option --no-setup. Fallback: Disabling option --gpu"
+      check_fallback
       Sharegpu="no"
       return 1
     }
@@ -2292,12 +2293,15 @@ setup_gpu() {                   # option --gpu: share /dev/dri and check nvidia 
     store_runoption cap CHOWN
     store_runoption cap FOWNER
 
-  [ "$Xcontainer" = "yes" ] && {
-    waitforlogentry "start_xcontainer()" "$Xinitlogfile" "X server container is ready" || return 1
-    note "Option --gpu: Installing NVIDIA driver in X container."
-    unpriv_xcbackend "$Xcontainerbackend exec --tty --privileged --user=root $Xcontainername bash $Sharefolder/nvidia_installer" >> "$Xinitlogfile" 2>&1 || note 'ERROR: NVIDIA driver installation in X container failed.'
-  }
-  
+    note "Option --gpu: x11docker will install NVIDIA driver in container.
+  You can provide images with pre-installed drivers to speed up container start.
+  Compare: https://github.com/mviereck/x11docker/wiki/NVIDIA-driver-support-for-docker-container"
+
+    [ "$Xcontainer" = "yes" ] && {
+      waitforlogentry "start_xcontainer()" "$Xinitlogfile" "X server container is ready" || return 1
+      note "Option --gpu: Installing NVIDIA driver in X container."
+      unpriv_xcbackend "$Xcontainerbackend exec --tty --privileged --user=root $Xcontainername bash $Sharefolder/nvidia_installer" >> "$Xinitlogfile" 2>&1 || note 'ERROR: NVIDIA driver installation in X container failed.'
+    }
     return 0
   }
 
@@ -5354,7 +5358,9 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
         esac
         echo         "echo \"Requesting \$Trusted cookie from X server\""
         echo         "xauth -v -n -i -f $Xclientcookie generate $Newdisplay . \$Trusted timeout 3600"
-        echo         "[ '$Xserver' = '--hostdisplay' ] && [ -n \"\$Hostcookie\" ] && sed -i /\$Hostcookie/d $Xclientcookie"
+        [ "$Xserver" = '--hostdisplay' ] && {
+          echo       "[ -n \"\$Hostcookie\" ] && sed -i /\$Hostcookie/d $Xclientcookie"
+        }
         echo         "[ -s '$Xclientcookie' ] || { "
         echo         "  :"
         case "$Xauthentication" in
@@ -5365,13 +5371,15 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
           ;;
         esac
         echo         "}"
-        echo         "[ ! -s '$Xclientcookie' ] && [ '$Xserver' = '--hostdisplay' ] && {"
-        echo         "  [ -n \"\$Hostcookie\" ] && {"
-        echo         "    debugnote 'xinitrc() --hostdisplay: Failed to retrieve cookie from X server.
+        [ "$Xserver" = "--hostdisplay" ] && {
+          echo       "[ ! -s '$Xclientcookie' ] && {"
+          echo       "  [ -n \"\$Hostcookie\" ] && {"
+          echo       "    debugnote 'xinitrc() --hostdisplay: Failed to retrieve cookie from X server.
   Maybe your X server misses extension SECURITY. Will bake one with host cookie.'"
-        echo         "    xauth -v -n -i -f $Xclientcookie add :$Newdisplaynumber . \$Hostcookie"
-        echo         "  }"
-        echo         "}"
+          echo       "    xauth -v -n -i -f $Xclientcookie add :$Newdisplaynumber . \$Hostcookie"
+          echo       "  }"
+          echo       "}"
+        }
         echo         "[ -s '$Xclientcookie' ] || { "
         echo         "  # still no cookie? try to create one without extension security"
         echo         "  debugnote 'xinitrc(): Failed to retrieve trusted cookie from X server. Will bake one directly with xauth'"
