`/etc/shadow`: fixed fedora issue with `000` file access. (#53)

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4584,19 +4584,21 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   # create container user
   echo "# create user entry in /etc/passwd (and delete possibly existing same uid)"
   echo "getent passwd | grep -v \$(getent passwd $Benutzeruid || echo USERNOTFOUND) > /tmp/passwd"
+  echo "# disable possible /etc/shadow passwords for other users"
+  echo "sed -i s%:x:%:-:% /tmp/passwd"
   echo "echo $Benutzerpasswdentry >> /tmp/passwd"
-  echo "mv /tmp/passwd /etc/passwd"
-  echo ""
-  echo "# make sure root has no password in /etc/shadow"
-  echo "sed -i /root.*/d /etc/shadow"
-  case $Sudouser in
-    no)  echo "echo 'root:*:17219:0:99999:7:::' >> /etc/shadow" ;;
-    yes) echo "echo 'root:$Benutzerpasswort:17219:0:99999:7:::' >> /etc/shadow  # with option --sudouser, set root password 'x11docker'" ;;
-  esac
+  echo "rm /etc/passwd"
+  echo "mv /tmp/passwd /etc/passwd || warning 'Unable to change /etc/passwd. That may be a seurity risk.'"
   echo ""
   echo "# create password entry for container user in /etc/shadow"
-  echo "sed -i /$Benutzer.*/d /etc/shadow # delete user entry if already existing"
-  echo "echo \"$Benutzer:$Benutzerpasswort:17293:0:99999:7:::\" >> /etc/shadow"
+  echo "rm -v /etc/shadow || warning 'Cannot change /etc/shadow. That may be a security risk.'"
+  echo "echo \"$Benutzer:$Benutzerpasswort:17293:0:99999:7:::\" > /etc/shadow"
+  case $Sudouser in
+    no)  echo "echo 'root:*:17219:0:99999:7:::' >> /etc/shadow" ;;
+    yes) echo "echo 'root:$Benutzerpasswort:17219:0:99999:7:::' >> /etc/shadow  # with option --sudouser, set root password 'x11docker'" 
+         echo "sed -i s%root:-:%root:x:% /etc/passwd                            # allow password in /etc/shadow"
+    ;;
+  esac
   echo ""
   echo "# add user to groups video, audio, systemd-journal"
   echo "# replace container GIDs of video and audio with host GIDs"
@@ -4622,7 +4624,8 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   
   # sudo configuration
   echo "# create /etc/sudoers, delete /etc/sudoers.d. Overwrite possible sudo setups in image."
-  echo "rm -v -R /etc/sudoers.d /etc/sudoers"
+  echo "[ -e /etc/sudoers.d ] && rm -v -R /etc/sudoers.d"
+  echo "[ -e /etc/sudoers ]   && rm -v /etc/sudoers"
   echo "echo '# /etc/sudoers created by x11docker' > /etc/sudoers"
   echo "echo 'root ALL=(ALL) ALL'                 >> /etc/sudoers"
   [ "$Sudouser" = "yes" ] && echo "echo '$Benutzer ALL=(ALL) ALL' >> /etc/sudoers"
@@ -4632,10 +4635,10 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   [ "$Sudouser" = "no" ] && {
     echo "# restrict PAM configuration of su and sudo"
     echo "echo 'auth sufficient pam_rootok.so' > /etc/pam.d/su  # allow root to switch user without a password" 
-    echo "rm -v /etc/pam.d/sudo"
+    echo "[ -e /etc/pam.d/sudo ] && rm -v /etc/pam.d/sudo"
     echo ""
   }
-
+  
   # --gpu with closed source nvidia driver
   [ "$Nvidiadriver" ] && {
     echo "Installationwillsucceed=maybe"
