--xwin: support in MSYS2, maybe WSL, too. Will be dropped again. #148 #160

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1879,7 +1879,7 @@ check_xdepends() {              # check dependencies on host for X server option
     no)  Message="note" ;;
   esac
   case ${1:-} in
-    --xephyr|--xpra|--nxagent|--xorg|--xvfb|--xdummy|--xwayland|--weston-xwayland|--kwin-xwayland|--xwin)
+    --xephyr|--xpra|--nxagent|--xorg|--xvfb|--xdummy|--xwayland|--weston-xwayland|--kwin-xwayland)
       command -v xinit >/dev/null || {
         $Message "${1:-}: xinit not found."
         Return=1
@@ -1939,28 +1939,30 @@ check_xdepends() {              # check dependencies on host for X server option
         Return=1
       } ;;
     --xwin)
-      command -v "xwin" >/dev/null || {
+      command -v "$Cygwinpath/bin/XWin.exe" >/dev/null || {
         $Message "${1:-}: Xwin not found. 
-  Need 'xinit' package from Cygwin (X11 section)."
+  Need 'xinit' package in Cygwin (X11 section)."
         Return=1
       }
-      command -v "xwininfo.exe" >/dev/null || {
+      command -v "$(convertpath --subsystem "$Xwininfoexe")" >/dev/null || {
         $Message "${1:-}: xwininfo.exe not found. 
-  Need 'xwininfo' package from Cygwin (X11 section)."
+  Need 'xwininfo' package either from Cygwin (X11 section) or in VcXsrv."
         Return=1
-      } ;;
+      }
+      ;;
     --vcxsrv)
-      Vcxsrvpath="$(convertpath --subsystem "C:/Program Files/VcXsrv/vcxsrv.exe")"
-      command -v "$Vcxsrvpath" >/dev/null || {
+      Vcxsrvexe="$(convertpath --subsystem "$Vcxsrvpath/vcxsrv.exe")"
+      #Vcxsrvexe="$(escapestring "$Vcxsrvexe")"
+      command -v "$Vcxsrvexe" >/dev/null || {
         $Message "${1:-}: X server VcXsrv not found."
         Return=1
         [ "$Winsubsystem" ] && note "To run x11docker within MSYS2, Cygwin or WSL on MS Windows,
-  please install X server VcXsrv (or Xwin on Cygwin).
+  please install either X server VcXsrv or Xwin on Cygwin.
   Searching for vcxsrv.exe in: 
     C:/Program Files/VcXsrv"
+#      [ -d "$Vcxsrvpath" ] && export PATH="${PATH:-}:$Vcxsrvpath"
       }
-      Vcxsrvpath="$(echo "$Vcxsrvpath" | rev | cut -d/ -f2- | rev)"
-      [ -d "$Vcxsrvpath" ] && export PATH="${PATH:-}:$Vcxsrvpath"
+#      Vcxsrvpath="$(echo "$Vcxsrvpath" | rev | cut -d/ -f2- | rev)"
       [ -z "$Winsubsystem" ] && Return=1 && $Message "${1:-}: X server VcXsrv is available on MS Windows only."
     ;;
   esac
@@ -2206,7 +2208,7 @@ check_newxenv() {               # find free display, create $Newxenv
   [ "$Newdisplaynumber" ] || for ((Newdisplaynumber=100 ; Newdisplaynumber <=1000 ; Newdisplaynumber++)); do
     [ -n "$(find /tmp/.X11-unix/X$Newdisplaynumber /tmp/.X$Newdisplaynumber-lock ${XDG_RUNTIME_DIR:-}/wayland-$Newdisplaynumber 2>/dev/null)" ] || { 
       case $Xserver in
-        --vcxsrv|--xwin) grep -q -E 'Authorization|Absolute' <<< "$(xwininfo.exe -display $Hostip:$Newdisplaynumber -root 2>&1)" || break ;;
+        --vcxsrv|--xwin) grep -q -E 'Authorization|Absolute|MIT-MAGIC-COOKIE' <<< "$(wincmd "$Xwininfoexe -display $Hostip:$Newdisplaynumber -root")" || break ;;
         *) break ;;
       esac
     }
@@ -2977,8 +2979,8 @@ esac
     ;;
 
     --vcxsrv|--xwin)
-      [ "$Xserver" = "--vcxsrv" ] && Xcommand="$(escapestring "$Vcxsrvpath")/vcxsrv.exe :$Newdisplaynumber"
-      [ "$Xserver" = "--xwin" ]   && Xcommand="$(command -v Xwin) :$Newdisplaynumber"
+      [ "$Xserver" = "--vcxsrv" ] && Xcommand="$Vcxsrvexe :$Newdisplaynumber"
+      [ "$Xserver" = "--xwin" ]   && Xcommand="$Cygwinpath/bin/Xwin :$Newdisplaynumber"
       
       Xcommand="$Xcommand \\
   $Xserveroptions \\
@@ -4384,7 +4386,6 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo "Windowmanagercommand=\"$Windowmanagercommand\""
   echo "Wmdockercommand=\"$Wmdockercommand\""
   echo '[ "$Windowmanager" = "container" ] && {'
-#  echo '  Windowmanagercommand="${Windowmanagercommand:-x11docker/openbox sh -c "openbox --config-file /etc/x11docker/openbox-nomenu.rc"}"'
   echo "  $Dockerexe inspect \"\$(cut -d' ' -f1 <<<\"\$Windowmanagercommand\")\" >>$Containerlogfile 2>&1 && {"
   echo '    Wmdockercommand="$Wmdockercommand \
   -- $Windowmanagercommand"'
@@ -4419,7 +4420,7 @@ $Wmdockercommand"'
   echo "  command -v '$Hostwindowmanager' >/dev/null || note 'Did not find a host window manager.
   Please pull image x11docker/openbox or provide one of:
   $Wm_good'"
-  echo "  note 'Option --wm: Starting host window manager: $Hostwindowmanager'"
+  echo "  note 'Option --wm: Starting host window manager: ${Hostwindowmanager:WM_NOT_FOUND}'"
   echo "  [ \"\$(id -u)\" = '0' ]  && su $Hostuser -c 'env $Newxenv ${Hostwindowmanager:-NO_WM_FOUND} >>$Xinitlogfile 2>&1 & storepid \$! windowmanager'"
   echo "  [ \"\$(id -u)\" != '0' ] &&                  env $Newxenv ${Hostwindowmanager:-NO_WM_FOUND} >>$Xinitlogfile 2>&1 & storepid \$! windowmanager"
   echo '}'
@@ -5411,8 +5412,8 @@ start_hostexe() {               # options --exe, --xonly: Run host executeable i
     echo "for i in 3 4 6 7 8 9; do"
     echo "  { >&\$i ;} 2>/dev/null && exec >&\$i-"
     echo "done"
-    [ "$Windowmanager" ] && {
-      echo "  note 'Option --wm: Starting host window manager: $Hostwindowmanager'"
+    [ "$Windowmanager" = "host" ] && {
+      echo "  note 'Option --wm: Starting host window manager: ${Hostwindowmanager:-WM_NOT_FOUND}'"
       echo "  ${Hostwindowmanager:-NO_WM_FOUND} >>$Xinitlogfile 2>&1 & storepid \$! windowmanager"
     }
     echo "\$Dbus $Hostexe $( [ "$Forwardstdin" = "yes" ] && echo "<$Cmdstdinfile") >>$Cmdstdoutlogfile 2>>$Cmdstderrlogfile &"
@@ -5479,7 +5480,22 @@ start_xserver() {               # start X server
   case $Xserver in
     --xpra|--xephyr|--xdummy|--xvfb|--xwayland|--nxagent|--weston-xwayland|--kwin-xwayland|--xpra-xwayland|--xdummy-xwayland)
       $Mksu "exec env WAYLAND_DISPLAY=$Newwaylandsocket      xinit $Xinitrc -- $Xcommand             >> $Xinitlogfile  2>&1 " ;;
-    --xwin) Xcommand="$(echo $Xcommand | sed 's/\\//g')" ;   xinit $Xinitrc -- $Xcommand             >> $Xinitlogfile  2>&1   ;;
+#    --xwin) Xcommand="$(echo $Xcommand | sed 's/\\//g')" ;   xinit $Xinitrc -- $Xcommand             >> $Xinitlogfile  2>&1   ;;
+    --xwin) 
+      set -x
+      Xcommand="$(echo $Xcommand | sed 's/\\//g')"
+      #wincmd "$Cygwinpath/bin/xinit $Xinitrc -- $Xcommand  >> $Xinitlogfile  2>&1 "
+      export -f wincmd
+      $Mksu "wincmd                                                           '$Xcommand'            >> $Xinitlogfile  2>&1 & echo \$! >$Cachefolder/Xserverpid"
+      Xserverpid=$(cat "$Cachefolder/Xserverpid")
+      [ "$Xserverpid" ] && {
+        storepid $Xserverpid Xserver
+        setonwatchpidlist $Xserverpid Xserver
+      } || error "Failed to receive PID of X server."
+      $Mksu "exec                                             bash $Xinitrc                          >> $Xinitlogfile  2>&1 "
+      set +x
+    ;;
+      #xinit $Xinitrc -- $Xcommand             >> $Xinitlogfile  2>&1   ;;
     --xorg)
       case $Xlegacywrapper in
         yes) $Mksu   "exec                                   xinit $Xinitrc -- $Xcommand             >> $Xinitlogfile  2>&1 " ;;
@@ -5497,11 +5513,11 @@ start_xserver() {               # start X server
         setonwatchpidlist $Xserverpid Xserver
       } || error "Failed to receive PID of X server."
       # Wait for VcXsrv to accept connections
-      for Count in $(seq -s' ' 25); do
-        sleep 0.2
-        verbose "$Count. access check for $Xserver"
-        grep -q -E 'Authorization|Absolute' <<< "$(xwininfo.exe -display $Newdisplay -root 2>&1)" && break
-      done
+#      for Count in $(seq -s' ' 25); do
+#        sleep 0.2
+#        verbose "$Count. access check for $Xserver"
+#        grep -q -E 'Authorization|Absolute|MIT-MAGIC-COOKIE' <<< "$(xwininfo.exe -display $Newdisplay -root 2>&1)" && break
+#      done
       # bug in WSL: WSL does not terminate Windows process on TERM for processes started in bash. Workaround to get Windows pid.
       [ "$Winsubsystem" = "WSL" ] && {
         Tasklistnew="$(tasklist.exe | rmcr | grep vcxsrv.exe | awk '{print $2}')"
@@ -5567,6 +5583,12 @@ check_host() {                  # check host environment
       [ -d "$(convertpath --subsystem "$Cygwinpath")" ] && break
     done
     [ -d "$(convertpath --subsystem "$Cygwinpath")" ] || Cygwinpath=""
+    
+    Vcxsrvpath="C:/Program Files/VcXsrv"
+    [ -d "$(convertpath --subsystem "$Vcxsrvpath")" ] || Vcxsrvpath=""
+    
+    [ -e "$(convertpath --subsystem $Vcxsrvpath/xwininfo.exe)" ]     && Xwininfoexe="$Vcxsrvpath/bin/xwininfo.exe"
+    [ -e "$(convertpath --subsystem $Cygwinpath/bin/xwininfo.exe)" ] && Xwininfoexe="$Cygwinpath/bin/xwininfo.exe"
   }
   
   # Check host IP. Needed for --pulseaudio=tcp, --vcxsrv and --xwin
@@ -5952,7 +5974,8 @@ check_option_interferences() {  # check multiple option interferences, change se
           warning "Command 'xauth.exe' not found.
   Please install Cygwin/X and make sure 'xauth.exe' is available.
   Securing X access with cookie authentication is not possible.
-  Fallback: Disabling X authentication protocol. (option --no-auth)"
+  Fallback: Disabling X authentication protocol. (option --no-auth)
+  Severe reduction of desired X server security!"
           Xauthentication="no"
         }
       ;;
@@ -6752,8 +6775,10 @@ declare_variables() {           # declare global variables
   Winpidlist=""                                   # List of stored Windows pids (currently vcxsrv.exe on WSL only)
   Winpty=""                                       # Path to winpty for --interactive on Windows
   Cygwinpath=""                                   # Path to cygwin64/bin on Windows
-  Vcxsrvpath=""                                   # path to vcxsrv.exe (--vcxsrv)
+  Vcxsrvexe=""                                    # Path to vcxsrv.exe (--vcxsrv)
+  Vcxsrvpath=""                                   # Path to VcXsrv program folder
   Xauthexe=""                                     # Path to 'xauth.exe' in Cygwin
+  Xwininfoexe=""                                  # Path to xwininfo.exe in Cygwin or VcXsrv
   
   # Gaining root privileges to run docker
   Passwordfrontend=""                             # --pw: method to prompt for password. one of pkexec, su, sudo, gksu, gksudo, kdesu, kdesudo, lxsu, lxsudo, beesu, auto, none
@@ -7084,7 +7109,6 @@ parse_options() {               # parse cli options
                          "host")                    Windowmanager="host" ;;
                          "container")               Windowmanager="container" ;;
                          ""|"auto"|"m")             Windowmanager="auto" ;;
-#                         *)                         Windowmanager="host"; Hostwindowmanager="${2:-}" ;;
                          *)                         Windowmanager="auto"; Windowmanagercommand="${2:-}" ;;
                        esac
                        shift ; Desktopmode="yes" ;;
