NVIDIA autoinstall: checked arch, debian, void, fedora, centos images

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -10,7 +10,7 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="4.2.0-beta-1"
+Version="4.2.0-beta"
 
 usage() {               # --help: show usage information
   echo "
@@ -2268,14 +2268,13 @@ Parsed options: $Parsedoptions"
   [ "$Gpu" = "yes" ] && [ -e "/proc/driver/nvidia" ] && {
     Nvidiaversion=$(cat /proc/driver/nvidia/version | head -n1 | awk '{ print $8 }')
     verbose "Detected nvidia driver $Nvidiaversion on host."
-    Nvidiadriver=$(ls $Cacherootfolder/NVIDIA* 2>/dev/null | grep $Nvidiaversion )
-    [ -e "$Nvidiadriver" ] && [ ! -x "$Nvidiadriver" ] && chmod +x $Nvidiadriver
-    [ -x "$Nvidiadriver" ] && {
+    Nvidiadriver=$(find /usr/share/x11docker/NVIDIA* $Hostuserhome/.local/share/x11docker/NVIDIA* $Cacherootfolder/NVIDIA* 2>/dev/null | grep $Nvidiaversion )
+    [ -e "$Nvidiadriver" ] && {
       verbose "Found proprietary closed source nvidia driver installer
   $Nvidiadriver"
       note "Will install closed source nvidia driver $Nvidiaversion in container.
-  That slows down container startup. 
-  Startup will be faster if image has package 'kmod' already installed.
+  That slows down container startup. Startup will be much faster if image 
+  already includes modprobe and xz (packages 'kmod' and 'xz').
   With free nouveau driver on host there would be no startup delay.
   Ask NVIDIA corp. to publish their closed source API and to support nouveau."
       Adminusercaps="yes"
@@ -2298,16 +2297,14 @@ Parsed options: $Parsedoptions"
     https://www.nvidia.com/Download/index.aspx
   A direct download URL may be:
     https://us.download.nvidia.com/XFree86/Linux-x86_64/$Nvidiaversion/NVIDIA-Linux-x86_64-$Nvidiaversion.run
-  If you got a driver, make it executeable with 'chmod +x' and move it to
-    $Cacherootfolder.
+  If you got a driver, store it at one of the following locations:
+    $Hostuserhome/.local/share/x11docker/
+    /usr/share/x11docker/
   Be aware that the version number must match exactly the version on host. 
   The file name must begin with 'NVIDIA', contain the version number $Nvidiaversion
   and end with suffix '.run'.
   To avoid all this, use free nouveau driver on host 
   instead of proprietary closed source nvidia driver."
-      [ -e "$Nvidiadriver" ] && [ ! -x "$Nvidiadriver" ] && warning "Found $Nvidiadriver
-  but it is not executeable. Please run:
-    chmod +x $Nvidiadriver"
     }
   }
 }
@@ -3904,25 +3901,26 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   }
   echo ""
   [ "$Nvidiadriver" ] && {
-    echo "[ -z \"\$(find . -name *${Nvidiaversion}* -print -quit)\" ] && {" 
+    echo "[ -z \"\$(find . -name *${Nvidiaversion}* -print 2>/dev/null)\" ] && {" 
     echo "  # Install nvidia driver"
-    echo "  /sbin/modprobe -V || {"
+    echo "  { command -v modprobe && command -v xz ; } || {"
     echo "    # Try to install modprobe"
-    echo "    echo 'x11docker WARNING: Did not find modprobe from package kmod."
-    echo "  Will try to install it. That slows down container startup.'"
-    echo "    apt-get update && apt-get install -y  kmod   # debian"
-    echo "    apk add --no-cache                    kmod   # alpine"
-    echo "    zypper install -n                     kmod   # opensuse"
-    echo "    dnf install -y kmod || yum install -y kmod   # fedora, centos"
-    echo "    pacman -S --noconfirm                 kmod   # arch"
-    echo "    xbps-install -Suy                     kmod   # void"
-    echo "    emerge --ask n                        kmod   # gentoo"
-    echo "    eopkg install                         kmod   # solus"
-    echo "    nix-env --install                     kmod   # nixos"
+    echo "    echo 'x11docker WARNING: Did not find modprobe/kmod or xz in image."
+    echo "  Will try to install them. That slows down container startup.'"
+    echo "    apt-get update && apt-get install -y  kmod xz-utils  # debian"         #ok
+    echo "    dnf install -y kmod || yum install -y kmod xz        # fedora, centos" #ok
+    echo "    xbps-install -Sy                      kmod xz        # void"           #ok
+    echo "    pacman -Sy --noconfirm                kmod xz        # arch"           #ok
+    echo "    apk add --no-cache                    kmod xz        # alpine"         #ok, but nvidia-installer FAILS: "line 1092: ./nvidia-installer: not found"
+    echo "    zypper --non-interactive install      kmod xz        # opensuse"       #ok, but nvidia-installer extraction FAILS
+    echo "    nix-env --install                     kmod xz        # nixos"          #ERROR: busybox-1.26.2-r5.trigger: script exited with error 127; /x11docker/NVIDIA-387.12.run: line 1092: ./nvidia-installer: not found
+    echo "    emerge --ask n                        kmod xz        # gentoo"         #NOT CHECKED
+    echo "    eopkg install                         kmod xz        # solus"          #NOT CHECKED
     echo "  }"
     echo "  echo 'x11docker WARNING: Installing proprietary closed source NVIDIA driver $Nvidiaversion. That slows down container startup.'"
     echo "  chmod +x $Cshare/NVIDIA-$Nvidiaversion.run"
-    echo "  $Cshare/NVIDIA-$Nvidiaversion.run  --accept-license --no-runlevel-check  --no-questions --ui=none --no-kernel-module --no-kernel-module-source --no-backup"
+    echo "  sh $Cshare/NVIDIA-$Nvidiaversion.run  --accept-license --no-runlevel-check  --no-questions --ui=none --no-kernel-module --no-kernel-module-source --no-backup"
+    echo "  [ \$? ] || echo 'x11docker ERROR: Installation of nvidia driver seems to have failed.'"
     echo "} || echo 'x11docker: NVIDIA driver $Nvidiaversion seems to be installed already."
     echo "  Skipping installation of $Cshare/NVIDIA-$Nvidiaversion.run'"
   }
@@ -4763,6 +4761,9 @@ $(tail $Compositorlogfile)"
 
 ######### ToDo notes for development
 todo() {
+# --runasroot: new option?
+# --add: change to --runfromhost?
+# BUG: ENTYPOINT (sbin/init or systemd fails with $Switchcontainruser=yes
 # ssh -X -- command fails. why?
 # --group-add: compare host and container GID? warn if group misses in container?
 # --fullscreen: --weston[-x] in weston crashes. Use X backend if DISPLAY is available.
