--xpra: parallel startup of server and clientsince r23060. --video-decoders=none #167

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -674,7 +674,13 @@ $(for Line in $Watchpidlist; do pspid $Line ; done)"
     [ "$Containername" ] && {
       # Container PID not watchable in MSYS2/Cygwin/WSL.
       $Dockerexe inspect $Containername >/dev/null 2>&1 || {
-        debugnote "watchpidlist: Container $Containername has terminated"
+        verbose -d "watchpidlist: Container $Containername has terminated"
+#        sleep 1
+#        verbose -d "
+#docker ps:
+#$($Dockerexe ps)
+#$Dockerexe inspect $Containername:
+#$($Dockerexe inspect $Containername)"
         saygoodbye "watchpidlist $Containername"
       }
     }
@@ -2665,6 +2671,7 @@ create_xcommand() {             # create command to start X server and/or Waylan
   $(check_xpraoption --socket-dirs="'$Cachefolder'") \\
   $(check_xpraoption --speaker=no) \\
   $(check_xpraoption --start-via-proxy=no) \\
+  $(check_xpraoption --video-decoders=none) \\
   $(check_xpraoption --video-encoders=none) \\
   $(check_xpraoption --webcam=no) \\
   $(check_xpraoption --xsettings=no)"
@@ -2677,7 +2684,7 @@ create_xcommand() {             # create command to start X server and/or Waylan
   $(check_xpraoption --keyboard-layout="'$Xkblayout'") \\
   $(check_xpraoption --keyboard-raw=yes)"
   
-#      Xpraoptions="$Xpraoptions  $(check_xpraoption --debug=all)"
+#      Xpraoptions="$Xpraoptions  $(check_xpraoption --debug=all)" ; Preservecachefiles="yes"  # Debugging only
   
       # xpra server command
       [ "$Desktopmode" = "yes" ] && Xpraservercommand="xpra start-desktop" || Xpraservercommand="xpra start"
@@ -2701,9 +2708,9 @@ create_xcommand() {             # create command to start X server and/or Waylan
       Xpraclientcommand="xpra attach :$Newdisplaynumber $Xpraoptions \\
   $(check_xpraoption --clipboard=$Shareclipboard) \\
   $(check_xpraoption --compress=0) \\
+  $(check_xpraoption --modal-windows=no) \\
   $(check_xpraoption --opengl=auto) \\
-  $(check_xpraoption --quality=100) \\
-  $(check_xpraoption --modal-windows=no)"
+  $(check_xpraoption --quality=100)"
       [ "$Fullscreen" = "yes" ]  && Xpraclientcommand="$Xpraclientcommand \\
   $(check_xpraoption --desktop-fullscreen=yes)"
       [ "$Scaling" ] && Xpraclientcommand="$Xpraclientcommand \\
@@ -2712,16 +2719,14 @@ create_xcommand() {             # create command to start X server and/or Waylan
   $(check_xpraoption --dpi="'$Dpi'")"
       [ "$Xpraborder" ] && Xpraclientcommand="$Xpraclientcommand \\
   $(check_xpraoption --border=$Xpraborder)"
-      case $X11dockermode in
-        run)
-          case "$Desktopmode" in
-            yes) Xpraclientcommand="$Xpraclientcommand \\
+      [ "$X11dockermode" = "run" ] && {
+        case "$Desktopmode" in
+          yes) Xpraclientcommand="$Xpraclientcommand \\
   $(check_xpraoption --title="'$Codename on $Newdisplay [in container] (shift+F11 toggles fullscreen)'")" ;;
-            no)  Xpraclientcommand="$Xpraclientcommand \\
+          no)  Xpraclientcommand="$Xpraclientcommand \\
   $(check_xpraoption --title="'@title@ [in container]'")" ;;
-          esac
-        ;;
-      esac
+        esac
+      }
       verbose -d "Xpra client command:
   $Xpraclientcommand"
     ;;
@@ -5338,11 +5343,13 @@ $(tail $Xpraserverlogfile)"
           echo "x11docker [$(timestamp)]: Starting Xpra server" >> $Xpraserverlogfile
           $Mksu "env $Newxenv GDK_BACKEND=x11 XPRA_OPENGL_DOUBLE_BUFFERED=1 $Xpraservercommand" >> $Xpraserverlogfile 2>&1 &
           Xpraserverpid=$! && storepid $Xpraserverpid xpraserver
-          waitforlogentry "xpra server" $Xpraserverlogfile 'xpra is ready' || {
-            rocknroll && error "Xpra server startup failed.
+          verlt "$Xprarelease" "r23060" && {
+            waitforlogentry "xpra server" $Xpraserverlogfile 'xpra is ready' || {
+              rocknroll && error "Xpra server startup failed.
   Last lines of Xpra server log:
 $(tail $Xpraserverlogfile)"
-            return 1
+              return 1
+            }
           }
         }
 
@@ -5351,7 +5358,7 @@ $(tail $Xpraserverlogfile)"
         [ -n "$Xpraclientpid" ] && note "Restarting Xpra client."
         verbose -d "Starting Xpra client"
         echo "x11docker [$(timestamp)]: Starting Xpra client" >> $Xpraclientlogfile
-        $Mksu "env $Hostxenv GDK_BACKEND=$GDK_BACKEND NO_AT_BRIDGE=1 $Xpraclientcommand" >> $Xpraclientlogfile 2>&1 &
+        $Mksu "env $Hostxenv GDK_BACKEND=$GDK_BACKEND NO_AT_BRIDGE=1 XPRA_MENU_ICONS=0 $Xpraclientcommand" >> $Xpraclientlogfile 2>&1 &
         Xpraclientpid=$! && storepid $Xpraclientpid xpraclient
         checkpid $Xpraclientpid && {
           while { checkpid $Xpraserverpid && checkpid $Xpraclientpid ; } do sleep 1 ; done
