--password: fix mkdir bug if ~/.config/x11docker does not exist #535 #537

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1902,13 +1902,12 @@ set_password() {                # option --password: set container user password
     read -rs -p "Please type in a new container user password (chars are invisible): " Password
     echo ""
     [ -z "$Password" ] && {
-      error "Empty input, password not changed."
+      error "Input empty, password not changed."
       return 1
     }
   }
   mkpasswd "$Password"
-
-  mkfolder "$(dirname "$Passwordfile")"
+  mkdir -p "$(dirname "$Passwordfile")" || error "Failed to create $(dirname "$Passwordfile")"
   echo "$Containeruserpassword" > "$Passwordfile"
   chmod 600                       "$Passwordfile"
   note "Option --password: Password changed, exiting."
