--nxagent: set keyboard='clone' #208

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="6.5.0"
+Version="6.5.1-beta"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -2979,11 +2979,7 @@ mode=$Screensize
       # set keyboard layout
       case $Xkblayout in
         "") # set layout from host.
-          command -v setxkbmap >/dev/null && {
-            Nxagentoptions="$Nxagentoptions,keyboard=$(setxkbmap -query | grep rules | awk '{print $2}')/$(setxkbmap -query | grep layout | awk '{print $2}')"
-          } || note "Could not check your keyboard layout due to missing setxkbmap
-  If you get mismatching keys, please install setxkbmap.
-  $Wikipackages"
+          Nxagentoptions="$Nxagentoptions,keyboard='clone'"
         ;;
         *) # --keymap
           Nxagentoptions="$Nxagentoptions,keyboard='evdev/$Xkblayout'"
@@ -2994,7 +2990,7 @@ mode=$Screensize
       echo "$Nxagentoptions" >> "$Nxagentoptionsfile"
       debugnote "$Xserver: Additional nxagent options: $Nxagentoptions"
       
-      # Workaround as nxagent ignores XAUTHORITY and fails to start if option -auth is given without containing the cookie fom host display. 
+      # Workaround as nxagent ignores XAUTHORITY and fails to start if option -auth is given without containing the cookie from host display. 
       # Option -ac above complies "xhost +" and is reverted in xinitrc.
       [ "$Xauthentication" = "yes" ] && unpriv "cp '$Hostxauthority' '$Xservercookie'"
         
@@ -5894,7 +5890,7 @@ start_xserver() {               # start X server
       unpriv "                                           bash  $Xinitrc                          >> $Xinitlogfile  2>&1 " ;;
   esac
 
-  [ $? != 0 ] && rocknroll && warning "X server $Xserver returned an error code.
+  [ $? != 0 ] && rocknroll && note "X server $Xserver returned an error code.
   Last lines of xinit logfile:
 $(tail $Xinitlogfile)
 
