--runtime: fix parsing of default runtime

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -2916,6 +2916,7 @@ check_xserver() {               # check chosen X server, auto-choose X server
     [ "$Scaling" ]              && [ "$Sharegpu" = "no" ]        && Xserver="--xpra2"
     [ "$Runsonconsole" = "yes" ]                                 && Xserver="--xorg"
     [ -z "$Hostdisplay" ]       && [ -n "$Hostwaylandsocket" ]   && Xserver="--xpra2"
+    [ -z "$Hostdisplay" ]       && [ -n "$Hostwaylandsocket" ]   && [ "$Desktopmode" = "yes"  ]  && Xserver="--weston-xwayland"
     [ "$Winsubsystem" ]                                          && Xserver="--runx"
     [ "$Winsubsystem" = "CYGWIN" ]                               && Xserver="--xwin"
     [ "$Setupwayland" = "yes" ] && { [ -n "$Hostwaylandsocket" ] && [ "$Desktopmode" = "no" ] && Xserver="--hostwayland" || Xserver="--weston" ; }
@@ -4483,13 +4484,15 @@ check_image() {                 # get some image information
 check_runtime() {               # option --runtime
   local Defaultruntime
 
-  Defaultruntime="$( { grep 'Default Runtime' <<< "$Backendinfo" ||: ;} | awk '{print $3}' )"
-  [ -z "$Defaultruntime" ] && Defaultruntime="runc"
-  [ -z "$Runtime" ]        && Runtime="$Defaultruntime"
+  case "$Backend" in
+    docker)  Defaultruntime="$(parse_inspect "$Backendinfo" "DefaultRuntime" | tr -d '"')" ;;
+    podman)  Defaultruntime="$(parse_inspect "$Backendinfo" "host"  "ociRuntime" "name" | tr -d '"')" ;;
+    nerdctl) Defaultruntime="" ;;
+  esac
 
+  [ -z "$Defaultruntime" ] && Defaultruntime="runc"
   debugnote "Default runtime: $Defaultruntime"
-  debugnote "All Runtimes:
-  $(grep 'Runtimes' <<< "$Backendinfo" ||: )"
+  [ -z "$Runtime" ]        && Runtime="$Defaultruntime"
 
   return 0
 }
@@ -8830,7 +8833,8 @@ setup_verbosity() {             # options --verbose, --stdout, --stderr
     $Xpraserverlogfile
     "
 
-  [ -n "$Verbose" ] && [ "$Verbose" != "yes" ] && Logfiles="$(grep -E "$Verbose" <<< "$Logfiles")"
+  [ -n "$Verbose" ] && [ "$Verbose" != "yes" ] && Logfiles="$(grep -E "$Verbose" <<< "$Logfiles")" # inofficial hack to optionally reduce log output
+  
   for Line in $Logfiles; do
     [ -e "$Line" ] && grep -q "/" <<< "$Line" && Logfiles="$Logfiles $Line"
   done
@@ -9685,7 +9689,7 @@ main() {
     ;;
     docker|podman|nerdctl)
       # Check whether docker daemon is running, get docker info
-      Backendinfo="$($Backendbin info 2>>$Containerlogfile)" || error "'$Backend info' failed.
+      Backendinfo="$($Backendbin info --format='{{json .}}' 2>>$Containerlogfile)" || error "'$Backend info' failed.
   If using docker: Is docker daemon running at all?
   Try to start docker daemon with 'systemctl start docker'.
   Last lines of log:
