update dependencies #137

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -49,28 +49,24 @@ Note that some applications might behave different than with a regular
 Unrestricted container setup is possible with --cap-default and/or --user=root
 
 Dependencies on host:
-  Depending on chosen options, x11docker needs some packages to be installed.
+  Depending on chosen options x11docker needs some packages to be installed.
   It will check for them on startup and show messages if some are missing.
-  List of possibly needed packages:
-   * most recommended to allow security and convenience:
+  Core list of possibly needed packages:
+   * Recommended to allow security and convenience:
        X servers: Xephyr xpra nxagent (on Windows: VcXsrv or Xwin)
-       X tools:   xauth xrandr xhost xinit
+       X tools:   xauth xclip xrandr xhost xinit
    * advanced GPU support:
        Desktop mode:  weston Xwayland
        Seamless mode: weston Xwayland xpra xdotool
-   * less important:
-       xclip xdpyinfo xdg-utils pulseaudio
-   * least important:
-       unzip wget xfishtank kwin_wayland Xvfb
-       xserver-xorg-legacy xserver-xorg-video-dummy
+  See also: https://github.com/mviereck/x11docker/wiki/Dependencies
 
 Dependencies in image:
-  Doesn't have dependencies inside of docker images, except for options:
+  Doesn't have dependencies inside of docker images except for a few features.
+  Most important:
    --gpu:  OpenGL packages, often already installed as package dependencies.
-   --pulseaudio: sound with pulseaudio needs pulseaudio on host and in image.
-   --lang: localedef to create missing language locales.
-   --dbus, --dbus-system, --hostdbus: needs dbus in image.
-   --init=systemd|openrc|runit|sysvinit: needs according init system in image.
+   --pulseaudio: Needs pulseaudio on host and pulseaudio client libs in image.
+   --printer: Needs cups on host and cups client libs in image.
+  See also: https://github.com/mviereck/x11docker/wiki/Dependencies
    
 Options:
      --help            display this message and exit.
@@ -1100,12 +1096,12 @@ installer() {                   # --install, --update, --update-master, --remove
           download "https://raw.githubusercontent.com/mviereck/x11docker/master/CHANGELOG.md" "CHANGELOG.md" || error "Could not download CHANGELOG.md from github."
           Releaseversion="v$(cat CHANGELOG.md | grep "## \[" | grep -v 'Unreleased' | head -n1 | cut -d[ -f2 | cut -d] -f1)"
           note "Downloading latest x11docker release $Releaseversion from github"
-          download "https://github.com/mviereck/x11docker/archive/$Releaseversion.zip" "x11docker-update.zip" || error "Could not download latest x11docker release from github"
+          download "https://github.com/mviereck/x11docker/archive/$Releaseversion.zip" "x11docker-update.zip" || error "Could not download latest x11docker release from github."
         ;;
       esac
 
       note "Unpacking archive"
-      unzip x11docker-update.zip || error "Could not unzip archive"
+      unzip x11docker-update.zip || error "Could not unzip archive."
 
       echo ""
       cd /tmp/x11docker-install/$(ls -l | grep drwx | rev | cut -d' ' -f1 | rev) || error "could not cd to /tmp/x11docker-update/$(ls -l | grep drwx | rev | cut -d' ' -f1 | rev)"
@@ -1124,7 +1120,7 @@ installer() {                   # --install, --update, --update-master, --remove
 
       note "Installing icon for x11docker with xdg-icon-resource"
       xdg-icon-resource install --context apps --novendor --mode system --size 64 "$(pwd)/x11docker.png" x11docker || warning "Could not install icon for x11docker.
-  Is 'xdg-icon-resource' installed on your system?"
+  Is 'xdg-icon-resource' (xdg-utils) installed on your system?"
       xdg-icon-resource uninstall --size 72 x11docker ||:  # deprecated icon size, may still be present.
 
       note "Creating application entry for x11docker"
@@ -1926,27 +1922,32 @@ check_xdepends() {              # check dependencies on host for X server option
   case ${1:-} in
     --xpra|--xpra-xwayland)
       command -v "xpra" >/dev/null || {
-        $Message "${1:-}: xpra not found."
+        $Message "${1:-}: xpra not found.
+  $Wikipackages"
         Return=1
       } ;;
     --xephyr)
       command -v "Xephyr" >/dev/null || command -v "Xnest" >/dev/null || {
-        $Message "${1:-}: Neither Xephyr nor Xnest found."
+        $Message "${1:-}: Neither Xephyr nor Xnest found.
+  $Wikipackages"
         Return=1
       } ;;
     --nxagent)
       command -v "nxagent" >/dev/null || {
-        $Message "${1:-}: nxagent not found."
+        $Message "${1:-}: nxagent not found.
+  $Wikipackages"
         Return=1
       } ;;
     --xvfb)
       command -v "Xvfb" >/dev/null || {
-        $Message "${1:-}: Xvfb not found."
+        $Message "${1:-}: Xvfb not found.
+  $Wikipackages"
         Return=1
       } ;;
     --xorg|--xdummy)
       command -v "Xorg" >/dev/null || {
-        $Message "${1:-}: Xorg not found."
+        $Message "${1:-}: Xorg not found.
+  $Wikipackages"
         Return=1
       } ;;
     --xwin)
@@ -1979,26 +1980,30 @@ check_xdepends() {              # check dependencies on host for X server option
   case ${1:-} in
     --weston|--xpra-xwayland|--weston-xwayland|--xdummy-xwayland)
       command -v "weston" >/dev/null || {
-        $Message "${1:-}: weston not found."
+        $Message "${1:-}: weston not found.
+  $Wikipackages"
         Return=1
       } ;;
     --kwin|--kwin-xwayland)
       command -v "kwin_wayland" >/dev/null || {
-        $Message "${1:-}: kwin_wayland not found."
+        $Message "${1:-}: kwin_wayland not found.
+  $Wikipackages"
         Return=1
       } ;;
   esac
   case ${1:-} in
     --xpra-xwayland|--weston-xwayland|--kwin-xwayland|--xwayland|--xdummy-xwayland)
       command -v "Xwayland" >/dev/null || {
-        $Message "${1:-}: Xwayland not found."
+        $Message "${1:-}: Xwayland not found.
+  $Wikipackages"
         Return=1
       } ;;
   esac
   case ${1:-} in
     --xpra-xwayland|--xdummy-xwayland)
       command -v "xdotool" >/dev/null || {
-        $Message "${1:-}: xdotool not found."
+        $Message "${1:-}: xdotool not found.
+  $Wikipackages"
         Return=1
       } ;;
   esac
@@ -2078,7 +2083,8 @@ check_screensize() {            # check physical and virtual screen size (also o
     }
     [ -z "$Maxxaxis" ] && note "Could not determine your screen size.
   Please improve this by installing one of xrandr, xdpyinfo or xwininfo.
-  Or use option --size=XxY."
+  Or use option --size=XxY.
+  $Wikipackages"
   }
   
   case $Xserver in
@@ -2124,7 +2130,8 @@ check_screensize() {            # check physical and virtual screen size (also o
           note "Could not determine size of your primary display to
   create a roughly maximized window for $Xserver.
   Please install xrandr or use option --size=XxY.
-  Fallback: setting virtual screen size 800x600"
+  Fallback: setting virtual screen size 800x600
+  $Wikipackages"
           Xaxis="800"
           Yaxis="600"
         }
@@ -2179,7 +2186,8 @@ disable_xhost() {               # remove any access to X server granted by xhost
   command -v xhost >/dev/null || {
     warning "Command 'xhost' not found.
   Can not check for possibly allowed network access to X.
-  Please install 'xhost'."
+  Please install 'xhost'.
+  $Wikipackages"
     return 1
   }
   xhost 2>&1 | rmcr | tail -n +2  /dev/stdin | while read -r Line ; do  # read all but the first line (header)
@@ -2606,7 +2614,8 @@ create_xcommand() {             # create command to start X server and/or Waylan
           Dpi=$(xdpyinfo | grep dots | cut -dx -f2 | cut -d' ' -f1)
         } || {
           [ -n "$Hostdisplay" ] && [ -z "$(command -v xdpyinfo)" ] && note "Could not determine dpi settings. If you encounter too big or
-  too small fonts with $Xserver, please install xdpyinfo or use option --dpi."
+  too small fonts with $Xserver, please install xdpyinfo or use option --dpi.
+  $Wikipackages"
         }
         case $Xserver in
           --xpra|--xpra-xwayland)
@@ -2784,7 +2793,8 @@ $(tail "$Compositorlogfile")"
         note "Xephyr not found. Fallback: using Xnest.
   Xnest is less stable and has less features than Xephyr.
   For example, it misses RandR and Composite extensions and fullscreen mode.
-  It is recommended to install 'Xephyr'."
+  It is recommended to install 'Xephyr'.
+  $Wikipackages"
       }
     ;;
 
@@ -2907,7 +2917,8 @@ mode=$Screensize
           command -v setxkbmap >/dev/null && {
             Nxagentoptions=$Nxagentoptions,keyboard=$(setxkbmap -query | grep rules | rev | cut -d" " -f1 | rev)/$(setxkbmap -query | grep layout | rev | cut -d" " -f1 | rev)
           } || note "Could not check your keyboard layout due to missing setxkbmap
-  If you get mismatching keys, please install setxkbmap."
+  If you get mismatching keys, please install setxkbmap.
+  $Wikipackages"
         ;;
         *) # --keymap
           Nxagentoptions=$Nxagentoptions,keyboard="evdev/$Xkblayout"
@@ -3145,7 +3156,8 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
               *)  setxkbmap "$Xkblayout" -print >> $Xkbkeymapfile ;;
             esac
           } || {
-            note "setxkbmap not found. Need setxkbmap and xkbcomp to set keyboard layout."
+            note "setxkbmap not found. Need setxkbmap and xkbcomp to set keyboard layout.
+  $Wikipackages"
           }
           [ -s "$Xkbkeymapfile" ] && {
             echo "#"
@@ -3723,7 +3735,8 @@ setup_hostdbus() {              # option --hostdbus: connect to host DBus sessio
   Creating abstract DBus socket with dbus-launch."
     } || note "Option --hostdbus: Is DBus running on host?
   Did not find an active session and did not find dbus-launch.
-  DBUS_SESSION_BUS_ADDRESS is empty."
+  DBUS_SESSION_BUS_ADDRESS is empty.
+  $Wikipackages"
   }
     
   grep -q "unix:path" <<< "$Busadress" && {
@@ -4820,11 +4833,15 @@ exit 0\" >> /etc/rc.local"
     echo "echo \"\$Locales\" | grep -q \$Langland.utf8  && Langcontainer=\$Langland.utf8"
     echo "[ -z \"\$Langcontainer\" ] && {"
     echo "  [ -e /usr/share/i18n/SUPPORTED ] || note \"Option --lang: /usr/share/i18n/SUPPORTED not found.
-  Please install 'locale' package in image (belongs to glibc)\""
+  Please install 'locale' package in image (belongs to glibc).
+  Look here to find a package for your image system:
+  https://github.com/mviereck/x11docker/wiki/dependencies#dependencies-in-image\""
     echo "  Langcontainer=\$Langland.utf8"
     echo "  verbose -d \"Option --lang: Generating language locale \$Langcontainer\"."
     echo "  command -v localedef >/dev/null || note 'Command localedef not found in image.
-  Need it for language locale creation (--lang).'"
+  Need it for language locale creation (--lang).
+  Look here to find a package for your image system:
+  https://github.com/mviereck/x11docker/wiki/dependencies#dependencies-in-image'"
     echo "  localedef --verbose --force -i \$Langland -f UTF-8 \$Langcontainer || verbose \"localedef exit code: \$?\""
     echo "  locale -a | grep -q \"\$Langcontainer\" || {"
     echo "    note \"Option --lang: Generation of locale \$Langcontainer failed.\""
@@ -5537,7 +5554,8 @@ check_option_interferences() {  # check multiple option interferences, change se
     --xpra) # check vfb for xpra
       { [ -z "$Xpravfb" ] || [ "$Xpravfb" = "Xvfb" ] ; } && ! command -v Xvfb >/dev/null && note "Option --xpra: Xvfb not found. 
   Will try to use dummy video driver Xdummy.
-  If you encounter xpra startup errors, please install 'Xvfb'." && Xpravfb="Xdummy"
+  If you encounter xpra startup errors, please install 'Xvfb'.
+  $Wikipackages" && Xpravfb="Xdummy"
       [ "$Xpravfb" ] || { command -v Xvfb >/dev/null && Xpravfb="Xvfb" || Xpravfb="Xdummy" ; }
     ;;
     --tty)
@@ -5588,7 +5606,8 @@ check_option_interferences() {  # check multiple option interferences, change se
     command -v $Xauthexe    >/dev/null || {
       warning "Command 'xauth' not found.
   Please install 'xauth' to allow X cookie authentication.
-  Fallback: Disabling X authentication protocol. (option --no-auth)"
+  Fallback: Disabling X authentication protocol. (option --no-auth)
+  $Wikipackages"
       Xauthentication="no"
     }
     command -v $Xauthexe | grep -q VcXsrv && {
@@ -5636,7 +5655,8 @@ check_option_interferences() {  # check multiple option interferences, change se
     } || note "Command 'xdpyinfo' not found. Need it to check
   whether Xorg supports untrusted cookies for --hostdisplay
   and whether extension MIT-SHM for shared memory is enabled.
-  Please install 'xdpyinfo'."
+  Please install 'xdpyinfo'.
+  $Wikipackages"
   }
 
   # --clipboard
@@ -5775,7 +5795,8 @@ check_option_interferences() {  # check multiple option interferences, change se
   command -v xrandr >/dev/null || case $Xserver in
     --xorg) { [ "$Scaling" ] || [ -n "$Rotation" ] || [ -n "$Screensize" ] ; } && note "Option --xorg needs 'xrandr' to support
   options --size, --scale and --rotate.
-  Please install 'xrandr'."
+  Please install 'xrandr'.
+  $Wikipackages"
     ;;
   esac
 
@@ -5814,7 +5835,8 @@ check_option_interferences() {  # check multiple option interferences, change se
   [ "$Xfishtank" = "yes" ] && {
     command -v xfishtank >/dev/null || {
       note "xfishtank not found. Can not show a fish tank.
-  Please install 'xfishtank' for option --xfishtank to show a fish tank."
+  Please install 'xfishtank' for option --xfishtank to show a fish tank.
+  $Wikipackages"
       Xfishtank="no"
     }
     case $Xserver in
@@ -6501,6 +6523,8 @@ declare_variables() {           # declare global variables
   Showcontainerpid1pid="no"                       # option --showpid1: output of host PID of container PID 1
   Verbosecolors="no"                              # colored output for --verbose and delete some systemd error messages.
   Debugmode="no"                                  # option --debug: Throw it all out
+  Wikipackages="You can look for the package name of this command at: 
+ https://github.com/mviereck/x11docker/wiki/dependencies#table-of-all-packages"
 
   # advanced options
   Containerenvironment=""                         # option '--env': set custom environment variables
@@ -7010,8 +7034,7 @@ todo() {
   # BUG: x11docker/xwayland in a nested setup: where is the X socket ??
   
   # FIXME: myrealpath()
-  # FIXME: check docker version. 1.16.2 does not support --rm --detach
-  
+  # FIXME: check docker version. 1.16.2 does not support --rm --detach  
   
   # --init
   # autodetect init system if possible, give a note.
