V1.6.0 new developer option --vt: set virtual console to use
# 13.02.2017 V1.6.0   logo changed from jpeg to png / x11docker-gui
#                     new developer option --vt: set virtual console to use
# 12.02.2017          minor bugfix: Only show warning for missing virtualgl if option --virtualgl was chosen

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -2,14 +2,14 @@
 
 # x11docker
 # Run GUI applications and desktop environments in docker on a separate X server.
-# Provides Gpu acceleration and pulseaudio sound. Circumvents some X security leaks.
+# Provides GPU acceleration and pulseaudio sound. Circumvents some X security leaks.
 # Type 'x11docker --help' or scroll down to read usage information.
 # https://github.com/mviereck/x11docker
 
-Version="V 1.5.9"
+Version="V 1.6.0"
 
 # ToDo:
-# - check Ubuntu 16.10: <dpkg-reconfigure x11-common> seems not to work
+# - try to find workaround for issue #5 / --X11 on Ubuntu 16.04 fails: xf86OpenConsole: Cannot open virtual console
 # - test --gpu and --virtualgl with different setups of graphic cards and drivers. 
 #   Known to work with Intel and AMD onboard chips with open source drivers.
 # - check pulseaudio: daemon on host seems to quit when image terminates. 
@@ -20,6 +20,9 @@ Version="V 1.5.9"
 # - try to integrate Alsa sound
 
 # x11docker changelog
+# 13.02.2017 V1.6.0   logo changed from jpeg to png / x11docker-gui
+#                     new developer option --vt: set virtual console to use
+# 12.02.2017          minor bugfix: Only show warning for missing virtualgl if option --virtualgl was chosen
 # 10.02.2017 V1.5.9   bugfix: Ubuntu since 16.04 needs xserver-xorg-legacy to be installed and reconfigured instead of x11-common for option --X11
 # 10.02.2017 V1.5.8   bugfix: option --root needs Getroor="bash -c" instead of "". Members of group docker: same bug and bugfix
 # 10.02.2017 V1.5.7   renamed $Command to $Dockercommand
@@ -163,11 +166,11 @@ only less secure option --hostdisplay will work out of the box from within X.
  
 Usage:
 To run a docker image with new X server (auto-choosing X server option):
-   x11docker [OPTIONS] IMAGE [Dockercommand]
-   x11docker [OPTIONS] -- [DOCKER_RUN_OPTIONS] IMAGE [Dockercommand [ARG1 ARG2 ...]]
+   x11docker [OPTIONS] IMAGE [COMMAND]
+   x11docker [OPTIONS] -- [DOCKER_RUN_OPTIONS] IMAGE [COMMAND [ARG1 ARG2 ...]]
 To run a host application on a new X server:
-   x11docker [OPTIONS] --exe command
-   x11docker [OPTIONS] --exe -- command [ARG1 ARG2 ...]
+   x11docker [OPTIONS] --exe COMMAND
+   x11docker [OPTIONS] --exe -- COMMAND [ARG1 ARG2 ...]
 To run only a new X server with window manager:
    x11docker [OPTIONS]
 
@@ -273,7 +276,7 @@ depending on chosen options                | rendering |             |
         Allows X server MIT-SHM extension.
 ------------------------------------------------------------------------------
 +++++ high container isolation, secure to use.
-++++  high container isolation, slightly degraded by container access to Gpu.
+++++  high container isolation, slightly degraded by container access to GPU.
 +:0   low container isolation due to X security leaks, considered insecure.
       (full access to X server on display :0 with host applications.
        For example, keylogging is possible. For use with trusted images only.)
@@ -579,7 +582,7 @@ xdparser() { # parse args for x11docker
   Longoptions="$Longoptions,clipboard,hostuser,sudouser,home,pulseaudio,gpu,virtualgl"             # comfort options
   Longoptions="$Longoptions,sudo,root,ipc,ps,verbose,cid,cache,log,LOG"                            # advanced options
   Longoptions="$Longoptions,starter,orphaned,license,licence,command,help"                         # special options without starting X server
-  Longoptions="$Longoptions,xhost,no-xhost,privileged,xsocket,tcp,sharegpu,tcpxsocket,pid,uts,net,alsa"     # developer options, not for regular use
+  Longoptions="$Longoptions,xhost,no-xhost,privileged,xsocket,tcp,sharegpu,tcpxsocket,pid,uts,net,alsa,vt:"     # developer options, not for regular use
   Parsedoptions=`getopt --options $Shortoptions --longoptions $Longoptions --name "$0" -- "$@"`
   if [ "$?" != "0" ] ; then error "Error while parsing options. See 'x11docker --help' for vaild options." ; fi
   eval set -- "$Parsedoptions"
@@ -632,6 +635,7 @@ xdparser() { # parse args for x11docker
       --uts) Shareuts="yes";;                           # set docker option --net=host
       --net) Sharenet="yes";;                           # set docker option --net=host
       --alsa) Alsa="yes" ;;
+      --vt) Newxvt="vt$2" && shift ;;                          # set virtual console to use
       ##### docker options / image
       --) shift                                         # arguments to submit to docker (or host executable)
         if [ "$X11dockermode" != "exe" ] ; then X11dockermode="run" ; fi        # will run image, if not already changed to '--exe'
@@ -772,11 +776,13 @@ s0_active_plugins = core;composite;opengl;decor;resize;move;
   fi
   
   ## option '--virtualgl': check if VirtualGL is installed
-  command -v "vglrun" >/dev/null 2>&1 || { warning "could not find VirtualGL.
+  if [ "$Gpu" = "virtualgl" ] ; then
+    command -v "vglrun" >/dev/null 2>&1 || { warning "could not find VirtualGL.
   It has to be installed on host to use option --virtualgl. 
   You can get in here: http://www.virtualgl.org/
   Fallback: disabling option --virtualgl" 
-    Gpu="" ; }
+      Gpu="" ; }
+  fi
   
   ## option '--pulseaudio': find a free tcp port
   if [ "$Pulseaudio" = "yes" ] ; then
@@ -960,7 +966,7 @@ s0_active_plugins = core;composite;opengl;decor;resize;move;
   Shareclipboardscript="$Cachefolder/$Shareclipboardscript"
   Newxsocket="/tmp/.X11-unix/X$Newdisplay"
   #Newxlock="/tmp/.X$Newdisplay-lock"
-  Newxvt="vt$[7+$Newdisplay]"                                # FIXME: assuming instead of knowing whether VT is free
+  if [ "$Newxvt" = "" ] ; then Newxvt="vt$[7+$Newdisplay]" ; fi    # FIXME: assuming instead of knowing whether VT is free
 
   Newdisplay=":$Newdisplay"                                  # finally: add ':' to $Newdisplay
   
