V 3.1.12 code cleanup, minor bugfixes
# 29.04.2017 V3.1.12 clean up confusion with x11docker.log
#                    minor bugfix: include warning() in xinitrc
#                    bugfix in xinitrc for --no-xhost
#                    don't share $Xclientcookie as $Sharefolder is already shared
#                    don't use $Cacherootfolder for parsererror
#                    hint to use --sudo on some systems
#                    use id -g instead of $Benutzer for group name
#                    add lsb-release -ds to verbose output

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -6,15 +6,24 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # https://github.com/mviereck/x11docker
 
-Version="3.1.11"
+Version="3.1.12"
 
 changelog() {
 # ToDo:
-# Ubuntu BUG: Ctrl-c: broken pipe in warnings (redirecting stderr) 
+# multimonitor: better check of screen size, dpyinfo and xwininfo not reliable present
+# Ubuntu+opensuse BUG: Ctrl-c: broken pipe in warnings (redirecting stderr) 
 # debian bugreport lightdm/sddm contra gdm, dm can crash on tty switch if multiple graphical sessions are running
 # check whether VT is not in use with --xorg
 
 # x11docker changelog
+# 29.04.2017 V3.1.12 clean up confusion with x11docker.log
+#                    minor bugfix: include warning() in xinitrc
+#                    bugfix in xinitrc for --no-xhost
+#                    don't share $Xclientcookie as $Sharefolder is already shared
+#                    don't use $Cacherootfolder for parsererror
+#                    hint to use --sudo on some systems
+#                    use id -g instead of $Benutzer for group name
+#                    add lsb-release -ds to verbose output
 # 29.04.2017 V3.1.11 disabled $Cidfile as not important and due to #10
 # 28.04.2017 V3.1.10  minor bugfix: check for xenial instead of 16.04/xvfb
 #                     regression fix: set XPRA_XSHM=0 on Shareipc=no
@@ -294,6 +303,7 @@ installer() {           # options --install, --update, --remove: Installer for x
   # --remove
   #   - remove installed files
   # Prepairing
+  echo $1
   case $1 in
     --install)
       [ $(command -v x11docker) ] &&   { error "x11docker seems to be installed already.
@@ -535,9 +545,7 @@ askforimagecommand() {  # ask for password to extract image command if needed an
 exec 3> >(cat >&2)                              # second stderr to show x11docker warnings and errors from within redirected output (especially xinitrc and xtermrc)
 
 Cacherootfolder=$HOME/.cache/x11docker          # define cache folder to store temporary files
-#mkdir -p $Cacherootfolder
-Logfile="$Cacherootfolder/x11docker.log"        # changes later to reside in $Sharefolder. On exit a copy of logfile will be placed here
-:>$Logfile
+Logfile="x11docker.log"                         # changes later to reside in $Sharefolder. On exit a copy of logfile will be placed here
 Sharefolder="share"                             # subfolder for shared files
 Cshare="/x11docker"                             # mountpoint of $Sharefolder in container
 
@@ -618,7 +626,7 @@ Shareclipboard="no"                             # option '-c, --clipboard' enabl
 Shareclipboardscript="clipboard.bash"           #    "              "      script used for text clipboard sharing to Xephyr/Xorg 
 Showdisplayenvironment="no"                     # option -E, --env: Show environment variables of new display
 
-Benutzer=$USER                                  # name of user to simulate in container
+Benutzer=$(id -un)                              # name of user to simulate in container
 Addhostuser="no"                                # option '-u, --hostuser': try to add user to container with same UID and GID as host user
 Addsudouser="no"                                # option '-o, --sudouser': same as '-u, --hostuser', but created user gains root access via sudo without password
 Createuserscript="createuser"                   #   "          "         : file to store commands to create container user
@@ -691,11 +699,11 @@ Wm_all="$Wm_recommended_desktop_light $Wm_recommended_nodesktop_light $Wm_recomm
   Longoptions="$Longoptions,xhost+,vt:,display:,no-auth,env:,showenv,sharewayland,waylandenv,root,ipc,net"  # developer option
   Longoptions="$Longoptions,kwin,kwin-xwayland,kwin-native,nothing"                                # developer options - further X/Wayland servers
   Longoptions="$Longoptions,desktop,+xsocket,tcpxsocket,virtualgl,glamor,xpra-image,xpra-attach,xorg-image,xdummy,xdummy-image,tcp"  # deprecated
-  Parsedoptions="$(getopt --options $Shortoptions --longoptions $Longoptions --name "$0" -- "$@" 2>$Cacherootfolder/parsererror)"
-  [ -s "$Cacherootfolder/parsererror" ] && { error $(cat $Cacherootfolder/parsererror) ; }
+  Parsedoptions="$(getopt --options $Shortoptions --longoptions $Longoptions --name "$0" -- "$@" 2>/tmp/x11docker_parsererror)"
+  [ -e /tmp/x11docker_parsererror ] && Parsererror=$(cat /tmp/x11docker_parsererror) && rm /tmp/x11docker_parsererror
+  [ -n "$Parsererror" ] && error "$Parsererror"
   
   eval set -- $Parsedoptions
-  
   [ "$*" = "-h --" ] &&    usage         && exit 0         # catch single -h for usage info, otherwise it means --hostdisplay
   
   while [ -n "$1" ] ; do
@@ -848,6 +856,10 @@ Wm_all="$Wm_recommended_desktop_light $Wm_recommended_nodesktop_light $Wm_recomm
     export XDG_RUNTIME_DIR=/tmp/XDG_RUNTIME.x11docker.$(id -u)
     chmod 700 $XDG_RUNTIME_DIR
   }
+  
+  [ "$Getroot" = "su -c" ] && case $(lsb_release -is) in
+    Ubuntu|Sparky) warning "You may need option --sudo if root has no password for su." ;;
+  esac
 }
 
 { #### part: check X server
@@ -908,9 +920,9 @@ Wm_all="$Wm_recommended_desktop_light $Wm_recommended_nodesktop_light $Wm_recomm
   esac
   case $Xserver in 
     Xpra|Xdummy)
-      [ -n "$(lsb_release -a 2>&1| grep xenial)" ] && {
-        command -v Xvfb >/dev/null || { warning "On Ubuntu 16.04 you need to install
-  package xvfb to use $Xserver.   Try 'apt-get install xvfb' to install Xvfb.
+      [ "$(lsb_release -is)" = "Ubuntu" ] && {
+        command -v Xvfb >/dev/null || { warning "On Ubuntu you may need to install
+  package xvfb to use $Xserver. Try 'apt-get install xvfb' to install Xvfb.
   Fallback: Will try to use Xephyr"
           Xserver="Xephyr"
         }
@@ -1097,7 +1109,7 @@ Wm_all="$Wm_recommended_desktop_light $Wm_recommended_nodesktop_light $Wm_recomm
   Shareclipboardscript="$Cachefolder/$Shareclipboardscript"
   Newxsocket="/tmp/.X11-unix/X$Newdisplaynumber"
   #Newxlock="/tmp/.X$Newdisplaynumber-lock"
-  Logfile="$Sharefolder/x11docker"
+  Logfile="$Sharefolder/x11docker.log"
   
   [ "$Newxvt" = "" ] && Newxvt="vt$Newdisplaynumber"    # FIXME: assuming instead of knowing whether VT is free
   Newdisplay=":$Newdisplaynumber"
@@ -1554,7 +1566,7 @@ esac
       Dockercommand='docker run'
 #      Dockercommand="$Dockercommand --cidfile=$Cidfile"             # write container id in file $Cidfile
       Dockercommand="$Dockercommand --name=$Containername"          # give container a name that can be found by --orphaned
-      Dockercommand="$Dockercommand -v $Sharefolder:$Cshare"
+      Dockercommand="$Dockercommand -v $Sharefolder:$Cshare:rw"
      
       case $Xserver in
         Nothing|Weston|Hostwayland|Kwin) ;;
@@ -1562,7 +1574,8 @@ esac
           #      share X socket from $Newdisplay
           Dockercommand="$Dockercommand -v $Newxsocket:$Newxsocket:ro"
           #      XAUTHORITY
-          [ "$Xauthentication" = "yes" ] && Dockercommand="$Dockercommand -v $Xclientcookie:$Cshare/Xclientcookie:rw -e XAUTHORITY=$Cshare/Xclientcookie"
+#          [ "$Xauthentication" = "yes" ] && Dockercommand="$Dockercommand -v $Xclientcookie:$Cshare/Xclientcookie:rw -e XAUTHORITY=$Cshare/Xclientcookie"
+          [ "$Xauthentication" = "yes" ] && Dockercommand="$Dockercommand -e XAUTHORITY=$Cshare/Xclientcookie"
           #      DISPLAY
           Dockercommand="$Dockercommand -e DISPLAY=unix$Newdisplay"
         ;;
@@ -1613,12 +1626,12 @@ esac
         { echo "#! /bin/bash"
           # create user
           echo "if [ -z \"\$(id -u `id -u` 2>/dev/null)\" ] ; then"
-          echo "  Benutzer=$Benutzer"
-          echo "  addgroup --force-badname --gid `id -g $Benutzer` \$Benutzer"
+          echo "  Benutzer=$(id -un)"
+          echo "  addgroup --force-badname --gid `id -g` \$Benutzer"
           echo "  useradd -l --password '' --uid `id -u` --gid `id -g` --create-home --home-dir /home/\$Benutzer \$Benutzer"
-          echo "  chown \$Benutzer:\$Benutzer /home/\$Benutzer"
+          echo "  chown \$Benutzer:$(id -g) /home/\$Benutzer"
           echo "else" 
-          echo "  Benutzer=\$(id -nu `id -u`)"
+          echo "  Benutzer=\$(id -un `id -u`)"
           echo "fi"
           echo "export HOME=/home/\$Benutzer"
           echo "cd \$HOME"
@@ -1633,7 +1646,6 @@ esac
           [ "$Gpu" = "yes" ]  && echo "adduser \$Benutzer video"
           
           echo '[ -e "$XDG_RUNTIME_DIR" ] && chown $Benutzer $XDG_RUNTIME_DIR'  # path to WAYLAND_DISPLAY
-          echo '[ -e "/tmp/.X11-unix" ] && chmod 1777 /tmp/.X11-unix'             # needed for Xservers created in Container 
           
           # run image command as user:
           echo "su \$Benutzer -c '$Imagecommand'"
@@ -1680,6 +1692,7 @@ esac
   declare -f storepid  # echoes storepid(), including it this way in xinitrc
   declare -f waitforxpraserver
   declare -f no_xhost 
+  declare -f warning 
 
   [ "$Pulseaudio" = "yes" ] && {
     echo "# option '--pulseaudio': enable pulseaudio sound over tcp"
@@ -1689,6 +1702,7 @@ esac
   
   [ "$Noxhost" = "yes" ] && [ -n "$Hostdisplay" ] && {  
     echo "## option --no-xhost: disable any access to host display granted by xhost"
+    echo "export $Hostxenv"
     echo "no_xhost"
   }
 
@@ -1718,11 +1732,11 @@ esac
           echo "export XAUTHORITY=$Xclientcookie.bak"
         }
         echo ':> '$Xclientcookie
-        echo "xauth -f $Xclientcookie generate $Newdisplay . $Trusted"  
+        echo "xauth -v -f $Xclientcookie generate $Newdisplay . $Trusted"  
         echo "cp $Xclientcookie $Xservercookie"
         echo "# create prepared cookie with localhost identification disabled by ffff, needed if X socket is shared. ffff means 'familiy wild'"
         echo "Cookie=\$(xauth -f $Xclientcookie nlist $Newdisplay | sed -e 's/^..../ffff/' )"   
-        echo 'echo $Cookie'"| xauth -f $Xclientcookie nmerge -"
+        echo 'echo $Cookie'"| xauth -v -f $Xclientcookie nmerge -"
         echo "export $Newxenv"
         echo "xauth list"
         [ "$Xserver" = "Nxagent" ] && echo "rm $Xclientcookie.bak"
@@ -1838,12 +1852,13 @@ echo ''"
 }
 
 { #### part:  some verbose output
-    verbose "$(date) $0 $X11dockerargs"
+    verbose "$(date) $(lsb_release -ds) $(Xorg -version 2>&1 | grep X.Org")
+  $0 $X11dockerargs"
     [ "$Xserver" != "Nothing" ] && {
       verbose "Found free display $Newdisplay"
       verbose "As X server will be used: $Xserver"
       verbose "Environment variables: 
-$Newxenv"
+  $Newxenv"
     }
     [ -n "$Waylandsocket" ] && {
       verbose "XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR"
@@ -1861,9 +1876,9 @@ $Newxenv"
     [ -n "$Hostexe" ] && verbose "Running host application: $Hostexe"
     [ "$Adduserhome" = "yes" ] && verbose "Sharing directory $Adduserhomefolder with container as its home directory /home/$Benutzer"
     [ "$Xserver" != "Nothing" ] && verbose "Created X server command:
-$Xcommand" 
+  $Xcommand" 
     verbose "Created docker command:
-$Dockercommand"
+  $Dockercommand"
     [ -e "$Sharefolder/x11docker_CMD" ] && verbose "Created x11docker_CMD script:
 $(cat $Sharefolder/x11docker_CMD)" 
     [ -e "$Sharefolder/Xdummy.sh" ] && verbose "Created Xdummy.sh:
@@ -1879,7 +1894,8 @@ $(cat $Xinitrc)"
   $Xpraserverlogfile
   $Xtermlogfile
   $Dockerlogfile
-Summary logfile: $Logfile"
+Summary logfile: $Logfile
+Copy of logfile: $Cacherootfolder/x11docker.log"
     verbose "Running X server $Xserver on display $Newdisplay now ..."
 
   # create summary logfile
