--preset: New option to allow predefined option sets #218

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -273,14 +273,18 @@ Container capabilities:
                        argument is 'yes'. Default for most cases is 'no'.
 
 Miscellaneous:
+     --cleanup         Clean up orphaned containers and cache files.
+                       Terminates currently running x11docker containers, too.
+     --cachebasedir DIR  Custom base folder for cache files.
+     --homebasedir DIR   Custom base folder for option --home.
      --launcher        Create application launcher on desktop and exit. 
                        You can move the created .desktop file to 
                        ~/.local/share/applications to get a menu entry.
-     --cachebasedir DIR  Custom base folder for cache files.
-     --homebasedir DIR   Custom base folder for option --home.
      --license         Show license of x11docker (MIT) and exit.
-     --cleanup         Clean up orphaned containers and cache files.
-                       Terminates currently running x11docker containers, too.
+     --preset FILE     Read a set of predefined options from file FILE.
+                       FILE searched in directory /etc/x11docker/preset,
+                       in directory ~/.config/x11docker/preset or absolute.
+                       Multiple lines in FILE are allowed. 
      
 Output of parseable information on stdout:
   Get output with e.g.:  read id < <(x11docker --showid x11docker/check)
@@ -1258,8 +1262,8 @@ create_launcher() {             # --launcher: create application launcher on des
 " -i "$Name" Name
   [ -z "$Name" ] && return 1 ### FIXME: check for valid file name / invalid chars?
 
-  Parsedoptions="${Parsedoptions//--launcher/}"
-  Parsedoptions="${Parsedoptions//--starter/}"
+  Parsedoptions_global="${Parsedoptions_global//--launcher/}"
+  Parsedoptions_global="${Parsedoptions_global//--starter/}"
   mkfile "$Cachefolder/$Name.desktop"
   {
     echo "#!/usr/bin/xdg-open
@@ -1267,15 +1271,15 @@ create_launcher() {             # --launcher: create application launcher on des
 # x11docker desktop file
 Type=Application
 Name=$Name
-Exec=x11docker $Parsedoptions
+Exec=x11docker $Parsedoptions_global
 Icon=x11docker
 Comment=
 Categories=System
 Keywords=docker x11docker $(echo $Name | tr -c '[:alpha:][:digit:][:blank:]' ' ' )
 "
     case $(command -v x11docker) in
-      "")echo "TryExec=$0 $Parsedoptions" ;;
-      *) echo "TryExec=x11docker $Parsedoptions" ;;
+      "")echo "TryExec=$0 $Parsedoptions_global" ;;
+      *) echo "TryExec=x11docker $Parsedoptions_global" ;;
     esac
   } >> "$Cachefolder/$Name.desktop"
 
@@ -7796,9 +7800,11 @@ declare_variables() {           # declare global variables
   Codename=""                                     # created from image name and command without special chars for use with container name and cache folder
   Dockerexe=""                                    # Can be docker.exe on MS Windows
   Hostexe=""                                      # --exe: Host command
-  Passwordterminal=""                             # Terminal emulator to use for password prompt (if no terminal emulator is needed, it will be 'bash -c')
-  Presetdir="$HOME/.config/x11docker/preset"
   Imagebasename=""                                # Image name without tags and / replaced with -. For use of --home folders.
+  Parsedoptions_global=""                         # Parsed options
+  Passwordterminal=""                             # Terminal emulator to use for password prompt (if no terminal emulator is needed, it will be 'bash -c')
+  Presetdirlocal="$HOME/.config/x11docker/preset"
+  Presetdirsystem="/etc/x11docker/preset"
   Preservecachefiles="no"                         # If yes, don't delete cache files on exit. For few failure cases only.
   Pullimage="ask"                                 # --pull: Allow 'docker pull' yes|no|always|ask
   X11dockermode="run"                             # --exe, --xonly: Can be either "run" (default), "exe", or "xonly".
@@ -7889,7 +7895,7 @@ stdout() {
 }'
 }
 parse_options() {               # parse cli options
-  local Shortoptions Longoptions Parsererror= Parsererrorfile
+  local Shortoptions Longoptions Parsedoptions Presetoptions Presetfile Parsererror= Parsererrorfile
   Shortoptions="aAcdDefFghHiKlmnpPqtTvVwWxXyY"
   Longoptions="exe,xonly"                                                                                                  # Alternate setups of x11docker
   Longoptions="$Longoptions,auto,desktop,tty,wayland,wm::"                                                                 # Influencing auto-setup of X/Wayland/x11docker
@@ -7898,7 +7904,7 @@ parse_options() {               # parse cli options
   Longoptions="$Longoptions,hostwayland,kwin,weston"                                                                       # Wayland compositors without X
   Longoptions="$Longoptions,border::,dpi:,fullscreen,output-count:,rotate:,scale:,size:,xfishtank"                         # X/Wayland appearance options
   Longoptions="$Longoptions,clean-xhost,display:,keymap:,no-auth,vt:,westonini:,xhost:,xoverip,xtest::"                    # X/Wayland config
-  Longoptions="$Longoptions,enforce-i,pull::,pw:"                                                                          # x11docker config
+  Longoptions="$Longoptions,enforce-i,preset:,pull::,pw:"                                                                  # x11docker config
   Longoptions="$Longoptions,cachebasedir:,home::,homebasedir:,share:"                                                      # Host folders
   Longoptions="$Longoptions,alsa::,clipboard,gpu,lang::,printer::,pulseaudio::,sharessh,webcam"                            # Host integration features
   Longoptions="$Longoptions,env:,mobyvm,name:,no-entrypoint,runtime:,workdir:"                                             # Container config
@@ -7912,7 +7918,7 @@ parse_options() {               # parse cli options
   Longoptions="$Longoptions,cleanup,help,launcher,licence,license,version,wmlist"                                          # Special options without starting X or container
   Longoptions="$Longoptions,install,remove,update,update-master"                                                           # Installation
   #
-  Longoptions="$Longoptions,iglx,xcomposite,xorgconf:,preset:"                                                             # Experimental
+  Longoptions="$Longoptions,iglx,xcomposite,xorgconf:"                                                                     # Experimental
   Longoptions="$Longoptions,dbus-system,homedir:,no-xhost,sharedir:,systemd"                                               # Deprecated
   Longoptions="$Longoptions,cachedir:,no-init,nothing,no-xtest,openrc,ps,runit,silent,starter,stderr,stdout"               # Removed
   Longoptions="$Longoptions,sys-admin,sysvinit,tini,trusted,untrusted,vcxsrv"                                              # Removed
@@ -7922,6 +7928,7 @@ parse_options() {               # parse cli options
   [ -e $Parsererrorfile ] && Parsererror=$(cat $Parsererrorfile) && rm $Parsererrorfile
   [ "$Parsererror" ] && error "$Parsererror"
   eval set -- "$Parsedoptions"
+  [ -z "$Parsedoptions_global" ] && Parsedoptions_global="$Parsedoptions"
   
   [ "$*" = "-h --" ] &&       usage &&        exit 0                 # Catch single -h for usage info, otherwise it means --hostdisplay
   [ "$*" = "--" ]    &&       usage &&        exit 0                 # x11docker without options
@@ -7960,7 +7967,23 @@ parse_options() {               # parse cli options
          --wmlist)            echo $Wm_all ;  exit 0 ;;              # Special option for x11docker-gui to retrieve list of window managers
 
       -e|--exe)               X11dockermode="exe" ;;                 # Execute application from host instead of running docker image
-         --xonly)             X11dockermode="xonly" ;;               # Only create X erver
+         --xonly)             X11dockermode="xonly" ;;               # Only create X server
+         
+     #### Predefined option sets
+         --preset)            Presetoptions=""
+                              Presetfile=""
+                              [ -f "$Presetdirsystem/${2:-}" ] && Presetfile="$Presetdirsystem/${2:-}"
+                              [ -f "$Presetdirlocal/${2:-}" ]  && Presetfile="$Presetdirlocal/${2:-}"
+                              [ -f "${2:-}" ]                  && Presetfile="${2:-}"
+                              [ -f "$Presetfile" ]             || error "Option --preset: File not found: ${2:-}
+  Searching in present working directory and in:
+  $Presetdirlocal
+  $Presetdirsystem"
+                              Presetoptions="$(sed '/^#/d' < "$Presetfile" | tr '\n' ' ')"
+                              debugnote "--preset ${2:-}: 
+  $Presetoptions"
+                              [ "$Presetoptions" ] && parse_options $Presetoptions
+                              shift ;; 
 
      #### Choice of X servers and Wayland compositors
          --auto)              Autochooseserver="yes" ;;              # Default: auto-choose X server or Wayland compositor
@@ -8121,16 +8144,6 @@ ${2:-}"                       ; shift ;;                             # Add custo
          --launcher)          Createlauncher="yes" ;;                # Create application launcher on desktop and exit
       
      #### Experimental options
-         --preset)            [ -e "$Presetdir/${2:-}" ] && {
-                                parse_options $(cat "$Presetdir/${2:-}")
-                                :
-                              } || {
-                                [ -e "${2:-}" ] && {
-                                  parse_options $(cat "${2:-}")
-                                  :
-                                }
-                              } || note "Option --preset: Not found: ${2:-}"
-                              shift ;             note "Option --preset: experimental only." ;; 
          --iglx)              Iglx="yes" ;        note "Option --iglx: experimental only." ;;            # Indirect rendering; broken since Xorg ~18.2
          --xcomposite)        Xcomposite="yes" ;  note "Option --xcomposite: experimental only." ;;      # Enable X extension COMPOSITE
          --xorgconf)          Xorgconf="${2:-}" ; note "Option --xorgconf: eperimental only" ; shift ;;  # Custom xorg.conf
@@ -8223,7 +8236,7 @@ x11docker version: $Version
 docker version:    $($Dockerexe --version 2>&1)
 Host system:       $(grep '^PRETTY_NAME' /etc/os-release 2>/dev/null | cut -d= -f2 || echo "$Hostsystem")
 Command:           '$0' $(for Line in "$@"; do echo -n "'$Line' " ; done)
-Parsed options:    $Parsedoptions"
+Parsed options:    $Parsedoptions_global"
 
   # Special x11docker jobs
   [ "$Createlauncher" = "yes" ] && { create_launcher ; exit ; }                   # --launcher: Create application launcher icon on desktop
