minor cleanup

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4052,37 +4052,37 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
   declare -f storepid
   echo "$Messagefifofuncs"
 
-  echo "getscreensize() {"
-  echo "  CurrentXaxis=\"\$(xrandr | grep primary | cut -d' ' -f4 | cut -dx -f1 )\""
-  echo "  CurrentYaxis=\"\$(xrandr | grep primary | cut -d' ' -f4 | cut -dx -f2 | cut -d+ -f1)\""
-  echo "}"
-  echo "checkscreensize() {"
-  echo "  getscreensize"
-  echo "  [ \"\$Xaxis\" = \"\$CurrentXaxis\" ] || return 1"
-  echo "  [ \"\$Yaxis\" = \"\$CurrentYaxis\" ] || return 1"
-  echo "  return 0"
-  echo "}"
-  echo "getprimary() {"
-  echo "  xrandr | grep -q primary || xrandr --output \$(xrandr | grep ' connected' | head -n1 | cut -d' ' -f1) --primary"
-  echo "  echo \$(xrandr | grep primary | cut -d' ' -f1)"
-  echo "}"
-  echo ""
+  echo               "getscreensize() {"
+  echo               "  CurrentXaxis=\"\$(xrandr | grep primary | cut -d' ' -f4 | cut -dx -f1 )\""
+  echo               "  CurrentYaxis=\"\$(xrandr | grep primary | cut -d' ' -f4 | cut -dx -f2 | cut -d+ -f1)\""
+  echo               "}"
+  echo               "checkscreensize() {"
+  echo               "  getscreensize"
+  echo               "  [ \"\$Xaxis\" = \"\$CurrentXaxis\" ] || return 1"
+  echo               "  [ \"\$Yaxis\" = \"\$CurrentYaxis\" ] || return 1"
+  echo               "  return 0"
+  echo               "}"
+  echo               "getprimary() {"
+  echo               "  xrandr | grep -q primary || xrandr --output \$(xrandr | grep ' connected' | head -n1 | cut -d' ' -f1) --primary"
+  echo               "  echo \$(xrandr | grep primary | cut -d' ' -f1)"
+  echo               "}"
+  echo               ""
 
-  echo "Messagefile='$Messagefifo'"
-  echo "Output=\"\$(getprimary)\""
-  echo "Storeinfofile='$Storeinfofile'"
-  echo "Storepidfile='$Storepidfile'"
-  echo "Timetosaygoodbyefile='$Timetosaygoodbyefile'"
-  echo ""
-  echo "export PATH='${PATH:-}'"
-  echo ""
-  echo "Cookie=''"
-  echo "Line=''"
-  echo "Var=''"
-  echo ""
+  echo               "Messagefile='$Messagefifo'"
+  echo               "Output=\"\$(getprimary)\""
+  echo               "Storeinfofile='$Storeinfofile'"
+  echo               "Storepidfile='$Storepidfile'"
+  echo               "Timetosaygoodbyefile='$Timetosaygoodbyefile'"
+  echo               ""
+  echo               "export PATH='${PATH:-}'"
+  echo               ""
+  echo               "Cookie=''"
+  echo               "Line=''"
+  echo               "Var=''"
+  echo               ""
 
-  echo "debugnote 'Running xinitrc'"
-  echo ""
+  echo               "debugnote 'Running xinitrc'"
+  echo               ""
 
   case $Xserver in
     --weston|--kwin|--hostwayland)
@@ -5829,8 +5829,9 @@ exec 1>&5 2>&6
         echo 'Systemd=/lib/systemd/systemd'
         echo '[ -x "$Systemd" ] || Systemd=/bin/systemd'
         echo '[ -x "$Systemd" ] || Systemd=/sbin/systemd'
-        echo '[ -x "$Systemd" ] || {'
-        echo '  error "Option --init=systemd: Executable for systemd not found."'
+        echo '[ -x "$Systemd" ] || Systemd=/sbin/init'
+        echo 'command -v systemctl >/dev/null || {'
+        echo '  error "Option --init=systemd: systemd not found."'
         echo '  exit 64'
         echo '}'
         echo 'exec $Systemd'
@@ -6491,38 +6492,38 @@ rootrc_prepare_init_systemd() {
 
 # remove failing and annoying services
 Unservicelist='
-              apt-daily.service
-              apt-daily.timer
-              apt-daily-upgrade.service
-              apt-daily-upgrade.timer
-              bluetooth.service
-              cgproxy.service
-              deepin-anything-monitor.service
-              deepin-sync-daemon.service
-              display-manager.service
-              fprintd.service
-              gdm3.service
-              gvfs-udisks2-volume-monitor.service
-              hwclock_stop.service
-              lastore-daemon.service
-              lastore-update-metadata-info.service
-              lightdm.service
-              NetworkManager.service
-              plymouth-quit.service
-              plymouth-quit-wait.service
-              plymouth-read-write.service
-              plymouth-start.service
-              rtkit-daemon.service
-              sddm.service
-              systemd-localed.service
-              systemd-hostnamed.service
-              tracker-extract.service
-              tracker-miner-fs.service
-              tracker-store.service
-              tracker-writeback.service
-              udisks2.service
-              upower.service
-              '
+apt-daily.service
+apt-daily.timer
+apt-daily-upgrade.service
+apt-daily-upgrade.timer
+bluetooth.service
+cgproxy.service
+deepin-anything-monitor.service
+deepin-sync-daemon.service
+display-manager.service
+fprintd.service
+gdm3.service
+gvfs-udisks2-volume-monitor.service
+hwclock_stop.service
+lastore-daemon.service
+lastore-update-metadata-info.service
+lightdm.service
+NetworkManager.service
+plymouth-quit.service
+plymouth-quit-wait.service
+plymouth-read-write.service
+plymouth-start.service
+rtkit-daemon.service
+sddm.service
+systemd-localed.service
+systemd-hostnamed.service
+tracker-extract.service
+tracker-miner-fs.service
+tracker-store.service
+tracker-writeback.service
+udisks2.service
+upower.service
+'
 for Service in \$(find /lib/systemd/system/* /usr/lib/systemd/user/* /etc/systemd/system/* /etc/systemd/user/*) ; do
   echo \"\$Unservicelist\" | grep -q \"\$(basename \$Service)\" && {
     debugnote \"--init=systemd: Removing \$Service\"
@@ -6604,10 +6605,11 @@ systemctl unmask console-getty.service
 systemctl enable console-getty.service
 systemctl enable x11docker-journal.service
 
+# enable logind service
 systemctl unmask systemd-logind
 systemctl enable systemd-logind
 
-# Just assuming that a DBus service file will be present
+# enable DBus service
 systemctl unmask dbus
 systemctl enable dbus
 "
@@ -6628,7 +6630,7 @@ exit 0
 
 chmod +x /etc/rc.local
 
-# DBus
+# DBus service
 echo '#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          dbus
