--showpid1: show pid1 only once, bug from previous commit #133

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4292,17 +4292,6 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo "  sleep 0.2"
   echo "done"
   echo "$Dockerexe logs -f \$Containerid 2>&1 | rmcr >> $Containerlogfile &"
-  echo "Failure=\"\$(cat $Containerlogfile | rmcr | grep -v grep | grep -E 'Error response from daemon|OCI runtime exec' ||:)\""
-  echo "[ \"\$Failure\" ] && {"
-  echo "  echo \"\$Failure\" >>$Containerlogfile"
-  echo "  error \"Got error message from docker daemon:
-\$Failure\""
-  echo "}"
-  echo ""
-
-  echo "$Dockerexe inspect --format '{{ .NetworkSettings.IPAddress }}' $Containername 2>>$Containerlogfile | rmcr >> $Containeripfile"
-  echo "verbose -d \"Container IP: \$(cat $Containeripfile)\""
-  echo ""
   
   echo "for ((Count=1 ; Count<=10 ; Count++)); do"
   echo "  Pid1pid=\$($Dockerexe inspect --format '{{.State.Pid}}' $Containername 2>>$Containerlogfile | rmcr)"
@@ -4313,9 +4302,19 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo "verbose -d \"Host PID of container PID 1: \$Pid1pid\""
   [ "$Showcontainerpid1pid" = "yes" ] && echo "stdout \$Pid1pid"
   echo ""
+
+  echo "$Dockerexe inspect --format '{{ .NetworkSettings.IPAddress }}' $Containername 2>>$Containerlogfile | rmcr >> $Containeripfile"
+  echo "verbose -d \"Container IP: \$(cat $Containeripfile)\""
+  echo ""
   
-  echo "verbose -d \"Host PID of container PID 1: \$Pid1pid\""
-  [ "$Showcontainerpid1pid" = "yes" ] && echo "stdout \$Pid1pid"
+  echo "Failure=\"\$(cat $Containerlogfile | rmcr | grep -v grep | grep -E 'Error response from daemon|OCI runtime exec' ||:)\""
+  echo "[ \"\$Failure\" ] && {"
+  echo "  echo \"\$Failure\" >>$Containerlogfile"
+  echo "  error \"Got error message from docker daemon:
+\$Failure\""
+  echo "}"
+  echo ""
+  
   echo ""
   echo "# get PID of container"
   echo "Containerpid=\$(ps -o ppid \$Pid1pid 2>/dev/null || echo unknown | tail -n1)"
