--init: fix ready signal in containerrootrc

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -842,10 +842,13 @@ unspecialstring() {             # replace special chars of $1 with _
   # Remove leading and trailing '-'
   echo "${1:-}" | LC_ALL=C sed -e 's/[^a-zA-Z0-9_]/\-/g; 1{$s/^$/""/}; 1!s/^/"/; $!s/$/"/ ; s/\([-]\)\1\+/\1/g ; s/-$//g ; s/^-//g'
 }
-envvarstring() {                # allow only chars in strings that can be exspected in used environment variables
+envvarstring() {                # allow only chars in string $1 that can be exspected in environment variables
+  # Option -w allows whitespace, too.
   local Newvar
-
-  Newvar="$(echo "${1:-}" | LC_ALL=C sed -e 's/[^a-zA-Z0-9_:/.-]/\X/g')"
+  case "${1:-}" in
+    -w) shift; Newvar="$(echo "${1:-}" | LC_ALL=C sed -e 's/[^a-zA-Z0-9_:/.@ -]/\X/g')" ;;
+    *)         Newvar="$(echo "${1:-}" | LC_ALL=C sed -e 's/[^a-zA-Z0-9_:/.@-]/\X/g')" ;;
+  esac
   echo "$Newvar"
   
   [ "$Newvar" = "${1:-}" ] && return 0 || {
@@ -855,7 +858,7 @@ envvarstring() {                # allow only chars in strings that can be exspec
   }
 }
 mysleep() {                     # catch cases where sleep only supports integer
-  sleep "${1:-}" 2>/dev/null || sleep 1
+  sleep "${1:-1}" 2>/dev/null || sleep 1
 }
 download() {                    # download file at URL $1 and store it in file $2
   # Uses wget or curl. If both are missing, returns 1. Follows redirects. 
@@ -864,9 +867,9 @@ download() {                    # download file at URL $1 and store it in file $
   command -v wget >/dev/null && Downloader="wget"
   command -v curl >/dev/null && Downloader="curl"
   [ "$Downloader" ] || return 1
-  [ "${1:-}" ] || return 0
+  [ "${1:-}" ]      || return 0
   case $Downloader in
-    wget) wget "${1:-}" -O "${2:-}" ;;
+    wget) wget    "${1:-}" -O       "${2:-}" ;;
     curl) curl -L "${1:-}" --output "${2:-}" ;;
   esac
 }
@@ -3906,14 +3909,11 @@ setup_capabilities() {          # check linux capabilities needed by container
   return 0
 }
 setup_hostdbus() {              # option --hostdbus: connect to host DBus session daemon.
-  local Busadress=
-  
   warning "--hostdbus: Connecting container to host DBus degrades
   container isolation. Container applications might send malicious requests."
-  Busadress="${DBUS_SESSION_BUS_ADDRESS:-}"
   Dbusrunsession=no
     
-  [ "$Busadress" ] || {
+  [ "$DBUS_SESSION_BUS_ADDRESS" ] || {
     # no running DBus session?
     command -v dbus-launch >/dev/null && {
       export $(dbus-launch)
@@ -3925,15 +3925,15 @@ setup_hostdbus() {              # option --hostdbus: connect to host DBus sessio
   $Wikipackages"
   }
     
-  grep -q "unix:path" <<< "$Busadress" && {
+  grep -q "unix:path" <<< "$DBUS_SESSION_BUS_ADDRESS" && {
     # DBus socket file
-    store_runoption env "DBUS_SESSION_BUS_ADDRESS=$Busadress"
-    store_runoption volume "/$(cut -d/ -f2- <<<"$Busadress"):ro"
+    store_runoption env "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS"
+    store_runoption volume "/$(cut -d/ -f2- <<<"$DBUS_SESSION_BUS_ADDRESS"):ro"
   }
     
-  grep -q "unix:abstract" <<< "$Busadress" && {
+  grep -q "unix:abstract" <<< "$DBUS_SESSION_BUS_ADDRESS" && {
     # DBus abstract socket (dbus-launch)
-    store_runoption env "DBUS_SESSION_BUS_ADDRESS=$Busadress"
+    store_runoption env "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS"
     [ "${DBUS_SESSION_BUS_PID:-}" ]      && store_runoption env  "${DBUS_SESSION_BUS_PID:-}"
     [ "${DBUS_SESSION_BUS_WINDOWID:-}" ] && store_runoption env  "${DBUS_SESSION_BUS_WINDOWID:-}"
     Sharehostnet="yes"
@@ -4994,10 +4994,10 @@ create_containerrootrc() {      # create container root setup script: This scrip
     echo "      ln -s /bin/true /tmp2/objcopy"
     echo "      ln -s /bin/true /tmp2/insmod"
     echo "      Nvidiaoptions='--accept-license --no-runlevel-check --no-questions --no-backup --ui=none --no-kernel-module --no-nouveau-check'"
-    echo "      env TMPDIR=/tmp2 PATH=/tmp2:\$PATH sh $Nvidiacontainerfile -A | grep -q -- '--install-libglvnd'        && Nvidiaoptions=\"\$Nvidiaoptions --install-libglvnd\""
-    echo "      env TMPDIR=/tmp2 PATH=/tmp2:\$PATH sh $Nvidiacontainerfile -A | grep -q -- '--no-nvidia-modprobe'      && Nvidiaoptions=\"\$Nvidiaoptions --no-nvidia-modprobe\""
-    echo "      env TMPDIR=/tmp2 PATH=/tmp2:\$PATH sh $Nvidiacontainerfile -A | grep -q -- '--no-kernel-module-source' && Nvidiaoptions=\"\$Nvidiaoptions --no-kernel-module-source\""
-    echo "      env TMPDIR=/tmp2 PATH=/tmp2:\$PATH sh $Nvidiacontainerfile --tmpdir /tmp2 \$Nvidiaoptions || note 'ERROR: Installation of NVIDIA driver failed."
+    echo "      env TMPDIR=/tmp2 PATH=\"/tmp2:\$PATH\" sh $Nvidiacontainerfile -A | grep -q -- '--install-libglvnd'        && Nvidiaoptions=\"\$Nvidiaoptions --install-libglvnd\""
+    echo "      env TMPDIR=/tmp2 PATH=\"/tmp2:\$PATH\" sh $Nvidiacontainerfile -A | grep -q -- '--no-nvidia-modprobe'      && Nvidiaoptions=\"\$Nvidiaoptions --no-nvidia-modprobe\""
+    echo "      env TMPDIR=/tmp2 PATH=\"/tmp2:\$PATH\" sh $Nvidiacontainerfile -A | grep -q -- '--no-kernel-module-source' && Nvidiaoptions=\"\$Nvidiaoptions --no-kernel-module-source\""
+    echo "      env TMPDIR=/tmp2 PATH=\"/tmp2:\$PATH\" sh $Nvidiacontainerfile --tmpdir /tmp2 \$Nvidiaoptions || note 'ERROR: Installation of NVIDIA driver failed."
     echo "  Run with option --verbose to see installer output.'"
     echo "      rm -R /tmp2 && unset TMPDIR"
     echo "    } || note 'Skipping installation of $Nvidiacontainerfile'"
@@ -5473,7 +5473,7 @@ reload() {
   # message to container.CMD.sh
   echo "# Ready."
   echo "debugnote 'Container root setup is ready'"
-  echo "echo x11docker: containerrootrc is ready"
+  echo "echo 'x11docker: containerrootrc is ready' >> $(convertpath share $Containerlogfile)"
   echo ""
   
   [ "$Switchcontaineruser" = "yes" ] && {   # if "no", container.CMD.sh is executed in command line $Dockercommand
@@ -7047,12 +7047,13 @@ declare_variables() {           # declare global variables
   # Global environment variables used in x11docker
   ALSA_CARD=$(envvarstring "${ALSA_CARD:-}")
   CUPS_SERVER=$(envvarstring "${CUPS_SERVER:-}")
+  DBUS_SESSION_BUS_ADDRESS=$(envvarstring "${DBUS_SESSION_BUS_ADDRESS:-}")
   DISPLAY=$(envvarstring "${DISPLAY:-}")
   GDK_BACKEND=$(envvarstring "${GDK_BACKEND:-}")
   HOME=$(envvarstring "${HOME:-}")
   LANG=$(envvarstring "${LANG:-}")
   LC_ALL=$(envvarstring "${LC_ALL:-}")
-  #PATH=$(envvarstring "${PATH:-}")  ### FIXME whitespaces on MS Windows in $PATH
+  PATH="$(envvarstring -w "${PATH:-}")"
   WAYLAND_DISPLAY=$(envvarstring "${WAYLAND_DISPLAY:-}")
   XAUTHORITY=$(envvarstring "${XAUTHORITY:-}")
   XDG_RUNTIME_DIR=$(envvarstring "${XDG_RUNTIME_DIR:-}")
@@ -7851,6 +7852,7 @@ main "$@"
 #### ToDo notes for development
 todo() {
   # BUG Cshare/timezone, something is wrong, no timezone file
+  # --init=runit x11docker/enlightenment: where is output of containerrootrc? Should appear in container.log. --runit appears later, wtf.
   # support --exe --user
   # --nxagent -d kdeneon/plasma:user-lts leads to black fullscreen
   # cleanup(): avoid hardcoded pathes
