--stdin: new option. #45: regard WORKDIR in image

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -10,7 +10,7 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="4.2.2-beta"
+Version="4.3.0-beta"
 
 usage() {               # --help: show usage information
   echo "
@@ -102,7 +102,8 @@ Special options:
                        Password:  x11docker
      --no-internet     Disable internet access for container.
      --no-entrypoint   Disable ENTRYPOINT in image to allow other commands, too
-     --workdir DIR     Set working directory DIR
+     --workdir DIR     Set working directory DIR.
+     --stdin           Forward stdin of x11docker to image command.
      --env VAR=value   Set custom environment variable VAR=value
                        Special use case for user shell: '--env SHELL=/bin/sh'
      --showenv         Echo new \$DISPLAY, \$XAUTHORITY and \$WAYLAND_DISPLAY.
@@ -1302,7 +1303,7 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
   Longoptions="$Longoptions,tini,no-init,systemd,runit,openrc,sysvinit,sys-admin,sharecgroup"                              # init system options
   Longoptions="$Longoptions,starter,cleanup,license,licence,help,version,install,update,update-master,remove,wmlist"       # special options without starting X server
   Longoptions="$Longoptions,xhost:,no-auth,vt:,display:,xtest,no-xtest,env:,showenv,showid"                                # X and environment options
-  Longoptions="$Longoptions,verbose,stdout,stderr,silent,debug"                                                            # verbose options
+  Longoptions="$Longoptions,verbose,silent,debug,stdout,stderr,stdin"                                                      # verbose options
   Longoptions="$Longoptions,hostipc,hostnet,ps,cache,cap-default,no-entrypoint,sudouser,hostuser:,group-add:"              # capabilities, users
   Longoptions="$Longoptions,cachedir:,homedir:,westonini:,sharedir:,keymap:,runfromhost:,runasroot:"                       # developer options
   Longoptions="$Longoptions,ipc,net,dbus-daemon,dbusdaemon,sharewayland,waylandenv,add:"                                   # deprecated
@@ -1382,6 +1383,8 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
                        [ "${1:-}" = "--add" ] && warning "Option --add changed to --runfromhost and is deprecated.
   Please use --runfromhost instead." ;;  
          --runasroot) Runasroot="${2:-}" ; shift ;;        # add custom root command in container setup script
+         --stdin)     Forwardstdin="yes" ;;                # forward stdin to image command
+
          
      #### Verbose options
       -v|--verbose)    Verbose="yes"  ;;                   # be verbose
@@ -1389,7 +1392,7 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
          --stderr)     Showstderr="yes" ;;                 # show stderr of image command
          --silent)     Silent="yes" ; exec 3>/dev/null ;;  # do not show warnings or errors
          --debug)      Debug="yes" ;;                      # debugging mode
-      
+               
      #### Developer options
        ## User settings
          --user)       Benutzer="${2:-}"  ; shift ;;       # set container user instead of host user
@@ -2224,7 +2227,9 @@ Parsed options: $Parsedoptions"
   mkfile "$Sharefolder/environment"
   
   # redirect stdin to named pipe. Named pipe is shared with container and used as stdin of image command in x11docker.CMD.sh
-  cat <&0 >$Cmdstdinfile & storepid $! catstdin
+  [ "$Forwardstdin" = "yes" ] && {
+    cat <&0 >$Cmdstdinfile & storepid $! catstdin
+  }
 
   # start watching pids. Compare waitfortheend()
   echo $$>$Pidwatchfifo
@@ -3887,8 +3892,12 @@ You can disable this ENTRYPOINT with option --no-entrypoint.\" >&4"
   }
   echo   "  echo 'export HOME=\"$Benutzerhome\"'"
   echo   "  echo 'cd \"\$HOME\"'"
-  [ "$Workdir" = "/tmp" ] || echo "  echo 'cd $Workdir'"
-
+  [ "$Workdir" = "/tmp" ] && {
+    echo "Workdir=\$(docker inspect --format='{{.Config.WorkingDir}}' $Imagename)"
+    echo '[ "$Workdir" ] && echo "cd $Workdir"' 
+  } || {
+    echo "  echo 'cd $Workdir'"
+  }
   echo   "  echo ''"
   
   [ -n "$Newdisplay" ] && {
@@ -3962,7 +3971,7 @@ You can disable this ENTRYPOINT with option --no-entrypoint.\" >&4"
   echo   "  echo ''"
 
   echo   "  echo \"echo x11docker: running image command: \$Tini \\\$Dbus \$Entrypoint \$Imagecommand\""
-  echo   "  echo \"exec \$Tini \\\$Dbus \$Entrypoint \$Imagecommand <$Cshare/stdin >>$Cshare/stdout 2>>$Cshare/stderr\""
+  echo   "  echo \"exec \$Tini \\\$Dbus \$Entrypoint \$Imagecommand $([ "$Forwardstdin" = "yes" ] && echo "<$Cshare/stdin") >>$Cshare/stdout 2>>$Cshare/stderr\""
 
   echo   "  echo '# Ready for docker run'"
   echo   "} >> $Imagecommandscript"
@@ -5095,7 +5104,7 @@ $(tail $Compositorlogfile)"
 
 ######### ToDo notes for development
 todo() {
-# BUG --showid fails with sudo: file descriptor closed
+# clean up watchfifo. find way to read more than 1 line.
 
 # watchwarningfifo() only displays first line.
 # BUG opensuse/arch: issues with x11docker/fluxbox, background missing, sometimes no context menu. where is the difference?
