adjust some messages

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="7.3.2-beta-2"
+Version="7.3.2-beta-3"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -2142,7 +2142,7 @@ setup_gpu() {                   # option --gpu: share /dev/dri and check nvidia 
   return 0
 }
 setup_hostdbus() {              # option --hostdbus: connect to host DBus session daemon.
-  warning "--hostdbus: Connecting container to host DBus degrades
+  warning "Option --hostdbus: Connecting container to host DBus degrades
   container isolation. Container applications might send malicious requests."
   Dbusrunsession="no"
 
@@ -5133,7 +5133,7 @@ check_backend() {               # options --backend, --rootless
     docker|podman|nerdctl)
       # Check whether docker daemon is running, get backend info
       Backendinfo="$(unpriv_backend "env LC_ALL=C $Backendbin info --format='{{json .}}'" 2>&1)"
-      [ "$?" != "0" ] || grep -q "permission denied" <<< "$Backendinfo" || [ -z "$Backendinfo" ] && error "--backend=$Backend: Error executing $Backend.
+      [ "$?" != "0" ] || grep -q "permission denied" <<< "$Backendinfo" || [ -z "$Backendinfo" ] && error "Option --backend=$Backend: Error executing $Backend.
   If using docker: Is docker daemon running at all?
   Maybe you need root privileges to run docker?
   Try to start docker daemon with 'systemctl start docker'.
@@ -5193,7 +5193,7 @@ check_backend() {               # options --backend, --rootless
   Effectively applications in proot have the same privileges as if
   they would have been installed and started directly on the host system."
       check_optionset "--backend=$Backend" "--cap-default --hostipc --ipc --limit --network --newprivileges --no-setup --runtime --sharecgroup --user" ||:
-      check_optionset "--backend=$Backend" "--user" || error "--backend=$Backend: Option --user is not allowed.
+      check_optionset "--backend=$Backend" "--user" || error "Option --backend=$Backend: Option --user is not allowed.
   Please try option --hostuser instead."
       # set defaults. Some might look misleading just to avoid later messages, but not affecting the setup.
       Network="host"
@@ -5209,18 +5209,18 @@ check_backend() {               # options --backend, --rootless
       Switchcontaineruser="yes"
 
       [ -z "$Rootfs" ] && [ -d "$Hosthomebasefolder/ROOTFS/$Imagebasename" ] && Rootfs="$Hosthomebasefolder/ROOTFS/$Imagebasename"
-      [ -z "$Rootfs" ] && error "--backend=$Backend: Did not find a rootfs for $Imagename
+      [ -z "$Rootfs" ] && error "Option --backend=$Backend: Did not find a rootfs for $Imagename
   in $Hosthomebasefolder/ROOTFS/$Imagebasename"
       [ -z "$Containercommand" ] && [ -e "$Rootfs/start" ] && Containercommand="/bin/sh /start"
       [ -z "$Containercommand" ] && {
         [ -e "$Rootfs/bin/bash" ]                          && Containercommand="/bin/bash" || Containercommand="/bin/sh"
         [ "$Containerusershell" != "auto" ]                && Containercommand="$Containerusershell"
-        note "--backend=$Backend: No command specified.
+        note "Option --backend=$Backend: No command specified.
 Fallback: using command '$Containercommand' and enabling option --interactive."
         check_fallback
         Interactive="yes"
       }
-      [ "$Sudouser" ] && note "--backend=$Backend --sudouser: sudo fails in $Backend.
+      [ "$Sudouser" ] && note "Option --backend=$Backend --sudouser: sudo fails in $Backend.
   Workaround: starting with user root.
   You can switch to user $Containeruser with 'su $Containeruser'.
   Note that root in $Backend is a fake and does not have real root privileges."
@@ -5233,7 +5233,7 @@ Fallback: using command '$Containercommand' and enabling option --interactive."
       # --dbus, --hostdbus, --init
       check_optionset "--backend=$Backend" "--alsa --cap-default --group-add --hostipc --ipc --limit --home --name --network --newprivileges --no-entrypoint --no-setup \
                        --printer --pulseaudio --runasroot --runtime --share --sharecgroup --sudouser --webcam" ||:
-      check_optionset "--backend=$Backend" "--user" || error "--backend=$Backend: Option --user is not allowed.
+      check_optionset "--backend=$Backend" "--user" || error "Option --backend=$Backend: Option --user is not allowed.
   Please try option --hostuser instead."
       # set defaults. Some might look misleading just to avoid later messages, but not affecting the setup.
       Sharealsa="no"
@@ -5968,7 +5968,7 @@ create_backendcommand() {       ### create command to run docker|podman|nerdctl 
   --volume $(convertpath volume "$Persistanthomevolume" "$Containeruserhomebasefolder")" ### FIXME $Containeruserhomebasefolder ?? mount/volume?
         ;;
         *)
-          error "--backend=$Backend: Sharing a docker volume is not supported.
+          error "Option --backend=$Backend: Sharing a docker volume is not supported.
   Failing option: --home=$Persistanthomevolume"
         ;;
       esac
@@ -5993,7 +5993,7 @@ create_backendcommand() {       ### create command to run docker|podman|nerdctl 
       ;;
       proot)
         grep -q ':ro' <<< "$Line" && {
-          warning "--backend=proot cannot mount read-only:
+          warning "Option --backend=proot cannot mount read-only:
   $Line
   Fallback: mounting with r/w"
           check_fallback
@@ -7949,8 +7949,8 @@ $(rmcr < "$Containerlogfile" | uniq )"
   $Remountcommand"
         echo "cgroup mount with nsenter:" >> "$Containerlogfile"
         unpriv_backend "$Remountcommand" >> "$Containerlogfile" 2>&1 || {
-          note "--init=$Initsystem: Failed to remount /sys/fs/cgroup in container.
-  Startup of systemd might fail.
+          note "Option --init=$Initsystem: Failed to remount /sys/fs/cgroup
+  in container. Startup of systemd might fail.
   nsenter command:
     $Remountcommand
   Last lines of log:
@@ -8031,14 +8031,14 @@ start_xcontainer() {            # --xc
     Xpid1pid="$(parse_inspect "$Containerinspect" "State" "Pid")"
     setonwatchpidlist "$Xpid1pid" "Xcontainerpid1"
   } || {
-    error "--xc: Startup of x11docker/xserver failed.
+    error "Option --xc: Startup of x11docker/xserver failed.
   Last lines of xinit log:
 $(tail "$Xinitlogfile")"
     return 1
   }
 
   [ "$Nvidiainstallerfile" ] && {
-    note "Installing NVIDIA driver in X container."
+    note "Option --gpu: Installing NVIDIA driver in X container."
     unpriv_xcbackend "$Xcontainerbackend exec --tty --privileged --user=root $Xcontainername bash $Sharefolder/nvidia_installer" >> "$Xinitlogfile" 2>&1 || note 'ERROR: NVIDIA driver installation in X container failed.'
   }
 
@@ -10246,7 +10246,7 @@ check_options_messages() {      # some messages depending on options, but not ch
   # --scale
   [ "$Scaling" ] && case "$Xserver" in
     --xorg)
-      [ -n "$Rotation" ] && [ "1" = "$(awk -v a="$Scaling" 'BEGIN {print (a < 1)}')" ] && note "--xorg does not work well with combination
+      [ -n "$Rotation" ] && [ "1" = "$(awk -v a="$Scaling" 'BEGIN {print (a < 1)}')" ] && note "Option --xorg does not work well with combination
   of --scale smaller than 1 and rotation different from 0."
     ;;
   esac
