new option --update-master. --update points to latest release now
### Added
 - `--update-master` updates to lastest x11docker master version. (Formerly job of `--update`).
### Changed
 - `--update` updates to latest x11docker release on github. (Formerly: latest master version).

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -9,9 +9,10 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # https://github.com/mviereck/x11docker
 
-Version="4.0.0"
+Version="4.0.1.0-beta"
 
-todo() {
+todo() {                # ToDo notes for development
+#
 # --dbus-system: policykit must not have no-new-privileges. Seems to use setuid? Core issue AccountsService?
 #                starting polkitd and accounts-daemon in setupscript helps:
 #                -> cinnamon starts up with lots of (harmless?) error messages
@@ -19,8 +20,7 @@ todo() {
 # --wayland --dbus-system GTK3 seems to work now!?
 # check fgconsole
 # bestwu/deepin: why sh is replaced by bash?
-# x11docker/fvwm: check quit option
-# opensuse/arch: issues with x11docker/fluxbox, background missing, sometimes no context menu
+# BUG opensuse/arch: issues with x11docker/fluxbox, background missing, sometimes no context menu. where is the difference?
 # BUG --weston,--kwin: docker sometimes fails although socket exists: "stat /run/user/1000/wayland-607: no such file or directory". dirty sleep needed?
 # check echo especially in sh scripts, replace with printf if needed (#25)
 # avoid possible confusions --home --sharedir. --sharedir mounts can overlap --home folder. What about softlinks with existing target in --home? Maybe avoid /home/$USER at all
@@ -51,6 +51,7 @@ todo() {
 # --xorg: check custom systemd start of X #7
 # check X in container #7
 # some tests with Xephyrglamor=no
+
 ### BUG collection: non x11docker bugs
 # BUG Xwayland does not always sit at 0:0 on multiple outputs. 
 #     bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1498665
@@ -309,7 +310,8 @@ Verbose options:
 
 Installation options (need root permissions):
      --install         Install x11docker and x11docker-gui from current folder.
-     --update          Download and install latest version from github.
+     --update          Download and install latest release from github.
+     --update-master   Download and install latest master version from github.
      --remove          Remove x11docker from your system.
 
 x11docker version: $Version
@@ -445,13 +447,15 @@ verbose() {             # show verbose messages
 " >> "$Logfile"
   return 0
 }
-installer() {           # --install, --update, --remove: Installer for x11docker
+installer() {           # --install, --update, --update-master, --remove: Installer for x11docker
   # --install:
   #   - copies x11docker and x11docker-gui to /usr/bin
   #   - installs icon in /usr/share/icons
   #   - creates x11docker.desktop file in /usr/share/applications
   # --update:
-  #   - download and install latest version from github
+  #   - download and install latest release from github
+  # --update-master:
+  #   - download and install latest master version from github
   # --remove
   #   - remove installed files
   local X11dockericonfile
@@ -471,35 +475,43 @@ installer() {           # --install, --update, --remove: Installer for x11docker
   x11docker itself does not need it and works fine from cli.
   Get kaptain on github: https://github.com/mviereck/kaptain" ; }
     ;;
-    --update)
-      mkdir -p /tmp/x11docker-install && cd /tmp/x11docker-install || error "Could not create or cd to /tmp/x11docker-install"
-
-      echo "Downloading latest x11docker version from github"
-      command -v wget >/dev/null || error "wget not found. Need 'wget' for download.
+    --update|--update-master)
+      [ -d /tmp/x11docker-install ] && rm -R /tmp/x11docker-install
+      mkdir -p /tmp/x11docker-install && cd /tmp/x11docker-install || error "Could not create or cd to /tmp/x11docker-install" 
+      command -v wget >/dev/null  || error "wget not found. Need 'wget' for download.
   Please install wget."
-      wget https://github.com/mviereck/x11docker/archive/master.zip || error "Could not download x11docker-master from github"
-
-      echo "Unpacking archive"
       command -v unzip >/dev/null || error "Can not unpack archive. Please install 'unzip'."
-      unzip master.zip || error "Could not unzip archive"
+  
+      case ${1:-} in
+        --update-master)
+          note "Downloading latest x11docker master version from github"
+          wget https://github.com/mviereck/x11docker/archive/master.zip -O x11docker-update.zip || error "Could not download x11docker-master from github"
+        ;;
+        --update)
+          note "Downloading latest x11docker release from github"
+          wget https://www.github.com/$(wget "https://github.com/mviereck/x11docker/releases/latest" -O - | grep "\.zip" | cut -d'"' -f2) -O x11docker-update.zip || error "Could not download latest x11docker release from github"
+        ;;
+      esac
+  
+      note "Unpacking archive"
+      unzip x11docker-update.zip || error "Could not unzip archive"
   
       echo ""
-      cd /tmp/x11docker-install/x11docker-master || error "could not cd to /tmp/x11docker-install/x11docker-master"
+      cd /tmp/x11docker-install/$(ls -l | grep drwx | rev | cut -d' ' -f1 | rev) || error "could not cd to /tmp/x11docker-update/$(ls -l | grep drwx | rev | cut -d' ' -f1 | rev)"
     ;;
   esac
 
   # Doing
   case ${1:-} in
-    --install|--update)
+    --install|--update|--update-master)
       [ -x /usr/local/bin/x11docker ]     && rm -v /usr/local/bin/x11docker
       [ -x /usr/local/bin/x11docker-gui ] && rm -v /usr/local/bin/x11docker-gui
-      echo "Installing x11docker and x11docker-gui in /usr/bin"
+      note "Installing x11docker and x11docker-gui in /usr/bin"
       cp x11docker /usr/bin/           || error "Could not copy x11docker to /usr/bin"
       chmod 755 /usr/bin/x11docker      || error "Could not set executeable bit on x11docker"
       cp x11docker-gui /usr/bin/  && chmod 755 /usr/bin/x11docker-gui || warning "x11docker-gui not found"
       
-
-      echo "Creating icon and application entry for x11docker"
+      note "Creating icon and application entry for x11docker"
       X11dockericonfile=$(x11docker-gui --icon)
       [ -e "$X11dockericonfile" ] && {
         xdg-icon-resource install --context apps --novendor --size 72 "$X11dockericonfile" x11docker
@@ -525,16 +537,17 @@ installer() {           # --install, --update, --remove: Installer for x11docker
     https://github.com/mviereck/kaptain
   Fallback: x11docker-gui will try to use image x11docker/kaptain."
 
-      echo "Storing README.md and LICENSE.txt in /usr/share/doc/x11docker"
+      note "Storing README.md, CHANGELOG.md and LICENSE.txt in /usr/share/doc/x11docker"
       mkdir -p /usr/share/doc/x11docker && {
-        cp README.md /usr/share/doc/x11docker/
-        cp LICENSE.txt /usr/share/doc/x11docker/
+        cp README.md    /usr/share/doc/x11docker/
+        cp CHANGELOG.md /usr/share/doc/x11docker/
+        cp LICENSE.txt  /usr/share/doc/x11docker/
       } || note "Error while creating /usr/share/doc/x11docker"
       
-      echo "Installation ready: x11docker version $(x11docker --version)"
+      note "Installation ready: x11docker version $(x11docker --version)"
     ;;
     --remove)
-      echo "removing x11docker from your system"
+      note "removing x11docker from your system"
       [ -x /usr/local/bin/x11docker ] && {    # from older installations. /usr/bin is default now as /usr/local/bin can miss in $PATH for root
         /usr/local/bin/x11docker --cleanup
         rm -v /usr/local/bin/x11docker
@@ -557,13 +570,13 @@ installer() {           # --install, --update, --remove: Installer for x11docker
 
   # Cleanup
   case ${1:-} in
-    --update)
-      echo "Removing downloaded files"
+    --update|--update-master)
+      note "Removing downloaded temporary files"
       cd ~
       rm -R /tmp/x11docker-install
     ;;
   esac
-  echo "Ready."
+  note "Ready."
 }
 checkorphaned() {       # --cleanup : check for non-removed containers and left cache files
   local Orphanedcontainers Orphanedfolders Line
@@ -723,7 +736,7 @@ $(sh -c "${1:-}")"
 isnum() {               # check if $1 is a number
   [ "1" = "$(awk -v a="${1:-}" 'BEGIN {print (a == a + 0)}')" ]
 }
-escapestring() {          # escape special chars of $1
+escapestring() {        # escape special chars of $1
   # escape all characters except those described in [^a-zA-Z0-9,._+@=/-]
   echo "${1:-}" | LC_ALL=C sed -e 's/[^a-zA-Z0-9,._+@=/-]/\\&/g; 1{$s/^$/""/}; 1!s/^/"/; $!s/$/"/'
 }
@@ -1086,7 +1099,7 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
   Longoptions="$Longoptions,user:,home,clipboard,pulseaudio,alsa,lang:"                                                    # comfort options
   Longoptions="$Longoptions,no-xhost,trusted,untrusted,dbus,dbus-system,pw:,no-internet,workdir:"                          # advanced options
   Longoptions="$Longoptions,tini,no-init,systemd,runit,openrc,sysvinit,sys-admin,sharecgroup"                              # init system options
-  Longoptions="$Longoptions,starter,cleanup,license,licence,help,version,install,update,remove,wmlist"                     # special options without starting X server
+  Longoptions="$Longoptions,starter,cleanup,license,licence,help,version,install,update,update-master,remove,wmlist"       # special options without starting X server
   Longoptions="$Longoptions,xhost:,no-auth,vt:,display:,xtest,no-xtest,env:,showenv"                                       # X and environment options
   Longoptions="$Longoptions,verbose,stdout,stderr,silent,debug"                                                            # verbose options
   Longoptions="$Longoptions,hostipc,hostnet,ps,cache,cap-default,no-entrypoint,sudouser,hostuser:"                         # capabilities, users
@@ -1246,7 +1259,7 @@ $Customenvironment"    ;  shift ;;                         # set custom environm
       --starter)       Createdesktopstarter="yes" ;;       # create desktop starter and exit
       --cleanup)       Checkorphaned="yes"  ;;             # check for orphaned containers and files owned by root, created by docker)
       --orphaned)      Checkorphaned="yes" ; note "Option '--orphaned' is now called '--cleanup'." ;;
-      --install|--update|--remove) Installermode="${1:-}" ;;   # installer
+      --install|--update|--update-master|--remove) Installermode="${1:-}" ;;   # installer
       --wmlist)        echo $Wm_all ; exit 0 ;;            # special option for x11docker-gui to retrieve list of window managers
 
      #### deprecated
