--xc=podman: fixes for sudo+'--rootless', fix for shared ipc #466

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="7.4.3-beta-4"
+Version="7.4.3-beta-5"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups. (deprecated)
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -2845,6 +2845,9 @@ check_xcontainer() {            # option --xc: check backend, rootless and image
     yes)
       { [ "$Xserver" = "--xorg" ] || [ -n "$Newxvt" ] ; } && Xcrootless="no" || Xcrootless="yes"
     ;;
+    no)
+      Xcrootless="no"
+    ;;
   esac
 
   # check if image x11docker/xserver is available
@@ -4482,7 +4485,7 @@ create_xcontainercommand() {    # option --xc: create docker command for X in co
   --ipc=host"
     ;;
     no)
-      case "$Backend" in
+      case "$Xcontainerbackend" in
         docker)
           Xcontainercommand="$Xcontainercommand \\
   --ipc=shareable"
@@ -5528,8 +5531,11 @@ Fallback: using command '$Containercommand' and enabling option --interactive."
 check_image() {                 # get some image information
 
   # Check if image $Imagename is available locally
-  Imageinspect="$(unpriv_backend "$Backendbin inspect $Imagename" 2>> $Containerlogfile)" || error "Image $Imagename not found locally.
+  Imageinspect="$(unpriv_backend "$Backendbin inspect $Imagename" 2>> $Containerlogfile)" || {
+    error "Image $Imagename not found locally.
   Please pull or build image first. (Backend $Backend, rootless $Backendrootless)"
+    return 1
+  }
 
   # Check architecture
   Imagearchitecture=$(parse_inspect "$Imageinspect" "Architecture")
@@ -5559,7 +5565,7 @@ check_image() {                 # get some image information
       Containeruser="${Imageuser:-root}"
     ;;
   esac
-  storeinfo containeruser="$Containeruser"
+  storeinfo "containeruser=$Containeruser"
 
   # Check ENTRYPOINT
   Imageentrypoint="$(parse_inspect "$Imageinspect" "Config" "Entrypoint")"
