nsenter: check if /sys/fs/cgroup is rw already

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -452,7 +452,7 @@ error() {                       # show error message and exit
   Message="$(rmcr <<< "$Message")"
 
   # output to terminal
-  [ -z "$Verbose" ] && echo -e "
+  echo -e "
 ${Colredbg}x11docker ERROR:${Colnorm} $Message
 " >&2
 
@@ -477,7 +477,7 @@ logentry() {                    # write into logfile
 $*"
 }
 note() {                        # show notice messages
-  [ -z "$Verbose" ] && echo "${Colgreen}x11docker note:${Colnorm} $*
+  [ "$Verbose" = "yes" ] || echo "${Colgreen}x11docker note:${Colnorm} $*
 " >&${FDstderr}
   logentry "x11docker note: $*
 "
@@ -495,7 +495,7 @@ verbose() {                     # show verbose messages
 "
 }
 warning() {                     # show warning messages
-  [ -z "$Verbose" ] && echo "${Colyellow}x11docker WARNING:${Colnorm} $*
+  [ "$Verbose" = "yes" ] || echo "${Colyellow}x11docker WARNING:${Colnorm} $*
 " >&${FDstderr}
   logentry "x11docker WARNING: $*
 "
@@ -6738,6 +6738,7 @@ sed -i 's/ProtectHostname=yes/ProtectHostname=no/' /lib/systemd/system/systemd-l
 
 # create systemd units for x11docker
 
+mkdir -p /etc/systemd/system.conf.d
 echo \"[Manager]
 DefaultEnvironment=$(while read -r Line; do echo -n "$Line " ; done < <(store_runoption dump env))
 \" > /etc/systemd/system.conf.d/x11docker.environment.conf
@@ -7185,12 +7186,14 @@ $(rmcr < "$Containerlogfile" | uniq )"
         Remountcommand="$Remountcommand --cap-add SYS_ADMIN --cap-add=SYS_PTRACE --security-opt apparmor=unconfined"
         Remountcommand="$Remountcommand --pid=container:$Containerid"
         Remountcommand="$Remountcommand --entrypoint /usr/bin/env"
+        [ "$Runtime" ] && Remountcommand="$Remountcommand --runtime $Runtime"
         Remountcommand="$Remountcommand -- $Imagename"
         Remountcommand="$Remountcommand nsenter -t 1 -m -C -p /bin/sh -c '"
         Remountcommand="$Remountcommand         set -x ; "
-        Remountcommand="$Remountcommand         mount -v -o remount,rw /sys/fs/cgroup/ && "
-        Remountcommand="$Remountcommand touch /nsenter_is_ready || echo \"ERROR: cgroup mount failed.\" '"
-        debugnote "start_container(): nsenter command:
+        Remountcommand="$Remountcommand         findmnt /sys/fs/cgroup -O rw || mount -v -o remount,rw /sys/fs/cgroup/ ; "
+        Remountcommand="$Remountcommand         findmnt /sys/fs/cgroup -O rw || echo \"ERROR: cgroup mount failed.:NOTE\" >>/x11docker/message.fifo ; "
+        Remountcommand="$Remountcommand         touch /nsenter_is_ready'"
+        note "start_container(): nsenter command:
   $Remountcommand"
         echo "cgroup mount with nsenter:" >> "$Containerlogfile"
         eval $Remountcommand >> "$Containerlogfile" 2>&1 || {
