--backend=nerdctl: allow --interactive; skip runtime check #357

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4087,15 +4087,19 @@ create_dockercommand() {        ### create command to run docker
   local Line= Memory Tini=
   
   Dockercommand="$Containerbackendbin run"
-  case "$Containerbackend" in
-    nerdctl) ;;
-    *) Dockercommand="$Dockercommand --tty" ;;
-  esac
   Wmdockercommand="$Containerbackendbin run --detach"
   #[ "$Preservecachefiles" = "no" ] && Dockercommand="$Dockercommand --rm"
   case $Interactive in
-    yes) Dockercommand="$Dockercommand --interactive" ;;
-    no)  Dockercommand="$Dockercommand --detach" ;;
+    yes) 
+      Dockercommand="$Dockercommand --interactive --tty" 
+    ;;
+    no)  
+      Dockercommand="$Dockercommand --detach" 
+      case "$Containerbackend" in
+        nerdctl) ;;
+        *) Dockercommand="$Dockercommand --tty" ;;
+      esac
+    ;;
   esac
 
   [ -z "$Containername" ] && Containername="x11docker_X${Newdisplaynumber}_${Codename}_${Cachenumber}"
@@ -5638,9 +5642,9 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
 
   echo "# Check whether docker daemon is running, get docker info"
   echo "$Containerbackendbin info >>$Dockerinfofile 2>>$Containerlogfile  || {
-  error \"Calling docker daemon failed.
-  Is docker daemon running at all?
-  Try to start docker daemon with:   systemctl start docker
+  error \"'$Containerbackend info' failed.
+  If using docker: Is docker daemon running at all?
+  Try to start docker daemon with 'systemctl start docker'.
   Last lines of log:
 \$(rmcr < '$Containerlogfile' | tail)\"
 }"
@@ -5649,20 +5653,22 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   
   echo "# Check default runtime"
   echo "Runtime=\"\$( { grep 'Default Runtime' < '$Dockerinfofile' ||: ;} | awk '{print \$3}' )\""
-  echo "debugnote \"dockerrc: Found default Runtime: \$Runtime\""
-  echo "debugnote \"dockerrc: All \$(grep 'Runtimes' < '$Dockerinfofile' ||: )\""
-  echo "[ \"\$Runtime\" != '$Runtime' ] && {"
-  echo "  case \$Runtime in"
-  echo "    kata-runtime)  warning 'Found default docker runtime kata-runtime.
+  echo '[ -n "$Runtime" ] && {' 
+  echo "  debugnote \"dockerrc: Found default Runtime: \$Runtime\""
+  echo "  debugnote \"dockerrc: All \$(grep 'Runtimes' < '$Dockerinfofile' ||: )\""
+  echo "  [ \"\$Runtime\" != '$Runtime' ] && {"
+  echo "    case \$Runtime in"
+  echo "      kata-runtime)  warning 'Found default docker runtime kata-runtime.
   Please run x11docker with --runtime=kata-runtime to avoid issues.' ;;"
-  echo "    nvidia) [ '$Sharegpu' = 'yes' ] &&  warning 'Option --gpu: Found default docker runtime nvidia.
+  echo "      nvidia) [ '$Sharegpu' = 'yes' ] &&  warning 'Option --gpu: Found default docker runtime nvidia.
   Please run x11docker with --runtime=nvidia to avoid issues.' ;;"
-  echo "    runc|crun|oci) ;;"
-  echo "    *) note \"Found unknown container runtime: \$Runtime
+  echo "      runc|crun|oci) ;;"
+  echo "      *) note \"Found unknown container runtime: \$Runtime
   Please report at:  https://github.com/mviereck/x11docker\" ;;"
-  echo "  esac"
-  [ "$Runtime" ] && echo "  Runtime='$Runtime'"
+  echo "    esac"
+  echo "  }"
   echo "}"
+  echo "Runtime='${Runtime:-UNDECLARED_RUNTIME}'"
   echo "debugnote \"dockerrc: Container Runtime: \$Runtime\""
   echo "storeinfo \"runtime=\$Runtime\""
   echo ""
