fix output for early errors

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="7.0.0-beta-19"
+Version="7.0.0-beta-20"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -2203,6 +2203,25 @@ setup_webcam() {                # option --webcam: share webcam devices
   
   # at least cheese and gnome-ring need some device information from udev.
   store_runoption volume "/run/udev/data:ro"
+  return 0
+}
+set_password() {                # option --password: set container user password
+  local Password
+  
+  Password="${1:-}"
+
+  command -v perl >/dev/null || error "Option --password: command 'perl' not found.
+  perl is needed to generate an encrypted password."
+  [ "$Password" = "INTERACTIVE" ] && {
+    read -rs -p "Please type in a new container user password (chars are invisible): " Password
+    echo ""
+    [ -z "$Password" ] && error "Empty input, password not changed."
+  }
+  Password="$(perl -e "print crypt(\"$Password\", \"salt\")")"
+  mkdir -p "$(dirname "$Passwordfile")"
+  echo "$Containeruserpassword" > "$Passwordfile"
+  chmod 600                       "$Passwordfile"
+  note "Option --password: Password changed, exiting."
   return 0
 }
 
@@ -8881,18 +8900,7 @@ main() {
   parse_options "$@"
   
   [ -n "$Containeruserpassword" ] && {                                            # --password
-    command -v perl >/dev/null || error "Option --password: command 'perl' not found.
-  perl is needed to generate an encrypted password."
-    [ "$Containeruserpassword" = "INTERACTIVE" ] && {
-      read -rs -p "Please type in a new container user password (chars are invisible): " Containeruserpassword
-      echo ""
-      [ -z "$Containeruserpassword" ] && error "Empty input, password not changed."
-    }
-    Containeruserpassword="$(perl -e "print crypt(\"$Containeruserpassword\", \"salt\")")"
-    mkdir -p "$(dirname "$Passwordfile")"
-    echo "$Containeruserpassword" > "$Passwordfile"
-    chmod 600                       "$Passwordfile"
-    note "Option --password: Password changed, exiting."
+    set_password "$Containeruserpassword"
     finish
   }
 
@@ -8907,6 +8915,7 @@ main() {
   check_runmode                 # modes: run image, or host command, or X only    # --exe, --xonly
   check_hostuser                # find unprivileged host user                     # --hostuser
   create_cachefiles             # create cache files owned by unprivileged user   # --cachebasedir
+  setup_verbosity                # create [and show] summary logfile              # --verbose
   check_hostxenv                # check X environment from host
   storeinfo "x11dockerpid=$$"   # store pid of x11docker
 
@@ -8963,7 +8972,6 @@ Parsed options:    $Parsedoptions_global"
   
   # some checks and setup
   drop_cachefiles                # remove cachefiles not needed for current setup
-  setup_verbosity                # create [and show] summary logfile              # --verbose
   setup_fifo                     # open message channels for container, dockerrc, xinitrc and watchpidlist()
   check_screensize               # size of host X and of new X server             # --size #time0,213
   [ "$Windowmanagermode" ]       && check_windowmanager                           # --wm  
