Add files via upload

diff --git a/x11docker-gui b/x11docker-gui
--- a/x11docker-gui
+++ b/x11docker-gui
@@ -14,10 +14,14 @@ if test ! `command -v kaptain` ; then
   exit 1
 fi
 
-if test ! `command -v x11docker` ; then
-  echo "Error: did not find executeable 'x11docker'. 
-  Please make x11docker available (for example in /usr/local/bin) and try again." >&2
-  xmessage "Error: did not find executeable 'x11docker'. 
+X11DOCKER="./x11docker"
+if test ! `command -v $X11DOCKER` ; then X11DOCKER="x11docker" ; fi
+if test ! `command -v $X11DOCKER` ; then
+  echo "Error: did not find executeable 'x11docker', neither in \$PATH. nor as
+ executeable ./x11docker.
+ Please make x11docker available (for example in /usr/local/bin) and try again." >&2
+  xmessage "Error: did not find executeable 'x11docker', neither in \$PATH. nor as
+  executeable ./x11docker.
   Please make x11docker available (for example in /usr/local/bin) and try again."
   exit 1
 fi
@@ -60,7 +64,7 @@ start "x11docker GUI" -> options buttons;
     frameleft:framed -> choose_image choose_X choose_wmordesktop;
     frameright:framed -> choose_options choose_options_advanced;
 
-  devel " Developer options. \n Use with care." -> devalsa devxsocket devtcp devtcpxsocket devsharegpu devxhost devprivileged devpid devnet devuts;
+  devel " Developer options. \n Use with care." -> devalsa devxsocket devtcp devtcpxsocket devsharegpu devxhost devprivileged devpid devnet devuts useless_options ;
     devalsa "--alsa: enable ALSA sound (alpha)" -> "--alsa " | ! "" ;
     devxsocket "--xsocket: Use shared \n X socket (default)" -> "--xsocket " | ! "" ;
     devtcp "--tcp: Use X over tcp \n instead of shared X socket" -> "--tcp " | ! "" ;
@@ -71,9 +75,9 @@ start "x11docker GUI" -> options buttons;
     devpid "--pid: docker run --pid=host" -> "--pid " | ! "";
     devnet "--net: docker run --net=host" -> "--net " | ! "";
     devuts "--uts: docker run --uts=host" -> "--uts " | ! "";
+  useless_options "Less usefull options" -> log LOG ps ;
 
     choose_image "Run GUI applications from inside of docker images" -> imageorexe dockeroptions command;
-      info -> @text("x11docker allows you to run GUI applications or full desktops environments \n from inside of docker images. See <Help> for dependencies and more infos.");
       imageorexe -> image | exe | xonly;
         image:beside "Run docker image in another X server" -> " " security_dialog;
         exe "Start host application in another X server (instead of docker image)" -> "exe ";
@@ -121,7 +125,8 @@ start "x11docker GUI" -> options buttons;
       root "--root: Allow root to run x11docker" -> "--root " | ! "";
       sudo "--sudo: Use sudo instead of su to run docker" -> "--sudo " | '$SUDO' "";
       
-  help:dialog "Help" -> @text("x11docker \n
+  help:dialog "Help" -> @text(
+  " x11docker \n
     \n
     x11docker allows you to run GUI applications and desktop environments from inside of docker images. \n
     Its main goal is to preserve container isolation. This is tricky due to some X security leaks. \n
@@ -233,7 +238,8 @@ start "x11docker GUI" -> options buttons;
                        from docker containers, it is recommended to use option --no-xhost.\n
                        You may also check your ~/.Xauthority cookies with command \"xauth list\"");
                        
-  MIT:dialog "MIT license" -> @text(" MIT License\n
+  MIT:dialog "MIT license" -> @text(
+               " MIT License\n
                  \n
                  Copyright (c) 2015,2016 Martin Viereck\n
                  \n
@@ -256,18 +262,16 @@ start "x11docker GUI" -> options buttons;
                  SOFTWARE.") @close="close";
 
 x11docker_options -> choose_X choose_wmordesktop choose_options choose_options_advanced devel "--" choose_image;
-x11docker -> "x11docker " x11docker_options;
+x11docker -> "'$X11DOCKER' " x11docker_options;
 
 buttons :horizontal ->  run preview desktop_starter orphanedcheck MIT help @close="Cancel";
   run -> @dump(x11docker)=" Run";
-  runxterm -> @dump("xterm -xrm '"'"'XTerm*selectToClipboard: true'"'"' -hold -e ",x11docker)="Run in xterm";
   preview -> @preview(x11docker,"monospace",900)="Preview command" ;
-  desktop_starter -> @dump("xterm -e '\''","x11docker --starter ",x11docker_options,"'\''")="Create desktop starter";
-  orphanedcheck -> @dump("xterm -hold -e '"'"'x11docker --orphaned '"'"'")="Check orphaned";
-  license -> @dump("xterm -hold -e '"'"'x11docker --license'"'"'")="MIT license";
+  desktop_starter -> @dump("xterm -e '\''","'$X11DOCKER' --starter ",x11docker_options,"'\''")="Create desktop starter";
+  orphanedcheck -> @dump("xterm -hold -e '"'"''$X11DOCKER' --orphaned '"'"'")="Check orphaned";
 '
 
-x11docker_command=$(echo $kaptain_script | kaptain /dev/stdin 2> /dev/null)
+x11docker_command=$(echo $kaptain_script | kaptain /dev/stdin)
 echo $x11docker_command
 eval $x11docker_command
 
