--sysvinit: clean shutdown on SIGINT / Ctrl-C

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -383,7 +383,7 @@ error() {               # show error messages on stderr and exit
 
   # output to terminal
   [ "$Verbose" = "no" ] && echo -e "
-\033[41mx11docker ERROR:\033[49m $Message
+${Colredbg}x11docker ERROR:${Colnorm} $Message
 " >&2
 
   # output to logfile
@@ -401,13 +401,13 @@ error() {               # show error messages on stderr and exit
   finish 1
 }
 warning() {             # show warning messages
-  [ "$Verbose" = "no" ] && echo "$(tput setaf 3)x11docker WARNING:$(tput sgr0) $*
+  [ "$Verbose" = "no" ] && echo "${Colyellow}x11docker WARNING:${Colnorm} $*
 " >&3
   logentry "x11docker WARNING: $*
 "
 }
 note() {                # show notice messages
-  [ "$Verbose" = "no" ] && echo "$(tput setaf 2)x11docker note:$(tput sgr0) $*
+  [ "$Verbose" = "no" ] && echo "${Colgreen}x11docker note:${Colnorm} $*
 " >&3
   logentry "x11docker note: $*
 "
@@ -422,7 +422,7 @@ verbose() {             # show verbose messages
 debugnote() {           # show debug output $*
   [ "$Debugmode" = "yes" ] && {
     logentry "DEBUGNOTE: $*"
-    [ "$Verbose" = "no" ] && echo "${Esc}[35mDEBUGNOTE:${Esc}[0m $*" >&3
+    [ "$Verbose" = "no" ] && echo "${Colblue}DEBUGNOTE:${Colnorm} $*" >&3
   } ||:
 }
 logentry() {            # write into logfile
@@ -517,7 +517,7 @@ $(ps -p $Pid)"
   [ "$$" = "$BASHPID" ] || return 0
 
   # Check if container is still running.
-  # if kill failed in loop above, most times terminating X server will already have stopped GUI applications.
+  # if kill of PID 1 failed in loop above, most times terminating X server will already have stopped GUI applications.
   checkpid $Containerpid && { 
     $Sudo docker stop $Containername >>$Containerlogfile 2>&1 || {
       note "Found remaining container process. Most probably the X session was
@@ -533,11 +533,11 @@ $(ps -p $Pid)"
         note "docker container didn't terminate as it should. 
   Will not clean cache to avoid file permission issues. 
   You can remove the new container with command:
-docker rm -f $Containername
+    docker rm -f $Containername
   Afterwards, remove cache files with:
-rm -R $Cachefolder
+    rm -R $Cachefolder
   or let x11docker do the cleanup work for you: 
-x11docker --cleanup"
+    x11docker --cleanup"
         Preservecachefiles="yes"
       else
         note "docker container terminated successfully"
@@ -644,7 +644,7 @@ waitfortheend() {       # wait for end of x11docker
   # signal is byte in $Timetosaygoodbyefifo
   # decent read to wait for signal to terminate
   while rocknroll; do
-    bash -c "read -n1 -t1 <&8"
+    bash -c "read -n1 -t1 <&8 ||:"
   done
 }
 waitforfilecreation() { # similar to inotify-wait: wait up to 15s for file $1 to be created
@@ -1160,7 +1160,17 @@ Messagefifo=message.fifo
 
 # x11docker log 
 Logfile=""
+
+# terminal colors
 Esc="$(printf '\033')"
+Colnorm="${Esc}[0m"
+Colblue="${Esc}[35m"
+Colyellow="${Esc}[33m"
+Colgreen="${Esc}[32m"
+Colgreenbg="${Esc}[42m"
+Colred="${Esc}[31m"
+Colredbg="${Esc}[41m"
+Coluline="${Esc}[4m"
 
 # Users
 Startuser="$(id -un)"                           # user who started x11docker
@@ -2535,15 +2545,15 @@ $(cowsay "$Wisdom" 2>/dev/null || echo "Wanda the fish says: $Wisdom")"
       no)  tail --pid=$$ --retry -n +1 -F $Logfile 2>/dev/null >&3 & ;;
       yes) tail --pid=$$ --retry -n +1 -F $Logfile 2>/dev/null | sed "
                                       /\(Failed to add fd to store\|Failed to set invocation ID\|Failed to reset devices.list\)/d;
-                                      s/\(ERROR\|Error\|error\|FAILURE\|FATAL\|Fatal\|fatal\)/${Esc}[41m\1${Esc}[0m/g;
-                                      s/\(Failed\|failed\|Failure\|failure\)/${Esc}[31m\1${Esc}[0m/g;
-                                      s/\(WARNING\|Warning\|warning\)/${Esc}[33m\1${Esc}[0m/g;
-                                      s/\(DEBUGNOTE\)/${Esc}[35m\1${Esc}[0m/g;
-                                      s/^==>.*/${Esc}[4m\0${Esc}[0m/;
-                                      s/\(Starting\)/${Esc}[32m\0${Esc}[0m/;
-                                      s/\(Started\|Reached target\)/${Esc}[42m\0${Esc}[0m/;
-                                      s/^\(+\|++\|+++\)/${Esc}[42m\0${Esc}[0m/ ;
-                                      s/^x11docker/${Esc}[32m\0${Esc}[0m/ " >&3 & ;;
+                                      s/\(ERROR\|Error\|error\|FAILURE\|FATAL\|Fatal\|fatal\)/${Colredbg}\1${Colnorm}/g;
+                                      s/\(Failed\|failed\|Failure\|failure\)/${Colred}\1${Colnorm}/g;
+                                      s/\(WARNING\|Warning\|warning\)/${Colyellow}\1${Colnorm}/g;
+                                      s/\(DEBUGNOTE\)/${Colblue}\1${Colnorm}/g;
+                                      s/^==>.*/${Coluline}\0${Colnorm}/;
+                                      s/\(Starting\)/${Colgreen}\0${Colnorm}/;
+                                      s/\(Started\|Reached target\)/${Colgreenbg}\0${Colnorm}/;
+                                      s/^\(+\|++\|+++\)/${Colgreenbg}\0${Colnorm}/ ;
+                                      s/^x11docker/${Colgreen}\0${Colnorm}/ " >&3 & ;;
     esac
   }
     
@@ -2699,11 +2709,6 @@ After finish: $Logbackup"
   Container gains access to GPU hardware.
   This allows reading host window content (palinopsia leak)
   and GPU rootkits (compare proof of concept: jellyfish)."
-  
-    note "Hardware acceleration (option --gpu) works quite well
-  with open source drivers on host and OpenGL/MESA in image.
-  If you have closed source nvidia driver on host, you need the very same
-  closed source driver version in container to get hardware acceleration."
   }
   
   # check for closed source nvidia driver on host, provide automated installation, warn about disadvantages
@@ -3796,11 +3801,7 @@ User=root
       echo "#! /bin/sh
 read Dummy <$Cshare/timetosaygoodbye.fifo
 echo timetosaygoodbye >$Cshare/timetosaygoodbye.fifo
-# kill su process to terminate container.CMD.sh
-Pid=\$(pstree -cp | grep '\-su(' | head -n1 | sed 's/^.*-su(//' | cut -d')' -f1)
-kill \$Pid
-sleep 1
-kill -s KILL \$Pid
+echo 'x11docker: dbus.watch.service sends: shutdown -h now
 " >> $Dbuswatchservicescript
       chmod +x $Dbuswatchservicescript
     ;;
@@ -4723,8 +4724,9 @@ start() {
     sysvinit)
       echo "# add x11docker start command to rc.local"
       echo "sed -i '/exit 0/d' /etc/rc.local"
-      echo "echo 'su - -s /bin/sh $Benutzer $Cshare/container.CMD.sh || verbose -d \"Exit code: \$?\"' >> /etc/rc.local"
-      echo "echo 'shutdown -hP 0' >> /etc/rc.local"
+      echo "echo 'su - -s /bin/sh $Benutzer $Cshare/container.CMD.sh || echo \"Exit code: \$?\"' >> /etc/rc.local"
+      echo "echo 'echo \"x11docker: rc.local sends shutdown -h now\"' >> /etc/rc.local"
+      echo "echo 'shutdown -h now' >> /etc/rc.local"
     ;;  
   esac
   
@@ -4824,6 +4826,7 @@ start() {
         echo "    org.freedesktop.PolicyKit1|org.freedesktop.Accounts) ;;"
         echo "    org.freedesktop.login1) ;;"
         echo "    org.x11docker.watch)"
+        echo '      verbose -d "DBus: starting service $Name: $Command"'
         echo '      sh -c "$Command" &'
         echo '    ;;'
         echo '    *)'
@@ -4834,6 +4837,13 @@ start() {
         echo '  esac'
         echo 'done'
       }
+      echo "verbose -d \"DBus: Running system services:
+\$(dbus-send --system         \
+  --dest=org.freedesktop.DBus \
+  --type=method_call          \
+  --print-reply               \
+  /org/freedesktop/DBus       \
+  org.freedesktop.DBus.ListNames)\""
     ;;
   esac
 
@@ -5067,9 +5077,9 @@ start() {
             echo "$Xhost" 
           }
           [ "$Initsystem" = "systemd" ] || [ "$Dbusdaemon" = "yes" ] && {
-            echo "note 'Allowing xhost access for $Benutzer on display $Newdisplay with" 
-            echo "  xhost +SI:localuser:$Benutzer"
-            echo "to avoid service issues with X access. (option --systemd or --dbus-system)'"
+            echo "note 'Allowing xhost access for $Benutzer on display $Newdisplay" 
+            echo "  to avoid service issues with X access. (option --systemd or --dbus-system):"
+            echo "    xhost +SI:localuser:$Benutzer'"
             echo "xhost +SI:localuser:$Benutzer"
           }
           # Keyboard layout
@@ -5675,13 +5685,11 @@ $(tail $Compositorlogfile)")"
   
 ######### ToDo notes for development
 todo() {
-# BUG x11docker-gui on console: cleanup&exit may terminate itself before it is ready
-
-# --xorg: check vt check with SSH
 # --weston/x: allow tty switch/option --vt if running as root?
-# check dbus.watch service, does not shut down with --sysvinit, maybe useless at all.
+# check dbus.watch.service, works well in sysvinit, but not obvious in --openrc and --runit.
 # further checks of pam.d
 # error message window in wayland fails: xterm: no display. should use konsole
+# x11docker-gui: menu entry management? persistant command storage?
 
 # --update: regard possible location in /opt
 # BUG arch: issues with x11docker/fluxbox, background missing, sometimes no context menu. where is the difference?
@@ -5713,7 +5721,7 @@ todo() {
 # some tests with Xephyrglamor=no
 
 ### BUG collection: non x11docker bugs
-# BUG Xwayland does not always sit at 0:0 on multiple outputs. 
+# BUG Xwayland does not always sit at 0.0 on multiple outputs. 
 #     bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1498665
 # BUG --kwin*: wrong fullscreen and crashes in gnome-wayland, strange in weston, WAYLAND_DISPLAY="" does not help, probably bug in kwin
 # BUG scale>1 Xwayland in Weston is too large (Xwayland bug), rendering issues on tty (switching scaled/unscaled Xwayland on keyboard/mouse events) 
