--debug: more rigorous. Improved error handling

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -389,6 +389,7 @@ traperror() {                   # trap ERR: --debug: Output for 'set -o errtrace
   debugnote "Command at Line ${2:-} returned with error code ${1:-}:
   ${4:-}
   ${3:-} - ${5:-}"
+  saygoodbye traperror
 }
 error() {                       # show error message and exit
   local Message
@@ -488,7 +489,7 @@ setup_verbosity() {             # options --verbose, --stdout, --stderr
   [ "$Showstdout" = "yes" ] && {
     { 
       trap '' SIGINT
-      waitforfilecontent $Containerpid1pidfile infinity
+      waitforfilecontent $Containerpid1pidfile infinity ||:
       tail --pid="$$" --retry -n +1 -F $Cmdstdoutlogfile     2>/dev/null
     } &
   }
@@ -681,6 +682,7 @@ waitfortheend() {               # wait for end of x11docker session
       done
     ;;
   esac
+  return 0
 }
 watchpidlist() {                # watch list of important pids
   # terminate x11docker if a PID in $Watchpidlist terminates
@@ -4232,6 +4234,7 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   declare -f pspid
   declare -f rmcr
   declare -f rocknroll
+  declare -f saygoodbye
   declare -f storepid
   declare -f waitforfilecreation
   declare -f waitfor_xserver
@@ -4271,7 +4274,15 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   [ "$Debugmode" = "yes" ] && {
     echo "PS4='+ dockerrc: \$(date +%S+%3N) '"
     #echo "set -x"
-    declare -f traperror | sed 's/Command/dockerrc: Command/'
+#    declare -f traperror | sed 's/Command/dockerrc: Command/'
+    #echo "set -o errtrace"
+    echo "traperror() {                   # trap ERR: --debug: Output for 'set -o errtrace'"
+    echo '  debugnote "dockerrc: Command at Line ${2:-} returned with error code ${1:-}:
+  ${4:-}
+  ${3:-} - ${5:-}"'
+    echo "  saygoodbye dockerrc-traperror"
+    echo "  exit 1"
+    echo "}"
     echo "set -Eu"
     echo "trap 'traperror \$? \$LINENO \$BASH_LINENO \"\$BASH_COMMAND\" \$(printf \"::%s\" \${FUNCNAME[@]})'  ERR"
   }
@@ -4348,7 +4359,6 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   esac
   echo "  $Sudo $Dockerexe pull $Imagename 1>&2 || error \"Pulling docker image '$Imagename' seems to have failed!\""
   echo "}"
-  echo ""
 
   [ "$Tinibinaryfile" ] && [ "$Switchcontaineruser" = "no" ] && echo "Tini=\"$Cshare/tini --\"" || echo "Tini="
   echo ""
@@ -5560,7 +5570,7 @@ create_xtermrc() {              # create xtermrc: script to prompt for password 
     *)              echo "$Passwordcommand \"${Sudo}bash $Dockerrc \"" ;;
   esac
   echo ""  
-  echo "exit"
+  echo "exit 0"
   return 0
 } >> $Xtermrc
 
@@ -7891,9 +7901,9 @@ $(nl -ba <$Westonini)"
   } <&0 & storepid $! containershell
   
   #### Start X server [and/or Wayland compositor]
-  waitforfilecontent $Readyforxfile
-  [ "$Compositorcommand" ] && start_compositor
-  start_xserver
+  waitforfilecontent $Readyforxfile ||:
+  rocknroll && [ "$Compositorcommand" ] && start_compositor
+  rocknroll && start_xserver
   saygoodbye main
   waitfortheend
 }
