improve error detection in set_password

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1909,9 +1909,22 @@ set_password() {                # option --password: set container user password
   }
   mkpasswd "$Password"
 
-  mkfolder "$(dirname "$Passwordfile")"
-  echo "$Containeruserpassword" > "$Passwordfile"
-  chmod 600                       "$Passwordfile"
+  local PasswordfileDirectory
+  PasswordfileDirectory="$(dirname "$Passwordfile")"
+  mkfolder "$PasswordfileDirectory"
+  (
+    echo "$Containeruserpassword" > "$Passwordfile" || exit 1
+    chmod 600                       "$Passwordfile" || exit 1
+  ) || {
+    local error_msg
+    error_msg="Error modifying file \"$Passwordfile\". If it already exists, check the ownership of the file."
+    if [ ! -w "$PasswordfileDirectory" ] ; then
+      error_msg="$error_msg Also, the parent directory \"$PasswordfileDirectory\" is not writable by current user \"$Hostuser\"."
+    fi
+    error "$error_msg"
+    return 1 # will not execute after error
+  }
+
   note "Option --password: Password changed, exiting."
   return 0
 }
