use image list instead of docker inspect to check for local image

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4107,14 +4107,14 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo ""
   
   echo "# refresh images.list for x11docker-gui"
-  echo "mkfile $Cachebasefolder/x11docker-gui/images.list"
-  echo "$Dockerexe images 2>>$Containerlogfile | grep -v REPOSITORY | awk '{print \$1 \":\" \$2}' >>$Cachefolder/images.list"
-  echo "rmcr $Cachefolder/images.list"
+  echo "$Dockerexe images 2>>$Containerlogfile | grep -v REPOSITORY | awk '{print \$1 \":\" \$2}' >>$Imageslist"
+  echo "rmcr $Imageslist"
   echo "while read -r Line ; do"
-  echo '  grep -q "<none>" <<<$Line || echo $Line >> '$Cachebasefolder/x11docker-gui/images.list
-  echo "done < <(sort < $Cachefolder/images.list)"
+  echo '  grep -q "<none>" <<<$Line || echo $Line >> '$Imageslist
+  echo "done < <(sort < $Imageslist)"
   echo ""
 
+  echo "# check if image $Imagename is available locally"
   echo "Dockerpull=no"
   case $Pullimage in
     no) ;;
@@ -4122,14 +4122,17 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
     yes) echo "$Dockerexe inspect $Imagename >>$Containerlogfile 2>&1 || Dockerpull=yes" ;;
     ask)
       [ "$Runsinterminal" = "yes" ] && {
-        echo "$Dockerexe inspect $Imagename >>$Containerlogfile 2>&1 || {"
-        echo "  echo 'Image $Imagename not found locally.'"
-        echo "  echo 'Do you want to pull it from docker hub?'"
-        echo "  askyesno && Dockerpull=yes"
+        echo "grep -x -q '$Imagename' < $Imageslist || grep -x -q '$Imagename:latest' < $Imageslist || {"
+        echo "  $Dockerexe inspect $Imagename >>$Containerlogfile 2>&1 || {"
+        echo "    echo 'Image $Imagename not found locally.'"
+        echo "    echo 'Do you want to pull it from docker hub?'"
+        echo "    askyesno && Dockerpull=yes"
+        echo "  }"
         echo "}"
       }
     ;;
   esac
+  echo ""
 
   echo "[ \"\$Dockerpull\" = 'yes' ] && {"
   echo "  note 'Pulling image $Imagename from docker hub'"
@@ -5769,6 +5772,8 @@ create_cachefiles() {           # create empty cache files owned by unprivileged
   writeaccess $Hostuseruid $Cachebasefolder || error "User $Hostuser does not have write access to
   cache folder $Cachebasefolder"  # can happen with --cachebasedir
   Logbackup="$Cachebasefolder/x11docker.log"       # afterward copy of $Logfile in $Cachebasefolder
+  $Mksu "mkdir -p $Cachebasefolder/x11docker-gui"
+  Imageslist="$Cachebasefolder/$Imageslist"                         && mkfile $Imageslist
 
   [ "$Cachebasefolder" != "$(echo $Cachebasefolder | sed -e 's/ *//g')" ] && error "Cache root folder must not contain whitespaces.
   $Cachebasefolder"
@@ -6761,6 +6766,7 @@ declare_variables() {           # declare global variables
 
   Dockerexe="docker"                              # can be docker.exe on Windows
   Dockerinfofile=docker.info                      # file to store outpu of 'docker info'
+  Imageslist="x11docker-gui/images.list"
   Runtime=""                                      # runtime in use. runc|nvidia|kata-runtime
   Bgpidfile=backgroundpids                        # file to store pids and names of background processes that shut be killed on exit
   Timetosaygoodbye=timetosaygoodbye               # file giving term signal to all parties
