--gpu: Don't install NVIDIA driver if already present in image

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1375,7 +1375,7 @@ setup_gpu() {                   # option --gpu: share /dev/dri and check nvidia 
   #Hostnvidia=yes
   [ "$Hostnvidia" = "yes" ] && {
     Nvidiaversion=$(head -n1 </proc/driver/nvidia/version | awk '{ print $8 }')
-    #Nvidiaversion="418.30"
+    #Nvidiaversion="415.25"
     verbose -d "Detected nvidia driver version $Nvidiaversion on host."
     Nvidiadriver=$(find /usr/local/share/x11docker/NVIDIA*$Nvidiaversion*.run $Hostuserhome/.local/share/x11docker/NVIDIA*$Nvidiaversion*.run 2>/dev/null | head -n1 )
     Nvidiadriver="$(realpath "$Nvidiadriver")"
@@ -1395,14 +1395,6 @@ setup_gpu() {                   # option --gpu: share /dev/dri and check nvidia 
   x11docker must give some capabilities to container that would be dropped
   otherwise for security reasons. Container security is reduced now.
   You would not have this issue with free nouveau driver on host."
-
-      note "Installation of proprietary closed source nvidia driver
-  fails in containers based on musl libc like NixOS and Alpine.
-  Installation in openSUSE containers fails with a self-extraction error.
-
-  For openSUSE images you can try to create a custom installation
-  command with option --runasroot or to install a closed source nvidia driver
-  in image itself that matches your nvidia driver version on host."
 
       case $Xserver in
         --hostdisplay|--xorg) ;;
@@ -1940,7 +1932,7 @@ check_xdepends() {              # check dependencies on host for X server option
       }
     ;;
   esac
-  case ${1:-} in
+  [ "$Hostnvidia" = "yes" ] && case ${1:-} in
     --xpra-xwayland|--weston-xwayland|--xwayland|--weston|--kwin|--kwin-xwayland|--xdummy-xwayland|--hostwayland)
       $Message "${1:-}: Closed source NVIDIA driver does not support Wayland."
       Return=1
@@ -4492,43 +4484,50 @@ create_containerrootrc() {      # create container root setup script: This scrip
 
   # --gpu with closed source nvidia driver
   [ "$Nvidiadriver" ] && {
-    echo "Installationwillsucceed=maybe"
-    echo '[ "$Containerlibc" = "musl" ] && {'
-    echo "  Installationwillsucceed=no"
-    echo "  note 'Found musl libc in image. Closed source NVIDIA driver
-is incompatible. Use free nouveau driver on host and ask NVIDIA corporation
-to publish driver source code to allow you using your hardware.
-Fallback: Skipping installation of nvidia driver'"
-    echo "}"
-    echo "case \$Containersystem in"
-    echo "  opensuse)"
-    echo "    Installationwillsucceed=no"
-    echo "    note \"Nvidia driver installation fails in \$Containersystem.
-  You can try to install nvidia driver $Nvidiaversion in image.
+    echo "Nvidiaversion=\$(nvidia-settings -v 2>/dev/null | grep version | rev | cut -d' ' -f1 | rev)"
+    echo '[ "$Nvidiaversion" ] && note "Found NVIDIA driver $Nvidiaversion in image."'
+    echo 'case "$Nvidiaversion" in'
+    echo "  $Nvidiaversion) note 'NVIDIA driver version in image matches version on host. Skipping installation.' ;;"
+    echo "  *)"
+    echo "    Installationwillsucceed=maybe"
+    echo '    case "$Containerlibc" in'
+    echo "      musl) note 'Installing NVIDIA driver in container systems"
+    echo "  based on musl libc like Alpine is not possible due to"
+    echo "  proprietary closed source policy of NVIDIA corporation.'"
+    echo "        Installationwillsucceed=no"
+    echo "      ;;"
+    echo "    esac"
+    echo "    case \$Containersystem in"
+    echo "      opensuse)"
+    echo "        Installationwillsucceed=no"
+    echo "        note \"Nvidia driver installation fails in \$Containersystem.
+  You can try to install nvidia driver $Nvidiaversion in image yourself.
   Otherwise, use free nouveau driver on host.\""
-    echo "  ;;"
-    echo "esac"
-    echo "[ \"\$Installationwillsucceed\" = \"maybe\" ] && [ -z \"\$(find . -name *${Nvidiaversion}* -print 2>/dev/null)\" ] && {"
-    echo "  mkdir -m 1777 /tmp2 && export TMPDIR=/tmp2"
-    echo "  # Install nvidia driver"
-    echo "  { command -v modprobe && command -v xz ; } || {"
-    echo "    # Try to install modprobe"
-    echo "    note 'Did not find modprobe/kmod or xz in image.
+    echo "      ;;"
+    echo "    esac"
+    echo "    [ \"\$Installationwillsucceed\" = \"maybe\" ] && [ -z \"\$(find . -name *${Nvidiaversion}* -print 2>/dev/null)\" ] && {"
+    echo "      mkdir -m 1777 /tmp2 && export TMPDIR=/tmp2"
+    echo "      # Install nvidia driver"
+    echo "      { command -v modprobe && command -v xz ; } || {"
+    echo "        # Try to install modprobe"
+    echo "        note 'Did not find modprobe/kmod or xz in image.
   modprobe and xz are needed by nvidia installer.
   Install them in image to speed up container startup.
   Will try to install them. That slows down container startup.'"
-    echo "    apt-get update && apt-get install -y     kmod xz-utils  # debian"
-    echo "    dnf install -y kmod xz || yum install -y kmod xz        # fedora, centos"
-    echo "    xbps-install -Sy                         kmod xz        # void"
-    echo "    pacman -Sy --noconfirm                   kmod xz        # arch"
-    echo "    emerge --ask n                           kmod xz        # gentoo"
-    echo "    zypper --non-interactive install         kmod xz        # opensuse"       #ok, but nvidia-installer extraction fails
-    echo "  }"
-    echo "  note 'Installing proprietary closed source NVIDIA driver
+    echo "        apt-get update && apt-get install -y     kmod xz-utils  # debian"
+    echo "        dnf install -y kmod xz || yum install -y kmod xz        # fedora, centos"
+    echo "        xbps-install -Sy                         kmod xz        # void"
+    echo "        pacman -Sy --noconfirm                   kmod xz        # arch"
+    echo "        emerge --ask n                           kmod xz        # gentoo"
+    echo "        zypper --non-interactive install         kmod xz        # opensuse"       #ok, but nvidia-installer extraction fails
+    echo "      }"
+    echo "      note 'Installing proprietary closed source NVIDIA driver
   version $Nvidiaversion. That slows down container startup.'"
-    echo "  sh $Cshare/NVIDIA-$Nvidiaversion.run  --accept-license --no-runlevel-check  --no-questions --ui=none --no-kernel-module --no-kernel-module-source --no-backup --tmpdir /tmp2"
-    echo "  rm -R /tmp2 && unset TMPDIR"
-    echo "} || note 'Skipping installation of $Cshare/NVIDIA-$Nvidiaversion.run'"
+    echo "      sh $Cshare/NVIDIA-$Nvidiaversion.run  --accept-license --no-runlevel-check  --no-questions --ui=none --no-kernel-module --no-kernel-module-source --no-backup --tmpdir /tmp2"
+    echo "      rm -R /tmp2 && unset TMPDIR"
+    echo "    } || note 'Skipping installation of $Cshare/NVIDIA-$Nvidiaversion.run'"
+    echo "  ;;"
+    echo "esac"
     echo ""
   }
   
