--showXY: optional argument FILE

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -317,11 +317,12 @@ Miscellaneous:
                        of nerdctl and podman.
      
 Output of parseable information on stdout:
-  Get output e.g. with:  read xenv < <(x11docker --showenv x11docker/check)
-     --showenv         Print new \$DISPLAY, \$XAUTHORITY and \$WAYLAND_DISPLAY.
-     --showid          Print container ID.
-     --showinfofile    Print path to internal x11docker info storage file.
-     --showpid1        Print host PID of container PID 1.
+  Get output e.g. with: read xenv < <(x11docker --showenv x11docker/check)
+  Optional argument FILE allows to print the information into a file.
+     --showenv [=FILE]        Print variables to access new display.
+     --showid [=FILE]         Print container ID.
+     --showinfofile [=FILE]   Print path to internal x11docker info storage.
+     --showpid1 [=FILE]       Print host PID of container PID 1.
 
 Verbosity options:
  -D, --debug           Debug mode: Show some less verbose debug output
@@ -450,6 +451,8 @@ debugnote() {                   # show debug output $*
 error() {                       # show error message and exit
   local Message
 
+  break >/dev/null 2>&1 # just in case error occured in a loop
+  
   Message="$*
 
   Type 'x11docker --help' for usage information
@@ -2162,13 +2165,21 @@ check_newxenv() {               # find free display, create $Newxenv
 
 
   # create $Newxenv: collection of environment variables to access new X from host (e.g. in xinitrc)
-  [ "$Newdisplay" ]         && storeinfo "DISPLAY=$Newdisplay"                && Newxenv="$Newxenv DISPLAY=$Newdisplay"
-  [ -e "$Xclientcookie" ]   && storeinfo "XAUTHORITY=$Xclientcookie"          && Newxenv="$Newxenv XAUTHORITY=$Xclientcookie"
-  [ "$Newxsocket" ]         && storeinfo "XSOCKET=$Newxsocket"                && Newxenv="$Newxenv XSOCKET=$Newxsocket"
-  [ "$Newwaylandsocket" ]   && storeinfo "WAYLAND_DISPLAY=$Newwaylandsocket"  && Newxenv="$Newxenv WAYLAND_DISPLAY=$Newwaylandsocket"
-  [ "$Setupwayland" = "yes" ] && for Line in $Waylandtoolkitenv ; do             Newxenv="$Newxenv $Line" ; done
-  [ -n "$XDG_RUNTIME_DIR" ] && storeinfo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"   && Newxenv="$Newxenv XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"
-  storeinfo "Xenv=$Newxenv"
+  [ "$Newdisplay" ]         && storeinfo "DISPLAY=$Newdisplay"                && Newxenv="$Newxenv
+DISPLAY=$Newdisplay"
+  [ -e "$Xclientcookie" ]   && storeinfo "XAUTHORITY=$Xclientcookie"          && Newxenv="$Newxenv
+XAUTHORITY=$Xclientcookie"
+  [ "$Newxsocket" ]         && storeinfo "XSOCKET=$Newxsocket"                && Newxenv="$Newxenv
+XSOCKET=$Newxsocket"
+  [ "$Newwaylandsocket" ]   && storeinfo "WAYLAND_DISPLAY=$Newwaylandsocket"  && Newxenv="$Newxenv
+WAYLAND_DISPLAY=$Newwaylandsocket"
+  [ "$Setupwayland" = "yes" ] && for Line in $Waylandtoolkitenv ; do             Newxenv="$Newxenv
+$Line" ; done
+  [ -n "$XDG_RUNTIME_DIR" ] && storeinfo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"   && Newxenv="$Newxenv
+XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"
+  Newxenv_cr="$(grep . <<< "$Newxenv")"
+  Newxenv="$(echo $Newxenv)"
+  storeinfo "Xenv=$(echo $Newxenv)"
   
   # X / Wayland environment variables for container
   case $Xserver in
@@ -6874,7 +6885,7 @@ check_option_interferences() {  # check multiple option interferences, change se
       esac
     ;;
     --xdummy|--xvfb)
-      Showdisplayenvironment="yes"
+      Showdisplayenvironment="${Showdisplayenvironment:-yes}"
     ;;
   esac
   case $Xserver in
@@ -7674,7 +7685,7 @@ check_runmode() {               # check run/--exe/--xonly
       Containercommand=""
       Codename="xonly"
       Imagebasename="xonly"
-      Showdisplayenvironment="yes"
+      Showdisplayenvironment="${Showdisplayenvironment:-yes}"
     ;;
   esac
   Codename="$(unspecialstring "$Codename" | cut -c1-40)"
@@ -8422,7 +8433,8 @@ declare_variables() {           # declare global variables
   Newdisplay=""                                   # --display: New DISPLAY for new X server
   Newdisplaynumber=""                             # --display: New display number for new X server.
   Newwaylandsocket=""                             # Wayland socket of $Compositorcommand
-  Newxenv=""                                      # Environment variables for new X server: DISPLAY XAUTHORITY XSOCKET WAYLAND_DISPLAY
+  Newxenv=""                                      # Environment variables for new X server: DISPLAY XAUTHORITY XSOCKET WAYLAND_DISPLAY XDG_RUNTIME_DIR
+  Newxenv_cr=""                                   # Like Newxenv, but with newlines
   Newxlock=""                                     # .Xn-lock - exists for running X server with socket n
   Newxsocket=""                                   # New X unix socket
   Newxvt=""                                       # --vt: number of virtual console to use for --xorg
@@ -8566,11 +8578,11 @@ declare_variables() {           # declare global variables
   
   # Verbosity options
   Debugmode="no"                                  # --debug: Excerpt of --verbose, also bash error checks
-  Showcontainerid="no"                            # --showid: Output of container ID on stdout
-  Showcontaineroutput="yes"                                # Show container command stdout
-  Showcontainerpid1pid="no"                       # --showpid1: Output of host PID of container PID 1 on stdout
-  Showdisplayenvironment="no"                     # --showenv: Output of environment variables of new display on stdout
-  Showinfofile="no"                               # --showinfofile: Show path of $Storeinfofile
+  Showcontainerid=""                              # --showid: Output of container ID on stdout
+  Showcontaineroutput="yes"                       # Show container command stdout
+  Showcontainerpid1pid=""                         # --showpid1: Output of host PID of container PID 1 on stdout
+  Showdisplayenvironment=""                       # --showenv: Output of environment variables of new display on stdout
+  Showinfofile=""                                 # --showinfofile: Show path of $Storeinfofile
   Silent="no"                                     # --quiet: Do not show x11docker messages
   Verbose="no"                                    # --verbose: Be verbose yes/no
   Verbosecolors="no"                              # -V: colored output for --verbose (and delete some noisy systemd error messages)
@@ -8667,7 +8679,7 @@ parse_options() {               # parse cli options
   Longoptions="$Longoptions,dbus::,init::,hostdbus,sharecgroup"                                                            # Container init and DBus
   Longoptions="$Longoptions,stdin,interactive"                                                                             # Container interaction
   Longoptions="$Longoptions,runasuser:,runfromhost:,runasroot:"                                                            # Additional commands to execute
-  Longoptions="$Longoptions,showenv,showid,showinfofile,showpid1"                                                          # Output of vars on stdout
+  Longoptions="$Longoptions,showenv::,showid::,showinfofile::,showpid1::"                                                  # Output of vars on stdout
   Longoptions="$Longoptions,debug,quiet,verbose"                                                                           # Verbose options
   Longoptions="$Longoptions,build,cleanup,help,launcher,licence,license,version"                                           # Special options without starting X or container
   Longoptions="$Longoptions,install,remove,update,update-master"                                                           # Installation
@@ -8883,13 +8895,13 @@ ${2:-}"                       ; shift ;;                             # Add custo
 
      #### Verbosity options
       -D|--debug)             Debugmode="yes" ;;                     # Debugging mode
-         --showinfofile)      Showinfofile="yes" ;;                  # Show path to $Storeinfofile
       -v|--verbose)           Verbose="yes" ;;                       # Be verbose  
       -V)                     Verbose="yes"; Verbosecolors="yes";;   # Be verbose with colored output
       -q|--quiet)             Silent="yes" ;;                        # Do not show warnings or errors
-         --showenv)           Showdisplayenvironment="yes" ;;        # Output of display number and cookie file on stdout. Catch with: read xenv < <(x11docker --showenv)
-         --showid)            Showcontainerid="yes" ;;               # Output of container id on stdout
-         --showpid1)          Showcontainerpid1pid="yes" ;;          # Output of host PID of container PID 1
+         --showenv)           Showdisplayenvironment="${2:-yes}" ; shift ;;  # Output of display number and cookie file on stdout. Catch with: read xenv < <(x11docker --showenv)
+         --showid)            Showcontainerid="${2:-yes}" ; shift ;;         # Output of container id on stdout
+         --showinfofile)      Showinfofile="${2:-yes}" ; shift ;;            # Show path to $Storeinfofile
+         --showpid1)          Showcontainerpid1pid="${2:-yes}" ; shift ;;    # Output of host PID of container PID 1
 
      #### Special options not starting X or docker
          --build)             Buildimage="yes" ;;                    # Build an image from x11docker repository
@@ -9206,13 +9218,28 @@ $(pstree -p $$ 2>&1 ||:)
 $(cat $Storeinfofile)"
     debugnote "storepid(): Stored pids:
 $(cat $Storepidfile)"
-    
+
     # optional info on stdout
-    [ "$Showinfofile" = "yes" ]           && echo "$Storeinfofile"                # --showinfofile
-    [ "$Showdisplayenvironment" = "yes" ] && echo "$(storeinfo dump Xenv)"        # --showenv
-    [ "$Showcontainerid" = "yes" ]        && echo "$(storeinfo dump containerid)" # --showid
-    [ "$Showcontainerpid1pid" = "yes" ]   && echo "$Pid1pid"                      # --showpid1
-    
+    case "$Showinfofile" in           # --showinfofile
+      "") ;;
+      yes) echo "$Storeinfofile" ;;
+      *)   echo "$Storeinfofile" > "$Showinfofile"         || error "Option --showinfofile: Invalid file $Showinfofile" ;;
+    esac
+    case "$Showdisplayenvironment" in # --showenv
+      "") ;;
+      yes) storeinfo dump Xenv ;;
+      *)   echo "$Newxenv_cr" > "$Showdisplayenvironment"  || error "Option --showenv: Invalid file $Showdisplayenvironment" ;;
+    esac
+    case "$Showcontainerid" in        # --showid
+      "") ;;
+      yes) storeinfo dump containerid ;;
+      *)   storeinfo dump containerid > "$Showcontainerid" || error "Option --showid: Invalid file $Showcontainerid" ;;
+    esac
+    case "$Showcontainerpid1pid" in   # --showpid1
+      "") ;;
+      yes) echo $Pid1pid ;;
+      *)   echo $Pid1pid > "$Showcontainerpid1pid"         || error "Option --showcontainerpid1pid: Invalid file $Showcontainerpid1pid" ;;
+    esac
     storeinfo "x11docker=ready"
   } <&0 & storepid $! containershell
   
