V3.6.2.9 bugfixes for terminal emulators: password prompt and pull dialog
# 17.10.2017 V3.6.2.9   bugfixes in terminal-emulator setup for password prompt and pull question
# 14.12.2017            xpra: --file-transfer=off (stores files in "Downloads" from host, useless here)

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -8,12 +8,14 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # https://github.com/mviereck/x11docker
 
-Version="3.6.2.8"
+Version="3.6.2.9"
 
 changelog() {
-# 12.10.2017 v3.6.2.8   --xdummy/--xpra: add multiple modelines for virtual display sizes to allow flexible changes of xpra client desktop window
+# 17.10.2017 V3.6.2.9   bugfixes in terminal-emulator setup for password prompt and pull question
+# 14.12.2017            xpra: --file-transfer=off (stores files in "Downloads" from host, useless here)
+# 12.10.2017 V3.6.2.8   --xdummy/--xpra: add multiple modelines for virtual display sizes to allow flexible changes of xpra client desktop window
 # 10.10.2017            --xpra: virtual display size always equal with physical display, create smaller mode in xinitrc -> allow fullscreen
-#                       xpra: disable some unused, but possibly leaking options (webcam, notifications, printer)
+#                       xpra: disable some unused, but possibly leaking features (forwarding of webcam, notifications, printer)
 #                       xpra: set xpra specific environment variables in dockerrc
 #                       xpra: show keyboard shortcuts
 # 08.10.2017 V3.6.2.7   --xephyr: title for Xephyr windows
@@ -55,7 +57,12 @@ changelog() {
   : 
 }
 todo() {
+  #test qterminal again, problem with asking for pull
+
 # check all FIXME 
+# new option --no-internet?
+# new option --printer: xpra printer forwarding?
+# xpra: --file-transfer? How to set folder?
 # --xpra-xwayland, xdummy-xwayland: use kwin-wayland as fallback for missing weston? 
 # fedora: SElinux issue: '--security-opt label=type:container_runtime_t': need more restrictive setting
 #         https://unix.stackexchange.com/questions/386767/selinux-and-docker-allow-access-to-x-unix-socket-in-tmp-x11-unix
@@ -381,6 +388,8 @@ installer() {           # --install, --update, --remove: Installer for x11docker
       mkdir -p /tmp/x11docker-install && cd /tmp/x11docker-install || error "Could not create or cd to /tmp/x11docker-install"
 
       echo "Downloading latest x11docker version from github"
+      command -v wget >/dev/null || error "wget not found. Need 'wget' for download.
+  Please install wget."
       wget https://github.com/mviereck/x11docker/archive/master.zip || error "Could not download x11docker-master from github"
 
       echo "Unpacking archive"
@@ -407,6 +416,8 @@ installer() {           # --install, --update, --remove: Installer for x11docker
       X11dockericonfile=$(x11docker-gui --icon)
       [ -e "$X11dockericonfile" ] && {
         xdg-icon-resource install --context apps --novendor --size 72 "$X11dockericonfile" x11docker
+        command -v xdg-icon-resource >/dev/null || warning "Could not install icon for x11docker.
+  Please install 'xdg-icon-resource' and try again."
         rm $X11dockericonfile
       } || note "Could not create icon for x11docker"
       [ -e "/usr/bin/x11docker-gui" ] && {
@@ -720,8 +731,9 @@ Etcpasswd=passwd                                # created /etc/passwd for contai
 # X server config files, log files and such stuff
 Xinitrc=xinitrc                                 # file to store xinitrc commands
 Xinitlogfile=xinit.log                          # file to log output of X server
-Xtermrc=xtermrc                                 # file to store xtermrc commands
-Xtermlogfile=xterm.log                          # file to log output of xterm
+Xtermrc=terminalrc                              # file for password prompt script
+Pullrc=pullrc                                   # file for pull dialog script
+Xtermlogfile=terminal.log                       # file to log output of xterm
 Compositorlogfile=compositor.log                # file to log output of Weston or KWin 
 Compositorpidfile=compositor.pid                # process id of compositor
 Xpraserverlogfile=xpraserver.log                # logfile for xpra server
@@ -1669,6 +1681,10 @@ Parsed options: $Parsedoptions"
   Or use option --size=XxY."
   }
   
+  # testing purposes
+  #Maxxaxis=1000
+  #Maxyaxis=600
+  
   [ -n "$Maxxaxis" ] && {
     Xaxis=$Maxxaxis
     Yaxis=$Maxyaxis
@@ -1775,6 +1791,7 @@ Parsed options: $Parsedoptions"
   Xinitrc="$Cachefolder/$Xinitrc"                           && mkfile $Xinitrc
   Xinitlogfile="$Cachefolder/$Xinitlogfile"                 && mkfile $Xinitlogfile
   Xtermrc="$Cachefolder/$Xtermrc"                           && mkfile $Xtermrc
+  Pullrc="$Cachefolder/$Pullrc"                             && mkfile $Pullrc
   Xtermlogfile="$Cachefolder/$Xtermlogfile"                 && mkfile $Xtermlogfile
   Dockerlogfile="$Cachefolder/$Dockerlogfile"               && mkfile $Dockerlogfile
   Dockerpidfile="$Cachefolder/$Dockerpidfile"               && mkfile $Dockerpidfile
@@ -2149,7 +2166,7 @@ fi
       verlt "$Xpraversion" "xpra v2.1" || Xpraoptions="$Xpraoptions --start-via-proxy=no"
       # disable sound transfer, --pulseaudio works different
       Xpraoptions="$Xpraoptions -z0 --no-speaker --no-pulseaudio"
-      Xpraoptions="$Xpraoptions --daemon=no --fake-xinerama=no --no-notifications --printing=no --webcam=no"
+      Xpraoptions="$Xpraoptions --daemon=no --fake-xinerama=no --notifications=no --file-transfer=off --printing=no --webcam=no"
       [ "$Fullscreen" = "yes" ]  && Xpraoptions="$Xpraoptions --desktop-fullscreen=yes"
       [ "$Desktopmode" = "yes" ] && Xpraoptions="$Xpraoptions --title='$Imagename on $Newdisplay (shift+F11 toggles fullscreen)'"
       # version check for scaling already done above
@@ -2164,6 +2181,9 @@ $(while [ -n "$Line" ] ; do
   done | column -t -s:)
 (Shortcuts starting with a # are disabled.
 Adjustable in /etc/xpra/conf.d/40_client.conf)"
+
+      # debug options for xpra
+      #Xpraoptions="$Xpraoptions -d randr,geometry,screen"
     ;;
   esac
 
@@ -2543,7 +2563,8 @@ done
   # Makes problems if X and Wayland are independently available at same time: xfce4-terminal
   # Works, but does not appear: 'guake -te'
   
-  Terminallist=("xterm lxterminal konsole qterminal terminator sakura termit pterm terminology terminix tilix xfce4-terminal NONE")
+  # check terminator, issue with pull
+  Terminallist=("xterm xfce4-terminal lxterm lxterminal konsole qterminal stterm sakura termit pterm terminology NOLUCK")
   [ -z "$Hostdisplay$Newdisplay" ] && {
     case $Xserver in
       Weston|Hostwayland)  Terminallist=("konsole qterminal terminator NOLUCK") ;;
@@ -2564,8 +2585,11 @@ done
     ;;
   esac
   
-  Pullterminal="$Pullterminal -e"
-  [ -z "$Passwordterminal" ] && Passwordterminal=$Pullterminal
+  case $Pullterminal in
+    xfce4-terminal) Pullterminal="$Pullterminal --disable-server -x" ;;
+    *)              Pullterminal="$Pullterminal -e" ;;
+  esac
+  [ -z "$Passwordterminal" ] && Passwordterminal="$Pullterminal"
   
   [ -z "$Hostdisplay$Newdisplay" ] && {
     case $Xserver in
@@ -2760,8 +2784,7 @@ done
   echo "# check if image is available locally"
   echo "$Sudo docker inspect --type=image $Imagename > /dev/null 2>&1 || {"
   echo "  warning 'Image $Imagename not found locally.'"
-  echo "  $Pullterminal bash -c 'read -n1 -e -p \"Image '$Imagename' not found locally. "
-  echo "  Do you want to pull it from docker hub? [Y|n]\" Choice && { [[ \"\$Choice\" == [YyJj]* ]] || [ -z \"\$Choice\" ] && $Sudo docker pull $Imagename 2>&1 ; sleep 2 ; } '"
+  echo "  $Pullterminal /bin/bash $Pullrc"
   echo "  $Sudo docker inspect --type=image $Imagename > /dev/null 2>&1 || {"
   echo "    echo \"ERROR: Image '$Imagename' not found locally and not pulled from docker hub. \" >&2"
   echo "    exit 1"
@@ -2840,9 +2863,17 @@ done
   echo "$Sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' $Containername >> $Containerip"
 } >> $Dockerrc
 
+{ #### part: create pullrc: interactive script to pull image from docker hub
+  echo "#! /bin/bash"
+  echo "read -n1 -e -p \"Image '$Imagename' not found locally. "
+  echo "Do you want to pull it from docker hub? [Y|n]\" Choice"
+  echo "[[ \"\$Choice\" == [YyJj]* ]] || [ -z \"\$Choice\" ] && $Sudo docker pull $Imagename 2>&1"
+  echo "sleep 2"
+} >> $Pullrc
+
 { #### part: create xtermrc: prompt for password and run dockerrc
   echo "#! /bin/bash
-echo \"Created docker command:
+echo \"Created docker command for $Imagename $Imagecommand:
 
 $Dockercommand
 \" >&2"
@@ -2850,7 +2881,7 @@ $Dockercommand
   echo "$Getroot \"${Pkexec}env DISPLAY=\$DISPLAY XAUTHORITY=\$XAUTHORITY bash $Dockerrc\""
 } >> $Xtermrc
 
-{ #### part: create xinitrc
+{ #### part: create xinitrc: set up X environment, create cookies
   echo "#! /bin/sh"
 
   # declaring functions echoes them into xinitrc
@@ -3203,12 +3234,13 @@ $(tail $Xinitlogfile)"
       export $Newxenv
       $Mksu "$Xpraservercommand" >> $Xpraserverlogfile 2>&1 &
       storepid $! xpra
-      waitforlogentry xpra $Xpraserverlogfile 'xpra is ready' || error "Xpra startup failed.
+      waitforlogentry "xpra server" $Xpraserverlogfile 'xpra is ready' && verbose "xpra server is ready" || error "Xpra server startup failed.
   Last lines of Xpra server log:
 $(tail $Xpraserverlogfile)"
 
       verbose "starting xpra client"
       export $Hostxenv
+      export XPRA_PADDING_COLORS="0,0.2,1"
       $Mksu "$Xpraclientcommand" >> $Xpraclientlogfile 2>&1 &
       Xpraclientpid=$!
       storepid $Xpraclientpid xpra
@@ -3250,8 +3282,10 @@ $(tail $Xpraserverlogfile)"
       esac
       
       # start docker in xtermrc
-      [ -n "$DISPLAY" ] && $Passwordterminal "/bin/bash $Xtermrc" >> $Xtermlogfile 2>&1
-      [ -z "$DISPLAY" ] && $Passwordterminal "/bin/bash $Xtermrc"
+      #[ -n "$DISPLAY" ] && $Passwordterminal "/bin/bash $Xtermrc" >> $Xtermlogfile 2>&1
+      #[ -z "$DISPLAY" ] && $Passwordterminal "/bin/bash $Xtermrc"
+      [ -n "$DISPLAY" ] && $Passwordterminal /bin/bash $Xtermrc >> $Xtermlogfile 2>&1
+      [ -z "$DISPLAY" ] && $Passwordterminal /bin/bash $Xtermrc
       
       [ -s "$Dockerpidfile" ] && { 
         Dockerpid=$(cat $Dockerpidfile)
