deprecated: --no-xhost, --sys-admin

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -206,7 +206,6 @@ X and Wayland appearance options:
 X and Wayland configuration:
      --xhost STR       Set \"xhost STR\" on new X server (see 'man xhost').
                        (Use with care. '--xhost +' allows access for everyone).
-     --no-xhost        Disable any access to host X server granted by xhost.
      --no-auth         Allow access to X for everyone. Security risk!
      --display N       Use display number N for new X server.
      --vt N            Use vt / tty N (regarded by --xorg only).
@@ -255,7 +254,6 @@ Container capabilities:
                        currently free RAM x FACTOR and available CPUs x FACTOR.
                        Allowed range is 0 < FACTOR <= 1. 
                        Default without argument FACTOR is 0.5
-     --sys-admin       Add capability SYS_ADMIN. Please avoid that.
 
 Miscellaneous:
      --launcher        Create application launcher on desktop and exit. 
@@ -4652,10 +4650,9 @@ exec su - -s /bin/sh  \$Containeruser $Cshare/container.CMD.sh
     echo "chmod +x /usr/local/bin/x11docker-login"
     
     echo "echo \"#! /bin/sh
-note() {
-  echo \"\$\*:NOTE\"      >>\$Messagefile
-}
+$Messagefifofuncs_escaped
 Messagefile=$Cshare/message.fifo
+debugnote \"Path of agetty: \$(command -v agetty || echo not found)\"
 [ -e /sbin/agetty ] && exec setsid agetty -a \$Containeruser -l /usr/local/bin/x11docker-login console
 [ '$Interactive' = 'yes' ] && note '/sbin/agetty not found. --interactive can fail.
   Please install package util-linux in image.'
@@ -5424,10 +5421,6 @@ check_host() {                  # check host environment
   
   # Check if host uses proprietary NVIDIA driver
   Nvidiaversion=$(head -n1 2>/dev/null </proc/driver/nvidia/version | awk '{ print $8 }')
-  
-  grep -q -- "--runtime.kata"   <<< "$Customdockeroptions" && Runtime="kata-runtime"
-  grep -q -- "--runtime.nvidia" <<< "$Customdockeroptions" && Runtime="nvidia"
-  grep -q -- "--runtime.runc"   <<< "$Customdockeroptions" && Runtime="runc"
   
   return 0
 }
@@ -6291,9 +6284,7 @@ option_messages() {             # some messages depending on options, but not ch
 
   # --sys-admin
   [ "$Capsysadmin" = "yes" ] && warning "Option --sys-admin is dangerous.
-  It adds insecure capability SYS_ADMIN to container.
-  It is needed to run debian 9 images with option --init=systemd.
-  Debian 10 images run well without --sys-admin."
+  It adds insecure capability SYS_ADMIN to container."
   
   # --webcam
   [ "$Sharewebcam" = "yes" ] && warning "Option --webcam: Container applications might look 
@@ -6720,7 +6711,7 @@ declare_variables() {           # declare global variables
   Sharehostipc="no"                               # option --hostipc, set --ipc=host.
   Sharehostnet="no"                               # option --hostnet, set --ipc=net
   Preservecachefiles="no"                         # if yes, dont delete cache files
-  Capsysadmin="no"                                # option --sys-admin: add capability SYS_ADMIN (deprecated)
+  Capsysadmin="no"                                # deprecated option --sys-admin: add capability SYS_ADMIN (deprecated)
   Runfromhost=""                                  # option --runfromhost: add host command to xinitrc
   Runasroot=""                                    # option --runasroot: add command running as root to container setup script
   Workdir="/tmp"                                  # option --workdir: set working directory
@@ -6737,7 +6728,7 @@ declare_variables() {           # declare global variables
   # X authentication
   Xauthentication="yes"                           # option '--no-auth' use cookie authentication yes/no
   Trusted="yes"                                   # Create trusted or untrusted cookies,  --hostdisplay uses untrusted cookies
-  Noxhost="no"                                    # option '--no-xhost': if yes, disable all X server access granted by xhost
+  Noxhost="no"                                    # deprecated option '--no-xhost': if yes, disable all X server access granted by xhost
   Xhost=""                                        # option '--xhost': custom xhost setting on new X server
 
   # special options not starting X or docker
@@ -6787,6 +6778,26 @@ error() {
 }
 stdout() {
   echo "$*:STDOUT"    >>$Messagefile
+}'
+  Messagefifofuncs_escaped='
+warning() {
+  echo \"\$*:WARNING\"   >>\$Messagefile
+}
+note() {
+  echo \"\$*:NOTE\"      >>\$Messagefile
+}
+verbose() {
+  echo \"\$*:VERBOSE\"   >>\$Messagefile
+}
+debugnote() {
+  echo \"\$*:DEBUGNOTE\" >>\$Messagefile
+}
+error() {
+  echo \"\$*:ERROR\"     >>\$Messagefile
+  exit 1
+}
+stdout() {
+  echo \"\$*:STDOUT\"    >>\$Messagefile
 }'
 }
 parse_options() {               # parse cli options
@@ -6935,27 +6946,7 @@ ${2:-}"                ; shift ;;        # add custom root command in container 
 
        ## init system
          --init)       Initsystem="${2:-tini}" ; shift ;;  # init in container
-         --no-init)    Initsystem="none"                   # no init, image command is PID 1
-                       note "Option --no-init is deprecated.
-  Please use --init=none instead." ;;
-         --tini)       Initsystem="tini"                   # default init system tini (run option --init)
-                       note "Option --tini is deprecated.
-  Please use --init=tini instead.
-  However, --init=tini is x11docker default already." ;;
-         --runit)      Initsystem="runit"                  # run runit as init system and image command as a service
-                       note "Option --runit is deprecated.
-  Please use --init=runit instead." ;;
-         --openrc)     Initsystem="openrc" 
-                       note "Option --openrc is deprecated.
-  Please use --init=openrc instead." ;;
-         --systemd)    Initsystem="systemd"                # run systemd as init system and image command as a service
-                       note "Option --systemd is deprecated.
-  Please use --init=systemd instead." ;;
-         --sysvinit)   Initsystem="sysvinit" 
-                       note "Option --sysvinit is deprecated.
-  Please use --init=sysvinit instead." ;;
          --sharecgroup)Sharecgroup="yes" ;;                # share /sys/fs/cgroup. default for --init=systemd, possible use with --init=openrc
-         --sys-admin)  Capsysadmin="yes" ;;                # add capability SYS_ADMIN for older systemd versions in image (i.e. debian 9 needs it, debian 10 runs well)
          --dbus-system) Dbussystem="yes" ;;                # set up dbus system daemon
       -b|--dbus)       Dbusrunsession="yes" ;;                 # run image command with dbus-launch or dbus-run-session
          --hostdbus)   Sharehostdbus="yes" ;;              # connect to host DBus
@@ -6964,8 +6955,8 @@ ${2:-}"                ; shift ;;        # add custom root command in container 
          --showid)     Showcontainerid="yes" ;;            # output of container id on stdout
          --showenv)    Showdisplayenvironment="yes" ;;     # output of display number and cookie file on stdout. Catch with  ~$ read xdenv < <(x11docker --showenv)
          --showpid1)   Showcontainerpid1pid="yes" ;;       # output of host PID of container PID 1
-         --env)        store_runoption env "${2:-}"              # set environment variables
-                       shift ;;                            
+         --env)        store_runoption env "${2:-}"        # set environment variables
+                       shift ;;
          --vt)         Newxvt="${2:-}" ;         shift ;;  # set virtual console to use
          --display)    Newdisplaynumber=${2:-}             # display number to use
                        [ "$(echo $Newdisplaynumber | cut -c1)" = ":" ] && Newdisplaynumber="$(echo $Newdisplaynumber | cut -c2-)"
@@ -6977,7 +6968,6 @@ ${2:-}"                ; shift ;;        # add custom root command in container 
        ## X Authentication
          --xhost)      Xhost="$2" ; shift ;;               # custom xhost setting on new X server
          --no-auth)    Xauthentication="no" ;;             # disable cookie authentication
-      -o|--no-xhost)   Noxhost="yes"  ;;                   # disable any access granted by xhost
 
        ## host folders
       -m|--home)         Sharehosthome="yes" ;;            # share folder ~/x11docker/Imagename with container
@@ -6985,14 +6975,7 @@ ${2:-}"                ; shift ;;        # add custom root command in container 
                          Containeruserhosthome="${2:-}" ; shift ;;
          --homebasedir)  Homebasefolder="${2:-}" ; shift ;;
          --cachebasedir) Cachebasefolder="${2:-}" ; shift ;; # set cache folder instead of default $Cachebasefolder
-         --cachedir)     Cachebasefolder="${2:-}" ; shift 
-                         note "Option --cachedir is deprecated.
-  Please use instead: --cachebasedir" ;;
          --share)        store_runoption volume "${2:-}"   # share host directory
-                         shift ;;
-         --sharedir)     store_runoption volume "${2:-}"   # share host directory
-                         note "Option --sharedir is deprecated.
-  Please use instead: --share"
                          shift ;;
 
        ## docker options
@@ -7030,6 +7013,37 @@ ${2:-}"                ; shift ;;        # add custom root command in container 
                        note "Option --silent is deprecated. Use --quiet instead." ;;
       -N|--nothing)    Xserver="--tty" ; Autochooseserver="no"  
                        warning "Option -N, --nothing is deprecated. Please use -t, --tty instead." ;; # Do not provide any X nor Wayland
+      -o|--no-xhost)   Noxhost="yes"  
+                       note "Option --no-xhost is deprecated without a replacement." ;; 
+         --no-init)    Initsystem="none"                   # no init, image command is PID 1
+                       note "Option --no-init is deprecated.
+  Please use --init=none instead." ;;
+         --tini)       Initsystem="tini"                   # default init system tini (run option --init)
+                       note "Option --tini is deprecated.
+  Please use --init=tini instead.
+  However, --init=tini is x11docker default already." ;;
+         --runit)      Initsystem="runit"                  # run runit as init system and image command as a service
+                       note "Option --runit is deprecated.
+  Please use --init=runit instead." ;;
+         --openrc)     Initsystem="openrc" 
+                       note "Option --openrc is deprecated.
+  Please use --init=openrc instead." ;;
+         --systemd)    Initsystem="systemd"                # run systemd as init system and image command as a service
+                       note "Option --systemd is deprecated.
+  Please use --init=systemd instead." ;;
+         --sysvinit)   Initsystem="sysvinit" 
+                       note "Option --sysvinit is deprecated.
+  Please use --init=sysvinit instead." ;;
+         --sharedir)   store_runoption volume "${2:-}"   # share host directory
+                       note "Option --sharedir is deprecated.
+  Please use instead: --share"
+                       shift ;;
+         --cachedir)   Cachebasefolder="${2:-}" ; shift 
+                       note "Option --cachedir is deprecated.
+  Please use instead: --cachebasedir" ;;
+         --sys-admin)  Capsysadmin="yes" 
+                       note "Option --sys-admin is deprecated without a replacement.
+  If you insist, use --cap-add=SYS_ADMIN in custom docker run options." ;; # add capability SYS_ADMIN for older systemd versions in image (i.e. debian 9 needs it, debian 10 runs well)
 
      ##### custom docker options / image name + image command
       --) shift
@@ -7054,6 +7068,14 @@ ${2:-}"                ; shift ;;        # add custom root command in container 
     esac
     shift
   done
+  
+  grep -q -- "--runtime.kata"   <<< "$Customdockeroptions" && Runtime="kata-runtime"
+  grep -q -- "--runtime.nvidia" <<< "$Customdockeroptions" && Runtime="nvidia"
+  grep -q -- "--runtime.runc"   <<< "$Customdockeroptions" && Runtime="runc"
+  grep -q -- "--runtime.crun"   <<< "$Customdockeroptions" && Runtime="crun"
+  grep -q -- "--runtime"        <<< "$Customdockeroptions" && note "Found option --runtime in custom DOCKER_RUN_OPTIONS.
+  Please use x11docker option --runtime instead."
+  
   return 0
 }
 main() {
@@ -7224,12 +7246,12 @@ todo() {
   # FIXME: myrealpath()
   # CHECK: Xwayland with X over IP
   # CHECK: --xpra-xwayland/py3 fails with tor-browser, but not with wine pcmanfm
-  # FIXME: --dbus-system: slow startup (90s timeout) e.g. in arch and debian buster containers for unknown reasons.
+  # FIXME: --dbus-system: slow startup (90s timeout) e.g. in arch containers for unknown reasons.
   # FIXME: --interactive with --init=systemd|runit|openrc|sysvinit: no job control in shell
   # FIXME: x11docker/deepin: new builds have strange issues
   # BUG x11docker/fluxbox on arch host: background missing, sometimes no context menu. where is the difference?
   # BUG error message window in wayland fails: xterm: no display. should use konsole
-  # BUG: x11docker/xwayland in a nested setup: where is the X socket ??
+  # CHECK: x11docker/xwayland in a nested setup: where is the X socket ??
   
   # --init
   # autodetect init system if possible, give a note.
