MSYS2/Cygwin/WSL: remove carriage return from several output (#55)

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -166,8 +166,8 @@ Special X servers:
                        Output of environment variables on stdout. (--showenv)
                        Along with option --gpu an invisible setup with Weston,
                        Xwayland and xdotool is used (instead of Xdummy or Xvfb).
-     --xwin            X server for Windows to run on CYGWIN/X.
-     --vcxsrv          X server for Windows to run on MSYS2, CYGWIN or WSL.
+     --xwin            X server for Windows to run on Cygwin/X.
+     --vcxsrv          X server for Windows to run on MSYS2, Cygwin or WSL.
  -N, --nothing         Do not provide any X or Wayland server.
 
 Wayland without X:
@@ -477,7 +477,7 @@ $(cat $Bgpidfile 2>/dev/null)"
         case $Name in
           xinit)                  killpid $Pid $Name xinit ;;
           Xserver)                killpid $Pid $Name 'Xorg|Xephyr|Xvfb|Xwayland|nxagent' ;;
-          vcxsrv.exe)             env MSYS2_ARG_CONV_EXCL='*' taskkill.exe /PID $Pid /T /F 2>&1 | rmcr ;;
+          vcxsrv.exe)             verbose -d "$(env MSYS2_ARG_CONV_EXCL='*' taskkill.exe /PID $Pid /T /F 2>&1 | rmcr)" ;;
           containershell)         killpid $Pid $Name x11docker ;;
           windowmanager)          killpid $Pid $Name ;;
           xpraserver|xpraclient)  killpid $Pid $Name xpra ;;
@@ -789,12 +789,12 @@ no_xhost() {            # remove any access to X server granted by xhost
   #xhost
   xhost 2>&1 | rmcr | tail -n +2  /dev/stdin | while read -r Line ; do  # read all but the first line (header)
     verbose -d "xhost: Removing entry $Line"
-    xhost -$Line                                         # disable every entry
+    xhost -$Line | rmcr                                  # disable every entry
   done
-  xhost -                                                # enable access control
+  xhost - | rmcr                                         # enable access control
   [ "$(xhost 2>&1 | rmcr | wc -l)" -gt "1" ] && {
     warning "Remaining xhost permissions found on display $DISPLAY
-$(xhost)"
+$(xhost 2>&1 | rmcr)"
     return 1
   }
   return 0
@@ -848,8 +848,8 @@ depends() {             # check dependencies on host for X server option $1
       command -v "$Vcxsrvpath" >/dev/null || {
         $Message "${1:-}: X server VcXsrv not found."
         Return=1
-        [ "$Winsubsystem" ] && note "To run x11docker within MSYS2, CYGWIN or WSL on MS Windows,
-  please install X server VcXsrv.
+        [ "$Winsubsystem" ] && note "To run x11docker within MSYS2, Cygwin or WSL on MS Windows,
+  please install X server VcXsrv (or Xwin on Cygwin).
   Searching for vcxsrv.exe in: 
     C:\Program Files\VcXsrv"
       }
@@ -2417,6 +2417,34 @@ $(cowsay "$Wisdom" 2>/dev/null || echo "Wanda the fish says: $Wisdom")"
       ;;
     esac
   }
+  
+  # MSYS2, Cygwin, WSL
+  [ "$Winsubsystem" ] && {
+    note "Support of MSYS2, Cygwin and WSL is in an early stage
+  of development. If you encounter issues, please report at github."
+    [ "$Alsa" = "yes" ] && { 
+      note "Option --alsa is not supported on MSYS2/Cygwin/WSL.
+  Fallback: enabling option --pulseaudio."
+      Alsa="no"
+      Pulseaudio="yes"
+    }
+    [ "$Pulseaudio" = "yes" ] && { 
+      note "Option --pulseaudio is not tested on MSYS2/Cygwin/WSL.
+  It will probably fail."
+    }
+    [ "$Initsystem" = "systemd" ] && {
+      note "Option --systemd is not possible on MSYS2/Cygwin/WSL.
+  systemd needs a running linux kernel with cgroup support.
+  Fallback: Disabling option --systemd, enabling option --dbus-system"
+      Initsystem="tini"
+      Dbusdaemon="yes"
+    } 
+    [ "$Sharecgroup" = "yes" ] && { 
+      note "Option --sharecgroup is not possible on MSYS2/Cygwin/WSL.
+  Fallback: Disabling option --sharecgroup."
+      Sharecgroup="no"
+    }
+  }
 }
 
 { #### part: some messages depending on options, but not changing settings
@@ -2828,7 +2856,7 @@ After finish: $Logbackup"
 { #### part: create $Hostxenv: Environment variables for host X display
   # get cookie from host display
   [ -n "$Hostdisplay" ] && {
-    xauth nlist $Hostdisplay 2>/dev/null | $Mksu "xauth -f $Hostxauthority nmerge - 2>/dev/null"
+    xauth nlist $Hostdisplay 2>/dev/null | rmcr | $Mksu "xauth -f $Hostxauthority nmerge - 2>/dev/null"
     chown $Hostuser $Hostxauthority
     chmod 600 $Hostxauthority
   } || {
@@ -2873,8 +2901,8 @@ After finish: $Logbackup"
       Maxyaxis=$(xdpyinfo | grep dimensions | cut -dx -f2 | cut -d ' ' -f1)
     }
     [ -z "$Maxxaxis" ] && command -v xwininfo >/dev/null && {
-      Maxxaxis=$(xwininfo -root -stats | grep Width  | rev | cut -d' ' -f1 | rev)
-      Maxyaxis=$(xwininfo -root -stats | grep Height | rev | cut -d' ' -f1 | rev)
+      Maxxaxis=$(xwininfo -root -stats | rmcr | grep Width  | rev | cut -d' ' -f1 | rev)
+      Maxyaxis=$(xwininfo -root -stats | rmcr | grep Height | rev | cut -d' ' -f1 | rev)
     }
     [ -z "$Maxxaxis" ] && note "Could not determine your screen size.
   Please improve this by installing one of xrandr, xdpyinfo or xwininfo.
@@ -4559,7 +4587,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   declare -f mkfile
   declare -f rocknroll
   declare -f waitforfilecreation
-  declare -f escapestring
+  declare -f escapestring rmcr
   echo "Hostuser=$Hostuser"
   echo "Hostusergid=$Hostusergid"
   echo "Timetosaygoodbye=$Timetosaygoodbye"
@@ -4581,7 +4609,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo ""
 
   echo "# check whether docker daemon is running and refresh images.list for x11docker-gui"
-  echo "docker images --format '{{.Repository}}:{{.Tag}}' >>$Cachefolder/images.list 2>>$Containerlogfile  || error \"Calling docker daemon failed.
+  echo "docker images --format '{{.Repository}}:{{.Tag}}' | rmcr >>$Cachefolder/images.list 2>>$Containerlogfile  || error \"Calling docker daemon failed.
   Is docker daemon running at all?
   Try to start docker daemon with:
       systemctl start docker
@@ -4610,7 +4638,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "# check CMD"
   echo "[ -z \"\$Imagecommand\" ] && {"
   echo "  # extract image command from image if not given on cli"
-  echo "  Imagecommand=\"\$(docker inspect --format='{{.Config.Cmd}}' $Imagename)\""
+  echo "  Imagecommand=\"\$(docker inspect --format='{{.Config.Cmd}}' $Imagename | rmcr)\""
   echo "  Imagecommand=\"\${Imagecommand#[}\""
   echo "  Imagecommand=\"\${Imagecommand%]}\""
   echo "  Imagecommand=\"\${Imagecommand#/bin/sh -c }\""
@@ -4622,7 +4650,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
     yes) echo "Entrypoint=" ;;
     no)
       echo "# check ENTRYPOINT"
-      echo "Entrypoint=\$(docker inspect --format='{{.Config.Entrypoint}}' $Imagename)"
+      echo "Entrypoint=\$(docker inspect --format='{{.Config.Entrypoint}}' $Imagename | rmcr)"
       echo "Entrypoint=\${Entrypoint#[}"
       echo "Entrypoint=\${Entrypoint#/bin/sh -c }"
       echo "Entrypoint=\${Entrypoint%]}"
@@ -4704,7 +4732,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
     echo "IFS=$'\n'"
     echo "while read -r Line; do"
     echo "  echo export \$(escapestring \"\$Line\")      >> $Imagecommandscript"
-    echo "done < <(docker run --rm --entrypoint env $Imagename env)"
+    echo "done < <(docker run --rm --entrypoint env $Imagename env | rmcr)"
     echo "IFS=$' \t\n'"
     echo ""
   }
@@ -4797,7 +4825,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo   "  echo ''"
 
   echo   "  echo 'cd \"\$HOME\"'"                                                    # HOME as default working directory
-  echo   "  Workdir=\$(docker inspect --format='{{.Config.WorkingDir}}' $Imagename)" # WORKDIR in image
+  echo   "  Workdir=\$(docker inspect --format='{{.Config.WorkingDir}}' $Imagename | rmcr)" # WORKDIR in image
   echo   '  [ "$Workdir" ] && echo "[ -d \"$Workdir\" ] && cd \"$Workdir\"   # WORKDIR in image"'
   [ "$Workdir" = "/tmp" ] || echo "  echo 'cd $Workdir'"                             # x11docker option --workdir
   echo   "  echo ''"
@@ -4851,7 +4879,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
 
   #### run docker image ####
   [ "$Winsubsystem" = "MSYS" ] && echo "export MSYS2_ARG_CONV_EXCL='*'"
-  echo "read Containerid < <($Dockercommand 2>>$Containerlogfile)"
+  echo "read Containerid < <($Dockercommand 2>>$Containerlogfile | rmcr)"
   ##########################
 
   echo ""
@@ -4862,11 +4890,11 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
 \$(tail $Containerlogfile)\""
   echo "echo \$Containerid >> $Containeridfile"
   [ "$Showcontainerid" = "yes" ] && echo "stdout \"\$(cat $Containeridfile)\""
-  echo "docker logs -f \$Containerid >> $Containerlogfile 2>&1 &"
+  echo "docker logs -f \$Containerid 2>&1 | rmcr >> $Containerlogfile &"
   echo ""
   echo "# wait for container to be ready"
   echo "for ((Count=1 ; Count<=20 ; Count++)); do"
-  echo "  docker exec $Containername sh -c : 2>>$Containerlogfile && { verbose -d 'Container is up and running.' ; break ; } || verbose -d \"Container not ready on \$Count. attempt, trying again.\""
+  echo "  docker exec $Containername sh -c : 2>&1 | rmcr >>$Containerlogfile && { verbose -d 'Container is up and running.' ; break ; } || verbose -d \"Container not ready on \$Count. attempt, trying again.\""
   echo "  sleep 0.2"
   echo "done"
   echo "Failure=\"\$(cat $Containerlogfile | grep -v grep | grep -E 'Error response from daemon|OCI runtime exec' ||:)\""
@@ -4877,10 +4905,10 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "}"
   echo ""
 
-  echo "docker inspect --format '{{ .NetworkSettings.IPAddress }}' $Containername >> $Containeripfile"
+  echo "docker inspect --format '{{ .NetworkSettings.IPAddress }}' $Containername | rmcr >> $Containeripfile"
   echo "verbose -d \"Container IP: \$(cat $Containeripfile)\""
   echo ""
-  echo "docker inspect --format '{{.State.Pid}}' $Containername >> $Containerpid1pidfile"
+  echo "docker inspect --format '{{.State.Pid}}' $Containername | rmcr >> $Containerpid1pidfile"
   echo "verbose -d \"Host PID of container PID 1: \$(cat $Containerpid1pidfile)\""
   [ "$Showcontainerpid1pid" = "yes" ] && echo "stdout \"\$(cat $Containerpid1pidfile)\""
   echo ""
@@ -4890,7 +4918,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "echo \$Containerpid >> $Containerpidfile"
   echo ""
   # container.CMD.sh will wait until setup script is ready
-  [ "$Switchcontaineruser" = "no" ] && echo "docker exec --tty -u root $Containername /bin/sh $Cshare/container.rootsetup.sh >>$Containerlogfile 2>&1"
+  [ "$Switchcontaineruser" = "no" ] && echo "docker exec --tty -u root $Containername /bin/sh $Cshare/container.rootsetup.sh 2>&1 | rmcr >>$Containerlogfile"
   echo "exit 0"
 } >> $Dockerrc
 
@@ -5413,7 +5441,7 @@ exit 0' >> /etc/rc.local"
     echo "export $Hostxenv"
     echo 'verbose -d "Option --no-xhost: disabling any access to host display $DISPLAY granted by xhost"'
     echo 'no_xhost || warning "Option --no-xhost failed. Output of xhost:'
-    echo '$(xhost 2>&1)"'
+    echo '$(xhost 2>&1 | rmcr)"'
   }
 
   echo "export $Newxenv"
@@ -5438,7 +5466,7 @@ exit 0' >> /etc/rc.local"
         echo     ":> $Xclientcookie"
         [ "$Xserver" = "--hostdisplay" ] && {
           [ -s "$Hostxauthority" ] && echo "export XAUTHORITY=$Hostxauthority"
-          echo   "xhost | grep -q 'SI:localuser:$Hostuser'|| { xhost +SI:localuser:$Hostuser ; Xhostentry='yes' ; }"
+          echo   "xhost | rmcr | grep -q 'SI:localuser:$Hostuser' || { xhost +SI:localuser:$Hostuser | rmcr ; Xhostentry='yes' ; }"
         }
         # TEST
         #echo "echo 'set DISPLAY=$Newdisplay"
@@ -5448,7 +5476,7 @@ exit 0' >> /etc/rc.local"
         case "$Ssh" in
           no)
             echo "verbose 'Requesting $Trusted cookie from X server'"
-            echo "xauth -v -i -f Xclientcookie generate $Newdisplay . $Trusted timeout 3600"
+            echo "xauth -v -i -f Xclientcookie generate $Newdisplay . $Trusted timeout 3600 | rmcr"
           ;;
           yes)
             echo "verbose 'Can not use cookies created over SSH. Will bake one myself.'"
@@ -5474,16 +5502,16 @@ exit 0' >> /etc/rc.local"
         echo     "[ -s '$Xclientcookie' ] || { "
         echo     "  # still no cookie? try to create one without extension security"
         echo     "  verbose -d 'Failed to retrieve trusted cookie from X server. Will bake one myself.'"
-        echo     "  xauth -v -i -f Xclientcookie add :$Newdisplaynumber . $(mcookie)"
+        echo     "  xauth -v -i -f Xclientcookie add :$Newdisplaynumber . $(mcookie) | rmcr"
         echo     "}"
         echo     "# create prepared cookie with localhost identification disabled by ffff, needed if X socket is shared. ffff means 'familiy wild'"
         echo     "Cookie=\$(xauth -i -f Xclientcookie nlist | rmcr | sed -e 's/^..../ffff/')"
-        echo     "echo \$Cookie | xauth -v -i -f Xclientcookie nmerge -"
+        echo     "echo \$Cookie | xauth -v -i -f Xclientcookie nmerge - | rmcr"
         echo     "cp $Xclientcookie $Xservercookie"
         echo     "[ -s '$Xclientcookie' ] || warning 'Cookie creation failed!'"
-        echo     "verbose -d \"Created cookie: \$(xauth -f Xclientcookie list 2>&1)\""
+        echo     "verbose -d \"Created cookie: \$(xauth -f Xclientcookie list 2>&1 | rmcr)\""
         echo     "chmod 644 $Xclientcookie"
-        [ "$Xserver" = "--hostdisplay" ] && echo "[ '\$Xhostentry' = 'yes' ] && env XAUTHORITY=$Hostxauthority xhost -SI:localuser:$Hostuser"
+        [ "$Xserver" = "--hostdisplay" ] && echo "[ '\$Xhostentry' = 'yes' ] && env XAUTHORITY=$Hostxauthority xhost -SI:localuser:$Hostuser | rmcr"
         [ "$Xserver" = "--nxagent" ]     && echo "rm $Xclientcookie.bak"
       }
 
@@ -5503,14 +5531,14 @@ exit 0' >> /etc/rc.local"
 
           [ -n "$Xhost" ] && {
             echo "verbose 'Custom xhost setting on $Newdisplay (option --xhost): $Xhost'"
-            echo "xhost $Xhost"
+            echo "xhost $Xhost | rmcr"
           }
 
           [ "$Initsystem" = "systemd" ] || [ "$Dbusdaemon" = "yes" ] && {
             echo "note 'Allowing xhost access for $Benutzer on display $Newdisplay"
             echo "  to avoid service issues with X access. (option --systemd or --dbus-system):"
             echo "    xhost +SI:localuser:$Benutzer'"
-            echo "xhost +SI:localuser:$Benutzer"
+            echo "xhost +SI:localuser:$Benutzer | rmcr"
           }
           # Keyboard layout
           command -v setxkbmap >/dev/null && {
@@ -5526,7 +5554,7 @@ exit 0' >> /etc/rc.local"
             echo "# set keyboard layout on $Newdisplay to same as on host"
             echo "echo 'x11docker: keyboard layout:'"
             echo "cat $Xkbkeymapfile"
-            echo "xkbcomp $Xkbkeymapfile $Newdisplay"
+            echo "xkbcomp $Xkbkeymapfile $Newdisplay | rmcr"
           }
         ;;
       esac
@@ -5592,7 +5620,7 @@ exit 0' >> /etc/rc.local"
   Recommended: Downgrade to xpra v2.2.5, upgrade to at least r19606,
   or use another X server option.
   Fallback: Setting 'xhost +SI:localuser:$Benutzer'"
-        echo "xhost +SI:localuser:$Benutzer"
+        echo "xhost +SI:localuser:$Benutzer | rmcr"
       }
     ;;
     --xorg) # --xorg: --scale, --size, --rotate
@@ -5910,7 +5938,7 @@ $(tail $Xpraserverlogfile)"
         storepid $Containerpid container
         setonwatchpidlist $(cat $Containerpid1pidfile) containerpid1
         verbose -d "Process tree of container (maybe not complete yet):
-$(pstree -cp $(cat $Containerpid1pidfile) 2>&1)"
+$(pstree -cp $(cat $Containerpid1pidfile) 2>&1 ||:)"
       } || {
         [ "$Xserver" = "--nothing" ] && saygoodbye "--nothing" || {
           error "Container startup seems to have failed!
@@ -5965,7 +5993,7 @@ $(tail $Logfile)"
       echo $Hostexepid >>$Containerpid1pidfile
 
       debugnote "Process tree of $Hostexe:
-$(pstree -p $Hostexepid 2>&1)"
+$(pstree -p $Hostexepid 2>&1 ||:)"
 
       storepid $Hostexepid hostexe
       setonwatchpidlist $Hostexepid hostexe
@@ -5974,7 +6002,7 @@ $(pstree -p $Hostexepid 2>&1)"
 }
 
 debugnote "Process tree of x11docker:
-$(pstree -p $$ 2>&1)"
+$(pstree -p $$ 2>&1 ||:)"
 } & storepid $! containershell                ####
 
 { #### part: start Compositor
@@ -6011,13 +6039,13 @@ $(tail $Compositorlogfile)"
       $Mksu "exec                                             bash $Xinitrc                       >> $Xinitlogfile  2>&1 " ;;
     --vcxsrv)
       Tasklistold="
-$(tasklist.exe | grep vcxsrv.exe | awk '{print $2}')"
+$(tasklist.exe | rmcr | grep vcxsrv.exe | awk '{print $2}')"
       $Mksu "exec                                                              $Xcommand          >> $Xinitlogfile  2>&1  &"
       case $Winsubsystem in
         MSYS|CYGWIN)
           Tasklistnew="$Tasklistold
-$(tasklist.exe | grep vcxsrv.exe | awk '{print $2}')"
-          Xserverpid="$(cat <<<"$Tasklistnew" | sort | uniq -u)"
+$(tasklist.exe | rmcr | grep vcxsrv.exe | awk '{print $2}')"
+          Xserverpid="$(cat <<<"$Tasklistnew" | rmcr | sort | uniq -u)"
           setonwatchpidlist $Xserverpid Xserver
           storepid $Xserverpid vcxsrv.exe
         ;;
@@ -6037,10 +6065,17 @@ $(tail $Compositorlogfile)")"
 
 ######### ToDo notes for development
 todo() {
-# --vcxsrv: create cookie, delete cookie
-#           --pulseaudio
-#           --gpu ?
-#           check further options
+# --vcxsrv: create cookie https://sourceforge.net/p/vcxsrv/bugs/79/
+#           --gpu implemented, needs test
+# MSYS2/Cygwin/WSL: check further options
+#                   --stdin:      will fail, needs fix
+#                   --pw:         set to none as default? does check already work?
+#                   --pulseaudio: not implemented. At least on Cygwin probably not too hard.
+#                   --wayland:    create nested setup for WSL in X?
+#                   impossible:
+#                   --alsa
+#                   --systemd, elogind
+# WSL: sharing from within WSL not possible so far. Needs check and error message.
 
 # BUG x11docker/cde fails
 # check xhost +localhost
