--showXY=FILE: use unpriv()

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="7.0.0-beta-1"
+Version="7.0.0-beta-2"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -9228,22 +9228,22 @@ $(cat $Storepidfile)"
     case "$Showinfofile" in           # --printinfofile
       "") ;;
       yes) echo "$Storeinfofile" ;;
-      *)   echo "$Storeinfofile" > "$Showinfofile"         || error "Option --printinfofile: Invalid file $Showinfofile" ;;
+      *)   unpriv "echo '$Storeinfofile' > '$Showinfofile'"         || error "Option --printinfofile: Invalid file $Showinfofile" ;;
     esac
     case "$Showdisplayenvironment" in # --printenv
       "") ;;
       yes) storeinfo dump Xenv ;;
-      *)   echo "$Newxenv_cr" > "$Showdisplayenvironment"  || error "Option --printenv: Invalid file $Showdisplayenvironment" ;;
+      *)   unpriv "echo '$Newxenv_cr' > '$Showdisplayenvironment'"  || error "Option --printenv: Invalid file $Showdisplayenvironment" ;;
     esac
     case "$Showcontainerid" in        # --printid
       "") ;;
       yes) storeinfo dump containerid ;;
-      *)   storeinfo dump containerid > "$Showcontainerid" || error "Option --printid: Invalid file $Showcontainerid" ;;
+      *)   unpriv "storeinfo dump containerid > '$Showcontainerid'" || error "Option --printid: Invalid file $Showcontainerid" ;;
     esac
     case "$Showcontainerpid1pid" in   # --printpid1
       "") ;;
       yes) echo $Pid1pid ;;
-      *)   echo $Pid1pid > "$Showcontainerpid1pid"         || error "Option --printcontainerpid1pid: Invalid file $Showcontainerpid1pid" ;;
+      *)   unpriv "echo $Pid1pid > '$Showcontainerpid1pid'"         || error "Option --printcontainerpid1pid: Invalid file $Showcontainerpid1pid" ;;
     esac
     storeinfo "x11docker=ready"
   } <&0 & storepid $! containershell
