Outsourced `x11docker.png` from `x11docker-gui`.

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -10,7 +10,7 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # More documentation at   https://github.com/mviereck/x11docker
 
-Version="4.1.1"
+Version="4.1.2-beta"
 
 usage() {               # --help: show usage information
   echo "
@@ -413,16 +413,11 @@ installer() {           # --install, --update, --update-master, --remove: Instal
   # Prepairing
   case ${1:-} in
     --install)
-      command -v x11docker > /dev/null && { error "x11docker seems to be installed already.
-  Try 'x11docker --update' instead." ; }
       [ -f "./x11docker" ]             || { error "File x11docker not found in current folder.
   Try 'x11docker --update' instead." ; }
-      command -v kaptain > /dev/null   || { warning "x11docker-gui needs package kaptain
-  to provide a GUI, but could not find kaptain on your system. 
-  Please install package kaptain if you want to use x11docker-gui.
-  x11docker-gui tries to use image x11docker/kaptain if kaptain missig.
-  x11docker itself does not need it and works fine from cli.
-  Get kaptain on github: https://github.com/mviereck/kaptain" ; }
+      command -v x11docker > /dev/null && { warning "x11docker seems to be installed already.
+  Will overwrite existing installation.
+  Consider to use option '--update' or '--update-master' instead." ; }
     ;;
     --update|--update-master)
       Oldversion="$($0 --version)"
@@ -456,21 +451,18 @@ installer() {           # --install, --update, --update-master, --remove: Instal
   # Doing
   case ${1:-} in
     --install|--update|--update-master)
-      [ -x /usr/local/bin/x11docker ]     && rm -v /usr/local/bin/x11docker
-      [ -x /usr/local/bin/x11docker-gui ] && rm -v /usr/local/bin/x11docker-gui
       note "Installing x11docker and x11docker-gui in /usr/bin"
-      cp x11docker /usr/bin/           || error "Could not copy x11docker to /usr/bin"
+      [ -e /usr/local/bin/x11docker ]     && rm -v /usr/local/bin/x11docker
+      [ -e /usr/local/bin/x11docker-gui ] && rm -v /usr/local/bin/x11docker-gui
+      cp x11docker /usr/bin/            || error "Could not copy x11docker to /usr/bin"
       chmod 755 /usr/bin/x11docker      || error "Could not set executeable bit on x11docker"
       cp x11docker-gui /usr/bin/  && chmod 755 /usr/bin/x11docker-gui || warning "x11docker-gui not found"
       
-      note "Creating icon and application entry for x11docker"
-      X11dockericonfile=$(x11docker-gui --icon)
-      [ -e "$X11dockericonfile" ] && {
-        xdg-icon-resource install --context apps --novendor --size 72 "$X11dockericonfile" x11docker
-        command -v xdg-icon-resource >/dev/null || warning "Could not install icon for x11docker.
-  Please install 'xdg-icon-resource' and try again."
-        rm $X11dockericonfile
-      } || note "Could not create icon for x11docker"
+      note "Installing icon for x11docker with xdg-icon-resource"
+      xdg-icon-resource install --context apps --novendor --mode system --size 64 "$(pwd)/x11docker.png" x11docker || warning "Could not install icon for x11docker.
+  Is 'xdg-icon-resource' installed on your system?"
+      
+      note "Creating application entry for x11docker"
       [ -e "/usr/bin/x11docker-gui" ] && {
         echo "[Desktop Entry]
   Version=1.0
@@ -512,8 +504,10 @@ installer() {           # --install, --update, --update-master, --remove: Instal
         rm -v /usr/bin/x11docker-gui
       }
       [ -e "/usr/share/applications/x11docker.desktop" ] && rm -v /usr/share/applications/x11docker.desktop
-      [ -e "/usr/share/doc/x11docker" ] &&                  rm -R -v /usr/share/doc/x11docker
-      xdg-icon-resource uninstall --size 72 x11docker
+      [ -e "/usr/share/doc/x11docker" ]                  && rm -R -v /usr/share/doc/x11docker
+      [ -e "/usr/share/icons/x11docker.png" ]            && rm /usr/share/icons/x11docker.png
+      xdg-icon-resource uninstall --size 64 x11docker ||:
+      xdg-icon-resource uninstall --size 72 x11docker ||:  # deprecated icon size, may still be present.
       note "Will not remove files in your home folder.
   There may be files left in \$HOME/.local/share/x11docker
   The symbolic link \$HOME/x11docker may exist, too.
diff --git a/x11docker-gui b/x11docker-gui
--- a/x11docker-gui
+++ b/x11docker-gui
@@ -720,7 +720,7 @@ stddevelline:beside -> develdialog;
 x11docker_options -> choose_xserver sizefullscreen choose_options_normal choose_options_advanced choose_options_hostfolders develcollect imageorexe "\"" setcapsdialog dockeroptions "\" " "\""dockerimage "\"" ;
 x11docker -> "'$X11docker_exe' " x11docker_options;
 
-buttons :horizontal ->  run runxterm preview desktop_starter orphanedcheck help @close="Cancel";
+buttons :horizontal ->  run runxterm preview desktop_starter orphanedcheck help @dump("")="Cancel";
   old_run -> @fork(x11docker)=" Run";
   run -> @dump(x11docker)=" Run";
   preview -> @preview(x11docker,"monospace",900)="Preview command" ;
@@ -729,81 +729,18 @@ buttons :horizontal ->  run runxterm preview desktop_starter orphanedcheck help 
   runxterm -> @dump("xterm -hold -e '"'"'",x11docker,"'"'"'")="Run in xterm";
 '
 
+##### create files
 
-# base64 coded image
-echo 'iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAHnpUWHRUaXRsZQAACJmrMDRMyU/OTi2KNzeqMDcCACm7BPwQXjsdAAAAGHpUWHRBdXRob3IAAAiZ
-80ksLU7OSC0CAA4MAzgnFwAHAAAatElEQVR42u1cZ2CUVdZ+7lumppAMCSChhNBEmrCAIiCs67pgRQR7WXR3YVWs2P38QFEU/BQXFQu7iGsFARFdwGVVqiAgUkV6DQnpyfR53/ude9+ZyUxIDIm4+oOL
-4zDztnufe85znnPuHYDT7XQ73U63X66xHzv47LPPckVRwFj1aZwbMM0wXcigqHr0FuLF5TvnHOPHj2e/xsEuXbqUr1mzBmJMooXDYUycOLHxfb300kt5dOQJr3TuzBjAba5etRyzXmef/Rv+awSoWbNm
-Sf3s27fvT+9nbm4u3UThTNF5amZffvkNC/mE17z8/v87zIdc+QZPzz6Pjqu8ScY5vMvZ43hWy4vkw8eOGfurAmnAgAFJ4OTk5Jya/n284GOu6yp3pHbndz21m89eFeATZu3kz719iH+w0uT/88oPvNvA
-yXz8i/v49M99/NFXjvF2XUZzhTH+1ltv/SpAGjt2bBI4TqeTf/zxx6eub+Puuov3GTyZz1rs570vfIkrjh7cntqTnz34Gf7KvBL+4b/L+ZiJ3/Hhd+zgzy4o4xdf8wE9nPEWLVr84gC9+eabgkeTAHr8
-8cdPfb/unbqJz15axi+8bQX/3eWvct2eSQ/ReI/BU/iStX5+3mUzec+BT/HbHl3HW7cfyYnCZWeGDBnyi4KUkZGRBM7ll1/+8/Rn/uoKPnPuMT5/TZBf/9B6rqfkcYpv3JHWi097v5SPeWg1B/PQbHkI
-HJWOqfFOPfboY78ISD169EgCp3379j9vP17+5xbetvdd5F6diWMUrkLnUJvz+57fzO9/cj09PLXWqKbrjC/6ZMF/FaQbb7zxBN4RYf5nf/BVV8VCvyqjW6rnYv7i7FI++oFvuT19CE/JGsybt7uMt8gb
-Re9X02sEd3kG8p79rvqvAfTCCy+cMEmTJ09u1PMbJZI6dL+aG0oz5LTrgS5n9cGf/piL5WsrEWQRpKfYkd7EAZtd0DRDOKKgrKQSVZV+YUvQdRvCBh1TyP5UoGm6iZZZCs7v0fSUiMsVK1bwYcOGobKy
-Mv7dyJEjMWfOHPazAvT5ukK+bW8IIRpwdpYTnmY22FJNLFz+BVJTNVx8dnc0y04HjAhNmSnBYdDBTVKtCilsZpICFyqcwwhrCBFIFd4gSitMlBSbqCoVYHJkNzFxZlsd/bo1DrAuXbrw7du3xz937doV
-W7dubTT49V74+Zpyvm5nFdLSFLRpB7TIsiPFrtKYFURo0PuLSuD3GWQFmVCZwIdLow6LlMRKTuR/pnyYSTKfQWPiXYUqrIg+q5oqjsAfYDh2NICCYxyl5WE0cegYOzL7pAd35ZUj+Lx5HyVGMCxcuBAD
-Bw78eQCa/l4R92shmgUDZ3hcsCkaDYOAgUoWEEEgEkbEMOkVoZdBeVj1tTx6a5HH8egB6++QeRyXf0QzIFI9je6tMRUumwabxhHkJo7kAzu3KnBGKjCo+bdon1UOM6UZ0jsPO6HfT02aSNHyf5KDyssv
-4/bbb/9Jrlvnxc/NOsizc3V0aq8ihQhFAMOJY8IRoCoQluCYnEdTVEUO0kpZuQTEZNUAiZOU2KN4FBpFXoWIacp7iPyREyjMIKDoGwGYzWlApYT4yCEFW5cfROequbig1XZKksU1dhjpGUjtORJLtvlx
-9cgRCPiD8f7/cfRo/OPvf//JvFbrDZ5/9yj3tAQ6tiPCtRGT0n+myVAZ9BE4BgyhdFRr4HGrYFF4xIcocDxmNfRHuCQhHA8sMcsyCSAmjiF2jTjHhERc+mWEXNpG17uxYSNZW1kpLu3P0cqRD2/xIewr
-Z7js5kdwYP9eKNaVOOfcQfh6zfJTQvon3OTfa4/zbw6YOL+PCbc7hWaSwSBiLfP6EAiHQAqQLlKjxsCTXSjmOsKaou4WK5XUPLf60Wbt88RjGAkQNYp4IbhdNhw6qGP31jDO75eCzm0NXHfVKCxdsiRe
-cmma1QILZ09Ej+Z+uM8ex6a/U8hNNYxx17RsFGBKzS/W7YzgzPYR2CgGqyqXHazwB+CV4CgngFNdJ7JcJ+ZS4j0REHk86Zq4jcXP4/HrIMlc/kU4MBNWq1HoJi7MNtHzXAXrt0Xw0MR1WLZsR/x+mqph
-ypRn0W/QEEQqjuLtqa9zv1uDj6LnJ6uON0oHaTW/8IcZ6RgDiuaWVuAn0vEFg9JFWHSmeYJlJFpJ7F1JsJqa5ySZby3WVdPAGCz+MsXfKL0LRoKw6xS++4aR1rwbDPd7+M/cD3Ho+zm4fewVuPnma1FU
-wbDYew8KWyvo1LESxeSWm/c2w+tzC3iPTnaSEE1Yo13s8Zn5/LcXKPC47BS2VRSTa/lCYYtDGOpwl9pBsPiF1QpObS3R2mJVP5Ob0ccq8bgXs1CdAGOmE3sOKvju6/3Iy8lGWoaOwlID6VkkaDtyHC45
-huJyE+kuFUYoFWXHbeCGDXbyjlRdgduhgani3gZysjUM7JnOftSCJElGSVZ0zqAQHq+q1hhEosvUdLkYMDXDvABNDD7xu9oAjoOLapdUYlYW1VZBEqFcCaJN+yDycnPg9ZLsQDmadSYRq2skQivJLSPy
-eRX+CAFaCs8Z4o4k800CzCCLVNxwOXUUFTmwdklZ/S4mwzkPWx0RHTJ5QieRpG1qWkdNzql5Xm3H6rKiRLeteV3smJCXMmgGUxBgfmgODhtzyFAh6uZuhxNtSfGHCDaDi3GJIowp6qNkNYCdIrTbpuBw
-sYHyAi9efLANqxcgh2IiTHLCcJpE0mo0OFQX5Ovij5h11HSn2s5jUdEkwK8JQl2AJX6O31OwkymACoBpVnQ1QyoqvRGEKJ3R7TTdJEfEIFOIuESaA3m9ikjEhsoqjk27/bCHUvDwHz3spEg63c1QUamj
-SRpFMs1maRTBA6yasuoaTOJApTvUcJckwMxk96ztHvVxlUocZGqMgoiCUlLdx/LpWmIEt82JjDSGKj8lfNxNxB4hi7HclUc1iEmpkB4oxED/THTt0xb3n2wUy8lORX5JEVqcYZM31InAgqZlytL1WfIs
-Vg+IzlZYPPcSClnltUscSWnWaYhJ8EQ3kt/FQGJWDmcKAUYvUT1VVYMsRMHxAg3HDpMD+VQ099hwYU8nWjUn5Z9iUsgXHGo5IjddZDHVi1NSuJIaF4tWoa0e8IMfoGLr33ha1zvrd7Gsr6dhg+tydO7o
-gaGbsGsavKFI0iBqjzwCRGsNLRAxsD+/SCrgVk3TZRJrJrkHk6lGNDGrzUSiEUuBJu8pQBGXqKggt9i9S0WwVEN2UxP9z0pFl9Y6Wb6gA82SdtyaSTUW8qgDNjVRf1lq3eTp0DrdhrC/ENqBj1C1612e
-0uG6uqNYwfvTeNWsx5DRqimKzh0JpyMApy7CfZBIziJthmSijA86roEAn8+Ho0WlxAEaPJ40pLAozUvSF7lcgO5nkDJ20iCiRJ5gbDKCCkZRI6TkKVoZbhQWUD62vghf/Ws5rrikI/50bS940oXr2qS1
-GoYqLViAGZ+EWpUMQyyDlP5od0M9cwz4hkfA9v/jx5W094NpcNNXeSUrsGFrMaqqvHLcNrIii9zMuPKtyRVS/cLy8yAp133ffoNsHiQSpQgiOq5YCa2AooTC7+GCIhwvqSIgjHgiK2pG4iSVsnkx48HK
-DGz8xoGZL3yHSbdPxnP3DUUzbRHuvLkrmqbbYFJiGzZFYmwTFbgasuBkmmpFtPR2MHOvBQsRBivH8Fot6MCj13C2bjE4uUWGehDHN32Pw7ltkZaSKiNAgBSslYidSKhxDhKuRB3OcLlQcXAvDqU50KVr
-F4QMI8pPkCCLyMIVG8oqq+CkQJCZbkdEMYg3KB4FOI7stePA7hC+WPQWdm76BCVHV9OVlejYMRcvvzIdLlcTS0BSpq/FrERJmKl61XFMpisEkU1OkJpzIXyFy2Ev/w6VP8zkqR1vZRaEwrXWLuKRd1+h
-WQvD0HSkGWVw+hn2N/8tUluGkKI6JOGFZTRQLB6Ocmk8dMciFh0QFtej3zlomdeerjERISWuSclgEbIvGIKfeE0hsEJhH1xuJ/xVOjZtMLBxeQG6tc7Ah6/fg1VLn4O/crck6czMJpg9+x10797dUtox
-t47mbg1R7CcIU1F9oTFGeAhK2SYovuOYNGvzhLiLhRe9B8UsJVOl/Ath2Mg3+wYWw7VuFQoOu1BYUU5mb4MmXU2RnVISXComtUU4j1Du5qfkVjijSg91UKiwOzVyH8WiXXrXdWlqUreEycT3HGB49elV
-ePHhW3DpQD/2b3kTK/7zbjSEiepQBJdddhmGDBmSVA1gSc//CSUNGUQo8mX0hWlvATV0HJV73+DVAG1dRQg6IZyQcV0SpJ1FMOjIU8hftAoHDzhQXllG1hCkmec06xQeyTL89Bd/KAgvAVLl88NP5BuJ
-kDAj03dRjkPpHCW9lOsoLro/zboWQSTIZC6kc+Ec9JlSBUWtonuW4P47LoDNLMFjj02MaihTajDRPvvsM4idGbVpp58KjgW3AdWZCTOjk6QRVrTRIun8+TM4vBVyhg2BJLPmJkSKunXgMEbm7YHOnNjw
-jRsHDjH4vcdR7i9CRaAKPlFVFFqJ8h6H0w4HIeKkpFAnCS+iixBxqmKnYGEi/6iCzWtd2LDaxKovyJpsYpQqtDCFBaUcg4ZdhO69L8aYMXdRFKxKTHnl/wsLC3H33XejvLy8wa5ULyMJQIQ/0MSqqe0J
-A+o/jV0CxLetg0YkahJJMqkCLQVso+gTJD7K6HYGbvx9KkYNccLlb4I921qSC2Sg+HAKfOU2ypB1BIMqfF4CNeCkyELvokQSClCCWIHvtxnYtCYIs8KG3/Zy4YqBQZTs2w6NkQbRdfJ7U1pSejOGhx97
-Dbt274nXnE6oVa1bhwkTJpwy66nWXVZVVIoNVx7Nmw6dODK47z2uhQ7vJLWsRudJnCvYl7hEIX4gL7CntJIs1qmVk15iqYbjYKETxwqDKCoLo7RY8IuGoC+MY5UhnNGOZlitoCGTtQVc8OcH8OcRzUjp
-OqU13HLTg1iy1EC7Ps/jnPPcKCguodlKB3NUwh90J2rtqCKqsZAwfTrOO+88jBgx4tSCJDUIpSa2FDIbMm8lAtN3iCayrIQ4QJUq2BQhGNWiT2UURu2aTAplDkMtzW2ia65KL7IWCpGmWPcSeoLccNaC
-ShRXkNTPNMlNUlC6z4NrL0wjcFQ54OnTZ+Cttz8U9on/zLkIZ585Cr07iuzbhh/2CGEYnSahh3jtAIldYQ888AB69+6Ntm3bnlBmabQFMdOSIIoYr5Dt1IdwGX0mYuUJ2sYCIpofxVKIuL4VYVzUqDUC
-hsITvbOozBOOeWYHAqZEw/GDrcGON8V1v3ehewdBxnZ89dVyPPLIw1H7CGHd0sew4O0NWLlCx7otIWzdrqK4YKtlN3LAap3j2bt3L+677z4JVmJt6qdU5q0cIVYRszI2M+ITqQ5DTOiz6tzR0jqke0yv
-P4HMYvVmHgVSj4Mj+teP8qK8M9JkhMvMVEB8Td+rOHTkMMaOHRNfDhaP79I5Cw/clYf1W3yYfP+bCFNoLS1YE00BeK3Wk9jmzZuHV199FePGjau1zNJggKKJrSlqPZQBqFa0gmI4UmSHlJipKlFhKiS4
-IO/8A9WA8erlBqGMRaVOkQItJvN1ZGdqyMm2ETiCm3SEiOzuu+ce7NixI96ftLQ0zHhlBllXG9xyRXP8rvdR7N/8GsLB0mi10CLu+toTTzyBtWvXxsuzjbKiqPVZE0738efTd2SZFMm4TvJEScuSa+aJ
-bmahyqGRfA7t3SLqcRYlxJM8Vj3BMY9kCaKNW0tF4vPU55/H3Llzk9TrpEmTMGDgAJkuKCQDJj0zFX369Gnw2MrKynAPgV9aWtpAN0vc+BEr48gFJnDfdqhR7cVsHij2Vh1owkj2m4KkuaWUuWVGYv08
-uOtbRCqL5WBFkYmbZrTkw2pEHIvceVQmiGqkEHfPPP10UtduueUW/OUvf4lm8Cy+hj5t2jRpWQ1tQjwKwGtuV64fH24BYhVirEAU9gLluyX7iSOKK4fEbY/fyJzVoqaYBVg+aYpk8Mhe+HesRYRZeZYJ
-E/xHxb3lqvv27cMdd9wBr9cbP9KrVy9MmTKFhKWeVE8yyJXPPfdcqXEa01566SUsWLCgASqbJXCdIVc0JElX7Aaqjsh1cK454Gx9NVOaXnIbU9KaIcRIapvVWQ4nHSBKFLpJ+uTLDynH8kq1bcbVdt3F
-M1EP+utf/ypBijWPx4MZM2bI95rLQbFVDnHN8OHDGwyQiGYiqu3fv//kF7tYNNOiICIn3KREveBLopVyMgSK0q421fWgcJ/esAWs3fPS9ESUIsCkKRGSyrdr4PtupURW7vvhJ8aYxNUIYfKLFy9O4p1n
-nnlG8kxdy0Oi2Ww2PE+c1a5duwaDJEL/+PHjk0J/fRTEuZWkgoJJsHIHeNHXxD8uSrmoj5l9qwFKvfBGBFwumTXLWp4sjOkSKEaq0k7W410wA4a3OCoieZ3giPA7derUpOO33norRo8eXetaWM375Obm
-yusT3fBkmwgGwkrrL/zzeN2S7Ia8oxKRvXNgC/vIOyIIOT1w5l7D4gA17f0HxgcMIw0Qin7DojvEoiVVSkbtO79C+fzXLJUbj2Y8vt1FdGrbtm1Sl4RCoXhXBLdMnjw57kZ1gZPIH8LN7rzzzkbxkQj9
-69evrzX0J29ctMQPpcuIHF0ItfhrMgZdBiLW4oLal573Xt+dOyrywTQibVnwscqkcvMOIcsVJ7Q/PQXP+dcQ+GEL32h4r6iokDWb5cuXVy8AZGVJVxPkXJ/11Fz3Eln70KFDZZRqaBswYAA+/fRTGRWT
-V38RXy0RYd0Qu+TyVwDbXoLOfRR6DQTSuyP1N1NZrTXp1OvvRpiTawnDE0uP0d1gojRpyF/2BBH459Mo++ZTBClnEcVyQbixmUsER8yg4JOGgJN4Tnp6Ol588UVS5JkNBmjlypV48skna+Vmob0iPCwr
-pJGiTeDfv05qOUDJORDQM5LAOQGgrGGjGbvkBphBA3qEVe+woJtqAgjSRUqwGJUzH0Xg60WU7Styy8ns2bPldrfEJkL8DTfcUOsS9clsYhChv2/fvuLnSo0O/cKKLD4y42v6YuebISb3+AaYm1+AHjhO
-gSwia0BK7nUnt8PsyNN/5uHV82F32K2tcooFlinKymQZgtpMhw3uUY9jW8qZuPTiy1BafDx+/cCBA2XnUlNTG5VtJ/JGhPLBm266Ce+//37Dtyt36IBly5ahVatW1rKzyDtFnevQ5+C73oAeqoCp2+l5
-BFC765HS4WZ20nsU9z03hmurF1E0IUD06FIogaOKGVG4tRmF8rjFJQ48uHA7jgWELAijVU5L4p0l6HLWWQ1yrdpAim2DOXr0KAYPHoxdu3Y1YGeYIkP41VePwiyycE5AIJgPYzcJygP/go2H5F74CIV4
-5A6Hq/NtrPaFoTratM/XT7j37tH/a+zZSAFfKEvVyvSj5M3FKgUxfmd3GL9rk4JCSvqPhjRMf+MNDBk0CBEjLMGMVwEaVcNi8eRW1H7mz58vLeokC6myrrNt2xZkNM3COR2IkDf+DWr+OrH9k+4dRFAj
-C+94Ldwdb2aN3iedP28q9348A+6AF8xulwDJxFa8EyeJaOfWDFSENexQm6Pfvc/CmddH7qBQ63wAj21TS1gKrt+SHnnkESk4G7KBrmebJrjnmk64akAL6GFKanWaaE7Bxt0GSqebkZJzAWv0Pul41vzd
-Ml72wfNw7t4AQyzhqDZZ5tCYtYvDEKUNSk10ylX8tkzwboPg7j8czra9oeguS3waZnwXqrRAUd6kTyoTe6/VOnuS6KZVVVUY+odhWLlqhSyxWIdiO9CYTDjlXkW6Z688D0b/PgdXnpcFj5viMoVxVRV7
-vG0IN+uHtH4n91vVBtl+wQdPc+3LuVCJ+SM0yAgJK6bE9loqkswVFkJIBDx7KszcbmA9hsLWuS80zxlwqG5rTysRZSzptdEsJ27vq08fbdj4HS4aehGKCwuTdsqKXUBtPE0wuJsHI/tnov9Z6WiSaiJE
-rm79LkRHvi8N6b3Ipdpf0fg9ivW18ddcwlsf3YShnVOQxXwIifKGaov+HoOSPLH+RaJSlXoqIi2Lp2cDOQRWhz5Q2/SALbM1NFc6qQY7rL37yUlAfZ18481ZGDd2LFJtGvKap6JPXjoGdPWgbycVOR5x
-TwY/C8MmfuZAWUB+pY4PluVj5rIjmPC3mRhx6SU/D0BTpkzl48c/SCasYGALB0Z18WBYxxQ4g2IlQ4VJyab4OYGsp6ni5wUkOIWViT0cJM4iYkXW4YQhdlg2bQ09K5csqw3MJs2hpmRBs6fQRcKFlWil
-W2xRiYjNRkDIDyNQBuY9jmDxHnzz74Vo6aKomeWUGzEV8Sx6qEJilukOmHYFR4o0zFtTjFlLf8DmgxWytNGxUwf8sHPXqQdo6dIl/IrhV8Ln9Ua35XJccvEwLPr0M1Yw9zlubFkMrWAfWQ4NyEZg6Tbi
-JhsN1oAtuuTMo8Vxk8WqT4K/mByMWHqC7iaAyPJ0Ra6oKLIGFSLtIvYW0n1FOqBYKw9Oh0O6aZg+M/qsEvlqOkcVRdIt+/xYsLYIH60pxN5CC5hE27z++hvxzjtvn1oOItHFhQ6JlVLy8tpj157dSdcX
-bVzK/TvXQNuzDnrpPojNjnIrHpm5XFoSGx9UK3WRmw+iUVAsAoglJxYVpdaiuGktVzNLXggeNxS72HdH54UtQpY7PDR4mRN78734cmsZ/vVtCdbvKYc/EjxhdTaxiYL/2LFj2SkBSPwDA5988kn8s9Pt
-wkdzPsSwYT/uy8e++DvXDm2DUfgDUFUIFqJIYpJFCFkvf0bG5YC1qEo3tOoFAHFMVH6tvT9MAibAIOUK09mEkjUK283aYcXmEtw78Q0cKAzBFw4geQHHrLNvTZs2RVFR0U8H6KGHHhI/Z0z6TmiRhx9+
-uFHqr2zNHM4rD8HwliLiq4AtRLxCyaJJ0Ua6niBWYSW6kzjNJZZ2wdwZYKnZUFKzkNZl+AnPHXT+EL78qy8a3Jf+/ftj9erVjV8vWrRoEaesWv4gNvYaNWrUr/KfnSClze12+0m/HA4H1zSNP/HEE7/K
-8Zxup9vpdrqdbqfb6fazt/8HLN2eJzJBCT8AAAAASUVORK5CYII=' | base64 -d >>  "$X11docker_logo"
+# copy icon in $Tmpdir, if available
+cp /usr/share/icons/hicolor/64x64/apps/x11docker.png       $X11docker_logo 2>/dev/null || :> $X11docker_logo
+cp /usr/local/share/icons/hicolor/64x64/apps/x11docker.png $X11docker_logo 2>/dev/null
 
 # store created grammar in a file
 echo "$Kaptain_grammar" | sed -e 's/  */ /g' >> "$X11docker_kaptn"
-# check options
+
+#### check options
 Verbose="--silent"
 case "$1" in
-  --icon) # option --icon: only create icon file and exit. used by installer
-    echo "$X11docker_logo"
-    rm "$X11docker_kaptn"
-    exit
-  ;;
   -v|--verbose) 
     kaptain --version
     Verbose="--verbose" 
@@ -814,6 +751,8 @@ $(cat $X11docker_kaptn)
 "
   ;;
 esac
+
+#### check executeables
 
 command -v kaptain >/dev/null && Hostkaptain="yes" || Hostkaptain="no"
 
@@ -830,6 +769,8 @@ $(kaptain --version)
   Hostkaptain="no"
 }
 
+#### Run kaptain
+
 case $Hostkaptain in
   yes)
     [ "$Verbose" = "--verbose" ] && {
@@ -844,6 +785,8 @@ Fallback: Will try to use image x11docker/kaptain."
     { read -r containerID ; read -r X11docker_command ;} < <(x11docker --hostdisplay --no-init --gpu $Verbose --stdout --env HOME="$CONTAINERUSERHOME" -- --volume="$X11docker_kaptn":"/x11docker.kaptn":ro --volume="$X11docker_logo":"$X11docker_logo":ro --volume="$CONTAINERUSERHOME":"$CONTAINERUSERHOME":ro x11docker/kaptain "/x11docker.kaptn")
   ;;
 esac
+
+#### clean up and run x11docker
 
 rm "$X11docker_logo" "$X11docker_kaptn"
 echo $X11docker_command
