--pulseaudio=host: mount socket read-only

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="7.1.1-beta-5"
+Version="7.1.1-beta-6"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -1701,6 +1701,31 @@ $(sed -n "/${Key1}/,/${Key2}/p" /usr/share/doc/x11docker/CHANGELOG.md | head -n-
   esac
   note "Ready."
 }
+set_password() {                # option --password: set container user password
+  local Password
+
+  Password="${1:-}"
+
+  command -v perl >/dev/null || {
+    error "Option --password: command 'perl' not found.
+  perl is needed to generate an encrypted password."
+    return 1
+  }
+  [ "$Password" = "INTERACTIVE" ] && {
+    read -rs -p "Please type in a new container user password (chars are invisible): " Password
+    echo ""
+    [ -z "$Password" ] && {
+      error "Empty input, password not changed."
+      return 1
+    }
+  }
+  Password="$(perl -e "print crypt(\"$Password\", \"salt\")")"
+  mkdir -p "$(dirname "$Passwordfile")"
+  echo "$Containeruserpassword" > "$Passwordfile"
+  chmod 600                       "$Passwordfile"
+  note "Option --password: Password changed, exiting."
+  return 0
+}
 
 #### features
 check_windowmanager() {         # option --wm: search a host window manager
@@ -2192,6 +2217,13 @@ setup_sound_pulseaudio() {      # option --pulseaudio: set up pulseaudio connect
   to catch your audio output and microphone input."
 
   case "$Pulseaudiomode" in
+    socket|tcp)
+      grep -q -i "PipeWire" <<< "$(pactl info)" && note "Option --pulseaudio: Found pipewire sound server.
+  If pulseaudio sound fails, you can try --pulseaudio=host instead."
+    ;;
+  esac
+  
+  case "$Pulseaudiomode" in
     socket)
       # create pulseaudio socket
       Pulseaudiomoduleid="$(unpriv "pactl load-module module-native-protocol-unix socket='$Pulseaudiosocket' 2>&1")"
@@ -2259,31 +2291,6 @@ setup_webcam() {                # option --webcam: share webcam devices
 
   # at least cheese and gnome-ring need some device information from udev.
   store_runoption volume "/run/udev/data:ro"
-  return 0
-}
-set_password() {                # option --password: set container user password
-  local Password
-
-  Password="${1:-}"
-
-  command -v perl >/dev/null || {
-    error "Option --password: command 'perl' not found.
-  perl is needed to generate an encrypted password."
-    return 1
-  }
-  [ "$Password" = "INTERACTIVE" ] && {
-    read -rs -p "Please type in a new container user password (chars are invisible): " Password
-    echo ""
-    [ -z "$Password" ] && {
-      error "Empty input, password not changed."
-      return 1
-    }
-  }
-  Password="$(perl -e "print crypt(\"$Password\", \"salt\")")"
-  mkdir -p "$(dirname "$Passwordfile")"
-  echo "$Containeruserpassword" > "$Passwordfile"
-  chmod 600                       "$Passwordfile"
-  note "Option --password: Password changed, exiting."
   return 0
 }
 
