--limit: change free memory check #360 --backend=nerdctl --pw=sudo: Do not use 'sudo -E' Generalize some messages mentioning 'docker'

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4114,7 +4114,7 @@ create_dockercommand() {        ### create command to run docker
   storeinfo "containername=$Containername"
   
   [ "$Limitresources" ] && {
-    Memory="$(awk "BEGIN {print int($(free -b | awk 'NR==2 {print $7}') * $Limitresources)}")"
+    Memory="$(awk "BEGIN {print int($(LC_ALL=C free -b | grep "Mem:" | awk ' {print $4 + $6}') * $Limitresources)}")"
     Dockercommand="$Dockercommand \\
   --cpus=$(awk "BEGIN {print $(nproc) * $Limitresources}") \\
   --memory=$Memory \\
@@ -5605,10 +5605,10 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   echo "Containerid="
   echo "Containerip="
   echo "Dockerlogspid=''"
-  echo "Dockerpull="
   echo "Exec="
   echo "Entrypoint="
   echo "Failure="
+  echo "Imagepull="
   echo "Imageuser="
   echo "Inspect="
   echo "Line="
@@ -5659,13 +5659,13 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   echo "# Check default runtime"
   echo "Runtime=\"\$( { grep 'Default Runtime' < '$Dockerinfofile' ||: ;} | awk '{print \$3}' )\""
   echo '[ -n "$Runtime" ] && {' 
-  echo "  debugnote \"dockerrc: Found default Runtime: \$Runtime\""
+  echo "  debugnote \"dockerrc: Found default container Runtime: \$Runtime\""
   echo "  debugnote \"dockerrc: All \$(grep 'Runtimes' < '$Dockerinfofile' ||: )\""
   echo "  [ \"\$Runtime\" != '$Runtime' ] && {"
   echo "    case \$Runtime in"
-  echo "      kata-runtime)  warning 'Found default docker runtime kata-runtime.
+  echo "      kata-runtime)  warning 'Found default container runtime kata-runtime.
   Please run x11docker with --runtime=kata-runtime to avoid issues.' ;;"
-  echo "      nvidia) [ '$Sharegpu' = 'yes' ] &&  warning 'Option --gpu: Found default docker runtime nvidia.
+  echo "      nvidia) [ '$Sharegpu' = 'yes' ] &&  warning 'Option --gpu: Found default container runtime nvidia.
   Please run x11docker with --runtime=nvidia to avoid issues.' ;;"
   echo "      runc|crun|oci) ;;"
   echo "      *) note \"Found unknown container runtime: \$Runtime
@@ -5678,7 +5678,7 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   echo "storeinfo \"runtime=\$Runtime\""
   echo ""
   
-  echo "# Refresh images.list for x11docker-gui"
+  echo "# Refresh images.list for x11docker-gui" ### FIXME makes no sense with multiple backends. But list needed below.
   echo "$Containerbackendbin images 2>>$Containerlogfile | grep -v REPOSITORY | awk '{print \$1 \":\" \$2}' >>$Dockerimagelistfile.sort"
   echo "rmcr $Dockerimagelistfile.sort"
   echo "while read -r Line ; do"
@@ -5688,12 +5688,12 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   echo ""
 
   echo "# Check if image $Imagename is available locally"
-  echo "Dockerpull=no"
+  echo "Imagepull=no"
   case $Pullimage in
     no) ;;
-    always) echo "Dockerpull=yes" ;;
-#    yes) echo "$Containerbackendbin inspect $Imagename >>$Containerlogfile 2>&1 || Dockerpull=yes" ;;
-    yes) echo "$Containerbackendbin images | grep -q '^$Imagename ' || Dockerpull=yes" ;;
+    always) echo "Imagepull=yes" ;;
+#    yes) echo "$Containerbackendbin inspect $Imagename >>$Containerlogfile 2>&1 || Imagepull=yes" ;;
+    yes) echo "$Containerbackendbin images | grep -q '^$Imagename ' || Imagepull=yes" ;;
     ask)
       [ "$Runsinterminal" = "yes" ] && {
         echo "grep -x -q '$Imagename' < $Dockerimagelistfile || grep -x -q '$Imagename:latest' < $Dockerimagelistfile || {"
@@ -5701,7 +5701,7 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
         echo "  $Containerbackendbin images | grep -q '^$Imagename ' || {"
         echo "    echo 'Image $Imagename not found locally.' >&2"
         echo "    echo 'Do you want to pull it from docker hub?' >&2"
-        echo "    askyesno && Dockerpull=yes || error \"Image '$Imagename' not available locally and not pulled from docker hub.\""
+        echo "    askyesno && Imagepull=yes || error \"Image '$Imagename' not available locally and not pulled from docker hub.\""
         echo "  }"
         echo "}"
       }
@@ -5712,13 +5712,13 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   echo "rocknroll || exit 64"
   echo ""
 
-  echo "[ \"\$Dockerpull\" = 'yes' ] && {"
+  echo "[ \"\$Imagepull\" = 'yes' ] && {"
   echo "  note \"Pulling image '$Imagename' from docker hub\""
   [ "$Runsinterminal" = "no" ] && case $Passwordneeded in
-    no)  echo "  env DISPLAY='$Hostdisplay' DBUS_SESSION_BUS_ADDRESS='${DBUS_SESSION_BUS_ADDRESS:-}' bash           -c \"notify-send 'x11docker: Pulling image $Imagename from docker hub'\" 2>/dev/null &" ;;
-    yes) echo "  env DISPLAY='$Hostdisplay' DBUS_SESSION_BUS_ADDRESS='${DBUS_SESSION_BUS_ADDRESS:-}' su '$Hostuser' -c \"notify-send 'x11docker: Pulling image $Imagename from docker hub'\" 2>/dev/null &" ;;
+    no)  echo "  env DISPLAY='$Hostdisplay' DBUS_SESSION_BUS_ADDRESS='${DBUS_SESSION_BUS_ADDRESS:-}' bash           -c \"notify-send 'x11docker: Pulling image $Imagename'\" 2>/dev/null &" ;;
+    yes) echo "  env DISPLAY='$Hostdisplay' DBUS_SESSION_BUS_ADDRESS='${DBUS_SESSION_BUS_ADDRESS:-}' su '$Hostuser' -c \"notify-send 'x11docker: Pulling image $Imagename'\" 2>/dev/null &" ;;
   esac
-  echo "  $Sudo $Containerbackendbin pull $Imagename 1>&2 || error \"Pulling docker image '$Imagename' seems to have failed!\""
+  echo "  $Sudo $Containerbackendbin pull $Imagename 1>&2 || error \"Pulling image '$Imagename' seems to have failed!\""
   echo "}"
   echo ""
 
@@ -5743,7 +5743,7 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
       echo "  Containercommand=\"\${Containercommand%]}\""
       echo "  debugnote \"dockerrc: Image CMD: \$Containercommand\""
       echo "  echo \"\$Containercommand\" | grep -q $(convertpath share $Containerrc) && error 'Recursion error: Found CMD $(convertpath share $Containerrc) in image.
-      Did you use docker commit with an x11docker container?
+      Did you use 'docker commit' with an x11docker container?
       Please build new images with a Dockerfile instead of using docker commit,
       or provide a different container command.'"
       echo "}"
@@ -6101,7 +6101,7 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   echo "rocknroll || exit 64"
   echo ""
 
-  [ "$Windowmanagermode" = "none" ] || {
+  [ "$Windowmanagermode" = "none" ] || { ### FIXME: check with podman and nerdctl. Or drop at all?
     echo "# run window manager (in image or from host)"
     echo "Windowmanagermode=\"$Windowmanagermode\""
     echo "Windowmanagercommand=\"$Windowmanagercommand\""
@@ -6174,7 +6174,7 @@ $Wmdockercommand"'
   echo ""
 
   echo "[ \"\$Containerid\" ] || {
-    error \"Startup of docker failed. Did not receive a container ID.
+    error \"Startup of $Containerbackend failed. Did not receive a container ID.
     
   Last lines of container log:
 \$(rmcr < $Containerlogfile | tail)\"
@@ -6223,7 +6223,7 @@ $Wmdockercommand"'
   Maybe the container immediately stopped for unknown reasons.
   Just in case, check if host and image architecture are compatible:
   Host architecture: '$Hostarchitecture', image architecture: $Containerarchitecture.
-  Output of \"docker ps | grep x11docker\":
+  Output of \"'$Containerbackend' ps | grep x11docker\":
 $('$Containerbackendbin' ps | grep x11docker)
   
   Content of container log:
@@ -6248,7 +6248,7 @@ $(rmcr < '$Containerlogfile' | uniq )"'
   echo "Failure=\"\$(rmcr < $Containerlogfile | grep -v grep | grep -E 'Error response from daemon|OCI runtime exec' ||:)\""
   echo "[ \"\$Failure\" ] && {"
   echo "  echo \"\$Failure\" >>$Containerlogfile"
-  echo "  error \"Got error message from docker daemon:
+  echo "  error \"Got error message from $Containerbackend:
 \$Failure
 
   Last lines of logfile:
@@ -7044,6 +7044,8 @@ check_option_interferences() {  # check multiple option interferences, change se
 
   case $Containersetup in
     no)
+      [ -z "$Workdir" ] && note "Option --no-setup: You might need to specify
+  e.g. '--workdir=/tmp' or '--env HOME=/tmp' to allow proper functionality."
       case $Initsystem in
         none) ;;
         tini|dockerinit) Initsystem="dockerinit" ;;
@@ -7591,6 +7593,7 @@ check_passwordfrontend() {      # check password prompt frontend (pkexec, su, su
   esac
   [ -z "$Passwordfrontend" ] && $Containerbackendbin info >/dev/null 2>&1 && Passwordfrontend="none" && Passwordneeded="no"
   [ -z "$Passwordfrontend" ] && sudo -n env >/dev/null 2>&1     && Passwordfrontend="sudo" && Passwordneeded="no"
+  [ "$Passwordfrontend" = "sudo" ] && sudo -n env >/dev/null 2>&1 && Passwordneeded="no"
 
   # check sudo. Check is not reliable, compare https://unix.stackexchange.com/questions/383918/su-or-sudo-how-to-know-which-one-will-work
   ### FIXME: just guessing that members of group sudo or wheel are allowed to run commands docker and env as root
@@ -7619,7 +7622,8 @@ check_passwordfrontend() {      # check password prompt frontend (pkexec, su, su
   case $Passwordfrontend in
     pkexec|"") Passwordcommand="bash -c"                                                 ; Passwordterminal="bash -c" ;;
     su)        Passwordcommand="su -c"                                                   ;;
-    sudo)      Passwordcommand="bash -c"                                                 ; Sudo="sudo -E " ;;
+#    sudo)      Passwordcommand="bash -c"                                                 ; Sudo="sudo -E " ;;
+    sudo)      Passwordcommand="bash -c"                                                 ; Sudo="sudo " ;;
     gksu)      Passwordcommand="gksu    --message 'x11docker $Imagename' --disable-grab" ; Passwordterminal="bash -c" ;;
     gksudo)    Passwordcommand="gksudo  --message 'x11docker $Imagename' --disable-grab" ; Passwordterminal="bash -c" ;;
     lxsu)      Passwordcommand="lxsu"                                                    ; Passwordterminal="bash -c" ;;
