--checkwindow: New option to run container as long as an X window is open

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="7.2.1-beta-3"
+Version="7.2.1-beta-4"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -222,6 +222,7 @@ X and Wayland appearance options:
  -F, --xfishtank       Show fish tank on new X server.
 
 X and Wayland special configuration:
+     --checkwindow     Run container until all X windows are closed.
      --clean-xhost     Disable xhost access policies on host display.
      --composite [=yes|no]  Enable or disable X extension Composite.
                        Default is yes except for --nxagent. Can cause or
@@ -791,7 +792,7 @@ waitfortheend() {               # wait for end of x11docker session
         bash -c "read -n1 <${FDtimetosaygoodbye}" && saygoodbye timetosaygoodbyefifo || sleep 1
       done
     ;;
-    no) # Reading from fifo fails on Windows, workaround
+    no|"") # Reading from fifo fails on Windows, workaround
       while rocknroll; do
         sleep 2
       done
@@ -2779,15 +2780,6 @@ check_xdepends() {              # check dependencies on host for X server option
     ;;
   esac
 
-  # --desktop
-  case "$Xserver" in
-    --hostdisplay|--hostwayland)
-      [ "$Desktopmode" = "yes" ] && {
-        $Message "${1:-} does not support option --desktop."
-        Return=1
-      }
-    ;;
-  esac
   # Wayland
   case "${1:-}" in
     --xpra-xwayland|--xpra2-xwayland|--weston-xwayland|--xwayland|--weston|--kwin|--kwin-xwayland|--hostwayland)
@@ -2826,6 +2818,7 @@ check_xdepends() {              # check dependencies on host for X server option
       Return=1
     ;;
   esac
+
   # xinit
   [ "$Xcopt" ] || {
     case "${1:-}" in
@@ -2837,6 +2830,7 @@ check_xdepends() {              # check dependencies on host for X server option
       ;;
     esac
   }
+
   # X command
   case "${1:-}" in
     --xpra2*)
@@ -3027,6 +3021,27 @@ check_xdepends() {              # check dependencies on host for X server option
       ;;
     esac
   }
+
+  # --checkwindow
+  [ "$Checkforopenwindow" = "yes" ] && {
+    case "$Xserver" in
+      --weston|--kwin|--hostwayland|--hostdisplay)
+        $Message "${1:-} does not support option --checkwindow."
+        Return=1
+      ;;
+    esac
+  }
+
+  # --desktop
+  case "$Xserver" in
+    --hostdisplay|--hostwayland)
+      [ "$Desktopmode" = "yes" ] && {
+        $Message "${1:-} does not support option --desktop."
+        Return=1
+      }
+    ;;
+  esac
+
   # --dpi
   [ -n "$Dpi" ] && case "$Xserver" in
     --weston|--kwin|--hostwayland|--hostdisplay)
@@ -3034,6 +3049,7 @@ check_xdepends() {              # check dependencies on host for X server option
       Return=1
     ;;
   esac
+
   # --gpu
   [ "$Sharegpu" = "yes" ] && {
     case "${1:-}" in
@@ -3045,6 +3061,7 @@ check_xdepends() {              # check dependencies on host for X server option
       ;;
     esac
   }
+
   # --rotate
   [ -n "$Rotation" ] && {
     case "$Xserver" in
@@ -3056,6 +3073,7 @@ check_xdepends() {              # check dependencies on host for X server option
       ;;
     esac
   }
+
   # --scale
   [ "$Scaling" ] && {
     case "${1:-}" in
@@ -3074,6 +3092,7 @@ check_xdepends() {              # check dependencies on host for X server option
       ;;
     esac
   }
+
   # --output-count
   [ "$Outputcount" != "1" ] && {
     case "$Xserver" in
@@ -3084,6 +3103,23 @@ check_xdepends() {              # check dependencies on host for X server option
       ;;
     esac
   }
+
+  # --vt
+  [ "$Newxvt" ] && {
+    case "${1:-}" in
+      --xorg|--weston|--weston-wayland|--kwin)
+        [ "$Xcrootless" = "yes" ] && {
+          $Message "${1:-} cannot claim a new virtual terminal (option --vt) with rootless X container (option --xc)."
+          Return=1
+        }
+      ;;
+      *)
+        $Message "${1:-} cannot claim a new virtual terminal (option --vt)."
+        Return=1
+      ;;
+    esac
+  }
+
   # --xc
   case "$Xcontainer" in
     yes)
@@ -3123,6 +3159,7 @@ check_xdepends() {              # check dependencies on host for X server option
       esac
     ;;
   esac
+
   # --xfishtank
   [ "$Xfishtank" = "yes" ] && {
     [ "$Xcontainer" = "no" ] && {
@@ -3140,6 +3177,7 @@ check_xdepends() {              # check dependencies on host for X server option
       ;;
     esac
   }
+
   # --xoverip
   [ "$Xoverip" = "yes" ] && {
     case "${1:-}" in
@@ -3157,21 +3195,6 @@ check_xdepends() {              # check dependencies on host for X server option
       ;;
       --weston|--kwin|--hostwayland)
         $Message "${1:-} does not support X over TCP (--xoverip)."
-      ;;
-    esac
-  }
-  # --vt
-  [ "$Newxvt" ] && {
-    case "${1:-}" in
-      --xorg|--weston|--weston-wayland|--kwin)
-        [ "$Xcrootless" = "yes" ] && {
-          $Message "${1:-} cannot claim a new virtual terminal (option --vt) with rootless X container (option --xc)."
-          Return=1
-        }
-      ;;
-      *)
-        $Message "${1:-} cannot claim a new virtual terminal (option --vt)."
-        Return=1
       ;;
     esac
   }
@@ -4392,7 +4415,7 @@ create_xcontainercommand() {    # option --xc: create docker command for X in co
 exec >> $Xinitlogfile 2>&1
 $(declare -f rocknroll)
 Timetosaygoodbyefile=$Timetosaygoodbyefile
-set -x
+
 mkdir -p -m 1777 /tmp/.X11-unix
 [ -S /X${Hostdisplaynumber} ] && ln -v -s /X$Hostdisplaynumber /tmp/.X11-unix/X$Hostdisplaynumber
 [ -S /${Hostwaylandsocket} ]  && ln -v -s /$Hostwaylandsocket \$XDG_RUNTIME_DIR/$Hostwaylandsocket
@@ -4440,6 +4463,7 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
   declare -f pspid
   declare -f rocknroll
   declare -f storeinfo
+  declare -f saygoodbye
   echo "$Messagefifofuncs"
   [ "$Xcontainer" = "yes" ] && {
     echo "storepid() { : ; }"
@@ -4760,6 +4784,7 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
   echo               "storeinfo xinitrc=ready"
   echo               ""
 
+  # --clipboard
   [ "$Shareclipboard" != "no" ] && {
     case "$Xserver" in
 #      --xpra*|--nxagent|--xwin|--runx) ;;         # have their own clipboard management
@@ -4767,10 +4792,20 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
       --hostdisplay) ;;                           # already same clipboard
       *)                                          # synchronizing between different X servers
         echo         "# option '-c, --clipboard': Run clipboard script "
-        echo         "bash $Clipboardrc"
+        echo         "bash $Clipboardrc &"
         echo         ""
       ;;
     esac
+  }
+
+  # --checkwindow
+  [ "$Checkforopenwindow" = "yes" ] && {
+    echo             "sleep 5"
+    echo             "while rocknroll; do"
+    echo             "  sleep 2"
+    echo             "  [ \"\$(xwininfo -root -children | grep -v '(has no name)' | awk '{print \$1}' | grep -c ^0x)\" = '0' ] && break"
+    echo             "done"
+    echo             "saygoodbye"
   }
 
   echo               "# wait for the end"
@@ -6768,6 +6803,8 @@ create_cmdrc() {                # This script runs as unprivileged user in conta
 
 $(declare -f storeinfo)
 $(declare -f saygoodbye)
+$(declare -f waitfortheend)
+$(declare -f rocknroll)
 $Messagefifofuncs
 Messagefile=$(convertpath share "$Messagefifo")
 Storeinfofile=\"$(convertpath share "$Storeinfofile")\"
@@ -6800,6 +6837,9 @@ debugnote \"cmdrc: Running container command:
 
     echo "
 storeinfo cmdexitcode=\$?
+"
+    [ "$Checkforopenwindow" = "yes" ] && echo "waitfortheend"
+    echo "
 export LD_PRELOAD=
 [ -h \"\$Homesoftlink\" ] && rm \$Homesoftlink
 saygoodbye cmdrc
@@ -8548,7 +8588,7 @@ parse_options() {               # parse cli options
   Longoptions="$Longoptions,hostwayland,kwin,weston"                                                                        # Wayland compositors without X
   Longoptions="$Longoptions,border::,dpi:,fullscreen,output-count:,rotate:,scale:,size:,xfishtank"                          # X/Wayland appearance options
   Longoptions="$Longoptions,clean-xhost,composite::,display:,keymap:,no-auth,vt::,westonini:,xhost::,xoverip,xtest::"       # X/Wayland config
-  Longoptions="$Longoptions,enforce-i,fallback::,preset:,pull::"                                                            # x11docker config
+  Longoptions="$Longoptions,checkwindow,enforce-i,fallback::,preset:,pull::"                                                # x11docker config
   Longoptions="$Longoptions,cachebasedir:,home::,homebasedir:,share:"                                                       # Host folders
   Longoptions="$Longoptions,alsa::,clipboard::,gpu::,lang::,printer::,pulseaudio::,webcam"                                  # Host integration features
   Longoptions="$Longoptions,backend:,env:,mobyvm,name:,no-entrypoint,no-setup,rootless::,runtime:,snap,workdir:"            # Container config
@@ -8681,6 +8721,7 @@ ${2:-${LANG:-}}" ; shift                                             # Locale/la
          --webcam)            Sharewebcam="yes" ;;                   # Webcam sharing
 
      #### Special options
+         --checkwindow)       Checkforopenwindow="yes" ;;            # Run container until all windows are closed
          --enforce-i)         ;;                                     # Run in bash interactive mode. Parsed at begin of script, nothing to do here.
          --fallback)          Fallback="${2:-yes}" ; shift ;;        # Allow/deny fallbacks for impossible options
       -i|--interactive)       Interactive="yes" ;;                   # Interactive terminal
@@ -9492,6 +9533,18 @@ check_options_interferences() { # check multiple option interferences, change se
     ;;
   esac
 
+  # --checkwindow
+  [ "$Checkforopenwindow" = "yes" ] && [ "$Xcontainer" = "no" ] && {
+    command -v xwininfo >/dev/null || {
+      note "Option --checkwindow needs 'xwininfo',
+  but xwininfo is not installed.
+  Fallback: Disabling option --checkwindow.
+  $Wikipackagesimage"
+      check_fallback
+      Checkforopenwindow="no"
+    }
+  }
+
   # --fullscreen is nonsense on tty at all. Avoids weston error on tty.
   [ "$Runsonconsole" = "yes" ] && Fullscreen="no"
 
@@ -10210,6 +10263,7 @@ declare_variables() {           # declare global variables
 
   # X and Wayland configuration
   Autochooseserver="yes"                          # --auto: automatic choice of X server (default)
+  Checkforopenwindow="no"                             # --checkwindow
   Cleanxhost="no"                                 # --clean-xhost: remove xhost access policies on host X
   Compositorerrorcodes="Failed to process Wayland|failed to create display|] fatal:"
   Desktopmode="no"                                # --desktop: image contains a desktop environment.
