improved dbus daemon startup. restrict PAM for su and sudo

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -291,7 +291,7 @@ OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.'
 }
 alertbox() {            # X alert box with title $1 and message $2
-  local Title Message
+  local Title= Message=
   Title=${1:-}
   Message=${2:-}
   
@@ -404,7 +404,7 @@ printstdout() {         # write something on stdout
   echo "$*" >&6
 }
 finish() {              # trap EXIT routine to clean up background processes and cache
-  local Pid Name Zeit Catlogfilepid
+  local Pid= Name= Zeit= Catlogfilepid=
   trap - EXIT
   verbose "terminating x11docker."
   
@@ -514,7 +514,7 @@ saygoodbye() {          # create file signaling watching processes to terminate
   }
 }
 mywatch() {             # repeat $1 untils its output changes
-  local Watchoutput
+  local Watchoutput=
   # --interval must be integer for centos and fedora watch despite contrary documentation in manpage
   verbose "Watching: sh -c '${1:-}'
   Current output:
@@ -533,9 +533,9 @@ watchpidlist() {        # watch list of important pids
   # terminate x11docker if a PID in $Pidwatchlist terminates
   # serves mainly watching X server, Wayland compositor, container and hostexe
   # echo PIDs to watch into >&9
-  local Pid
+  local Pid=
   while rocknroll ; do
-    read -t1 Pid <&9
+    read -t1 Pid <&9 ||:
     [ "$Pid" ] && {
       Pidwatchlist="$Pidwatchlist $Pid"
       verbose "watching $(ps --no-headers -p $Pid)"
@@ -568,7 +568,7 @@ waitfortheend() {       # wait for end of x11docker, optional for end of pid $1,
 waitforfilecreation() { # similar to inotify-wait: wait up to 15s for file $1 to be created
   # $1 file to wait for
   # $2 time to wait. default: 15s. possible: infinity
-  local Zeit Warten Dauer Count
+  local Zeit= Warten= Dauer= Count=
   Zeit=$(date +%s)
   verbose "Waiting for file creation of ${1:-}"
   case ${2:-} in
@@ -617,7 +617,7 @@ waitforlogentry() {     # wait for entry $3 in logfile $2 of application $1
   # $1 is the application we are waiting for to be ready
   # $2 points to logfile
   # $3 keyword to wait for 
-  local Zeit Warten Dauer Count
+  local Zeit= Warten= Dauer= Count=
   Zeit=$(date +%s)
   Warten=60
   while ! cat "${2:-}" | grep -q "${3:-}" ; do
@@ -640,11 +640,11 @@ storepid () {           # store pids and names of background processes in file $
   # for use on exit / with trap to clean up with background processes
   # this subroutine has a twin in xinitrc
   echo ${1:-} ${2:-} >> $Bgpidfile
-  disown ${1:-} 2>/dev/null
   verbose "stored background pid ${1:-} of ${2:-}"
+  disown ${1:-} 2>/dev/null || verbose "can not disown ${1:-} ${2:-}"
 }
 no_xhost() {            # remove any access to X server granted by xhost
-  local Line
+  local Line=
   xhost
   xhost | tail -n +2  /dev/stdin | while read -r Line ; do  # read all but the first line (header)
     xhost -$Line                                         # disable every entry
@@ -665,7 +665,7 @@ mkfile() {              # create file $1 owned by $Hostuser
 }
 depends() {             # check dependencies on host for X server option $1
   # Return 1 if something is missing
-  local Return Message
+  local Return= Message=
   Return="0"
   case $Autochooseserver in
     yes) Message=verbose ;;
@@ -767,7 +767,7 @@ depends() {             # check dependencies on host for X server option $1
   return ${Return:-0}
 }
 checkorphaned() {       # --cleanup : check for non-removed containers and left cache files
-  local Orphanedcontainers Orphanedfolders Line
+  local Orphanedcontainers= Orphanedfolders= Line=
   note "x11docker will check for orphaned containers from earlier sessions.
   This can happen if docker was not closed successfully. 
   x11docker will look for those containers and will clean up x11docker cache.
@@ -815,7 +815,7 @@ installer() {           # --install, --update, --update-master, --remove: Instal
   #   - download and install latest master version from github
   # --remove
   #   - remove installed files
-  local X11dockericonfile Key1 Key2 Oldversion Newversion
+  local X11dockericonfile= Key1= Key2= Oldversion= Newversion=
   export PATH="$PATH:/usr/local/bin"  # avoid bug on opensuse where root does not have this in $PATH. Will become obsolete as new default is /usr/bin
   
   # Prepairing
@@ -985,7 +985,7 @@ escapestring() {        # escape special chars of $1
   echo "${1:-}" | LC_ALL=C sed -e 's/[^a-zA-Z0-9,._+@=:/-]/\\&/g; 1{$s/^$/""/}; 1!s/^/"/; $!s/$/"/'
 }
 writeaccess() {         # check if useruid $1 has write access to folder $2
-  local dirVals gMember IFS
+  local dirVals= gMember= IFS=
   if IFS=$'\t' read -a dirVals < <(stat -Lc "%U	%G	%A" "${2:-}") && (
     ( [ "$(id -u $dirVals)" == "${1:-}" ] && [ "${dirVals[2]:2:1}" == "w" ] ) ||
     ( [ "${dirVals[2]:8:1}" == "w" ] ) ||
@@ -1219,6 +1219,7 @@ Initsystem="tini"                               # options --systemd --openrc --r
 Sharecgroup="no"                                # options --systemd, --cgroup: share /sys/fs/cgroup
 Dbuslaunch="no"                                 # option '--dbus': run image command with dbus-launch
 Dbusdaemon="no"                                 # option '--dbus-dameon': set up dbus daemon in container
+Tinibinary=""                                   # option --tini/default: binary for tini; either /usr/bin/docker-exec or provided by user in ...share/x11docker
 
 # X authentication
 Xauthentication="yes"                           # option '--no-auth' use cookie authentication yes/no
@@ -3432,7 +3433,7 @@ WantedBy=multi-user.target
 Description=x11docker watch service
 [Service]
 Type=simple
-ExecStart=/bin/sh -c 'while sleep 1; do systemctl is-active x11docker-startcmd >/dev/null || { su --shell /bin/sh $Benutzer -c echo timetosaygoodbye >>$Cshare/timetosaygoodbye ; systemctl halt ; } ; [ -s $Cshare/timetosaygoodbye ] && systemctl halt ; done'
+ExecStart=/bin/sh -c 'while sleep 1; do systemctl is-active x11docker-startcmd >/dev/null || { echo timetosaygoodbye >>$Cshare/timetosaygoodbye ; systemctl halt ; } ; [ -s $Cshare/timetosaygoodbye ] && systemctl halt ; done'
 [Install]
 WantedBy=x11docker.target
 " >> $Systemdwatch
@@ -3493,7 +3494,12 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   
       [ "$Benutzeruid" = "0" ]     && Sudouser="yes"
       [ "$Sudouser" = "yes" ]      && Adminusercaps="yes"
-      [ "$Dbusdaemon" = "yes" ]    && Switchcontainerusercaps="yes"
+      [ "$Dbusdaemon" = "yes" ]    && {
+        case $Sharewayland in
+          yes) Switchcontaineruser="yes" ;;
+          no)  Switchcontainerusercaps="yes" ;;
+        esac
+      }
       
       case $Initsystem in
         none|tini)
@@ -3758,7 +3764,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "}"
   echo ""
   
-  [ "$Tinibinary" ] && echo "Tini=\"$Cshare/tini --\""
+  [ "$Tinibinary" ] && echo "Tini=\"$Cshare/tini --\"" || echo "Tini="
   case $Noentrypoint in
     yes) echo "Entrypoint=" ;;
     no)
@@ -3849,7 +3855,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   }
   echo   "  echo 'export HOME=\"$Benutzerhome\"'"
   echo   "  echo 'cd \"\$HOME\"'"
-  [ "$Workdir" ] && echo "  echo 'cd $Workdir'"
+  [ "$Workdir" = "/tmp" ] || echo "  echo 'cd $Workdir'"
 
   echo   "  echo ''"
   
@@ -3980,7 +3986,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "  sleep 0.2"
   echo "  docker exec $Containername sh -c : && { echo 'x11docker: container is up and running.' ; break ; } || echo \"x11docker: container not ready on \$Count. attempt, trying again.\" "
   echo "done"
-  echo "cat $Dockerlogfile | grep -E 'Error response from daemon|OCI runtime exec' && exit 1"  # repeat possible error message to make it visible in error() after verbose Count loop
+  echo "cat $Dockerlogfile | grep -v grep | grep -E 'Error response from daemon|OCI runtime exec' && exit 1 ||:"  # repeat possible error message to make it visible in error() after verbose Count loop
   echo ""
 
   
@@ -4003,8 +4009,8 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   [ "$Debug" = "yes" ] && echo "set -x"
   echo "echo 'x11docker: setup as root in container'"
   echo ""
-  #echo "set -x"
   
+  # prepare X environment
   echo "# create some system dirs with needed permissions"
   echo "mkdir -v -p /var/lib/dbus /var/run/dbus"
   echo "mkdir -v -p -m 1777 /tmp/.ICE-unix /tmp/.X11-unix /tmp/.font-unix"
@@ -4019,6 +4025,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "echo \"x11docker: container system ID: \$Containersystem\""
   echo ""
   
+  # custom environment variables
   IFS=$'\n'
   for Line in $Customenvironment ; do
     [ "$Line" ] && echo "export $Line" 
@@ -4026,6 +4033,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   IFS=$' \t\n'
   echo ""
   
+  # create container user
   echo "# create user entry in /etc/passwd (and delete possibly existing same uid)"
   echo "getent passwd | grep -v \$(getent passwd $Benutzeruid || echo USERNOTFOUND) > /tmp/passwd"
   echo "echo $Benutzerpasswdentry >> /tmp/passwd"
@@ -4064,15 +4072,16 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   [ "$Benutzerhosthome" = "no" ] && echo "mkdir -v -m 777 /fakehome"
   echo ""
   
+  # sudo configuration
   echo "# create /etc/sudoers, delete /etc/sudoers.d. Overwrite possible sudo setups in image."
-  echo "rm -R /etc/sudoers.d"
+  echo "rm -v -R /etc/sudoers.d"
   echo "echo '# /etc/sudoers created by x11docker' > /etc/sudoers"
   echo "echo 'root ALL=(ALL) ALL'                 >> /etc/sudoers"
   case $Sudouser in
     yes)
       echo "echo '$Benutzer ALL=(ALL) ALL'        >> /etc/sudoers"
     ;;
-    no) echo "rm /etc/sudoers" ;;
+    no) echo "rm -v /etc/sudoers" ;;
   esac
   echo ""
   
@@ -4080,10 +4089,11 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   [ "$Sudouser" = "no" ] && {
     echo "# restrict PAM configuration of su and sudo"
     echo "echo 'auth sufficient pam_rootok.so' > /etc/pam.d/su  # allow root to switch user without a password" 
-    echo "rm /etc/pam.d/sudo"
+    echo "rm -v /etc/pam.d/sudo"
     echo ""
   }
 
+  # --gpu with closed source nvidia driver
   [ "$Nvidiadriver" ] && {
     echo "Installationwillsucceed=maybe"
     echo "ldd 2>&1 | grep 'musl libc' && {"
@@ -4124,37 +4134,16 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
     echo ""
   }
   
+  # prepare container depending on container init system
   case $Initsystem in
     systemd) ;;
     *)
       echo "# systemd dbus service causes shutdown after 10s if system runs without systemd. WTF"
-      echo "rm /etc/dbus-1/system.d/org.freedesktop.systemd1.conf /usr/share/dbus-1/system-services/org.freedesktop.systemd1.service /usr/share/dbus-1/services/org.freedesktop.systemd1.service"
+      echo "rm -v /etc/dbus-1/system.d/org.freedesktop.systemd1.conf /usr/share/dbus-1/system-services/org.freedesktop.systemd1.service /usr/share/dbus-1/services/org.freedesktop.systemd1.service"
     ;;
   esac
   case $Initsystem in
-    tini|none)
-      case $Dbusdaemon in
-        yes)
-          echo "echo 'x11docker: starting dbus system daemon'"
-          echo "dbus-daemon --system --fork"
-          echo "for Count in 1 2 3 4 5 6 7 8 9 10 ; do"
-          echo "  [ -e /run/dbus/system_bus_socket ] && break"
-          echo "  sleep 0.1"
-          echo "done"
-          [ "$Nonewprivileges" = "yes" ] && {
-            echo "# support for dbus daemon with no-new-privileges"
-            echo "[ -x /usr/lib/policykit-1/polkitd ] && {"
-            echo "  echo 'x11docker: starting polkitd'"
-            echo "  /usr/lib/policykit-1/polkitd &"
-            echo "}"
-            echo "[ -x /usr/lib/accountsservice/accounts-daemon ] && {"
-            echo "  echo 'x11docker: starting accounts-daemon'"
-            echo "  /usr/lib/accountsservice/accounts-daemon &"
-            echo "}"
-          } ||:
-        ;;
-      esac
-    ;;
+    tini|none) ;;
     systemd)
       echo "# to be sure, allow/unmask most important services"
       echo "systemctl unmask systemd-logind dbus"
@@ -4223,7 +4212,79 @@ start() {
   esac
   echo "# disable getty in inittab" 
   echo "sed -i 's/.*getty/##getty disabled by x11docker## \0/' /etc/inittab"
+  
+  # start dbus daemon and dbus services
+  case $Dbusdaemon in
+    yes)
+      warning "Will run DBus services as root in container.
+  If the image contains malicious applications started by DBus service files,
+  they may abuse their root privileges and may try to break out of container."
+  
+      case $Initsystem in
+        systemd) ;;
+        *)
+          echo "echo x11docker: DBus: removing failing services"
+          echo "for Line in \$(find /usr/share/dbus-1/system-services -type f); do"
+          echo "  Name=\"\$(cat \$Line | grep Name= | cut -d= -f2)\""
+          echo "  case \$Name in"
+          echo "    org.freedesktop.UPower|org.freedesktop.login1|org.freedesktop.ConsoleKit|org.freedesktop.systemd1|org.freedesktop.resolve1|org.freedesktop.network1|org.freedesktop.timedate1)"
+          echo "      rm -v \$Line"
+          echo "    ;;"
+          echo "  esac"
+          echo "done"
+            
+          echo "echo 'x11docker: DBus: starting dbus system daemon'"
+          echo "dbus-daemon --system --fork"
+          echo "for Count in 1 2 3 4 5; do"
+          echo "  [ -e /run/dbus/system_bus_socket ] && break"
+          echo "  sleep 0.1"
+          echo "done"
+          echo "[ -e /run/dbus/system_bus_socket ] || echo x11docker WARNING: DBus startup seems to have failed. system bus socket not found."
+          
+          [ "$Nonewprivileges" = "yes" ] && {
+            echo "# support for dbus daemon with no-new-privileges"
+            echo "waitforservice() {"
+            echo "  # wait for dbus service \$1 to appear in dbus service list"
+            echo "  for Count in 1 2 3 4 5 6 7 8 9 10 ; do"
+            echo "    dbus-send --system --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep -q \$1 && break"
+            echo "    echo x11docker: DBus: waiting for \$1 to be ready"
+            echo "    sleep 0.1"
+            echo "  done"
+            echo "}"
+            echo "# start polkitd as first service"
+            echo "[ -x /usr/lib/policykit-1/polkitd ] && {"
+            echo "  echo 'x11docker: DBus: starting PolicyKit'"
+            echo "  /usr/lib/policykit-1/polkitd &"
+            echo "  /usr/lib/dbus-1.0/dbus-daemon-launch-helper org.freedesktop.PolicyKit1.service"
+            echo "  waitforservice org.freedesktop.PolicyKit1"
+            echo "}"
+            echo "[ -x /usr/lib/accountsservice/accounts-daemon ] && {"
+            echo "  echo 'x11docker: DBus: starting Accounts daemon'"
+            echo "  /usr/lib/accountsservice/accounts-daemon &"
+            echo "  /usr/lib/dbus-1.0/dbus-daemon-launch-helper org.freedesktop.Accounts.service"
+            echo "  waitforservice org.freedesktop.Accounts"
+            echo "}"
+            echo "# start all other dbus system services (except some failing candidates)"
+            echo "for Line in \$(find /usr/share/dbus-1/system-services -type f); do"
+            echo "  Name=\"\$(cat \$Line | grep Name= | cut -d= -f2)\""
+            echo "  Command=\"\$(cat \$Line | grep Exec= | cut -d= -f2)\""
+            echo "  case \$Name in"
+            echo "    org.freedesktop.PolicyKit1|org.freedesktop.Accounts) ;;"
+            echo "    *)"
+            echo "      echo x11docker: DBus: starting service \$Name: \$Command"
+            echo "      sh -c \"\$Command\" &"
+            echo "      /usr/lib/dbus-1.0/dbus-daemon-launch-helper \$Name"
+            echo "      waitforservice \$Name"
+            echo "    ;;"
+            echo "  esac"
+            echo "done"
+          } ||:
+        ;;
+      esac
+    ;;
+  esac
 
+  # --lang: language locale
   [ "$Langwunsch" ] && {
     echo "echo \"x11docker: Searching for language locale matching $Langwunsch\""
     echo "Locales=\"\$(locale -a)\""
@@ -4264,20 +4325,27 @@ start() {
     echo ""
   }
   
+  # --pulseaudio check
   [ "$Pulseaudio" = "yes" ] && {
     echo "command -v pulseaudio >/dev/null || echo \"x11docker ERROR: pulseaudio not found in image (option --pulseaudio)\""
     echo ""
   }  
   
+  # --runasroot command added here
   [ "$Runasroot" ] && {
     echo "# custom setup root command added with option --runasroot"
     echo "$Runasroot"
   }
   
+  # message to x11docker.CMD.sh
   echo ":> /x11docker.setupready"
+  
   [ "$Switchcontaineruser" = "yes" ] && {   # if "no", x11docker.CMD.sh is executed in command line $Dockercommand
     case $Initsystem in
-      tini|none)
+      none)
+        echo "/bin/su - -s /bin/sh $Benutzer $Cshare/x11docker.CMD.sh" 
+      ;;
+      tini)
         echo "exec /bin/su - -s /bin/sh $Benutzer $Cshare/x11docker.CMD.sh" 
       ;;
       runit|openrc|sysvinit) 
@@ -4794,7 +4862,7 @@ $(tail $Dockerlogfile)"
           }
         }
         ps -p $Xpraclientpid >/dev/null 2>&1 && kill $Xpraclientpid
-        #[ -n "$Xpraclientpid" ] && [ "$Desktopmode" = "yes" ] && [ "$Xpracrashcount" = "0" ] && saygoodbye ### FIXME does not terminate x11docker
+        [ -n "$Xpraclientpid" ] && [ "$Desktopmode" = "yes" ] && [ "$Xpracrashcount" = "0" ] && saygoodbye ### FIXME does not terminate x11docker
         verbose "starting Xpra client"
         [ -n "$Xpraclientpid" ] && note "Restarting Xpra client."
         $Mksu "env $Hostxenv XPRA_PADDING_COLORS='0,0.2,1' $Xpraclientcommand" >> $Xpraclientlogfile 2>&1 &
@@ -4977,13 +5045,13 @@ $(tail $Compositorlogfile)"
 
 ######### ToDo notes for development
 todo() {
-# --systemd now needs SYS_BOOT. check for content of $Timetosaygoodbye fails? watch service fails?
-# check password frontend check: runs gksu although sudo is available
-# xpraloop: saygoodbye does not terminate
+# mkfifo for warning() and note() to support messages from within container?
 # BUG opensuse/arch: issues with x11docker/fluxbox, background missing, sometimes no context menu. where is the difference?
+# run several code pathes with --debug
+# --dbus-system: find way to start dbus services with dbus itself
 
-# --no-init no-new-privileges switchuser: exec fails, but why? currently not switching user, issue cannot happen.
-# replace su with capsh? (missing in alpine) But how to trigger logind?
+# --no-init no-new-privileges switchuser: exec fails, but why?
+# check out capsh. replace su with capsh? (missing in alpine) But how to trigger logind?
 # --hostuser: mkfifo to wayland socket possible?
 # --group-add: compare host and container GID? warn if group misses in container, or create it?
 # work on traperror(). 'set -u' possible without a stop?
