v4.2.1 release
## Added
 - Forward `stdin` of x11docker to container command with a named pipe/fifo.
## Changed
 - `x11docker-gui`: Use stdin for kaptain grammar transmission. Don't use cache.
 - `--dbus-system`: Don't create `--tmpf /tmp --tmpfs /run --tmpfs /var/run --tmpfs /run/lock`.
   [(#43)](https://github.com/mviereck/x11docker/issues/43)
 - Some internal improvements for faster startup and shutdown.
### Fixed
 - `x11docker-gui`: fixed x11docker startup failure due to changed stdout output.

diff --git a/x11docker-gui b/x11docker-gui
--- a/x11docker-gui
+++ b/x11docker-gui
@@ -1,8 +1,8 @@
 #! /bin/bash
 #########################################
-## GUI for x11docker 
-## Published under MIT licence
-## Uses 'kaptain' to provide a GUI
+# GUI for x11docker 
+# Published under MIT licence
+# Uses 'kaptain' to provide a GUI
 # https://github.com/mviereck/x11docker
 #########################################
 
@@ -27,10 +27,9 @@ warning() {
 export PATH="$PATH:/usr/local/bin" # can miss if executed as root
 
 # Try to find x11docker
-command -v x11docker >/dev/null && X11docker_exe="x11docker"                                              # look whether x11docker is in $PATH
-[ -z "$X11docker_exe" ] && [ -e "$PWD/x11docker" ] && X11docker_exe="$PWD/x11docker"                      # otherwise, look in current directory
-[ -z "$(command -v $X11docker_exe)" ] && [ -e "$PWD/x11docker" ] && X11docker_exe="bash $PWD/x11docker"   # if not marked as executeable, run with bash
-[ -z "$X11docker_exe" ] && error "x11docker not found"
+X11docker_exe="${0%-gui}"                                            # look at path of current x11docker-gui
+[ ! -f "$X11docker_exe" ] && X11docker_exe="$(command -v x11docker)" # look whether x11docker is in $PATH
+[ ! -f "$X11docker_exe" ] && error "x11docker not found"
 Version="$($X11docker_exe --version)"
 
 # check logged-in user
@@ -79,31 +78,16 @@ GPU="!"
 DESKTOP="!"
 #####################
 
-# check temporary folder
-[ -d "$Lognameuserhome/.cache/x11docker" ] && Tmpdir="$Lognameuserhome/.cache/x11docker/x11docker-gui"
-[ -z "$Tmpdir" ] && [ -n "$TMPDIR" ] &&       Tmpdir="$TMPDIR/x11docker-gui"
-[ -z "$Tmpdir" ] &&                           Tmpdir="/tmp/x11docker-gui"
-mkdir -p "$Tmpdir"
-chown "$Lognameuser" "$Tmpdir"
-
-# temporary files
-Cookie=".$(mcookie | cut -c1-4)"
-[ "$1" = "--icon" ] && Cookie=""
-X11docker_logo="$Tmpdir/x11docker.png$Cookie"
-X11docker_kaptn="$Tmpdir/x11docker.kaptn$Cookie"
-touch "$X11docker_logo"
-chown "$Lognameuser" "$X11docker_logo"
-touch "$X11docker_kaptn"
-chown "$Lognameuser" "$X11docker_kaptn"
-
 ## needed for github screenshots only
-CONTAINERUSER="\\\$USER"
-CONTAINERUSERHOME="/home/\\\$USER"
+#CONTAINERUSER="\\\$USER"
+#CONTAINERUSERHOME="/home/\\\$USER"
 
 # check list of available window managers
 Wm_all="$($X11docker_exe --wmlist)"
-for wm in $Wm_all ; do
-  command -v $wm >/dev/null 2>&1 && [ -z "$(echo $HOSTWM | grep $wm)" ] && HOSTWM="$HOSTWM\"$wm\","
+for Wm in $Wm_all ; do
+  command -v "$Wm" >/dev/null && {
+    grep -q "$Wm" <<< "$HOSTWM" || HOSTWM="$HOSTWM\"$Wm\","
+  }
 done
 
 HOSTWM="$HOSTWM\"\",\"auto\",\"none\""
@@ -116,18 +100,11 @@ done < <(cat /proc/asound/cards | grep ':' | cut -d[ -f2 | cut -d] -f1)
 ALSALIST="$ALSALIST\"\""
 
 # if docker can run without password prompt, create list of available named images
-sudo -n docker images >/dev/null 2>&1 && Sudo="sudo -n" || Sudo=""
-$Sudo   docker images >/dev/null 2>&1 && {
-  while read -r Image ; do
-    Image="$(echo $Image | cut -d' ' -f1):$(echo $Image | cut -d' ' -f2)"
-    [ "$(echo $Image | cut -d: -f2)" = "<none>" ] && Image=$(echo $Image | cut -d: -f1)
-    case $Image in
-      "REPOSITORY:TAG"|"<none>")     ;;
-      *) IMAGELIST="$IMAGELIST,\"$Image \"" ;;
-    esac
-  done < <($Sudo docker images)
-}
-[ "$(echo $IMAGELIST | cut -c1)" = "," ] && IMAGELIST="\"\"$IMAGELIST"
+sudo -n echo 2>/dev/null && Sudo="sudo -n" || Sudo=""
+while read -r Image ; do
+    Image="${Image%:<none>}"
+    IMAGELIST="$IMAGELIST,\"$Image \""
+done < <($Sudo docker images --format "{{.Repository}}:{{.Tag}}" | sort)
 
 Hostlangland=$(echo $LANG | cut -d. -f1)
 Langcombo="\"$Hostlangland\""
@@ -155,6 +132,10 @@ Keymapscombo=${Keymapscombo:-\"\"}
 for Line in $Keymaps; do Keymapscombo="$Keymapscombo,\"$Line\"" ; done
 
 
+# Look for icon
+[ -e /usr/share/icons/hicolor/64x64/apps/x11docker.png ]       && X11docker_icon=/usr/share/icons/hicolor/64x64/apps/x11docker.png
+[ -e /usr/local/share/icons/hicolor/64x64/apps/x11docker.png ] && X11docker_icon=/usr/local/share/icons/hicolor/64x64/apps/x11docker.png
+
 Kaptain_grammar='#! /usr/bin/kaptain
 start "Run GUI applications in docker images - x11docker '$Version'"  -> options buttons;
   options:beside              -> frameleft frameright;
@@ -163,7 +144,7 @@ start "Run GUI applications in docker images - x11docker '$Version'"  -> options
     
   choose_image_framed:framed -> choose_image;
   choose_image "Choose docker image"                                                        -> logo_imageorexe dockerimage;
-    logo_imageorexe:beside                                                                  -> @icon("'$X11docker_logo'") imageorexe ;
+    logo_imageorexe:beside                                                                  -> @icon("'$X11docker_icon'") imageorexe ;
       imageorexe                                                                            -> image | exe | xonly;
         image:beside     "Run docker image in segregated X server"                          -> "-- " security_dialog;
         exe              "--exe: Start host application in another X server"                -> "--exe -- ";
@@ -171,8 +152,8 @@ start "Run GUI applications in docker images - x11docker '$Version'"  -> options
     dockerimage          "docker image [and command] to run:"                               -> @combow('$IMAGELIST');
   
   choose_xserver_framed:framed -> choose_xserver;
-  choose_xserver -> xserverbla xservercombo desktop gpu wm wayland;
-    xserverbla:beside "Choose X server" -> @fill xinfobutton xdependenciesbutton ;
+  choose_xserver "Choose X server" -> xserverbla xservercombo desktop gpu wm wayland;
+    xserverbla:beside -> @fill xinfobutton xdependenciesbutton ;
     xservercombo -> s/(:.*$)/ / @combo(
         ": Automatically choose X server (regards --desktop, --gpu and --wayland)",
         "--xpra:             Show container application windows on your main desktop",
@@ -734,34 +715,26 @@ buttons :horizontal ->  run runxterm preview desktop_starter orphanedcheck help 
   runxterm -> @dump("xterm -hold -e '"'"'",x11docker,"'"'"'")="Run in xterm";
 '
 
-##### create files
+# remove double whitespaces
+Kaptain_grammar="$(sed -e 's/  */ /g' <<< "$Kaptain_grammar")"
 
-# copy icon in $Tmpdir, if available
-cp /usr/share/icons/hicolor/64x64/apps/x11docker.png       $X11docker_logo 2>/dev/null || :> $X11docker_logo
-cp /usr/local/share/icons/hicolor/64x64/apps/x11docker.png $X11docker_logo 2>/dev/null
-
-# store created grammar in a file
-echo "$Kaptain_grammar" | sed -e 's/  */ /g' >> "$X11docker_kaptn"
-
-#### check options
+# check options
 Verbose="--silent"
 case "$1" in
   --icon)
-    echo "x11docker-gui does no longer create an icon on demand."
+    echo "x11docker-gui does no longer create an icon on demand." >&2
     exit 1
   ;;
   -v|--verbose) 
     kaptain --version
     Verbose="--verbose" 
-    echo "x11docker-gui: created kaptain grammar:
-    
-$(cat $X11docker_kaptn)
-
-"
+    echo "x11docker-gui: created kaptain grammar:"
+    printf "%s" "$Kaptain_grammar"
+    echo ""
   ;;
 esac
 
-#### check executeables
+# check kaptain version
 
 command -v kaptain >/dev/null && Hostkaptain="yes" || Hostkaptain="no"
 
@@ -769,7 +742,6 @@ command -v kaptain >/dev/null && Hostkaptain="yes" || Hostkaptain="no"
   # regard kde3-kaptain from openSUSE KDE:KDE3 repository
   # up to date from decades ago is 0.73
   warning " Your version 0.72 of kaptain is outdated.
-  Most probably startup will fail.
   kaptain version 0.73 with important bugfixes is available at:
     https://github.com/mviereck/kaptain
   Output of 'kaptain --version':
@@ -778,25 +750,23 @@ $(kaptain --version)
   Hostkaptain="no"
 }
 
-#### Run kaptain
-
+# Run kaptain either from host or with x11docker/kaptain image
 case $Hostkaptain in
   yes)
     [ "$Verbose" = "--verbose" ] && {
-       X11docker_command="$(kaptain "$X11docker_kaptn")" ||:
-    } || X11docker_command="$(kaptain "$X11docker_kaptn" 2>/dev/null)"
+         X11docker_command="$(kaptain <<< "$Kaptain_grammar")" ||:
+    } || X11docker_command="$(kaptain 2>/dev/null <<< "$Kaptain_grammar")"
   ;;
   no)
     warning "Did not find executeable 'kaptain'.
 If your distribution does not provide package kaptain (>=0.73), look at
 kaptain repository:   https://github.com/mviereck/kaptain
 Fallback: Will try to use image x11docker/kaptain."
-    { read -r containerID ; read -r X11docker_command ;} < <(x11docker --hostdisplay --no-init --clipboard $Verbose --stdout --env HOME="$CONTAINERUSERHOME" --sharedir $X11docker_kaptn -- --volume="$X11docker_logo":"$X11docker_logo":ro --volume="$CONTAINERUSERHOME":"$CONTAINERUSERHOME":ro x11docker/kaptain $X11docker_kaptn)
+#    read -r X11docker_command < <(printf "%s" "$Kaptain_grammar" | bash $X11docker_exe --hostdisplay --size 980x720 --no-init --clipboard $Verbose --stdout --sharedir "$X11docker_icon" --env HOME="$CONTAINERUSERHOME" -- --volume="$CONTAINERUSERHOME":"$CONTAINERUSERHOME":ro x11docker/kaptain)
+    read -r X11docker_command < <(bash $X11docker_exe --hostdisplay --size 980x720 --no-init --clipboard $Verbose --stdout --sharedir "$X11docker_icon" --env HOME="$CONTAINERUSERHOME" -- --volume="$CONTAINERUSERHOME":"$CONTAINERUSERHOME":ro x11docker/kaptain <<< "$Kaptain_grammar")
   ;;
 esac
 
-#### clean up and run x11docker
-
-rm "$X11docker_logo" "$X11docker_kaptn"
+# run x11docker
 echo $X11docker_command
 eval $X11docker_command
