V3.6.3.9 code cleanup
# 25.10.2017 V3.6.3.9   show error messages regardless of --silent
#                       change "sudo" to "sudo -E", needed for OpenSUSE
#                       code cleanup, some improved messages

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -8,9 +8,12 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # https://github.com/mviereck/x11docker
 
-Version="3.6.3.8"
+Version="3.6.3.9"
 
 changelog() {
+# 25.10.2017 V3.6.3.9   show error messages regardless of --silent
+#                       change "sudo" to "sudo -E", needed for OpenSUSE
+#                       code cleanup, some improved messages
 # 25.10.2017 V3.6.3.8   fedora: set --ipc and --trusted for --hostdisplay only
 # 25.10.2017 V3.6.3.7   bugfix --hostdisplay on fedora: use host cookie, custom cookie is rejected
 # 24.10.2017 V3.6.3.6   --wmlist: new option to retrieve list of window managers, used by x11docker-gui
@@ -86,6 +89,7 @@ changelog() {
 todo() {
 # further checks on centos 7, manjaro and mageia
 # rework $Getroot $Sudo $Pkexec, new situation with setsid in dockerrc
+# check out solution for 'setsid sudo' to allow 'sudo docker' directly again
 
 # check all FIXME 
 # new option --printer: xpra printer forwarding?
@@ -179,8 +183,8 @@ Shared folders, GPU, clipboard and sound options:
  -p, --pulseaudio      Sound with pulseaudio over tcp. Needs
                        'pulseaudio' to be installed on host and in image.
  -g, --gpu             Hardware accelerated OpenGL rendering. Shares files in
-                       /dev/dri. Works best with open source drivers (mesa)
-                       installed on host and in image. Closed source drivers 
+                       /dev/dri. Works best with open source drivers installed
+                       on host and OpenGL/Mesa in image. Closed source drivers 
                        need to be the very same on host and in image.
                        Degrades container isolation. Container access to GPU.
 
@@ -250,7 +254,7 @@ Screensize and appearance options:
                        
 Advanced options:
  -v, --verbose         Be verbose. (Shows logfiles).
-     --silent          Do not show any terminal messages.
+     --silent          Do not show terminal messages (except errors).
      --stdout          Show stdout of container applications.
      --stderr          Show stderr of container applications.
  -E, --waylandenv      Set some environment variables summoning some toolkits
@@ -348,9 +352,9 @@ error() {               # show error messages on stderr and exit
   please report at https://github.com/mviereck/x11docker"
   echo "
 $(tput setaf 1)x11docker ERROR$(tput sgr0) $Message
-" >&3
-  [ -n "$Hostxenv" ] && [ "$Xserver" != "Xorg" ] && local $Hostxenv
-  [ ! -s "$Timetosaygoodbye" ] && [ "$Silent" != "yes" ] && [ -n "$DISPLAY" ] && {
+" >&2
+  [ -n "$Hostxenv" ] && [ "$Xserver" != "Xorg" ] && export $Hostxenv
+  [ ! -s "$Timetosaygoodbye" ] && [ -n "$DISPLAY" ] && {
     command -v xmessage >/dev/null && {
       echo "x11docker ERROR: $Message" | xmessage -file - -default okay
       :
@@ -462,8 +466,9 @@ installer() {           # --install, --update, --remove: Installer for x11docker
 " > /usr/share/applications/x11docker.desktop
       } || note "Did not create desktop entry for x11docker-gui"
       command -v kaptain >/dev/null || warning "Could not find 'kaptain' for x11docker-gui.
-  Please install 'kaptain'. If your distributions does not provide it, look at
-  kaptain repository:  https://github.com/mviereck/kaptain"
+  Please install 'kaptain'. 
+  If your distributions does not provide it, look at kaptain repository:  
+    https://github.com/mviereck/kaptain"
 
       echo "Storing README.md and LICENSE.txt in /usr/share/doc/x11docker"
       mkdir -p /usr/share/doc/x11docker && {
@@ -1193,13 +1198,26 @@ Parsed options: $Parsedoptions"
   [ "$Tty" = "no" ] && [ -z "$Hostdisplay" ] && warning "Environment variable DISPLAY is empty, but
   it seems x11docker was started within X, not from console. 
   Please set DISPLAY and XAUTHORITY.
-  If you have started x11docker with sudo, it may be configured to unset
-  X environment variables. You can trick it out, for example with
+  If you have started x11docker with sudo, sudo may be configured to unset
+  X environment variables. It may work if you run x11docker with
+    sudo -E x11docker [...]
+  If your system does not support 'sudo -E', you can try
     sudo env DISPLAY=\$DISPLAY XAUTHORITY=\$XAUTHORITY x11docker [...]
   Otherwise, you can use tools like gksu/gksudo/kdesu/kdesudo/lxsu/lxsudo."
   
-  # option '--pulseaudio': find a free tcp port
+  # option '--pulseaudio'
   [ "$Pulseaudio" = "yes" ] && {
+    command -v pulseaudio >/dev/null && {
+      note "Option --pulseaudio needs pulseaudio to be 
+      installed in image, too."
+    } || {
+      note "pulseaudio not found on your host.
+  Need pulseaudio to provide sound with --pulseaudio.
+  Fallback: Disabling option --pulseaudio."
+      Pulseaudio="no"
+    }
+  }
+  [ "$Pulseaudio" = "yes" ] && { # find a free tcp port
     read -r Lowerport Upperport < /proc/sys/net/ipv4/ip_local_port_range
     while : ; do
       Pulseaudiotcpport="$(shuf -i $Lowerport-$Upperport -n 1)"
@@ -1232,7 +1250,8 @@ Parsed options: $Parsedoptions"
     Hostwayland=""
   }
   
-  while read -r Line; do  # estimate host system
+  # determine host system
+  while read -r Line; do  
     [ "$(echo $Line | cut -c1-3)" = "ID=" ] && Hostsystem=$(echo $Line | cut -d= -f2 | cut -d'"' -f2)
   done < <(cat /etc/os-release | grep 'ID=')
 }
@@ -1400,7 +1419,7 @@ Parsed options: $Parsedoptions"
         yes) Xserver="Xorg" ;;
         no)  Xserver="Hostdisplay" ;;
       esac
-      warning "Did not find a satisfying solution to provide hardware
+      note "Did not find a satisfying solution to provide hardware
   acceleration with option --gpu. Best solutions to provide security:
   Either install: xpra weston Xwayland xdotool
   or install: weston Xwayland
@@ -1453,11 +1472,17 @@ Parsed options: $Parsedoptions"
     Xserver="Xorg"
   }
   
+  [ "$Autochooseserver" = "yes" ] && note "Using X server $Xserver"
+
   case $Xserver in 
     Xorg|Xdummy)
       command -v "Xorg" >/dev/null 2>&1 || error "Could not find executable 'Xorg'." ;;
   esac
   [ "$Xserver" = "Xorg" ] && {
+    [ "$Hostsystem" = "opensuse" ] && [ "$Tty" = "no" ] && error "openSUSE does not support starting a second Xorg server
+  from within X. Possible solutions: install nested X server 'Xephyr',
+  or switch to console tty1...tty6 with <CTRL><ALT><F1>...<F6>
+  and start x11docker there."
     [ "$Autochooseserver" = "yes" ] && [ -n "$Hostdisplay" ] && note "Could not find Xephyr or an alternative
   to run desktop in container. Will try to run a second core Xorg server."
     note "You can switch between X servers and console terminals
@@ -2004,8 +2029,10 @@ s0_active_plugins = core;composite;opengl;decor;resize;move;
           ;;
         esac
         #
-        [ -n "$Windowmanager" ] && [ -z "$(command -v $Windowmanager)" ] && error "No executeable window manager '$Windowmanager' found. 
-  Have a look at 'x11docker --help' for a list of recommended window managers."
+        [ -n "$Windowmanager" ] && [ -z "$(command -v $Windowmanager)" ] && error "No executeable window manager '$Windowmanager' found."
+        [ -z "$Windowmanager" ] && warning "Could not detect a host window manager.
+  Please specify one with option --wm=WINDOWMANAGER or install one of
+  $Wm_good"
       ;;
     esac
     ;;
@@ -2262,8 +2289,8 @@ fi
         xdpyinfo >/dev/null 2>&1 && {
         Dpi=$(xdpyinfo | grep dots | cut -dx -f2 | cut -d' ' -f1)
         } || {
-          [ -n "$Hostdisplay" ] && [ -z "$(command -v xdpyinfo)" ] && note "Could not determine dpi settings. If you encounter too
-  big or small fonts in $Xserver, please install xdpyinfo or use option --dpi."
+          [ -n "$Hostdisplay" ] && [ -z "$(command -v xdpyinfo)" ] && [ "$Xserver" != "Hostdisplay" ] && note "Could not determine dpi settings. If you encounter too big or
+  too small fonts in $Xserver, please install xdpyinfo or use option --dpi."
         }
         case $Xserver in
           Xpra|Xpra-Xwayland)
@@ -2292,16 +2319,6 @@ fi
       # version check for scaling already done above
       [ "$Scaling" != "0" ] && Xpraoptions="$Xpraoptions --desktop-scaling=$Scaling"
       
-#      # show xpra keyboard shortcuts  ### FIXME: disabled, slows down startup too much
-#      Line=$($Mksu 'xpra showconfig' | grep "key-shortcut" | head -n1 | cut -d= -f2-)
-#      note "Xpra keyboard shortcuts:
-#$(while [ -n "$Line" ] ; do
-#    echo $Line | cut -d"'" -f2
-#    Line=$(echo $Line | cut -d"'" -f3- -s)
-#  done | column -t -s:)
-#(Shortcuts starting with a # are disabled.
-#Adjustable in /etc/xpra/conf.d/40_client.conf)"
-
       # debug options for xpra
       #Xpraoptions="$Xpraoptions -d randr,geometry,screen"
     ;;
@@ -2411,8 +2428,6 @@ $(tail "$Compositorlogfile")"
       Waylandsocket="$Hostwayland"
     ;;
     Xpra-Xwayland|Xdummy-Xwayland)
-#      [ "$Desktopmode" = "yes" ] && [ "$Xserver" != "Xpra-Xwayland" ] && Xserveroptions="$Xserveroptions -rootless" 
-#      [ "$Xserver" = "Xdummy-Xwayland" ] && Xserveroptions="$Xserveroptions -rootless" 
       Xcommand="$(command -v Xwayland) $Newdisplay \\
   $Xserveroptions"
       [ -z "$Hostwayland" ] && Waylandsocket="wayland-$Newdisplaynumber" || {
@@ -2590,11 +2605,14 @@ esac
   # Host X enviroment
   [ -n "$Hostdisplay" ] && [ -e "$Hostxsocket" ] && {
     Hostxenv="DISPLAY=$Hostdisplay"
-    [ -e "$XAUTHORITY" ] && cp $XAUTHORITY $Hostxauthority && chown $Hostuser $Hostxauthority && Hostxenv="$Hostxenv XAUTHORITY=$Hostxauthority"
-    [ -e "$XAUTHORITY" ] || Hostxenv="$Hostxenv XAUTHORITY="
+    [ -e "$XAUTHORITY" ] && {
+      cp $XAUTHORITY $Hostxauthority
+      chown $Hostuser $Hostxauthority
+      Hostxenv="$Hostxenv XAUTHORITY=$Hostxauthority"
+    } || Hostxenv="$Hostxenv XAUTHORITY= "
     Hostxenv="$Hostxenv XSOCKET=$Hostxsocket" 
     Hostxenv="$Hostxenv $Xprashm" 
-  } || Hostxenv="DISPLAY= XAUTHORITY= XSOCKET="
+  } || Hostxenv="DISPLAY= XAUTHORITY= XSOCKET= "
 }
 
 { #### part: create shareclipboard script (option --clipboard)
@@ -2648,16 +2666,8 @@ done
 { #### part: check password prompt frontend (pkexec, su, sudo, ...) 
   # check if x11docker can run docker without prompting for password
   [ -z "$Passwordprompt" ] &&         docker images  >/dev/null 2>&1 && Passwordprompt="none"
-#  [ -z "$Passwordprompt" ] && sudo -n docker images  >/dev/null 2>&1 && Passwordprompt="sudo" && Passwordterminal="bash -c"   # FIXME: does not work anymore due to 'sudo setsid'
   [ -z "$Passwordprompt" ] && sudo -n env  >/dev/null 2>&1 && Passwordprompt="sudo" && Passwordterminal="bash -c"              # check for general passwordless sudo instead
 
-  # check pkexec ### disabled, too many pitfalls. dialog fails in opensuse, on console and on additional X servers
-  #[ -z "$Passwordprompt" ] && command -v pkexec >/dev/null && {
-  #  Passwordprompt="pkexec"                                                         # default if itchy requirements are fulfilled
-  #  { [ "$Xserver" = "Xorg" ] || [ "$Tty" = "yes" ] ; }       && Passwordprompt=""  # pkexec ignores $DISPLAY, can appear on wrong vt or fail at all
-  #  [ "$Passwordprompt" = "pkexec" ] && [ -z "$Hostdisplay" ] && Passwordprompt=""  # pkexec is only reliable on host display :0
-  #}
-  
   # check sudo. Check is not reliable, compare https://unix.stackexchange.com/questions/383918/su-or-sudo-how-to-know-which-one-will-work
   ### FIXME: just guessing that members of group sudo or wheel are allowed to run commands docker and env as root
   [ -z "$Passwordprompt" ] && { sudo -ln docker >/dev/null 2>&1 || [ -n "$(id | grep '(sudo)')" ]|| [ -n "$(id | grep '(wheel)')" ] ; } && command -v sudo >/dev/null && {
@@ -2681,17 +2691,17 @@ done
 
   # Getroot or Pkexec: prefix to start dockerrc. Sudo: prefix to start docker in dockerrc
   case $Passwordprompt in
-    pkexec|"") Getroot="bash -c"                                                ; Sudo=""     ; Pkexec="pkexec " ; Passwordterminal="bash -c" ;;
-    su)        Getroot="su -c"                                                  ; Sudo=""     ; Pkexec=""        ;;
-    sudo)      Getroot="bash -c"                                                ; Sudo="sudo" ; Pkexec=""        ;;
-    gksu)      Getroot="gksu    --message 'x11docker $Imagename'"               ; Sudo=""     ; Pkexec=""        ; Passwordterminal="bash -c" ;;
-    gksudo)    Getroot="gksudo  --message 'x11docker $Imagename'"               ; Sudo=""     ; Pkexec=""        ; Passwordterminal="bash -c" ;;
-    lxsu)      Getroot="lxsu"                                                   ; Sudo=""     ; Pkexec=""        ; Passwordterminal="bash -c" ;;
-    lxsudo)    Getroot="lxsudo"                                                 ; Sudo=""     ; Pkexec=""        ; Passwordterminal="bash -c" ;;
-    kdesu)     Getroot="kdesu -c"                                               ; Sudo=""     ; Pkexec=""        ; Passwordterminal="bash -c" ;;
-    kdesudo)   Getroot="kdesudo --comment 'x11docker $Imagename'"               ; Sudo=""     ; Pkexec=""        ; Passwordterminal="bash -c" ;;
-    beesu)     Getroot="beesu -c"                                               ; Sudo=""     ; Pkexec=""        ; Passwordterminal="bash -c" ;;
-    none)      Getroot="bash -c"                                                ; Sudo=""     ; Pkexec=""        ; Passwordterminal="bash -c" ;;
+    pkexec|"") Getroot="bash -c"                                                ; Sudo=""        ; Pkexec="pkexec " ; Passwordterminal="bash -c" ;;
+    su)        Getroot="su -c"                                                  ; Sudo=""        ; Pkexec=""        ;;
+    sudo)      Getroot="bash -c"                                                ; Sudo="sudo -E" ; Pkexec=""        ;;
+    gksu)      Getroot="gksu    --message 'x11docker $Imagename'"               ; Sudo=""        ; Pkexec=""        ; Passwordterminal="bash -c" ;;
+    gksudo)    Getroot="gksudo  --message 'x11docker $Imagename'"               ; Sudo=""        ; Pkexec=""        ; Passwordterminal="bash -c" ;;
+    lxsu)      Getroot="lxsu"                                                   ; Sudo=""        ; Pkexec=""        ; Passwordterminal="bash -c" ;;
+    lxsudo)    Getroot="lxsudo"                                                 ; Sudo=""        ; Pkexec=""        ; Passwordterminal="bash -c" ;;
+    kdesu)     Getroot="kdesu -c"                                               ; Sudo=""        ; Pkexec=""        ; Passwordterminal="bash -c" ;;
+    kdesudo)   Getroot="kdesudo --comment 'x11docker $Imagename'"               ; Sudo=""        ; Pkexec=""        ; Passwordterminal="bash -c" ;;
+    beesu)     Getroot="beesu -c"                                               ; Sudo=""        ; Pkexec=""        ; Passwordterminal="bash -c" ;;
+    none)      Getroot="bash -c"                                                ; Sudo=""        ; Pkexec=""        ; Passwordterminal="bash -c" ;;
     *) error "Unknown password prompt '$Passwordprompt' (option --pw).
   Possible are: pkexec su sudo gksu gksudo lxsu lxsudo kdesu kdesudo none" ;;
   esac
@@ -2871,8 +2881,8 @@ done
         Dockercommand="$Dockercommand \\
   --security-opt label=type:container_runtime_t" 
         note "SELinux restrictions for this container are decreased
-  with option '--security-opt label=type:container_runtime_t'
-  to allow access to X unix socket. A more precise restriction is desirable."
+  with option '--security-opt label=type:container_runtime_t' to allow access
+  to X unix socket $Newxsocket. A more precise restriction is desirable."
       }
       
       Containername="x11docker_X${Newdisplaynumber}_${Mycookie}_$(echo $Imagename | tr / _ | tr : _ )"
@@ -2987,16 +2997,6 @@ done
   echo "  echo 'mkdir -p /tmp/.X11-unix'"
   echo "  [ -e '$Newxsocket' ] && echo 'ln -s /tmp/X$(echo $Newdisplay | cut -d: -f2 | cut -d. -f1) $Newxsocket'"
   echo "  echo ''"
-  #case $Xserver in
-  #  Xpra|Xpra-Xwayland)  # FIXME: disabled, takes too long. static setting of environment variables instead.
-  #    echo "  echo '# xpra specific environment variables'"
-  #    Line=$($Mksu 'xpra showconfig' | grep start-env | head -n1 | cut -d= -f2-)
-  #    while [ -n "$Line" ] ; do
-  #      Line=$(echo $Line | cut -d"'" -f2- -s)
-  #      Byte="$(echo $Line | cut -c1)"
-  #      [ "$Byte" != "${Byte,,}" ] && echo "  echo 'export $(echo $Line | cut -d"'" -f1)'"
-  #    done ;;
-  #esac
   echo "  echo '# xpra environment settings'"
   echo "  echo 'export UBUNTU_MENUPROXY= QT_X11_NO_NATIVE_MENUBAR=1 MWNOCAPTURE=true MWNO_RIT=true MWWM=allwm'"
   echo "  echo ''"
