--exe: fixed background PID handling

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -858,7 +858,7 @@ depends() {             # check dependencies on host for X server option $1
       } 
     ;;
   esac
-  verbose -d "dependency check for ${1:-}: $Return"
+  debugnote "dependency check for ${1:-}: $Return"
   
   [ "$Return" = "1" ] && {
     $Message "${1:-} not possible: missing dependencies."
@@ -1671,7 +1671,7 @@ $Customenvironment"    ;  shift ;;                         # set custom environm
   
   grep -q beta <<<$Version && note "You are running a beta version of x11docker.
   Beta versions change often and may introduce new bugs.
-  You can help in finding and reporting bugs at:
+  You can help to find bugs and to report them at:
     https://github.com/mviereck/x11docker
   If you prefer latest stable release, run 'x11docker --update'.
   If you prefer to follow development, run 'x11docker --update-master'."
@@ -2505,8 +2505,8 @@ Parsed options: $Parsedoptions"
   ps -p "$Xwaylandpid" >/dev/null 2>&1 && {
     verbose -d "Terminating Xwayland"
     kill $Xwaylandpid
-    export DISPLAY=$Hostdisplay
   }
+  export DISPLAY=$Hostdisplay
 }
 
 { #### part: --gpu: check nvidia driver
@@ -5271,6 +5271,9 @@ $(tail $Dockerlogfile)"
       # run host application without docker. includes --xonly
       { echo "#! /bin/bash"
         [ "$Debugmode" = "yes" ] && echo "set -Eux"
+        echo "storepid() {"
+        echo "  echo \${1:-} \${2:-} >> $Bgpidfile"
+        echo "}"
         echo "export $Newxenv"
         [ "$Benutzerhosthome" = "yes" ] && {
           echo "export HOME='$Benutzerhosthomefolder'"
@@ -5281,14 +5284,22 @@ $(tail $Dockerlogfile)"
         echo "for i in 3 4 6 7 8 9; do"
         echo "  { >&\$i ;} 2>/dev/null && exec >&\$i-"
         echo "done"
-        echo "exec $Hostexe $( [ "$Forwardstdin" = "yes" ] && echo "<$Cmdstdinfile") >>$Cmdstdoutlogfile 2>>$Cmdstderrlogfile"
+        echo "$Hostexe $( [ "$Forwardstdin" = "yes" ] && echo "<$Cmdstdinfile") >>$Cmdstdoutlogfile 2>>$Cmdstderrlogfile &"
+        echo "storepid \$! hostexe"
       } >> $Imagecommandscript
       nl -ba <$Imagecommandscript >> $Dockerlogfile
-      $Mksubenutzer "bash $Imagecommandscript" & Hostexepid=$! && storepid $! hostexe
+
+      $Mksubenutzer "bash $Imagecommandscript"
       sleep 1 # wait for possible startup failure
-      checkpid $Hostexepid && setonwatchpidlist $Hostexepid || error "Startup of '$Hostexe' failed.
+      Hostexepid=$(grep hostexe <$Bgpidfile | cut -d' ' -f1)
+      debugnote "pstree of $Hostexe
+$(pstree -p $Hostexepid)"
+      
+      checkpid $Hostexepid || error "Startup of '$Hostexe' failed,
+  or the process forked itself and cannot be supervised.
   Last lines of log:
-$(tail $Dockerlogfile)"
+$(tail $Logfile)"
+      setonwatchpidlist $Hostexepid
     ;;
   esac
   debugnote "Process tree of x11docker:
@@ -5376,9 +5387,7 @@ todo() {
 # further checks of pam.d
 # error message  window in wayland fails: xterm: no display. should use konsole
 # error message window in --xorg fails if xinit fails: no display
-# BUG --wayland --exe xfce4-terminal: Sometimes startup error message although startup was successfull
 
-# --weston and --kwin on pure wayland host: check screen size with Xwayland -rootless
 # --update: regard possible location in /opt
 # BUG opensuse/arch: issues with x11docker/fluxbox, background missing, sometimes no context menu. where is the difference?
 
