x11docker-gui: support option --backend #392

diff --git a/x11docker-gui b/x11docker-gui
--- a/x11docker-gui
+++ b/x11docker-gui
@@ -46,22 +46,43 @@ export PATH="$PATH:/usr/local/bin" # can miss if executed as root
 
 # check options
 #Verboseoption="--quiet"
+Backend=""
+Nerdctl=""
+Podman=""
 Verboseoption=""
-case "${1:-}" in
-  --icon)
-    echo "x11docker-gui does not create an icon on demand anymore." >&2
-    exit 1
-  ;;
-  -v|--verbose) 
-    Verbose="yes"
-    Verboseoption="--verbose" 
-  ;;
-  "") ;;
-  *) echo "Options:
-  -v  --verbose    Be verbose"
-    exit 1
-  ;;
-esac
+
+
+Shortoptions="hv"
+Longoptions="backend:,help,verbose"
+Parsedoptions="$(getopt --options "$Shortoptions" --longoptions "$Longoptions" --name "$0" -- "$@" )" || error "Failed to parse options."
+eval set -- "$Parsedoptions"
+
+while [ $# -gt 0 ]; do
+  case "${1:-}" in
+    --backend)
+      Backend="${2:-}"
+      shift
+      case $Backend in
+        docker) ;;
+        podman) Podman="!" ;;
+        nerdctl) Nerdctl="!" ;;
+        *) error "Unknown backend $Backend" ;;
+      esac
+    ;;
+    -v|--verbose) 
+      Verbose="yes"
+      Verboseoption="--verbose" 
+    ;;
+    -h|--help) echo "x11docker-gui options:
+      --backend=BACKEND   Container backend to use: docker, podman or nerdctl.
+                          Default: docker.
+  -v  --verbose           Be verbose."
+      exit 1
+    ;;
+    --) ;;
+  esac
+  shift
+done
 
 # Try to find x11docker
 X11docker_exe="${0%-gui}"                                   # look at path of current x11docker-gui
@@ -161,7 +182,7 @@ for Line in $Keymaps; do Keymapscombo="$Keymapscombo,\"$Line\"" ; done
 Presetcombo=""
 while read Line; do
   Presetcombo="$Presetcombo,'$Line'"
-done < <(find /etc/x11docker/preset "$HOME/.config/x11docker/preset" -type f -exec basename {} \; | sort -V | uniq)
+done < <(find /etc/x11docker/preset "$HOME/.config/x11docker/preset" -type f -exec basename {} \; 2>/dev/null | sort -V | uniq)
 Presetcombo="${Presetcombo#,}"
 Presetcombo="${Presetcombo:-"''"}"
 
@@ -183,7 +204,7 @@ start "Run GUI applications in containers - x11docker '$Version'"    -> options 
         exe               "--exe: Run host application instead of docker container."         -> "--exe -- ";
         xonly             "--xonly: Only create new empty X server."                         -> "--xonly -- "; 
     dockerimage           "Image [and command] to run:"                                      -> "--IMG=" @combow('$Imagelist');
-    backend:beside "--backend:"        -> backenddocker | backendpodman | backendnerdctl;
+    backend:beside "--backend:"        -> backenddocker | '$Podman' backendpodman | '$Nerdctl' backendnerdctl;
       backenddocker "docker"             -> "" ;
       backendpodman "podman"             -> "--backend=podman" ;
       backendnerdctl "nerdctl"           -> "--backend=nerdctl" ;
