--update[-master]: New optional argument 'diff' #460

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="7.4.0"
+Version="7.4.1-beta-1"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups. (deprecated)
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -376,8 +376,10 @@ Verbosity options:
 Installation options and cleanup (need root permissions):
      --install         Install x11docker from current folder.
                        Useful to install from an extracted zip file.
-     --update          Download and install latest release from github.
-     --update-master   Download and install latest master version from github.
+     --update [=diff]  Download and install latest release from github.
+     --update-master [=diff]  Download and install latest master version.
+                       Optional argument 'diff' shows the difference between
+                       installed and new version without installing it.
      --remove          Remove x11docker from your system. Includes --cleanup.
                        Preserves ~/.local/share/x11docker from option --home.
      --cleanup         Clean up orphaned containers and cache files. Those
@@ -1639,13 +1641,18 @@ installer() {                   # --install, --update, --update-master, --remove
     case "$Winsubsystem" in
       CYGWIN|MSYS2) ;;
       *)
-        case "$Binowner" in
-          root)
-            error "Must run as root to install, update or remove x11docker system wide."
-            return 1
-          ;;
-          *) warning "Option ${1:-}: Not running as root.
+        case "$Installerarg" in
+          diff) ;;
+          *)
+            case "$Binowner" in
+              root)
+                error "Must run as root to install, update or remove x11docker system wide."
+                return 1
+              ;;
+              *) warning "Option ${1:-}: Not running as root.
   Installing or updating non-essential files in system wide folders might fail." ;;
+            esac
+          ;;
         esac
       ;;
     esac
@@ -1660,7 +1667,8 @@ installer() {                   # --install, --update, --update-master, --remove
         return 1
       }
       command -v x11docker > /dev/null && {
-        warning "x11docker seems to be installed already.
+        warning "x11docker seems to be installed already
+  at $Binpath/x11docker.
   Will overwrite existing installation.
   Consider to use option '--update' or '--update-master' instead."
       }
@@ -1728,59 +1736,10 @@ installer() {                   # --install, --update, --update-master, --remove
     ;;
   esac
 
-  # Doing
+  # New version number
   case "${1:-}" in
     --install|--update|--update-master)
-      note "Installing x11docker in $Binpath"
-      cp x11docker "$Binpath/"                                                || {
-        error "Could not copy x11docker to $Binpath"
-        return 1
-      }
-      chmod 755 "$Binpath/x11docker"                                          || {
-        error "Could not set executable bit on x11docker"
-        return 1
-      }
-      chown "$Binowner:$Bingroup" "$Binpath/x11docker"                        || warning "Could not set ownership '$Binowner:$Bingroup' to '$Binpath/x11docker'"
-
-      note "Installing icon for x11docker with xdg-icon-resource"
-      xdg-icon-resource install --context apps --novendor --mode system --size 64 "$(pwd)/x11docker.png" x11docker || warning "Could not install icon for x11docker.
-  Is 'xdg-icon-resource' (xdg-utils) installed on your system?"
-      xdg-icon-resource uninstall --size 72 x11docker ||:  # deprecated icon size, may still be present.
-
-      note "Storing README.md, CHANGELOG.md and LICENSE.txt in
-  /usr/share/doc/x11docker"
-      mkdir -p /usr/share/doc/x11docker && {
-        cp README.md    /usr/share/doc/x11docker/
-        cp CHANGELOG.md /usr/share/doc/x11docker/
-        cp LICENSE.txt  /usr/share/doc/x11docker/
-      } || note "Error while creating /usr/share/doc/x11docker"
-
-      Newversion="$("$Binpath/x11docker" --version)"
-      note "Installed x11docker version $Newversion"
-    ;;
-    --remove)
-      note "Removing x11docker from your system."
-      cleanup
-      [ -x "$Binpath/x11docker" ]     && rm -v "$Binpath/x11docker"
-      [ -x "$Binpath/x11docker-gui" ] && rm -v "$Binpath/x11docker-gui"
-      [ -e "/usr/share/applications/x11docker.desktop" ] && rm -v /usr/share/applications/x11docker.desktop
-      [ -e "/usr/share/doc/x11docker" ]                  && rm -R -v /usr/share/doc/x11docker
-      [ -e "/usr/share/icons/x11docker.png" ]            && rm /usr/share/icons/x11docker.png
-      xdg-icon-resource uninstall --size 64 x11docker ||:
-      xdg-icon-resource uninstall --size 72 x11docker ||:  # deprecated icon size, may still be present.
-      note "Will not remove files in your home folder.
-  There may be files left in \$HOME/.local/share/x11docker
-  The symbolic link \$HOME/x11docker may exist, too.
-  The cache folder \$HOME/.cache/x11docker should be removed already."
-    ;;
-  esac
-
-  # Cleanup
-  case "${1:-}" in
-    --update|--update-master)
-      note "Removing downloaded temporary files."
-      cd ~
-      rm -R /tmp/x11docker-install
+      Newversion="$(bash $(pwd)/x11docker --version)"
     ;;
   esac
 
@@ -1817,7 +1776,73 @@ installer() {                   # --install, --update, --update-master, --remove
   case "${1:-}" in
     --update|--update-master)
       note "Excerpt of x11docker changelog:
-$(sed -n "/${Key1}/,/${Key2}/p" /usr/share/doc/x11docker/CHANGELOG.md | head -n-1)"
+$(sed -n "/${Key1}/,/${Key2}/p" CHANGELOG.md | head -n-1)"
+    ;;
+  esac
+
+  # show diff
+  [ "$Installerarg" = "diff" ] && {
+    case "${1:-}" in
+      --update|--update-master)
+        note "Difference of installed version to new version:
+  $ diff $Binpath/x11docker $(pwd)/x11docker
+$(diff $Binpath/x11docker $(pwd)/x11docker 2>&1)"
+      ;;
+    esac
+  }
+
+  # Doing
+  [ -z "$Installerarg" ] && case "${1:-}" in
+    --install|--update|--update-master)
+      note "Installing x11docker in $Binpath"
+      cp x11docker "$Binpath/"                                                || {
+        error "Could not copy x11docker to $Binpath"
+        return 1
+      }
+      chmod 755 "$Binpath/x11docker"                                          || {
+        error "Could not set executable bit on x11docker"
+        return 1
+      }
+      chown "$Binowner:$Bingroup" "$Binpath/x11docker"                        || warning "Could not set ownership '$Binowner:$Bingroup' to '$Binpath/x11docker'"
+
+      note "Installing icon for x11docker with xdg-icon-resource"
+      xdg-icon-resource install --context apps --novendor --mode system --size 64 "$(pwd)/x11docker.png" x11docker || warning "Could not install icon for x11docker.
+  Is 'xdg-icon-resource' (xdg-utils) installed on your system?"
+      xdg-icon-resource uninstall --size 72 x11docker ||:  # deprecated icon size, may still be present.
+
+      note "Storing README.md, CHANGELOG.md and LICENSE.txt in
+  /usr/share/doc/x11docker"
+      mkdir -p /usr/share/doc/x11docker && {
+        cp README.md    /usr/share/doc/x11docker/
+        cp CHANGELOG.md /usr/share/doc/x11docker/
+        cp LICENSE.txt  /usr/share/doc/x11docker/
+      } || note "Error while creating /usr/share/doc/x11docker"
+
+      note "Installed x11docker version $Newversion"
+    ;;
+    --remove)
+      note "Removing x11docker from your system."
+      cleanup
+      [ -x "$Binpath/x11docker" ]     && rm -v "$Binpath/x11docker"
+      [ -x "$Binpath/x11docker-gui" ] && rm -v "$Binpath/x11docker-gui"
+      [ -e "/usr/share/applications/x11docker.desktop" ] && rm -v /usr/share/applications/x11docker.desktop
+      [ -e "/usr/share/doc/x11docker" ]                  && rm -R -v /usr/share/doc/x11docker
+      [ -e "/usr/share/icons/x11docker.png" ]            && rm /usr/share/icons/x11docker.png
+      xdg-icon-resource uninstall --size 64 x11docker ||:
+      xdg-icon-resource uninstall --size 72 x11docker ||:  # deprecated icon size, may still be present.
+      note "Will not remove files in your home folder.
+  There may be files left in \$HOME/.local/share/x11docker
+  The symbolic link \$HOME/x11docker may exist, too.
+  The cache folder \$HOME/.cache/x11docker should be removed already."
+    ;;
+  esac
+
+  # Cleanup
+  case "${1:-}" in
+    --update|--update-master)
+      note "Removing downloaded temporary files."
+      cd ~
+      rm -R /tmp/x11docker-install
     ;;
   esac
   note "Ready."
@@ -9017,7 +9042,7 @@ parse_options() {               # parse cli options
   Longoptions="$Longoptions,printenv::,printid::,printinfofile::,printpid1::"                                               # Output of vars on stdout
   Longoptions="$Longoptions,debug,printcheck,quiet,verbose::"                                                               # Verbose options
   Longoptions="$Longoptions,build,cleanup,help,launcher,licence,license,version"                                            # Special options without starting X or container
-  Longoptions="$Longoptions,install,remove,update,update-master"                                                            # Installation
+  Longoptions="$Longoptions,install,remove,update::,update-master::"                                                        # Installation
   #
   Longoptions="$Longoptions,keepcache,remountcgroup,xopt:,xorgconf:"                                                        # Experimental
   Longoptions="$Longoptions,dbus-system,enforce-i,exe,homedir:,hostipc,hostnet,iglx,kwin-xwayland"                          # Deprecated
@@ -9215,7 +9240,8 @@ ${2:-}"                       ; shift ;;                             # Add custo
      #### Special options not starting X or docker
          --build)             Buildimage="yes" ;;                    # Build an image from x11docker repository
          --cleanup)           Cleanup="yes"  ;;                      # Remove orphaned containers and cache files
-         --install|--update|--update-master|--remove) Installermode="${1:-}" ;;   # Installer
+         --install|--remove)  Installermode="${1:-}" ;;              # Installer
+         --update|--update-master) Installermode="${1:-}" ; Installerarg="${2:-}" ; shift ;;   # Installer
          --launcher)          Createlauncher="yes" ;;                # Create application launcher on desktop and exit
 
      #### Experimental options
@@ -9595,6 +9621,15 @@ check_options_arguments() {     # check for [likely] valid arguments
   Fallback: Disabling option --sudouser."
       Sudouser=""
       check_fallback
+    ;;
+  esac
+
+  # --update, --update-master
+  case "$Installerarg" in
+    "") ;;
+    diff) ;;
+    *)
+      error "Option --update/--update-master: Unknown argument '$Installerarg'."
     ;;
   esac
 
@@ -10968,6 +11003,7 @@ declare_variables() {           # declare global variables
   Cleanup=""                                      # --cleanup: Remove orphaned containers and cache files
   Createlauncher=""                               # --launcher: Create application launcher on desktop and exit yes/no
   Installermode=""                                # --install/--update/--update-master/--remove
+  Installerarg=""                                 # --update/--update-master: show diff only, do not install
 
   # Lists of window managers
   # - these window managers are known to work well with x11docker (alphabetical order)(excluding $Wm_not_recommended and $Wm_ugly):
