--backend=proot: startup fix

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -6138,7 +6138,8 @@ reload() {
     case $Initsystem in
       proot) 
         echo "exec 1>&5 2>&6"
-        echo "exec /usr/local/bin/x11docker-login"
+        #echo "exec /usr/local/bin/x11docker-login"
+        echo "exec /bin/sh $(convertpath share $Containerrc)"
       ;;
       none|dockerinit)
 #        echo "exec /usr/local/bin/x11docker-login"
@@ -9144,13 +9145,18 @@ main() {
   storeinfo "x11dockerpid=$$"   # store pid of x11docker
   
   [ "$X11dockermode" = "run" ] && {
-    # Check whether docker daemon is running, get docker info
-    Backendinfo="$($Backendbin info 2>>$Containerlogfile)" || error "'$Backend info' failed.
+    case $Backend in
+      proot) ;;
+      *)
+        # Check whether docker daemon is running, get docker info
+        Backendinfo="$($Backendbin info 2>>$Containerlogfile)" || error "'$Backend info' failed.
   If using docker: Is docker daemon running at all?
   Try to start docker daemon with 'systemctl start docker'.
   Last lines of log:
 $(rmcr < "$Containerlogfile" | tail)"
     check_runtime
+      ;;
+    esac
   }
 
   debugnote "
