V3.5.11.2 more verbose output on docker pull

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -2308,10 +2308,12 @@ esac
   declare -f warning
   echo "Imagecommand='$Imagecommand'"
   echo "Imagename='$Imagename'"
+  echo "Logfile='$Logfile'"
   echo "# check if image is available locally"
-  echo "docker inspect --type=image $Imagename > /dev/null || {"
+  echo "docker inspect --type=image $Imagename > /dev/null 2>&1 || {"
   echo "  warning 'Image $Imagename not found locally. Will try to pull it'"
-  echo "  docker pull $Imagename"
+  echo "  echo 'Image $Imagename not found locally. docker will try to pull it:'"
+  echo "  docker pull $Imagename >&3 2>&1"
   echo "}"  
   echo "[ -z \"\$Imagecommand\" ] && {"
   echo "  # extract image command from image if not given on cli"
