new options --printXY[=FILE]. Replace --showXY options

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -149,7 +149,7 @@ Special X server options:
      --xdummy          Invisible X server using dummy video driver.
      --xvfb            Invisible X server using Xvfb.
                        --xdummy and --xvfb can be used for custom  VNC access.
-                       Output of environment variables on stdout. (--showenv)
+                       Output of environment variables on stdout. (--printenv)
                        Along with option --gpu an invisible setup with Weston,
                        Xwayland and xdotool is used (instead of Xdummy or Xvfb).
  -X, --xwayland        Blanc Xwayland, needs a running Wayland compositor.
@@ -317,12 +317,12 @@ Miscellaneous:
                        of nerdctl and podman.
      
 Output of parseable information on stdout:
-  Get output e.g. with: read xenv < <(x11docker --showenv x11docker/check)
+  Get output e.g. with: read xenv < <(x11docker --printenv x11docker/check)
   Optional argument FILE allows to print the information into a file.
-     --showenv [=FILE]        Print variables to access new display.
-     --showid [=FILE]         Print container ID.
-     --showinfofile [=FILE]   Print path to internal x11docker info storage.
-     --showpid1 [=FILE]       Print host PID of container PID 1.
+     --printenv [=FILE]        Print variables to access new display.
+     --printid [=FILE]         Print container ID.
+     --printinfofile [=FILE]   Print path to internal x11docker info storage.
+     --printpid1 [=FILE]       Print host PID of container PID 1.
 
 Verbosity options:
  -D, --debug           Debug mode: Show some less verbose debug output
@@ -2624,7 +2624,7 @@ check_xdepends() {              # check dependencies on host for X server option
       ;;
       --xwayland|--weston-xwayland|--kwin|--kwin-xwayland|--xpra-xwayland|--xdummy-xwayland|--hostwayland)
         $Message "${1:-} does not support X over TCP."
-        Return=1
+        #Return=1
       ;;
     esac
   }
@@ -8578,11 +8578,11 @@ declare_variables() {           # declare global variables
   
   # Verbosity options
   Debugmode="no"                                  # --debug: Excerpt of --verbose, also bash error checks
-  Showcontainerid=""                              # --showid: Output of container ID on stdout
+  Showcontainerid=""                              # --printid: Output of container ID on stdout
   Showcontaineroutput="yes"                       # Show container command stdout
-  Showcontainerpid1pid=""                         # --showpid1: Output of host PID of container PID 1 on stdout
-  Showdisplayenvironment=""                       # --showenv: Output of environment variables of new display on stdout
-  Showinfofile=""                                 # --showinfofile: Show path of $Storeinfofile
+  Showcontainerpid1pid=""                         # --printpid1: Output of host PID of container PID 1 on stdout
+  Showdisplayenvironment=""                       # --printenv: Output of environment variables of new display on stdout
+  Showinfofile=""                                 # --printinfofile: Show path of $Storeinfofile
   Silent="no"                                     # --quiet: Do not show x11docker messages
   Verbose="no"                                    # --verbose: Be verbose yes/no
   Verbosecolors="no"                              # -V: colored output for --verbose (and delete some noisy systemd error messages)
@@ -8679,13 +8679,14 @@ parse_options() {               # parse cli options
   Longoptions="$Longoptions,dbus::,init::,hostdbus,sharecgroup"                                                            # Container init and DBus
   Longoptions="$Longoptions,stdin,interactive"                                                                             # Container interaction
   Longoptions="$Longoptions,runasuser:,runfromhost:,runasroot:"                                                            # Additional commands to execute
-  Longoptions="$Longoptions,showenv::,showid::,showinfofile::,showpid1::"                                                  # Output of vars on stdout
+  Longoptions="$Longoptions,printenv::,printid::,printinfofile::,printpid1::"                                              # Output of vars on stdout
   Longoptions="$Longoptions,debug,quiet,verbose"                                                                           # Verbose options
   Longoptions="$Longoptions,build,cleanup,help,launcher,licence,license,version"                                           # Special options without starting X or container
   Longoptions="$Longoptions,install,remove,update,update-master"                                                           # Installation
   #
   Longoptions="$Longoptions,keepcache,no-setup,xopt:,xorgconf:"                                                            # Experimental
   Longoptions="$Longoptions,dbus-system,homedir:,hostnet,no-internet,no-xhost,sharedir:,sharessh,systemd"                  # Deprecated
+  Longoptions="$Longoptions,showenv,showid,showinfofile,showpid1"                                                          # Deprecated
   Longoptions="$Longoptions,cachedir:,no-init,nothing,no-xtest,openrc,podman,pull:,ps,runit,silent,starter"                # Removed
   Longoptions="$Longoptions,stderr,stdout,sys-admin,sysvinit,tini,trusted,untrusted,vcxsrv"                                # Removed
 
@@ -8898,10 +8899,10 @@ ${2:-}"                       ; shift ;;                             # Add custo
       -v|--verbose)           Verbose="yes" ;;                       # Be verbose  
       -V)                     Verbose="yes"; Verbosecolors="yes";;   # Be verbose with colored output
       -q|--quiet)             Silent="yes" ;;                        # Do not show warnings or errors
-         --showenv)           Showdisplayenvironment="${2:-yes}" ; shift ;;  # Output of display number and cookie file on stdout. Catch with: read xenv < <(x11docker --showenv)
-         --showid)            Showcontainerid="${2:-yes}" ; shift ;;         # Output of container id on stdout
-         --showinfofile)      Showinfofile="${2:-yes}" ; shift ;;            # Show path to $Storeinfofile
-         --showpid1)          Showcontainerpid1pid="${2:-yes}" ; shift ;;    # Output of host PID of container PID 1
+         --printenv)           Showdisplayenvironment="${2:-yes}" ; shift ;;  # Output of display number and cookie file on stdout. Catch with: read xenv < <(x11docker --printenv)
+         --printid)            Showcontainerid="${2:-yes}" ; shift ;;         # Output of container id on stdout
+         --printinfofile)      Showinfofile="${2:-yes}" ; shift ;;            # Show path to $Storeinfofile
+         --printpid1)          Showcontainerpid1pid="${2:-yes}" ; shift ;;    # Output of host PID of container PID 1
 
      #### Special options not starting X or docker
          --build)             Buildimage="yes" ;;                    # Build an image from x11docker repository
@@ -8934,6 +8935,10 @@ ${2:-}"                       ; shift ;;                             # Add custo
                               note "Option --sharessh is deprecated.
   Please use (directly or with help of option --preset):
   --share \$(dirname \$SSH_AUTH_SOCK) --env SSH_AUTH_SOCK=\"\$SSH_AUTH_SOCK\"" ;;
+         --showenv)           Showdisplayenvironment="yes" ; note "Option --showenv is deprecated. Please use option --printenv instead." ;;
+         --showid)            Showcontainerid="yes" ;        note "Option --showid is deprecated. Please use option --printid instead." ;;
+         --showinfofile)      Showinfofile="yes" ;           note "Option --showinfofile is deprecated. Please use option --printinfofile instead." ;;
+         --showpid1)          Showcontainerpid1pid="yes" ;   note "Option --showpid1 is deprecated. Please use option --printpid1 instead." ;;
                        
      #### Removed options
          --vcxsrv)            error "Option --vcxsrv is no longer supported.
@@ -9220,25 +9225,25 @@ $(cat $Storeinfofile)"
 $(cat $Storepidfile)"
 
     # optional info on stdout
-    case "$Showinfofile" in           # --showinfofile
+    case "$Showinfofile" in           # --printinfofile
       "") ;;
       yes) echo "$Storeinfofile" ;;
-      *)   echo "$Storeinfofile" > "$Showinfofile"         || error "Option --showinfofile: Invalid file $Showinfofile" ;;
+      *)   echo "$Storeinfofile" > "$Showinfofile"         || error "Option --printinfofile: Invalid file $Showinfofile" ;;
     esac
-    case "$Showdisplayenvironment" in # --showenv
+    case "$Showdisplayenvironment" in # --printenv
       "") ;;
       yes) storeinfo dump Xenv ;;
-      *)   echo "$Newxenv_cr" > "$Showdisplayenvironment"  || error "Option --showenv: Invalid file $Showdisplayenvironment" ;;
+      *)   echo "$Newxenv_cr" > "$Showdisplayenvironment"  || error "Option --printenv: Invalid file $Showdisplayenvironment" ;;
     esac
-    case "$Showcontainerid" in        # --showid
+    case "$Showcontainerid" in        # --printid
       "") ;;
       yes) storeinfo dump containerid ;;
-      *)   storeinfo dump containerid > "$Showcontainerid" || error "Option --showid: Invalid file $Showcontainerid" ;;
+      *)   storeinfo dump containerid > "$Showcontainerid" || error "Option --printid: Invalid file $Showcontainerid" ;;
     esac
-    case "$Showcontainerpid1pid" in   # --showpid1
+    case "$Showcontainerpid1pid" in   # --printpid1
       "") ;;
       yes) echo $Pid1pid ;;
-      *)   echo $Pid1pid > "$Showcontainerpid1pid"         || error "Option --showcontainerpid1pid: Invalid file $Showcontainerpid1pid" ;;
+      *)   echo $Pid1pid > "$Showcontainerpid1pid"         || error "Option --printcontainerpid1pid: Invalid file $Showcontainerpid1pid" ;;
     esac
     storeinfo "x11docker=ready"
   } <&0 & storepid $! containershell
