--xpra: XPRA_UINPUT=0 XPRA_MENU_ICONS=0 XPRA_ICON_OVERLAY=0 XPRA_EXPORT_ICON_DATA=0  #167

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -5313,8 +5313,6 @@ start_xpra() {                  # options --xpra / --xpra-xwayland: start and wa
   local Xpracrashcount= Xpraserverpid= Xpraclientpid=
   case $Xserver in
     --xpra|--xpra-xwayland)
-      notify-send 'x11docker: stay tuned, xpra will start soon.' 2>/dev/null &
-      note                   'Stay tuned, xpra will start soon.'
       # loop to keep xpra running.
       # xpra server can crash with some applications like atom editor, --mmap=no fixes that.
       # xpra client can be disconnected after a tty switch, will be restarted in that case.
@@ -5341,10 +5339,18 @@ $(tail $Xpraserverlogfile)"
           }
           verbose -d "Starting Xpra server"
           echo "x11docker [$(timestamp)]: Starting Xpra server" >> $Xpraserverlogfile
-          $Mksu "env $Newxenv GDK_BACKEND=x11 XPRA_OPENGL_DOUBLE_BUFFERED=1 $Xpraservercommand" >> $Xpraserverlogfile 2>&1 &
+          $Mksu "env $Newxenv GDK_BACKEND=x11 XPRA_OPENGL_DOUBLE_BUFFERED=1 XPRA_UINPUT=0 $Xpraservercommand" >> $Xpraserverlogfile 2>&1 &
           Xpraserverpid=$! && storepid $Xpraserverpid xpraserver
           verlt "$Xprarelease" "r23060" && {
             waitforlogentry "xpra server" $Xpraserverlogfile 'xpra is ready' || {
+              rocknroll && error "Xpra server startup failed.
+  Last lines of Xpra server log:
+$(tail $Xpraserverlogfile)"
+              return 1
+            }
+            :
+          } || {
+            waitforlogentry "xpra server" $Xpraserverlogfile 'created unix domain socket' || {
               rocknroll && error "Xpra server startup failed.
   Last lines of Xpra server log:
 $(tail $Xpraserverlogfile)"
@@ -5358,7 +5364,7 @@ $(tail $Xpraserverlogfile)"
         [ -n "$Xpraclientpid" ] && note "Restarting Xpra client."
         verbose -d "Starting Xpra client"
         echo "x11docker [$(timestamp)]: Starting Xpra client" >> $Xpraclientlogfile
-        $Mksu "env $Hostxenv GDK_BACKEND=$GDK_BACKEND NO_AT_BRIDGE=1 XPRA_MENU_ICONS=0 $Xpraclientcommand" >> $Xpraclientlogfile 2>&1 &
+        $Mksu "env $Hostxenv GDK_BACKEND=$GDK_BACKEND NO_AT_BRIDGE=1 XPRA_MENU_ICONS=0 XPRA_ICON_OVERLAY=0 XPRA_EXPORT_ICON_DATA=0 $Xpraclientcommand" >> $Xpraclientlogfile 2>&1 &
         Xpraclientpid=$! && storepid $Xpraclientpid xpraclient
         checkpid $Xpraclientpid && {
           while { checkpid $Xpraserverpid && checkpid $Xpraclientpid ; } do sleep 1 ; done
@@ -5661,6 +5667,7 @@ check_hostuser() {              # check for unprivileged host user
 
   # Mksu: prefix to run command as unprivileged host user
   [ "$Hostuser" = "$Startuser" ] && Mksu="bash -c" || Mksu="su $Hostuser -c"  # differenciated as only root can use su on itself and others without password
+#  [ "$Hostuser" = "$Startuser" ] && Mksu="eval" || Mksu="su $Hostuser -c"  # differenciated as only root can use su on itself and others without password
 
   [ "$Hostuser" = "root" ] && warning "Running as user root.
   Maybe \$(logname) did not provide an unprivileged user.
@@ -6357,7 +6364,6 @@ check_option_interferences() {  # check multiple option interferences, change se
   return 0
 }
 option_messages() {             # some messages depending on options, but not changing settings
-
   # X server specific messages
   case $Xserver in
     --hostdisplay)
@@ -6433,9 +6439,10 @@ option_messages() {             # some messages depending on options, but not ch
   It is recommended to use --xephyr or --nxagent instead.
   Rendering issues can be reduced disabling OpenGL in Xpra tray icon. Screen
   size issues can be avoided with non-integer scaling (e.g. --scale=1.01)."
-      [ "$Desktopmode" = "no" ] && note "Xpra startup is rather slow. For faster startup
+      [ "$Desktopmode" = "no" ] && verlt $Xprarelease r23069 && note "Xpra startup can be slow. For faster startup
   with seamless applications,   try --nxagent.
-  If security is not a concern, try --hostdisplay."
+  If security is not a concern, try --hostdisplay.
+  Xpra version v3.0-r23066 and higher starts up faster."
       [ "$Sharegpu" = "yes" ] && note "If performance of GPU acceleration with $Xserver
   is not satisfying, you can try insecure '--hostdisplay --gpu'."
     ;;
@@ -7444,6 +7451,7 @@ main "$@"
   
 #### ToDo notes for development
 todo() {
+  # replace verbose -d with debugnote
   # --xpra --wayland (experimental): version check, py3 check
   # dependeny wiki: Cygwin packages
   
