V2.1.0 new options --install --update --remove
# 24.02.2017 V 2.1.0  new options --install --update --remove / integrating x11docker-installer.sh

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -6,7 +6,7 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # https://github.com/mviereck/x11docker
 
-Version="V 2.0.0"
+Version="2.1.0"
 
 # ToDo:
 # - --xpra-attach: check --mmap, check virtualgl possibility, --webcam=no versioning, check further options
@@ -22,6 +22,7 @@ Version="V 2.0.0"
 # - try to integrate Alsa sound
 
 # x11docker changelog
+# 24.02.2017 V 2.1.0  new options --install --update --remove / integrating x11docker-installer.sh
 # 24.02.2017 V 2.0.1  minor bugfix syntax
 # 24.02.2017 V 2.0.0  bugfix: xpra crashes on debian 9, leaving black screen. See debian bug 855980
 #                     version check for xpra on option --xpra-attach
@@ -270,6 +271,12 @@ Advanced options:
      --log             show log in an xterm window on display :0
      --LOG             show log in an xterm window on new display
  -v, --verbose         be verbose
+ 
+ Installation options (need root permissions):
+     --install        install x11docker (and x11docker-gui) on your system
+                      (uses /usr/local/bin) (creates icon and desktop entry)
+     --update         update x11docker with latest version from github
+     --remove         remove x11docker from your system
 
 Dependencies: depending on chosen options, x11docker needs some packages
          to be installed. It will check for them on startup and show messages 
@@ -615,9 +622,94 @@ orphaned() { # option --orphaned : check for non-removed containers and left cac
     fi
   fi
 }
+installer() { # options --install, --update, --remove: Installer for x11docker
+  # --install:
+  #   - copies x11docker and x11docker-gui to /usr/local/bin
+  #   - installs icon in /usr/share/icons
+  #   - creates x11docker.desktop file in /usr/share/applications
+  # --update:
+  #   - download and install latest version from github
+  # --remove
+  #   - remove installed files
+  
+  [ "0" = "$(id -u)" ] || { error "Must run as root to install, update or remove x11docker." ; }
+
+  # Prepairing
+  case $1 in
+    --install)
+      [ $(command -v x11docker) ] &&   { error "x11docker seems to be installed already.
+  Try 'x11docker --update' instead." ; }
+      [ -e "./x11docker" ] ||          { error "File x11docker not found in current folder.
+  Try 'x11docker --update' instead." ; }
+      [ `command -v kaptain` ] ||      { warning "x11docker-gui needs package kaptain
+  to provide a GUI, but could not find kaptain on your system. 
+  Please install package kaptain if you want to use x11docker-gui.
+  x11docker itself does not need it." ; }
+    ;;
+    --update)
+      mkdir /tmp/x11docker-install
+      cd /tmp/x11docker-install
+      [ $? ] || error "Could not create or move to /tmp/x11docker-install"
+
+      echo "Downloading latest x11docker version from github"
+      wget https://github.com/mviereck/x11docker/archive/master.zip
+      [ $? ] || error "Could not download x11docker-master from github"
+
+      echo "Unpacking archive"
+      unzip master.zip
+      [ $? ] || error "Could not unzip archive"
+  
+      echo ""
+      cd /tmp/x11docker-install/x11docker-master
+    ;;
+  esac
+
+  # Doing
+  case $1 in
+    --install|--update)
+      echo "Installing x11docker and x11docker-gui in /usr/local/bin"
+      cp x11docker /usr/local/bin/
+      chmod +x /usr/local/bin/x11docker
+      cp x11docker-gui /usr/local/bin/
+      chmod +x /usr/local/bin/x11docker-gui
+
+      echo "Creating icon and application entry for x11docker"
+      x11docker-gui --icon
+      xdg-icon-resource install --context apps --novendor --size 72 /tmp/x11docker.png x11docker
+      rm /tmp/x11docker.png
+      echo "[Desktop Entry]
+Version=1.0
+Type=Application
+Name=x11docker
+Comment=Run GUI applications in docker images
+Exec=x11docker-gui
+Icon=x11docker
+Categories=System
+" > /usr/share/applications/x11docker.desktop
+      echo "Installation ready: x11docker version $(x11docker --version)"
+    ;;
+    --remove)
+      echo "removing x11docker from your system"
+      rm -v /usr/local/bin/x11docker
+      rm -v /usr/local/bin/x11docker-gui
+      rm -v /usr/share/applications/x11docker.desktop
+      xdg-icon-resource uninstall --size 72 x11docker
+    ;;
+  esac
+
+  # Cleanup
+  case $1 in
+    --update)
+      echo "Removing downloaded files"
+      cd ~
+      rm -R /tmp/x11docker-install
+    ;;
+  esac
+}
 xdparser() { # parse args for x11docker
   Shortoptions="hw:daryxXtcFS:RGeuompsnvgliN0U"
   Longoptions="wm:,desktop,auto,x,X,xpra,Xpra,xpra-attach,xephyr,Xephyr,X11,x11,xorg,hostdisplay,exe"          # X server and WM, exe instead of docker
+  Longoptions="install,update,remove,version"
   Longoptions="$Longoptions,fullscreen,resizeable,size:,glamor"                                    # Xephyr options
   Longoptions="$Longoptions,clipboard,hostuser,sudouser,home,pulseaudio,gpu,virtualgl"             # comfort options
   Longoptions="$Longoptions,sudo,root,ipc,ps,verbose,cid,cache,log,LOG,nopwd"                      # advanced options
@@ -668,6 +760,9 @@ xdparser() { # parse args for x11docker
       --orphaned) Orphanedcheck="yes"  ;;               # check for orphaned containers and files owned by root, created by docker)
       -i|--ipc) Shareipc="yes";;                        # set docker option --ipc=host
       -N|--no-xhost) Noxhost="yes"  ;;                  # disable any access granted by xhost
+      ##### Installer options 
+      --install|--update|--remove) installer $1 ; exit ;;
+      --version) echo $Version ; exit ;;
       #####some developer options, not for regular use, can change any time
       --xhost) Xhost="+"  ;;                            # set 'xhost +' on both X servers
       --xsocket) Xconnection="xsocket" ;;               # Use shared X socket
