dependency check in container for setup #235

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4620,6 +4620,17 @@ create_containerrootrc() {      ### create containerrootrc: This script runs as 
 
   echo "debugnote 'Running containerrootrc: Setup as root in container'"
   echo ""
+  
+  echo "Error=''"
+  echo "for Line in cat chmod chown cut cd cp date echo env export grep id ln ls mkdir mv printf rm sed sh sleep tail touch; do"
+  echo "  command -v \"\$Line\" || {"
+  echo "    warning \"ERROR: Command not found in image: \$Line\""
+  echo "    Error=1"
+  echo "  }"
+  echo "done"
+  echo "[ \"\$Error\" ] && error 'Commands for container setup missing in image.
+  You can try with option --no-setup to avoid this error.'"
+  echo ""
 
   echo "# Check type of libc"
   echo "ldd --version 2>&1 | grep -q 'musl libc' && Containerlibc='musl'"
@@ -5632,9 +5643,6 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   echo     "  echo '$(declare -f saygoodbye)'"
   echo     "  echo '$(declare -f storeinfo)'"
   echo     "  echo '$(declare -f waitforlogentry)'"
-  echo     "  echo 'calculate() {'"
-  echo     "  echo '  LC_ALL=C printf %.3f\\\\n \"\$((10**9 * \$@))e-9\"'"
-  echo     "  echo '}'"
   echo     "  echo '$Messagefifofuncs'"
   echo     "  echo 'Messagefile=$(convertpath share $Messagefifo)'"
   echo     "  echo 'Storeinfofile=$(convertpath share $Storeinfofile)'"
@@ -5800,6 +5808,7 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   \\\"\""
   echo     "  echo ''"
   
+#  echo     "  echo 'exec 1>&6 2>&7 6>&- 7>&-'"
   case $Interactive in
     no)
       echo "  echo 'tail -f $(convertpath share $Cmdstdoutlogfile)     2>/dev/null &'"
