skip availability check after docker pull

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4126,7 +4126,7 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
         echo "  $Dockerexe inspect $Imagename >>$Containerlogfile 2>&1 || {"
         echo "    echo 'Image $Imagename not found locally.'"
         echo "    echo 'Do you want to pull it from docker hub?'"
-        echo "    askyesno && Dockerpull=yes"
+        echo "    askyesno && Dockerpull=yes || error 'Image '$Imagename' not available locally and not pulled from docker hub.'"
         echo "  }"
         echo "}"
       }
@@ -4135,21 +4135,12 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo ""
 
   echo "[ \"\$Dockerpull\" = 'yes' ] && {"
-  echo "  note 'Pulling image $Imagename from docker hub'"
+  echo "  note 'Pulling image '$Imagename' from docker hub'"
   case $Passwordneeded in
     no)  echo "  env DISPLAY='$Hostdisplay' DBUS_SESSION_BUS_ADDRESS='${DBUS_SESSION_BUS_ADDRESS:-}' bash           -c \"notify-send 'x11docker: Pulling image $Imagename from docker hub'\" 2>/dev/null &" ;;
     yes) echo "  env DISPLAY='$Hostdisplay' DBUS_SESSION_BUS_ADDRESS='${DBUS_SESSION_BUS_ADDRESS:-}' su '$Hostuser' -c \"notify-send 'x11docker: Pulling image $Imagename from docker hub'\" 2>/dev/null &" ;;
   esac
-  echo "  $Sudo $Dockerexe pull $Imagename 1>&2"
-  echo "}"
-
-  echo "$Dockerexe inspect $Imagename >>$Containerlogfile 2>&1 || {"
-  echo "  error 'Did not find image $Imagename.
-  Please build image first or pull it from docker hub with:
-  
-      docker pull $Imagename
-      
-  or run x11docker with option --pull=yes'"
+  echo "  $Sudo $Dockerexe pull $Imagename 1>&2 || error 'Pulling docker image '$Imagename' seems to have failed!'"
   echo "}"
 
   echo "# check CMD"
