--pull: removed x11docker-gui: removed references / connections

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="6.10.1-beta-5"
+Version="7.0.0-beta-1"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -333,7 +333,7 @@ Verbosity options:
  -V                    Be verbose with colored output. 
 
 Installation options and cleanup (need root permissions):
-     --install         Install x11docker and x11docker-gui from current folder.
+     --install         Install x11docker from current folder.
                        Useful to install from an extracted zip file.
      --update          Download and install latest release from github.
      --update-master   Download and install latest master version from github.
@@ -1334,9 +1334,7 @@ cleanup() {                     # --cleanup : check for non-removed containers a
 
   cd $Cachebasefolder || error "Could not cd to cache folder '$Cachebasefolder'."
 
-  grep -q .cache/x11docker <<<$Cachebasefolder && Orphanedfolders="$(find "$Cachebasefolder" -mindepth 1 -maxdepth 1 -type d | sed s%$Cachebasefolder/%% | grep -w -v x11docker-gui)"
-  # e X11DOCKER_LASTCLEANFOLDER may be set by x11docker-gui to spare its cache folder.
-  [ "${X11DOCKER_LASTCLEANFOLDER:-}" ] && Orphanedfolders="$(echo "$Orphanedfolders" | grep -v $X11DOCKER_LASTCLEANFOLDER)"
+  grep -q -- "\.cache/x11docker" <<< $Cachebasefolder && Orphanedfolders="$(find "$Cachebasefolder" -mindepth 1 -maxdepth 1 -type d | sed s%$Cachebasefolder/%% )"
   Orphanedcontainers="$($Containerbackendbin ps -a | grep x11docker_X | rev | cut -d' ' -f1 | rev)"
   Orphanedcontainers="$Orphanedcontainers $(find "$Cachebasefolder" -mindepth 2 -maxdepth 2 -type f -name 'container.id' -exec cat {} \;)"
   Orphanedcontainers="$(env IFS='' echo $Orphanedcontainers)"
@@ -1449,7 +1447,7 @@ Keywords=docker x11docker $(echo $Name | tr -c '[:alpha:][:digit:][:blank:]' ' '
 }
 installer() {                   # --install, --update, --update-master, --remove: Installer for x11docker
   # --install:
-  #   - copies x11docker and x11docker-gui to /usr/bin
+  #   - copies x11docker to /usr/bin
   #   - installs icon in /usr/share/icons
   #   - creates x11docker.desktop file in /usr/share/applications
   # --update:
@@ -1461,7 +1459,6 @@ installer() {                   # --install, --update, --update-master, --remove
   
   ### FIXME: (--update)
   ### do not require sudo if installed x11docker is owned by user
-  ### do not install x11docker-gui if not present
   ### maybe not install additional files if x11docker is owned by user
   local Key1= Key2= Oldversion= Newversion= Format= 
   local Binpath Binowner Bingroup Binpathdefault
@@ -1556,38 +1553,15 @@ installer() {                   # --install, --update, --update-master, --remove
   # Doing
   case ${1:-} in
     --install|--update|--update-master)
-      note "Installing x11docker and x11docker-gui in $Binpath"
+      note "Installing x11docker in $Binpath"
       cp x11docker "$Binpath/"                                                || error "Could not copy x11docker to $Binpath"
       chmod 755 "$Binpath/x11docker"                                          || error "Could not set executable bit on x11docker"
       chown "$Binowner:$Bingroup" "$Binpath/x11docker"                        || warning "Could not set ownership '$Binowner:$Bingroup' to '$Binpath/x11docker'"
-      cp x11docker-gui "$Binpath/" && {
-        chmod 755 "$Binpath/x11docker-gui"
-        chown "$Binowner:$Bingroup" "$Binpath/x11docker-gui"                  || warning "Could not set ownership '$Binowner:$Bingroup' to '$Binpath/x11docker-gui'"      
-      } || warning "x11docker-gui not found"
 
       note "Installing icon for x11docker with xdg-icon-resource"
       xdg-icon-resource install --context apps --novendor --mode system --size 64 "$(pwd)/x11docker.png" x11docker || warning "Could not install icon for x11docker.
   Is 'xdg-icon-resource' (xdg-utils) installed on your system?"
       xdg-icon-resource uninstall --size 72 x11docker ||:  # deprecated icon size, may still be present.
-
-      note "Creating application entry for x11docker."
-      [ -e "$Binpath/x11docker-gui" ] && {
-        echo "[Desktop Entry]
-  Version=1.0
-  Type=Application
-  Name=x11docker
-  Comment=Run GUI applications in docker images
-  Exec=x11docker-gui
-  Icon=x11docker
-  Categories=System
-" > /usr/share/applications/x11docker.desktop
-      } || note "Did not create desktop entry for x11docker-gui"
-      command -v kaptain >/dev/null || note "Could not find 'kaptain' for x11docker-gui.
-  Consider to install 'kaptain' (version 0.73 or higher).
-  It's useful for x11docker-gui only, though. x11docker itself doesn't need it.
-  If your distributions does not provide kaptain, look at kaptain repository:
-    https://github.com/mviereck/kaptain
-  Fallback: x11docker-gui will try to use image x11docker/kaptain."
 
       note "Storing README.md, CHANGELOG.md and LICENSE.txt in
   /usr/share/doc/x11docker"
@@ -1603,10 +1577,8 @@ installer() {                   # --install, --update, --update-master, --remove
     --remove)
       note "Removing x11docker from your system."
       cleanup
-      [ -x "$Binpath/x11docker" ] && {
-        rm -v "$Binpath/x11docker"
-        rm -v "$Binpath/x11docker-gui"
-      }
+      [ -x "$Binpath/x11docker" ]     && rm -v "$Binpath/x11docker"
+      [ -x "$Binpath/x11docker-gui" ] && rm -v "$Binpath/x11docker-gui"
       [ -e "/usr/share/applications/x11docker.desktop" ] && rm -v /usr/share/applications/x11docker.desktop
       [ -e "/usr/share/doc/x11docker" ]                  && rm -R -v /usr/share/doc/x11docker
       [ -e "/usr/share/icons/x11docker.png" ]            && rm /usr/share/icons/x11docker.png
@@ -5745,7 +5717,6 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   echo "Exec="
   echo "Entrypoint="
   echo "Failure="
-  echo "Imagepull="
   echo "Imageuser="
   echo "Inspect="
   echo "Line="
@@ -5789,7 +5760,6 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
 }"
   echo ""
 
-  
   echo "# Check default runtime"
   echo "Runtime=\"\$( { grep 'Default Runtime' < '$Dockerinfofile' ||: ;} | awk '{print \$3}' )\""
   echo '[ -n "$Runtime" ] && {' 
@@ -5811,57 +5781,14 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
   echo "debugnote \"dockerrc: Container Runtime: \$Runtime\""
   echo "storeinfo \"runtime=\$Runtime\""
   echo ""
-  
-  echo "# Refresh images.list for x11docker-gui" ### FIXME makes no sense with multiple backends. But list needed below.
-  echo "$Containerbackendbin images 2>>$Containerlogfile | grep -v REPOSITORY | awk '{print \$1 \":\" \$2}' >>$Dockerimagelistfile.sort"
-  echo "rmcr $Dockerimagelistfile.sort"
-  echo "while read -r Line ; do"
-  echo '  grep -q "<none>" <<<$Line || echo $Line >> '$Dockerimagelistfile
-  echo "done < <(sort < $Dockerimagelistfile.sort)"
-  echo "rm $Dockerimagelistfile.sort"
-  echo ""
 
   echo "# Check if image $Imagename is available locally"
-  echo "Imagepull=no"
-  case $Pullimage in
-    no) ;;
-    always) echo "Imagepull=yes" ;;
-#    yes) echo "$Containerbackendbin inspect $Imagename >>$Containerlogfile 2>&1 || Imagepull=yes" ;;
-    yes) echo "$Containerbackendbin images | grep -q '^$Imagename ' || Imagepull=yes" ;;
-    ask)
-      [ "$Runsinterminal" = "yes" ] && {
-        echo "grep -x -q '$Imagename' < $Dockerimagelistfile || grep -x -q '$Imagename:latest' < $Dockerimagelistfile || {"
-        echo "  $Containerbackendbin images | grep -q '^$Imagename ' || {"
-        echo "    echo $Imagename | grep -q 'x11docker/' && echo 'You can build images from x11docker repository with e.g.:
-  x11docker --build $Imagename
-'"
-        echo "    echo 'Image $Imagename not found locally.' >&2"
-        echo "    echo 'Do you want to pull it from docker hub?' >&2"
-        echo "    askyesno && Imagepull=yes || error \"Image '$Imagename' not available locally and not pulled from docker hub.\""
-        echo "  }"
-        echo "}"
-      }
-    ;;
-  esac
+  echo "Inspect=\"\$($Containerbackendbin inspect $Imagename)\" || error 'Image $Imagename not found locally.
+  Please pull or build image first.'"
   echo ""
   
   echo "rocknroll || exit 64"
   echo ""
-
-  echo "[ \"\$Imagepull\" = 'yes' ] && {"
-  echo "  note \"Pulling image '$Imagename' from docker hub\""
-  [ "$Runsinterminal" = "no" ] && case $Passwordneeded in
-    no)  echo "  env DISPLAY='$Hostdisplay' DBUS_SESSION_BUS_ADDRESS='${DBUS_SESSION_BUS_ADDRESS:-}' bash           -c \"notify-send 'x11docker: Pulling image $Imagename'\" 2>/dev/null &" ;;
-    yes) echo "  env DISPLAY='$Hostdisplay' DBUS_SESSION_BUS_ADDRESS='${DBUS_SESSION_BUS_ADDRESS:-}' su '$Hostuser' -c \"notify-send 'x11docker: Pulling image $Imagename'\" 2>/dev/null &" ;;
-  esac
-  echo "  $Sudo $Containerbackendbin pull $Imagename 1>&2 || error \"Pulling image '$Imagename' seems to have failed!\""
-  echo "}"
-  echo ""
-
-  echo "rocknroll || exit 64"
-  echo ""
-
-  echo "Inspect=\"\$($Containerbackendbin inspect $Imagename)\""
   
   echo "# Check architecture"
   echo 'Containerarchitecture=$(parse_inspect "$Inspect" "Architecture")'
@@ -6748,6 +6675,7 @@ check_host() {                  # check host environment
   Pythonbin="$(command -v python)"
   [ -z "$Pythonbin" ] && Pythonbin="$(command -v python3)"
   [ -z "$Pythonbin" ] && Pythonbin="$(command -v python2)"
+  "$Pythonbin" --version >/dev/null 2>&1 || Pythonbin=""
   [ -z "$Pythonbin" ] && error "x11docker needs 'python' to parse output of '$Containerbackend inspect'.
   This is needed to check ENTRYPOINT and CMD that in turn is needed to set up
   some x11docker features. To allow more features, please install 'python'
@@ -7542,16 +7470,6 @@ check_option_interferences() {  # check multiple option interferences, change se
     ;;
   esac
   
-  # --pull
-  case "$Pullimage" in
-    yes|no|always|ask) ;;
-    *) note "Option --pull: Invalid argument: $Pullimage
-  Allowed arguments: yes|no|always|ask
-  Fallback: Setting --pull=ask" 
-      check_fallback
-    ;;
-  esac
-  
   case "$Runtime" in
     ""|runc|crun|oci) ;;
     nvidia) Sharegpu="yes" ;;
@@ -7912,7 +7830,6 @@ $Hostuserhome/.cache/x11docker/symlink
   Xclientcookie="$Sharefolder/$Xclientcookie"                       && mkfile $Xclientcookie
   
   # Files in $Cachebasefolder
-  Dockerimagelistfile="$Cachebasefolder/$Dockerimagelistfile"       && mkfile $Dockerimagelistfile
   Logfilebackup="$Cachebasefolder/x11docker.log"
   Modelinefilebasepath="$Cachebasefolder/$Modelinefilebasepath"
   
@@ -8423,7 +8340,6 @@ declare_variables() {           # declare global variables
   Xpraserverlogfile="xpra.server.log"             # Logfile for xpra server
     
   Dockercommandfile="docker.command"              # File to store generated docker command, needed for --interactive
-  Dockerimagelistfile="docker.imagelist"          # File with list of local images.Used by x11docker-gui, too
   Dockerinfofile="docker.info"                    # File to store output of 'docker info'
   
   # Generated commands
@@ -8650,12 +8566,10 @@ declare_variables() {           # declare global variables
   Presetdirlocal="$HOME/.config/x11docker/preset"
   Presetdirsystem="/etc/x11docker/preset"
   Preservecachefiles="no"                         # If yes, don't delete cache files on exit. For few failure cases only.
-  Pullimage="ask"                                 # --pull: Allow 'docker pull' yes|no|always|ask
   X11dockermode="run"                             # --exe, --xonly: Can be either "run" (default), "exe", or "xonly".
   
   # Verbosity options
   Debugmode="no"                                  # --debug: Excerpt of --verbose, also bash error checks
-  Showcache="no"                                  # --showcache: Output of $Cachefolder on stdout (x11docker-gui only)
   Showcontainerid="no"                            # --showid: Output of container ID on stdout
   Showcontaineroutput="yes"                                # Show container command stdout
   Showcontainerpid1pid="no"                       # --showpid1: Output of host PID of container PID 1 on stdout
@@ -8757,9 +8671,9 @@ parse_options() {               # parse cli options
   Longoptions="$Longoptions,dbus::,init::,hostdbus,sharecgroup"                                                            # Container init and DBus
   Longoptions="$Longoptions,stdin,interactive"                                                                             # Container interaction
   Longoptions="$Longoptions,runasuser:,runfromhost:,runasroot:"                                                            # Additional commands to execute
-  Longoptions="$Longoptions,showenv,showid,showinfofile,showpid1,showcache"                                                # Output of vars on stdout
+  Longoptions="$Longoptions,showenv,showid,showinfofile,showpid1"                                                          # Output of vars on stdout
   Longoptions="$Longoptions,debug,quiet,verbose"                                                                           # Verbose options
-  Longoptions="$Longoptions,build,cleanup,help,launcher,licence,license,version,wmlist"                                    # Special options without starting X or container
+  Longoptions="$Longoptions,build,cleanup,help,launcher,licence,license,version"                                           # Special options without starting X or container
   Longoptions="$Longoptions,install,remove,update,update-master"                                                           # Installation
   #
   Longoptions="$Longoptions,backend:,keepcache,no-setup,podman,xopt:,xorgconf:"                                            # Experimental
@@ -8773,7 +8687,6 @@ parse_options() {               # parse cli options
   
   [ "$*" = "-h --" ] &&       usage &&        exit 0                 # Catch single -h for usage info, otherwise it means --hostdisplay
   [ "$*" = "--" ]    &&       usage &&        exit 0                 # x11docker without options
-  [ "$*" = "-- --" ] &&       usage &&        exit 0                 # x11docker-gui without options
   
   while [ $# -gt 0 ]; do
     case "${1:-}" in
@@ -8803,7 +8716,6 @@ parse_options() {               # parse cli options
          --help)              usage ;         exit 0 ;;              # Show help/usage and exit
          --license|--licence) license ;       exit 0 ;;              # Show MIT license and exit
          --version)           echo $Version ; exit 0 ;;              # Output version number and exit
-         --wmlist)            echo $Wm_all ;  exit 0 ;;              # Special option for x11docker-gui to retrieve list of window managers
 
       -e|--exe)               X11dockermode="exe" ;;                 # Execute application from host instead of running docker image
          --xonly)             X11dockermode="xonly" ;;               # Only create X server
@@ -8979,7 +8891,6 @@ ${2:-}"                       ; shift ;;                             # Add custo
       -v|--verbose)           Verbose="yes" ;;                       # Be verbose  
       -V)                     Verbose="yes"; Verbosecolors="yes";;   # Be verbose with colored output
       -q|--quiet)             Silent="yes" ;;                        # Do not show warnings or errors
-         --showcache)         Showcache="yes" ;;                     # Output of $Cachefolder. For x11docker-gui only
          --showenv)           Showdisplayenvironment="yes" ;;        # Output of display number and cookie file on stdout. Catch with: read xenv < <(x11docker --showenv)
          --showid)            Showcontainerid="yes" ;;               # Output of container id on stdout
          --showpid1)          Showcontainerpid1pid="yes" ;;          # Output of host PID of container PID 1
@@ -9009,9 +8920,7 @@ ${2:-}"                       ; shift ;;                             # Add custo
                               note "Option --no-internet is deprecated.
   Please use --network=none instead." ;;
          --podman)            Containerbackend="podman" ;         note "Option --podman is deprecated. Use --backend=podman instead." ;;         
-         --pull)              Pullimage="${2:-yes}" ; shift          # Allow 'docker pull'
-                              note "Option --pull is deprecated. 
-  Please use 'docker pull'  or 'x11docker --build IMAGE'  instead." ;;
+         --pull)              error "Option --pull has been removed. Please pull images yourself." ;; 
          --sharessh)          [ -e "${SSH_AUTH_SOCK:-}" ] && {       # SSH socket sharing
                                 store_runoption volume "$(dirname $SSH_AUTH_SOCK)"
                                 store_runoption env "SSH_AUTH_SOCK=$(escapestring "${SSH_AUTH_SOCK:-}")"
@@ -9306,7 +9215,6 @@ $(cat $Storepidfile)"
     
     # optional info on stdout
     [ "$Showinfofile" = "yes" ]           && echo "$Storeinfofile"                # --showinfofile
-    [ "$Showcache" = "yes" ]              && echo "$Cachefolder"                  # --showcache (x11docker-gui only)
     [ "$Showdisplayenvironment" = "yes" ] && echo "$(storeinfo dump Xenv)"        # --showenv
     [ "$Showcontainerid" = "yes" ]        && echo "$(storeinfo dump containerid)" # --showid
     [ "$Showcontainerpid1pid" = "yes" ]   && echo "$Pid1pid"                      # --showpid1
