Release v5.3.2

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="5.3.2-beta"
+Version="5.3.2"
 
 usage() {                       # --help: show usage information
   echo "
@@ -3877,11 +3877,18 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo "done < <(sort < $Cachefolder/images.list)"
   echo ""
 
-  echo "# check if image is available locally"
+  echo "# check whether image is available locally"
   echo "$Dockerexe inspect --type=image $Imagename >/dev/null 2>&1 || {"
   [ "$Pullterminal" = "$Passwordterminal" ] && [ "$Passwordneeded" = "yes" ] && Pullterminal=""
   echo "  env $Terminalxenv $Pullterminal /bin/bash $Pullrc"
-  echo "  waitforfilecreation $Cachefolder/pullready infinity"
+  echo "  waitforfilecreation $Cachefolder/pullterminalready 5 && {"
+  echo "    rm $Cachefolder/pullterminalready"
+  echo "    waitforfilecreation $Cachefolder/pullready infinity ||:"
+  echo "  } || {"
+  echo "    warning 'Interactive terminal to ask for and show \"docker pull\"
+  has failed. Will run \"docker pull $Imagename\" nonetheless.'"
+  echo "    $Dockerexe pull $Imagename 2>> $Containerlogfile"
+  echo "  }"
   echo "  $Dockerexe inspect --type=image $Imagename >>$Containerlogfile 2>&1 || {"
   echo "    error \"Image '$Imagename' not found locally
   and not pulled from docker hub. Last lines of log:
@@ -3963,7 +3970,7 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   esac
   echo ""
 
-  echo "[ -z \"\$Imagecommand\$Entrypoint\" ] && warning 'No image command specified and no CMD or ENTRYPOINT found in image.'"
+  echo "[ -z \"\$Imagecommand\$Entrypoint\" ] && error 'No image command specified and no CMD or ENTRYPOINT found in image.' && exit 1"
   echo ""
 
   #### create container.CMD.sh ####
@@ -4197,7 +4204,7 @@ create_containerrootrc() {      # create container root setup script: This scrip
   
   echo "id"
   
-  [ "$Debugmode" = "yes" ] && echo "set -x"
+  #[ "$Debugmode" = "yes" ] && echo "set -x"
   
   echo "$Messagefifofuncs"
   echo "Messagefile=$Cshare/message.fifo"
@@ -4681,6 +4688,7 @@ create_pullrc() {               # create pullrc: interactive script to pull imag
   echo "  exit"
   echo "}"
   echo "trap touchpullready EXIT"
+  echo ":>$Cachefolder/pullterminalready"
   echo "echo ''"
   [ "$Winsubsystem" ] && echo "export PATH=\"$(convertpath --subsystem "C:/Program Files/docker"):$(convertpath --subsystem "C:/Program Files/Docker/Docker/resources/bin"):\$PATH\""
   echo "read -n1 -e -p \"Image '$Imagename' not found locally. "
