Append "-beta" to master version

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -2,14 +2,15 @@
 
 # x11docker
 # Run GUI applications and desktop environments in docker on a separate X server or Wayland compositor.
-# Circumvents common X security leaks. 
-# Provides GPU acceleration and pulseaudio sound. 
-# Restrictes docker container privileges with 'docker run --cap-drop=ALL --security-opt=no-new-privileges' 
-# Container user is same as host user to avoid root in container.
+#
+# - Circumvents common X security leaks. 
+# - Improves container security restricting container capabilities
+# - Container user is same as host user to avoid root in container.
+#
 # Type 'x11docker --help' or scroll down to read usage information.
-# https://github.com/mviereck/x11docker
+# More documentation at   https://github.com/mviereck/x11docker
 
-Version="4.1.0"
+Version="4.1.1-beta"
 
 usage() {               # --help: show usage information
   echo "
@@ -576,7 +577,7 @@ saygoodbye() {          # create file signaling watching processes to terminate
   verbose "Creating $Timetosaygoodbye"
   [ -e "$Sharefolder" ] && $Mksu "touch $Timetosaygoodbye"
 }
-finish() {              # trap routine, clean up background processes and cache
+finish() {              # trap EXIT routine to clean up background processes and cache
   local Pid Name Zeit
   trap - EXIT
   verbose "terminating x11docker ..."
@@ -660,10 +661,10 @@ x11docker --cleanup"
   [ "$Preservecachefiles" = "no" ] && echo "$Cachefolder" | grep -q .cache && echo "$Cachefolder" | grep -q x11docker && [ "x11docker" != "$(basename "$Cachefolder")" ] && rm -f -R "$Cachefolder"
   if [ -e "$Errorfile" ]; then rm "$Errorfile" ; exit 1; else exit 0; fi
 }
-traperror() {
-  warning "Command at Line $2 returned with error code $1:
-  $4
-  $3 - $5" 
+traperror() {           # trap ERR: --debug: Output for debugging
+  warning "Command at Line ${2:-} returned with error code ${1:-}:
+  ${4:-}
+  ${3:-} - ${5:-}" 
 }
 verlte() {              # version number check $1 less than or equal $2
   [  "${1:-}" = "$(echo -e "${1:-}\n${2:-}" | sort -V | head -n1)" ] && return 0 || return 1
@@ -4585,7 +4586,9 @@ $(tail $Compositorlogfile)"
 
 ######### ToDo notes for development
 todo() {
-# work on traperror()
+# docker exec: set other environment variables, too?
+# work on traperror(). 'set -u' possible without a stop?
+# check for other init systems in ENTRYPOINT, especially systemd
 #
 # --dbus-system: policykit must not have no-new-privileges. Seems to use setuid? Core issue AccountsService?
 #                starting polkitd and accounts-daemon in setupscript helps:
@@ -4600,6 +4603,7 @@ todo() {
 # check out possibilities to allow 'sudo docker' directly again.
 # xpra restart on tty switch -> bug report
 # --xpra --desktop restarts client if closing desktop window
+# bug report to docker about --volume in --volume
 
 # --lang: find out locale package names for several distris for documentation
 # --keymap does not work on tty with --kwin and --kwin-xwayland. No idea how to set it.
@@ -4607,7 +4611,7 @@ todo() {
 
 # BUG check whether VT is not in use with --xorg/--xpra/--xdummy, bug if accidently using vt that is already in use
 # check all FIXME 
-# note: SYS_PTRACE allows polkit in docker
+# note: SYS_PTRACE allows polkit in docker?
 # --systemd: try to avoid xhost +SI:localuser:$Benutzer
 # --xpra-xwayland, xdummy-xwayland: use kwin-wayland as fallback for missing weston? 
 # --xorg: getty and autologin to avoid Xwrapper.config changes?
