Avoid xpra server error message if container terminates fast. #134

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -2190,14 +2190,14 @@ $(xhost 2>&1 | rmcr)"
 check_newxenv() {               # find free display, create $Newxenv
   # find free display number
   [ "$Newdisplaynumber" ] || for ((Newdisplaynumber=100 ; Newdisplaynumber <=1000 ; Newdisplaynumber++)); do
-    [ -n "$(find /tmp/.X11-unix/X$Newdisplaynumber /tmp/.X$Newdisplaynumber-lock $XDG_RUNTIME_DIR/wayland-$Newdisplaynumber 2>/dev/null)" ] || { 
+    [ -n "$(find /tmp/.X11-unix/X$Newdisplaynumber /tmp/.X$Newdisplaynumber-lock ${XDG_RUNTIME_DIR:-}/wayland-$Newdisplaynumber 2>/dev/null)" ] || { 
       case $Xserver in
         --vcxsrv) grep -q -E 'Authorization|Absolute' <<< "$(xwininfo.exe -display :$Newdisplaynumber -root 2>&1)" || break ;;
         *) break ;;
       esac
     }
   done
-  
+
   # X over IP/TCP
   [ "$Xoverip" ] || case $Xserver in
     --vcxsrv|--xwin) Xoverip="yes" ;;
@@ -4943,9 +4943,12 @@ $(tail $Xpraserverlogfile)"
           verbose -d "Starting Xpra server"
           $Mksu "env $Newxenv XPRA_OPENGL_DOUBLE_BUFFERED=1 $Xpraservercommand" >> $Xpraserverlogfile 2>&1 &
           Xpraserverpid=$! && storepid $Xpraserverpid xpraserver
-          waitforlogentry "xpra server" $Xpraserverlogfile 'xpra is ready' && verbose "Xpra server is ready" || error "Xpra server startup failed.
+          waitforlogentry "xpra server" $Xpraserverlogfile 'xpra is ready' && verbose "Xpra server is ready" || {
+            warning xpra
+            rocknroll && error "Xpra server startup failed.
   Last lines of Xpra server log:
 $(tail $Xpraserverlogfile)"
+          }
         }
 
         # xpra client
