Add files via upload

diff --git a/x11docker-gui b/x11docker-gui
--- a/x11docker-gui
+++ b/x11docker-gui
@@ -9,30 +9,24 @@
 # option -d shows some developer options
 
 
-if test ! `command -v kaptain` ; then
-  echo "Error: did not find executeable 'kaptain'. Please install package 'kaptain' and try again." >&2
-  xmessage "Error: did not find executeable 'kaptain'. Please install package 'kaptain' and try again."
+error() {
+  echo $1
+  xmessage $1
   exit 1
-fi
-
-if [ "$(echo $PATH | grep $(dirname $0) )" = "" ] ; then # avoid check for ./x11docker if running in $PATH. Important for desktop starters
-  X11DOCKER="./x11docker"
-else
-  X11DOCKER="x11docker"
-fi
-if test ! `command -v $X11DOCKER` ; then X11DOCKER="x11docker" ; fi
-if test ! `command -v $X11DOCKER` ; then
-  MESSAGE="Error: did not find executeable 'x11docker', neither in \$PATH. nor as
-  executeable ./x11docker.
-  Please make x11docker available (for example in /usr/local/bin) and try again."
-  echo     $MESSAGE >&2
-  xmessage $MESSAGE
-  exit 1
-fi
-VERSION="$(x11docker --version)"
+}
 
 
-if [ "$1" = "-d" ] ; then DEVELOPEROPTIONS="developeroptions" ; fi  # option -d shows developer options
+[ -n "$(command -v kaptain)" ] || error "Error: did not find executeable 'kaptain'. Please install package 'kaptain' and try again."
+
+# Try to find x11docker
+[ -n "$(echo $PATH | grep $(dirname $0) )" ] && X11DOCKER="x11docker"                          # if x11docker-gui is running in $PATH, x11docker will be there,too(I assume) 
+[ -z "$X11DOCKER" ]                          && X11DOCKER="$PWD/x11docker"                     # otherwise, look in current directory
+[ -e "$X11DOCKER" ] || error "Error: did not find x11docker, neither in \$PATH nor in current directory"
+[ -z "$(command -v $X11DOCKER)" ]            && X11DOCKER="bash $PWD/x11docker"                # if not marked as executeable, run with bash
+
+VERSION="$($X11DOCKER --version)"
+
+[ "$1" = "-d" ] && DEVELOPEROPTIONS="developeroptions"  # option -d shows developer options
 
 #####################
 # Preset some options you may want to be set as default
