V3.6.2.5  sh instead of bash to run image command
# 05.10.2017 V3.6.2.5   no_xhost() after cookie creation avoids xhost warning on Xwayland 
# 04.10.2017            --output-count in --auto mode: choose --weston-xwayland
# 01.10.2017            --display: allow : before display number
# 30.09.2017            sh instead of bash to run x11docker_CMD

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -8,14 +8,18 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # https://github.com/mviereck/x11docker
 
-Version="3.6.2.4"
+Version="3.6.2.5"
 
 changelog() { 
+# 05.10.2017            no_xhost() after cookie creation avoids xhost warning on Xwayland 
+# 04.10.2017            --output-count in --auto mode: choose --weston-xwayland
+# 01.10.2017            --display: allow : before display number
+# 30.09.2017            sh instead of bash to run x11docker_CMD
 # 27.09.2017 V3.6.2.4   --starter: missing xdg-user-dir is no longer an error
 #                       --silent: redirect stderr already while parsing
 #                       --user=root: disable --cap-drop=ALL
 #                       --help: update usage info
-#                       weston.ini: background color and zoom-in
+#                       weston.ini: background color and zoom-in effect
 # 26.09.2017            bugfix --xonly: do not fail if docker daemon is not running
 # 25.09.2017            use Kwin/Kwin-Xwayland as fallback for Weston/Weston-Xwayland
 #                       catch closing xpra client in every case, not only in desktop mode
@@ -43,7 +47,7 @@ changelog() {
 }
 todo() {
 # check all FIXME 
-# try xpra ssh setup
+# --xpra-xwayland, xdummy-xwayland: use kwin-wayland as fallback for missing weston? 
 # xpra --desktop: client window has wrong size, communication issue with xpra server? better with scale not being integer
 # fedora: SElinux issue: '--security-opt label=type:container_runtime_t': need more restrictive setting
 #         https://unix.stackexchange.com/questions/386767/selinux-and-docker-allow-access-to-x-unix-socket-in-tmp-x11-unix
@@ -58,12 +62,10 @@ todo() {
 # BUG KDE-Wayland fails with different --user, seems to be ownership issues with wayland socket
 ### BUG collection: non x11docker bugs
 # BUG kdeneon/all:user-lts plasmashell: no kwin?
-# BUG Xwayland does not always sit at 0:0 on multiple outputs
-# BUG Xwayland ignores xhost -SI:localuser:$USER
+# BUG Xwayland does not always sit at 0:0 on multiple outputs. bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1498665
 # BUG nxagent with x11docker/lxde: segmentation fault of lxpanel with --userns-remap. bug in nxagent, lxpanel or x11docker?
 # BUG --kwin*: wrong fullscreen and crashes in gnome-wayland, strange in weston, WAYLAND_DISPLAY="" does not help, probably bug in kwin
-# BUG --output-count: sometimes multiple windows don't close although x11docker is finished. high cpu load, probably Weston and Kwin bug
-# BUG scale>1 Xwayland in Weston is too large (Xwayland bug), rendering issues on tty (switching scaled/unscaled Xwayland on keyboard/mouse events)
+# BUG scale>1 Xwayland in Weston is too large (Xwayland bug), rendering issues on tty (switching scaled/unscaled Xwayland on keyboard/mouse events) bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1498669
 # BUG x11docker-gui in weston freezes weston in combo boxes. Weston bug ? QT3/4 bug?
 # BUG debian bug report lightdm/sddm contra gdm, dm can crash on tty switch if multiple graphical sessions are running
   :
@@ -160,7 +162,7 @@ X server options:
                        Ubuntu 16.04 and debian 9: Install xserver-xorg-legacy.
  
 Special X servers:
- -n, --nxagent         Like --xpra for single applications, but faster.
+ -n, --nxagent         Like --xpra for single applications, but faster startup.
                        With --desktop like --xephyr, but resizeable.
                        (Needs 'nxagent' to be installed). (Experimental).
  -N, --kwin-native     Seamless X and Wayland together. (Experimental).
@@ -198,18 +200,18 @@ Screensize and appearance options:
      --dpi N           dpi value (dots per inch) to submit to clients.
                        Influences font size of some applications.
      --output-count N  Multiple outputs for Weston, KWin or Xephyr.
-     --xfishtank       Show fish tank on new X server (needs xfishtank)
+     --xfishtank       Show fish tank on new X server (needs 'xfishtank').
                        
 Advanced options:
  -v, --verbose         Be verbose. (Shows logfiles).
      --silent          Do not show any terminal messages.
      --stdout          Show stdout of container applications.
-     --stderr          Show stderr of container applcations.
+     --stderr          Show stderr of container applications.
  -E, --waylandenv      Set some environment variables summoning some toolkits
                        to use Wayland. (GTK3 QT5 Clutter SDL Elementary Evas)
  -b, --dbus            Start image command with dbus-launch.
                        (often needed for QT5 applications running on Wayland).
-                       (Needs dbus-x11 to be installed in image)
+                       (Needs dbus-launch to be installed in image)
      --no-entrypoint   Disable ENTRYPOINT in image to allow other commands, too
      --pw FRONTEND     Choose frontend for password prompt. Possible FRONTEND:
                          su sudo gksu gksudo lxsu lxsudo kdesu kdesudo
@@ -219,7 +221,7 @@ Developer options:
      --user N          Create container user N (N=name or N=uid). Default: 
                        same as host user. N can also be an unknown user id.
                        You can specify a group id with N being 'user:gid'.
-     --sudouser        sudo without password for container user,
+     --sudouser        sudo without password for container user.
                        Severe reduction of default x11docker security!
      --hostuser USER   Run X (and container user) as user USER. Default is
                        result of \$(logname). (x11docker must run as root).
@@ -233,7 +235,7 @@ Developer options:
  -o, --no-xhost        Disable any access to host X server granted by xhost
      --no-auth         Disable cookie authentication on new X server.
      --trusted         Use trusted cookies for --hostdisplay and --kwin-native
- -   --untrusted       Create untrusted cookies. Restricts X access. 
+     --untrusted       Create untrusted cookies. Restricts X access. 
                        Default for --hostdisplay and --kwin-native to avoid
                        MIT-SHM errors. Avoids keylogging with --hostdisplay.
                        If --gpu is set, --trusted is used.
@@ -965,7 +967,9 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
          --env)        Customenvironment="$Customenvironment\n${2:-}" ; shift ;;   # set custom environment variables
       -S|--sharewayland) Sharewayland="yes" ;;             # Share wayland socket
          --vt)         Newxvt="vt${2:-}" ;       shift ;;  # set virtual console to use
-         --display)    Newdisplaynumber=${2:-} ; shift ;;  # set display to use
+         --display)    Newdisplaynumber=${2:-}             # display number to use
+                       [ "$(echo $Newdisplaynumber | cut -c1)" = ":" ] && Newdisplaynumber="$(echo $Newdisplaynumber | cut -c2-)"
+                       shift ;;  
          
        ## X Authentication
          --xhost)      Xhost="xhost $2" ; shift ;;         # set 'xhost +' on both X servers
@@ -1173,13 +1177,6 @@ Parsed options: $Parsedoptions"
     [ "$Xserver" = "Xephyr" ]  && { command -v "Xephyr" >/dev/null 2>&1 || Xserver="Weston-Xwayland" ; } # try weston if Xephyr is missing
     [ "$Gpu" = "yes" ] && [ "$Xserver" = "Xephyr" ]  && Xserver="Weston-Xwayland"
     [ -z "$Hostdisplay" ] && Xserver="Xorg"
-
-    #command -v "nxagent" >/dev/null && {   # currently disabled as nxagent is experimental
-    #  case $Xserver in
-    #    Xpra)   Xserver="Nxagent" ;;
-    #    Xephyr) Xserver="Nxagent" ; Desktopmode="yes" ;;
-    #  esac
-    #}
   }
 
   ## check if dependencies for chosen X server are installed
@@ -1221,6 +1218,8 @@ Parsed options: $Parsedoptions"
   Fallback: Will try to run Weston"
     Xserver="Weston"
   }
+  
+  [ "$Outputcount" != "1" ] && [ "$Autochooseserver" = "yes" ] && Xserver="Weston-Xwayland"
   
   [ "$Xserver" = "Nxagent" ] && {
     command -v "nxagent" >/dev/null 2>&1 || {  
@@ -1377,6 +1376,12 @@ Parsed options: $Parsedoptions"
   [ "$Xserver" = "Xorg" ] && {
     [ "$Autochooseserver" = "yes" ] && [ -n "$Hostdisplay" ] && note "Could not find Xephyr or an alternative
   to run desktop in container. Will try to run a second core Xorg server."
+    note "You can switch between X servers and console terminals
+  with [CTRL][ALT][F1]...[F12]."
+    warning "On debian 9, often switching between multiple X servers can 
+  cause a crash of one X server. This bug may be debian specific and is 
+  probably some sort of race condition. If you know more about this or it 
+  occurs on other systems, too, please report."
     # if x11docker is running from within an X server, check if user is allowed to run a new core X server
     [ -z "$Newxvt" ] && {
       if [ ! -e "/etc/X11/Xwrapper.config" ] || [ -z "$(cat /etc/X11/Xwrapper.config | grep "allowed_users" | grep "anybody")" ] ; then
@@ -1545,6 +1550,7 @@ Parsed options: $Parsedoptions"
     case $Xserver in
       Weston-Xwayland) note "Weston does not work well with Xwayland in scaled mode.
   In summary, Xwayland does not get the right screen resolution from Weston.
+  (Bug report at https://bugzilla.redhat.com/show_bug.cgi?id=1498669 ).
   Try out if it works for you. Otherwise, you can combine 
   '--xpra-xwayland --desktop --scale $Scaling' for better desktop scaling support.
   --scale for single applications works best with --xpra / --xpra-xwayland.
@@ -1590,7 +1596,8 @@ Parsed options: $Parsedoptions"
     Weston|Kwin|Hostwayland)
      note "You are running a pure Wayland environment.
   X applications without Wayland support will fail."
-    [ "$Dbuslaunch" = "no" ] || [ "$Setwaylandenv" = "no" ] && note "QT5 / KDE applications need options --dbus --waylandenv to run in Wayland."
+    [ "$Dbuslaunch" = "no" ] || [ "$Setwaylandenv" = "no" ] && note "QT5 / KDE applications need 
+  options --dbus --waylandenv to run in Wayland."
     ;;
   esac
 
@@ -1616,7 +1623,8 @@ Parsed options: $Parsedoptions"
     case $Xserver in
       Weston-Xwayland) note "Xwayland sometimes does not position itself well
   at origin 0+0 of first virtual screen, and some screens appear to be unused. 
-  You may need to move Xwayland manually with [META]+[LeftMouseButton]." ;;
+  You may need to move Xwayland manually with [META]+[LeftMouseButton].
+  (Bug report at https://bugzilla.redhat.com/show_bug.cgi?id=1498665 )" ;;
       Xephyr) note "Xinerama support would be best for multiple outputs,
   but is disabled in Xephyr because Xephyr does not handle it well.
   Different window managers handle this different. Just try out." ;;
@@ -2698,8 +2706,8 @@ done
       # add custom docker arguments, imagename and imagecommand
       Dockercommand="$Dockercommand $Dockeroptions"
       case $Sudouser in
-        no)  Dockercommand="$Dockercommand -- $Imagename /bin/bash $Cshare/x11docker_CMD" ;;
-        yes) Dockercommand="$Dockercommand -- $Imagename /bin/bash $Cshare/createsudouser" ;;
+        no)  Dockercommand="$Dockercommand -- $Imagename /bin/sh $Cshare/x11docker_CMD" ;;
+        yes) Dockercommand="$Dockercommand -- $Imagename /bin/sh $Cshare/createsudouser" ;;
       esac
     ;;
   esac
@@ -2740,7 +2748,7 @@ done
   [ "$Dbuslaunch" = "yes" ] && echo 'Dbus=dbus-launch' || echo "Dbus=''"
   echo ""
   echo "# create x11docker_CMD (shared with container and given as image command on docker run)"
-  echo "{ echo '#! /bin/bash'"
+  echo "{ echo '#! /bin/sh'"
   echo "  echo '# created startscript for docker run: x11docker_CMD'"
   echo '  echo Imagecommand="\"$Imagecommand\""'
   echo '  echo Entrypoint="\"$Entrypoint\""'
@@ -2821,15 +2829,6 @@ $Dockercommand
       echo "# set X variables to new display"
       [ "$Xserver" = "Hostdisplay" ] && echo "export $Hostxenv" || echo "export $Newxenv"
       
-      [ "$Xserver" = "Hostdisplay" ] || {
-        [ -n "$Xhost" ] && {
-          echo "verbose 'custom xhost setting (option --xhost): $Xhost'"
-          echo "$Xhost" 
-        }  || {
-          echo "verbose 'disabling any possible access to new X server possibly granted by xhost'"
-          echo "no_xhost"
-        }
-      }
       
       [ "$Xserver" = "Nxagent" ] && echo "env $Hostxenv xhost -SI:localuser:$Hostuser"
       
@@ -2876,7 +2875,17 @@ $Dockercommand
 
       [ "$Benutzeruid" = "$Hostuseruid" ]   || echo "setfacl -m u:$Benutzeruid:r $Xclientcookie"  # read permissions for option --user
       [ "$nsBenutzeruid" = "$Benutzeruid" ] || echo "chmod 644 $Xclientcookie"                    # read permissions for user namespace remapping
-
+      
+      [ "$Xserver" = "Hostdisplay" ] || {
+        [ -n "$Xhost" ] && {
+          echo "verbose 'custom xhost setting (option --xhost): $Xhost'"
+          echo "$Xhost" 
+        }  || {
+          echo "verbose 'disabling any possible access to new X server possibly granted by xhost'"
+          echo "no_xhost"
+        }
+      }
+      
       [ "$Shareclipboard" = "yes" ] && [ -n "$Hostdisplay" ] && {
         case $Xserver in
           Xpra|Xpra-Xwayland|Nxagent) ;;           # have their own clipboard management
@@ -3013,14 +3022,15 @@ $Dockercommand
     }
     verbose "Image name: $Imagename"
     verbose "Image command: $Imagecommand"
-    verbose "Users:
+    verbose "Users and terminal:
   x11docker was started by: $(id -un)
   As host user serves (running X, storing cache): $Hostuser
   Container user will be: $Benutzer
   Getting permission to run docker with: $Getroot $Sudo
   Running X and other user commands with: $Mksu
   Terminal for password frontend: $Passwordterminal
-  Terminal to show docker pull progress: $Pullterminal"
+  Terminal to show docker pull progress: $Pullterminal
+  Running on console: $Tty"
     verbose "Current cache folder: $Cachefolder"
     [ -n "$Xcommand" ] && verbose "Created X server command:
   $Xcommand" 
@@ -3104,11 +3114,12 @@ Keywords=docker x11docker $(echo $Name | tr -c '[:alpha:][:digit:][:blank:]' ' '
   fi
 }
 
-{ #### part: wait for and watch X server, [start xpra] and run xtermrc-> dockerrc-> docker
+{ #### part: wait for and watch X server, [start xpra] and run xtermrc-> dockerrc-> docker run x11docker_CMD
 
   #### watch X server ####
   
-  waitforfilecreation $Cachefolder/Xready || error "Startup of $Xserver failed. Last lines of xinit logfile:
+  waitforfilecreation $Cachefolder/Xready || error "Startup of X server $Xserver failed. 
+  Last lines of xinit logfile:
 $(tail $Xinitlogfile)"
   
   [ -s "$Compositorpidfile" ] && {
@@ -3119,10 +3130,13 @@ $(tail $Xinitlogfile)"
   case $Xserver in       # --xpra / --xpra-xwayland: start xpra
     Xpra|Xpra-Xwayland) 
       export XPRA_OPENGL_DOUBLE_BUFFERED=1 # avoid xpra resizing window bug in older versions http://xpra.org/trac/ticket/1469
-      export $Newxenv $Xprashm
-      [ "$Desktopmode" = "no" ] && Desktopmode="start" || Desktopmode="start-desktop"
-      # start xpra server on new display
-      $Mksu "xpra $Desktopmode $Newdisplay --use-display --no-daemon $Xpraoptions --exit-with-children --start-child='$Waitforgoodbye'" >> $Xpraserverlogfile 2>&1 &
+      export $Newxenv
+      case $Desktopmode in
+        yes) # shadow works with --ipc only
+             $Mksu "xpra shadow $Newdisplay --use-display --no-daemon $Xpraoptions --exit-with-children --start-child='$Waitforgoodbye'" >> $Xpraserverlogfile 2>&1 & ;;
+             #$Mksu "xpra start-desktop $Newdisplay --use-display --no-daemon $Xpraoptions --exit-with-children --start-child='$Waitforgoodbye'" >> $Xpraserverlogfile 2>&1 & ;;
+        no)  $Mksu "xpra start $Newdisplay --use-display --no-daemon $Xpraoptions --exit-with-children --start-child='$Waitforgoodbye'" >> $Xpraserverlogfile 2>&1 & ;;
+      esac
       storepid $! xpra
       waitforlogentry xpra $Xpraserverlogfile 'xpra is ready' || error "Xpra startup failed.
   Last lines of Xpra server log:
