--hostdisplay: warn if xauth is missing

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4833,7 +4833,7 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
           ;;
         esac
         echo         ""
-        echo         "[ -s '$Xclientcookie' ] || error 'xinitrc(): Option --xauth=$Xauthentication: Cookie creation failed!'"
+        echo         "[ -s '$Xclientcookie' ] || error 'xinitrc(): Option --xauth=$Xauthentication: Cookie creation failed.'"
       }
       echo           "export XAUTHORITY=$Xclientcookie"
       echo           "[ '$Xauthentication' = 'no' ] || [ ! -s '$Xclientcookie' ] && unset XAUTHORITY && warning 'Option --xauth=no: X server $Newdisplay runs without cookie authentication.'"
@@ -9681,6 +9681,13 @@ check_options_interferences() { # check multiple option interferences, change se
   # --xauth
   [ "$Xauthentication" != "no" ] && case "$Xserver" in
     --tty|--weston|--kwin|--hostwayland) Xauthentication="no" ;;
+    --hostdisplay)
+      xtool --check "xauth" || note "Option --hostdisplay --xauth=$Xauthentication:
+  Command xauth not found. Accessing host display might fail.
+  Fallback: Setting --xauth=no.
+  $Wikipackagesimage"
+      Xauthentication="no"
+    ;;
   esac
 
   # --xtest
