Prefer starting terminal for interactive pull or password prompt #109

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -406,9 +406,9 @@ ${Colredbg}x11docker ERROR:${Colnorm} $Message
   [ -e "$Cachefolder/error" ] && waitfortheend         # Avoid double alert boxes
   [ -d "$Cachefolder" ] && mkfile "$Cachefolder/error" # also regarded by finish() for exit code
 
-  # output to X dialogbox
-  [ "$Silent" = "no" ] && export ${Terminalxenv:-DISPLAY} && alertbox "x11docker ERROR" "$Message"
-
+  # output to X dialogbox if not running in terminal
+  [ "$Runsinterminal" = "no" ] && [ "$Silent" = "no" ] && export ${Terminalxenv:-DISPLAY} && alertbox "x11docker ERROR" "$Message" &
+  
   finish 1
 }
 warning() {                     # show warning messages
@@ -3924,17 +3924,21 @@ create_dockerrc() {             # create dockerrc: This script runs as root (or 
   echo "done < <(sort < $Cachefolder/images.list)"
   echo ""
 
-  echo "# check whether image is available locally, otherwise pull from docker hub"
+  [ "$Runsinterminal" = "yes" ] && {
+    echo "$Dockerexe inspect --type=image $Imagename >>$Containerlogfile 2>&1 || {"
+    echo "  read -t60 -n1 -e -p \"Image '$Imagename' not found locally. "
+    echo "Do you want to pull it from docker hub? [Y|n]"
+    echo "(Will wait up to 60s for a response, otherwise assuming no)\" Choice"
+    echo "  [ \"\$?\" = '0' ] && {"
+    echo "    [[ \"\$Choice\" == [YyJj]* ]] || [ -z \"\$Choice\" ] && $Sudo $Dockerexe pull $Imagename 1>&2"
+    echo "  }"
+    echo "}"
+  }
   echo "$Dockerexe inspect --type=image $Imagename >>$Containerlogfile 2>&1 || {"
-  echo "  note 'Image $Imagename not found locally. Will try to pull from docker hub.'"
-  echo "  notify-send 'x11docker: Image $Imagename not found locally. Will try to pull from docker hub.' 2>/dev/null"
-  echo "  docker pull $Imagename 1>&2"
-  echo "  $Dockerexe inspect --type=image $Imagename >>$Containerlogfile 2>&1 || {"
-  echo "    error \"Image '$Imagename' not found locally
-  and not pulled from docker hub. Last lines of log:
-\$(tail $Containerlogfile)\""
-  echo "    exit 1"
-  echo "  }"
+  echo "  error 'Did not find image $Imagename.
+  Please build image first or pull it from docker hub with:
+  
+      docker pull $Imagename'"
   echo "}"
   
   echo "# check CMD"
@@ -5115,6 +5119,9 @@ check_host() {                  # check host environment
   [ "$Winsubsystem"   ] && Hosttty="no"
   XDG_VTNR=${XDG_VTNR:-}
   
+  # Check whether x11docker runs in an interactive terminal
+  tty -s && Runsinterminal="yes" || Runsinterminal="no"
+  
   # Check whether ps can watch processes of other users
   mount | grep "^proc" | grep -q "hidepid=2" && {
     Hosthidepid="yes"
@@ -6027,8 +6034,8 @@ check_terminalemulator() {      # check terminal for password prompt of su or su
       *) ;;
     esac
   }
-  [ "$Interactive" = "yes" ] && Terminallist="bash NOLUCK"
-  [ "$Xserver" = "--tty" ]   && Terminallist="bash NOLUCK"
+  [ "$Runsinterminal" = "yes" ] && Terminallist="bash NOLUCK"
+  [ "$Xserver" = "--tty" ]      && Terminallist="bash NOLUCK"
 
   for Passwordterminal in $Terminallist ; do command -v $Passwordterminal >/dev/null && break ; done
   [ "$Passwordterminal" = "NOLUCK" ] && warning "Can not find a terminal emulator that works for
@@ -6041,6 +6048,7 @@ check_terminalemulator() {      # check terminal for password prompt of su or su
       konsole) Passwordterminal="env QT_QPA_PLATFORM=wayland dbus-run-session $Passwordterminal --nofork -e" ;;
     esac
   }
+  
   case $Passwordterminal in
     xfce4-terminal) Passwordterminal="$Passwordterminal --disable-server -x" ;;
     mate-terminal)  Passwordterminal="dbus-run-session $Passwordterminal -x" ;;
@@ -6178,6 +6186,7 @@ declare_variables() {           # declare global variables
   Hosttty=""                                      # x11docker runs on tty yes/no
   Hosthidepid=""                                  # /proc is mounted with hidepid=2 yes/no
   Hostcanwatchroot=""                             # x11docker can watch root processes yes/no
+  Runsinterminal=""                               # x11docker runs in a terminal yes/no
   
   Winsubsystem=""                                 # Windows subsystem WSL, MSYS2 or CYGWIN
   Winsubmount=""                                  # path within subsystem to mounted Windows drives
@@ -6726,6 +6735,8 @@ Parsed options:    $Parsedoptions"
     
   check_terminalemulator        # find terminal emulator like xterm for error messages and 'docker pull'
   check_passwordfrontend        # check for su/sudo/gksu/pkexec etc.            # --pw
+  [ "$Runsinterminal" = "no" ] && [ "$Passwordneeded" = "yes" ] && warning "You might need to run x11docker in terminal
+  for password prompt if prompting for password with a GUI fails."
   
   verbose -d "Users and terminal:
   x11docker was started by:                       $Startuser
