--xpra*: use less xpra options --backend=chroot: experimental code, disabled yet

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -3000,8 +3000,15 @@ check_xserver() {               # check chosen X server, auto-choose X server
         esac
       ;;
     esac
+    case $Backend in
+      chroot)
+        Xoverip="yes"
+      ;;
+    esac
     case $Mobyvm in
-      yes) Xoverip="yes" ;;
+      yes) 
+        Xoverip="yes" 
+      ;;
     esac
     [ "$Xoverip" = "yes" ] && [ "$Autochooseserver" = "no" ] && debugnote "Enabled X over TCP instead of sharing unix socket."
   }
@@ -3307,9 +3314,9 @@ create_xcommand() {             ### create command to start X server and/or Wayl
     --xpra*)
       [ "$Xprahelp" ] || Xprahelp="$(xpra --help 2>/dev/null)"
 
+#  $(check_xpraoption --csc-modules=none) \\
+#  $(check_xpraoption --encodings=rgb) \\
       Xpraoptions="\\
-  $(check_xpraoption --csc-modules=none) \\
-  $(check_xpraoption --encodings=rgb) \\
   $(check_xpraoption --microphone=no) \\
   $(check_xpraoption --mmap=$Sharefolder/xpra.mmap) \\
   $(check_xpraoption --notifications=no) \\
@@ -3344,10 +3351,8 @@ create_xcommand() {             ### create command to start X server and/or Wayl
   $(check_xpraoption --printing=no) \\
   $(check_xpraoption --session-name="$Codename") \\
   $(check_xpraoption --start-new-commands=no) \\
-  $(check_xpraoption --systemd-run=no) \\
-  $(check_xpraoption --video-encoders=none)"
-      # disable --dpi for buggy versions
-      [ -n "$Dpi" ] && verlt "$Xpraversion" "v2.1-r16547" && ! verlt "$Xpraversion" "v2.1" &&  Dpi=""
+  $(check_xpraoption --systemd-run=no)"
+#  $(check_xpraoption --video-encoders=none)"
       [ -n "$Dpi" ] && Xpraservercommand="$Xpraservercommand \\
   $(check_xpraoption --dpi="$Dpi")"
       case $Xserver in
@@ -3356,14 +3361,14 @@ create_xcommand() {             ### create command to start X server and/or Wayl
       esac
 
       # xpra client command
+#  $(check_xpraoption --compress=0) \\
+#  $(check_xpraoption --quality=100) \\
+#  $(check_xpraoption --video-decoders=none)"
       Xpraclientcommand="xpra attach :$Newdisplaynumber $Xpraoptions \\
   $(check_xpraoption --clipboard=$Shareclipboard) \\
-  $(check_xpraoption --compress=0) \\
   $(check_xpraoption --modal-windows=no) \\
-  $(check_xpraoption --opengl=auto) \\
-  $(check_xpraoption --quality=100) \\
-  $(check_xpraoption --reconnect=no) \\
-  $(check_xpraoption --video-decoders=none)"
+  $(check_xpraoption --opengl=noprobe) \\
+  $(check_xpraoption --reconnect=no)"
       [ "$Fullscreen" = "yes" ]  && Xpraclientcommand="$Xpraclientcommand \\
   $(check_xpraoption --desktop-fullscreen=yes)"
       [ "$Scaling" ] && Xpraclientcommand="$Xpraclientcommand \\
@@ -4736,6 +4741,11 @@ create_backendcommand() {       ### create command to run docker
     ;;
     chroot)
       Backendcommand="chroot"
+      Chrootmountlist="
+/sys|$Rootfs/sys
+/proc|$Rootfs/proc
+/dev|$Rootfs/dev
+/run/shm|$Rootfs/run/shm"
     ;;
   esac
   
@@ -5039,7 +5049,7 @@ create_backendcommand() {       ### create command to run docker
     ;;
     chroot)
       Chrootmountlist="$Chrootmountlist
-'$Sharefolder' '$Rootfs/$Sharefoldercontainer'"
+$Sharefolder|$Rootfs/$Sharefoldercontainer"
     ;;
   esac
   
@@ -5058,7 +5068,7 @@ create_backendcommand() {       ### create command to run docker
         ;;
         chroot)
           Chrootmountlist="$Chrootmountlist
-'$Persistanthomevolume' '$Rootfs/$Containeruserhome'"
+$Persistanthomevolume|$Rootfs/$Containeruserhome"
         ;;
       esac
     ;;
@@ -5100,7 +5110,7 @@ create_backendcommand() {       ### create command to run docker
       ;;
       chroot)
         Chrootmountlist="$Chrootmountlist
-'$Line' '$Rootfs/$Line'"
+$Line|$Rootfs/$Line"
       ;;
     esac
   done < <(store_runoption dump volume)
@@ -5119,7 +5129,7 @@ create_backendcommand() {       ### create command to run docker
       ;;
       chroot)
         Chrootmountlist="$Chrootmountlist
-'$Nvidiainstallerfile' '$Rootfs/$Nvidiacontainerfile'"
+$Nvidiainstallerfile|$Rootfs/$Nvidiacontainerfile"
       ;;
     esac
   }
@@ -5157,7 +5167,7 @@ create_backendcommand() {       ### create command to run docker
           ;;
           chroot)
             Chrootmountlist="$Chrootmountlist
-'$Newxsocket' '$Rootfs/$Newxsocket'"
+$Newxsocket|$Rootfs/$Newxsocket"
           ;;
         esac
       }
@@ -5336,7 +5346,7 @@ create_backendcommand() {       ### create command to run docker
               Backendcommand="$Backendcommand /bin/sh - $(convertpath share $Containerrc)"
             ;;
             chroot)
-              Backendcommand="$Backendcommand /bin/sh - $(convertpath share $Containerrc)"
+              Backendcommand="$Backendcommand /bin/sh - $(convertpath share $Containerrootrc)"
             ;;
           esac
         ;;
@@ -5349,7 +5359,7 @@ create_backendcommand() {       ### create command to run docker
               Backendcommand="$Backendcommand /bin/sh - $(convertpath share $Containerrootrc)"
             ;;
             chroot)
-              Backendcommand="$Backendcommand $Rootfs /bin/sh - $(convertpath share $Containerrootrc)"
+              Backendcommand="$Backendcommand /bin/sh - $(convertpath share $Containerrootrc)"
             ;;
           esac
         ;;
@@ -5988,8 +5998,8 @@ debugnote 'Running x11docker-login'
 chmod +x $(convertpath share $Containerrc)
 \" >/usr/local/bin/x11docker-login"
     case $Backend in
-      proot)                 echo "echo 'exec /bin/sh - $(convertpath share $Containerrc)' >>/usr/local/bin/x11docker-login" ;;
-      docker|podman|nerdctl) echo "echo \"exec su - -s /bin/sh  \$Containeruser $(convertpath share $Containerrc)\" >>/usr/local/bin/x11docker-login" ;;
+      proot)                 echo "echo 'exec /bin/sh - $(convertpath share $Containerrc)'                          >>/usr/local/bin/x11docker-login" ;;
+      docker|podman|nerdctl|chroot) echo "echo \"exec su - -s /bin/sh  \$Containeruser $(convertpath share $Containerrc)\" >>/usr/local/bin/x11docker-login" ;;
     esac
     echo "chmod +x /usr/local/bin/x11docker-login"
     echo ""
@@ -6487,14 +6497,16 @@ reload() {
 #        echo "exec /usr/local/bin/x11docker-login"
         case $Backend in
           proot)                 echo "exec /bin/sh $(convertpath share $Containerrc)" ;;
+          chroot      )          echo "exec /bin/sh /usr/local/bin/x11docker-login" ;;
           docker|podman|nerdctl) echo "exec /usr/local/bin/x11docker-agetty" ;;
         esac
       ;;
       tini)
         case $Backend in
-          proot) echo "exec env TINI_SUBREAPER=1 $Tinicontainerpath /bin/sh $(convertpath share $Containerrc)" ;;
+          proot)                 echo "exec env TINI_SUBREAPER=1 $Tinicontainerpath /bin/sh $(convertpath share $Containerrc)" ;;
+          chroot)                echo "exec env TINI_SUBREAPER=1 $Tinicontainerpath /bin/sh /usr/local/bin/x11docker-login" ;;
           docker|podman|nerdctl)
-            echo "exec $Tinicontainerpath -- /usr/local/bin/x11docker-agetty"
+                                 echo "exec $Tinicontainerpath -- /usr/local/bin/x11docker-agetty"
 #            echo "exec /usr/local/bin/x11docker-agetty"
           ;;
         esac
@@ -6542,13 +6554,16 @@ create_containerrc() {          # This script runs as unprivileged user in conta
 [ '$Interactive' = 'no' ] && exec >>$(convertpath share $Containerlogfile) 2>&1
      
 $(declare -f mysleep)
+$(declare -f pspid)
 $(declare -f rocknroll)
 $(declare -f saygoodbye)
 $(declare -f storeinfo)
+$(declare -f storepid)
 $(declare -f waitforlogentry)
 $Messagefifofuncs
 Messagefile=$(convertpath share $Messagefifo)
 Storeinfofile=$(convertpath share $Storeinfofile)
+Storepidfile=$(convertpath share $Storepidfile)
 Timetosaygoodbyefile=$(convertpath share $Timetosaygoodbyefile)
       
 waitforlogentry containerrc \$Storeinfofile containerrootrc=ready "" infinity
@@ -6715,8 +6730,14 @@ verbose \"Container environment:
     [ "$Initsystem" = 'systemd' ] && echo "systemctl --user start dbus"
     case $Interactive in
       no)
-        echo "tail -f $(convertpath share $Cmdstdoutlogfile)     2>/dev/null &"
-        echo "tail -f $(convertpath share $Cmdstderrlogfile) >&2 2>/dev/null &"
+        echo "tail -f $(convertpath share $Cmdstdoutlogfile)     2>/dev/null & Stdoutpid=\$!"
+        echo "tail -f $(convertpath share $Cmdstderrlogfile) >&2 2>/dev/null & Stderrpid=\$!"
+        case $Backend in
+          proot|chroot)
+            echo 'storepid $Stdoutpid'
+            echo 'storepid $Stderrpid'
+          ;;
+        esac
         echo "exec \$Dbus sh $(convertpath share $Cmdrc) >> $(convertpath share $Cmdstdoutlogfile) 2>>$(convertpath share $Cmdstderrlogfile)"
       ;;
       yes)
@@ -6757,10 +6778,10 @@ debugnote \"cmdrc: Running container command:
 "
     case $Backend in
       host|chroot)
-        echo "# close additional file descriptors"
-        echo "for i in 3 4 6 7 8 9; do"
-        echo "  { >&\$i ;} 2>/dev/null && exec >&\$i-"
-        echo "done"
+        #echo "# close additional file descriptors"
+        #echo "for i in 3 4 6 7 8 9; do"
+        #echo "  { >&\$i ;} 2>/dev/null && exec >&\$i-"
+        #echo "done"
         echo ""
       ;;
     esac
@@ -7778,7 +7799,10 @@ Fallback: using command '$Containercommand' and enabling option --interactive."
       Sudouser="no"
       Sharewebcam=""
     ;;
-    chroot) ### FIXME
+    chrootXXX) ### FIXME
+      warning "--backend=$Backend is highly experimental.
+   Rather use another backend. Even 'proot' is more stable.
+   Isolation is close to not existant."
       [ -z "$Rootfs" ] && [ -d "$Hosthomebasefolder/ROOTFS/$Imagebasename" ] && Rootfs="$Hosthomebasefolder/ROOTFS/$Imagebasename"
       [ -z "$Rootfs" ] && error "--backend=$Backend: Did not find a rootfs for $Imagename
   in $Hosthomebasefolder/ROOTFS/$Imagebasename"
@@ -7791,6 +7815,7 @@ Fallback: using command '$Containercommand' and enabling option --interactive."
         check_fallback
         Interactive="yes"
       }
+      Switchcontaineruser="yes"
     ;;
     *) 
       error "Option --backend=$Backend: Backend $Backend is not supported."
@@ -8327,7 +8352,6 @@ $Hostuserhome/.cache/x11docker/symlink
   Hostxauthority="$Cachefolder/$Hostxauthority"                     && mkfile $Hostxauthority
   Messagelogfile="$Cachefolder/$Messagelogfile"                     && mkfile $Messagelogfile
   Pulseaudioconf="$Cachefolder/$Pulseaudioconf"                     && mkfile $Pulseaudioconf
-  Storepidfile="$Cachefolder/$Storepidfile"                         && mkfile $Storepidfile
   Systemdconsoleservice=$Cachefolder/$Systemdconsoleservice         && mkfile $Systemdconsoleservice
   Systemdenvironment=$Cachefolder/$Systemdenvironment               && mkfile $Systemdenvironment
   Systemdjournallogfile=$Sharefolder/$Systemdjournallogfile         && mkfile $Systemdjournallogfile
@@ -8360,6 +8384,7 @@ $Hostuserhome/.cache/x11docker/symlink
   Pulseaudiocookie="$Sharefolder/$Pulseaudiocookie"
   Pulseaudiosocket="$Sharefolder/$Pulseaudiosocket"
   Storeinfofile="$Sharefolder/$Storeinfofile"                       && mkfile $Storeinfofile 666
+  Storepidfile="$Sharefolder/$Storepidfile"                         && mkfile $Storepidfile
   Timetosaygoodbyefile="$Sharefolder/$Timetosaygoodbyefile"         && mkfile $Timetosaygoodbyefile
   Timetosaygoodbyefifo="$Sharefolder/$Timetosaygoodbyefifo"
   Westonini="$Sharefolder/$Westonini"                               && mkfile $Westonini
@@ -9720,16 +9745,6 @@ $(nl -ba <$Containerrc)"
     verbose "Generated cmdrc:
 $(nl -ba <$Cmdrc)"
   }
-  
-  #### Create helper script xinitrc to set up X
-  ## xinitrc is started by xinit and does some setup within new X server.
-  # Main job: create cookie, check xhost, set keyboard layout.
-  # Optional jobs: run window manager, run xfishtank, run host command, share clipboard, scale/rotate --xorg, create set of screen resolutions.
-  create_xinitrc >> "$Xinitrc"
-  verbose "Generated xinitrc:
-$(nl -ba <$Xinitrc)"
-  [ -s "$Westonini" ] && verbose "Generated weston.ini:
-$(nl -ba <$Westonini)"
 
   { #### Run docker image
     # For code flow logic, start_xserver() should run here first and be moved to background.
@@ -9760,11 +9775,20 @@ $(nl -ba <$Westonini)"
       chroot)
         Chrootmountlist="$(grep . <<< "$Chrootmountlist")"
         while read -r Line; do
-          debugnote "mount --bind $Line"
-          eval mount --bind $Line 2>>$Containerlogfile || error "--backend=$Backend: mount failed.
+          debugnote "--backend=$Backend: mount/ln $Line"
+          Source="$(cut -d'|' -f1 <<< "$Line")"
+          Target="$(cut -d'|' -f2 <<< "$Line")"
+          [ -d "$Source" ] && {
+            mkdir -v -p "$Target"
+            umount -f "$Target" || debugnote "umount failed on '$Target'"
+            mount --bind "$Source" "$Target" 2>> "$Containerlogfile" || error "--backend=$Backend: mount failed.
   Last lines of log:
 $(tail "$Containerlogfile")"
+          }
+          [ -S "$Source" ] && ln "$Source" "$Target"
+          [ -f "$Source" ] && ln "$Source" "$Target"
         done <<< "$Chrootmountlist"
+        mount -t devpts devpts "$Rootfs/dev/pts" || error "--backend=$Backend: mount of devpts failed."
       ;;
     esac
     
@@ -9826,8 +9850,20 @@ $(cat $Storepidfile)"
   } <&0 & storepid $! containershell
   
   #### Start X server [and/or Wayland compositor] [and xpra]
-  waitforlogentry "start_xserver()" $Storeinfofile "readyforX=ready" "" infinity
+  rocknroll && waitforlogentry "main()" $Storeinfofile "readyforX=ready" "" infinity
 
+  ## Create helper script xinitrc to set up X
+  # xinitrc is started by xinit and does some setup within new X server.
+  # Main job: create cookie, check xhost, set keyboard layout.
+  # Optional jobs: run window manager, run xfishtank, run host command, share clipboard, scale/rotate --xorg, create set of screen resolutions.
+  rocknroll && {
+    create_xinitrc >> "$Xinitrc"
+    verbose "Generated xinitrc:
+$(nl -ba <$Xinitrc)"
+    [ -s "$Westonini" ] && verbose "Generated weston.ini:
+$(nl -ba <$Westonini)"
+  }
+  
   case $Xserver in
     --xpra*)
       {
