Don't fail on missing /etc/passwd #55

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1143,7 +1143,7 @@ export IFS=$' \n\t'                             # set IFS to default
 exec 3>&2                                       # stderr channel for warning() and error()
 exec 4>&2                                       # stderr channel for --stderr
 
-pstree -ps $$ | grep -q sshd && Ssh="yes" || Ssh="no"  # check if running over SSH
+pstree -ps $$ | grep -q sshd && Ssh="yes" || Ssh="no"  # check if running over SSH            ### FIXME pstree is not available everywhere
 tty | grep -q tty            && Tty="yes" || Tty="no"  # check if running on X or on tty
 Ttyinuse=
 XDG_VTNR=${XDG_VTNR:-}
@@ -1252,7 +1252,7 @@ Cmdstdoutlogfile=stdout                         # stdout for image command
 Cmdstderrlogfile=stderr                         # stderr for image command
 
 # host environment
-Hostsystem="$(source /etc/os-release ; echo $ID)"
+Hostsystem="$(source /etc/os-release 2>/dev/null; echo $ID)"
 Hostdisplay="$DISPLAY"                          # store environment variable containing name of current display
 Hostdisplaynumber="$(echo $Hostdisplay | cut -d: -f2 | cut -d. -f1)"                         # display number without ":" and ".0"
 Hostxauthority="Xauthority-$Hostdisplaynumber"                                               # file to store copy of $XAUTHORITY
@@ -1681,12 +1681,25 @@ $Customenvironment"    ;  shift ;;                         # set custom environm
     [ "$Startuser" = "root" ] || error "x11docker must run as root to choose a host user
   different from user '$Lognameuser'. (option --hostuser)"
   }
-  getent passwd $Hostuser >/dev/null 2>&1 || error "Could not find user '$Hostuser' in /etc/passwd."
-  
+#  getent passwd $Hostuser >/dev/null 2>&1 || error "Could not find user '$Hostuser' in /etc/passwd."
+  getent passwd $Hostuser >/dev/null 2>&1 || {
+    [ -e /etc/passwd ] || warning "Your system misses /etc/passwd"
+    error "Could not find user '$Hostuser' in /etc/passwd."
+  }
   Hostuser=$(id -un $Hostuser)
   Hostuseruid=$(id -u $Hostuser)
   Hostusergid=$(id -g $Hostuser)
-  Hostuserhome=$(getent passwd $Hostuser | cut -d: -f6)
+  Hostuserhome=$(getent passwd $Hostuser 2>/dev/null | cut -d: -f6)
+  [ -z "$Hostuserhome" ] && {
+    warning "Could not read your home directory from /etc/passwd.
+  Will try HOME=${HOME:-<not found>} instead."
+    Hostuserhome=${HOME:-}
+  }
+  [ -z "$Hostuserhome" ] && {
+    warning "Please set \$HOME with a valid path.
+  Fallback: setting HOME=/tmp"
+    Hostuserhome="/tmp"
+  }
 
   # Mksu: prefix to run command as unprivileged host user
   [ "$Hostuser" = "$Startuser" ] && Mksu="bash -c" || Mksu="su $Hostuser -c"  # differenciated as only root can use su on itself and others without password
@@ -2757,8 +2770,9 @@ After finish: $Logbackup"
   # check for closed source nvidia driver on host, provide automated installation, warn about disadvantages
   [ "$Gpu" = "yes" ] && [ -e "/proc/driver/nvidia" ] && {
     Nvidiaversion=$(head -n1 </proc/driver/nvidia/version | awk '{ print $8 }')
-    verbose "Detected nvidia driver version $Nvidiaversion on host."
+    verbose -d "Detected nvidia driver version $Nvidiaversion on host."
     Nvidiadriver=$(find /usr/local/share/x11docker/NVIDIA* $Hostuserhome/.local/share/x11docker/NVIDIA* 2>/dev/null | grep $Nvidiaversion )
+    Nvidiadriver="$(realpath "$Nvidiadriver")"
     
     [ -e "$Nvidiadriver" ] && {
       verbose -d "Found proprietary closed source nvidia driver installer
@@ -3181,7 +3195,7 @@ fi
   due to xpra bug #1605. Need at least xpra v2.1-r16547 or one of 2.0 series.
   This affects option --scale, too, leading to wrong font sizes.
   Fallback: disabling dpi settings."
-        Dpi=
+        Dpi="-1"
       } ;;
   esac
   case $Xserver in
@@ -3207,6 +3221,7 @@ fi
       }
     ;;
   esac
+  [ "$Dpi" = "-1" ] && Dpi=""
   [ -n "$Dpi" ] && Xserveroptions="$Xserveroptions -dpi $Dpi"
   
   # xpra server and client command
@@ -3724,8 +3739,8 @@ done
   }
   
   for Pullterminal in $Terminallist ; do command -v $Pullterminal >/dev/null && break ; done
-  [ "$Pullterminal" = "NOLUCK" ] && error "Can not find a terminal emulator that works for $Xserver.
-  Please install one of:
+  [ "$Pullterminal" = "NOLUCK" ] && warning "Can not find a terminal emulator that works for 
+  option $Xserver. Please install one of:
   ${Terminallist%"NOLUCK"}"
   
   [ -z "$Hostdisplay" ] && [ -n "$Newwaylandsocket" ] && {
@@ -5675,6 +5690,7 @@ $(tail $Compositorlogfile)")"
   
 ######### ToDo notes for development
 todo() {
+# --hostdisplay: check xdpyinfo for MIT-SHM to avoid --hostipc
 # further checks of pam.d
 # error message window in wayland fails: xterm: no display. should use konsole
 
