bugfix --weston/--kwin: do not mount --volume in --volume to avoid random docker error

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,58 +11,6 @@
 
 Version="4.1.0"
 
-todo() {                # ToDo notes for development
-#
-# --dbus-system: policykit must not have no-new-privileges. Seems to use setuid? Core issue AccountsService?
-#                starting polkitd and accounts-daemon in setupscript helps:
-#                -> cinnamon starts up with lots of (harmless?) error messages
-#                -> deepin needs --pulseaudio again
-# --wayland --dbus-system GTK3 seems to work now!?
-# check fgconsole
-# bestwu/deepin: why sh is replaced by bash?
-# BUG opensuse/arch: issues with x11docker/fluxbox, background missing, sometimes no context menu. where is the difference?
-# BUG --weston,--kwin: docker sometimes fails although socket exists: "stat /run/user/1000/wayland-607: no such file or directory". dirty sleep needed?
-# check echo especially in sh scripts, replace with printf if needed (#25)
-# avoid possible confusions --home --sharedir. --sharedir mounts can overlap --home folder. What about softlinks with existing target in --home? Maybe avoid /home/$USER at all
-# check out possibilities to allow 'sudo docker' directly again.
-# xpra restart on tty switch -> bug report
-# --xpra --desktop restarts client if closing desktop window
-
-# --lang: find out locale package names for several distris for documentation
-# --keymap does not work on tty with --kwin and --kwin-xwayland. No idea how to set it.
-# further check of xpra server crashes with jess/atom and chromium. --mmap=no avoids the bug: xpra bug report?
-
-# BUG check whether VT is not in use with --xorg/--xpra/--xdummy, bug if accidently using vt that is already in use
-# check all FIXME 
-# note: SYS_PTRACE allows polkit in docker
-# --systemd: try to avoid xhost +SI:localuser:$Benutzer
-# --xpra-xwayland, xdummy-xwayland: use kwin-wayland as fallback for missing weston? 
-# --xorg: getty and autologin to avoid Xwrapper.config changes?
-# gnome3 based desktop failing due to gnome bugs: pantheon budgie gnome3
-# check Xorg version for +iglx, check security implications, maybe option --iglx?
-# GTK3 in Wayland: --dbus once worked with $Dbusdaemon=yes
-# --wayland --user/--hostuser: wayland socket access denied due to XDG_RUNTIME_DIR
-# --nxagent 3.5.0: Mageia 6: seamless mode fails
-# fedora: SElinux issue: '--security-opt label=type:container_runtime_t': need more restrictive setting
-#         https://unix.stackexchange.com/questions/386767/selinux-and-docker-allow-access-to-x-unix-socket-in-tmp-x11-unix
-# multimonitor support for --scale and --size
-# check current multimonitor behaviour for weston on tty
-# --xdummy --gpu on tty allows real resolutions only
-# --xorg: check custom systemd start of X #7
-# check X in container #7
-# some tests with Xephyrglamor=no
-
-### BUG collection: non x11docker bugs
-# BUG Xwayland does not always sit at 0:0 on multiple outputs. 
-#     bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1498665
-# BUG nxagent with x11docker/lxde: segmentation fault of lxpanel with --userns-remap. bug in nxagent, lxpanel or x11docker?
-# BUG --kwin*: wrong fullscreen and crashes in gnome-wayland, strange in weston, WAYLAND_DISPLAY="" does not help, probably bug in kwin
-# BUG scale>1 Xwayland in Weston is too large (Xwayland bug), rendering issues on tty (switching scaled/unscaled Xwayland on keyboard/mouse events) 
-#     bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1498669
-# BUG x11docker-gui in weston freezes weston in combo boxes. Weston bug ? QT3/4 bug?
-# BUG debian bug report lightdm/sddm contra gdm, dm can crash on tty switch if multiple graphical sessions are running
-  :
-}
 usage() {               # --help: show usage information
   echo "
 x11docker: Run GUI applications and desktop environments in docker.
@@ -712,6 +660,11 @@ x11docker --cleanup"
   [ "$Preservecachefiles" = "no" ] && echo "$Cachefolder" | grep -q .cache && echo "$Cachefolder" | grep -q x11docker && [ "x11docker" != "$(basename "$Cachefolder")" ] && rm -f -R "$Cachefolder"
   if [ -e "$Errorfile" ]; then rm "$Errorfile" ; exit 1; else exit 0; fi
 }
+traperror() {
+  warning "Command at Line $2 returned with error code $1:
+  $4
+  $3 - $5" 
+}
 verlte() {              # version number check $1 less than or equal $2
   [  "${1:-}" = "$(echo -e "${1:-}\n${2:-}" | sort -V | head -n1)" ] && return 0 || return 1
 }
@@ -1184,7 +1137,7 @@ Wm_all="$Wm_recommended_nodesktop_light $Wm_recommended_nodesktop_heavy  $Wm_rec
          --stdout)     Showstdout="yes" ;;                 # show stdout of image command
          --stderr)     Showstderr="yes" ;;                 # show stderr of image command
          --silent)     Silent="yes" ; exec 3>/dev/null ;;  # do not show warnings or errors
-         --debug)      Debug="yes" ; Verbose="yes" ;;      # show all executed lines
+         --debug)      Debug="yes" ;;                      # debugging mode
       
      #### Developer options
        ## User settings
@@ -1372,7 +1325,12 @@ $Customenvironment"    ;  shift ;;                         # set custom environm
 Command: $0 $X11dockerargs
 Parsed options: $Parsedoptions"
 
-  [ "$Debug" = "yes" ] && PS4="$DebugPS4" && set -x
+  [ "$Debug" = "yes" ] && {
+    # PS4="$DebugPS4" && set -x
+    set -E
+    #set -u
+    trap 'traperror $? $LINENO $BASH_LINENO "$BASH_COMMAND" $(printf "::%s" ${FUNCNAME[@]})'  ERR
+  }
 
   [ "$Cacherootfolder" != "$(echo $Cacherootfolder | sed -e 's/ *//g')" ] && error "Cache root folder must not contain whitespaces.
   $Cacherootfolder"
@@ -3437,7 +3395,7 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
       
       # entrypoint is checked in dockerrc
       Dockercommand="$Dockercommand \\
-  --entrypoint=env --workdir=/tmp"
+  --entrypoint=env"
       
       # At least OpenRC and systemd regard this hint
       Dockercommand="$Dockercommand \\
@@ -3465,18 +3423,14 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
         --weston|--hostwayland|--kwin) ;;
         *) 
           [ "$Newxlock" ] && Dockercommand="$Dockercommand \\
-  -v $Newxlock:$Newxlock:ro"
-          [ "$Newxsocket" ] && case $Adminusercaps in # especially systemd can have issues with soft linked X socket, avoiding that here
-            no)  Dockercommand="$Dockercommand \\
-  -v $Newxsocket:$Cshare/X$Newdisplaynumber:ro" ;;
-            yes) Dockercommand="$Dockercommand \\
-  -v $Newxsocket:$Newxsocket:ro" ;;
-          esac
+  -v $Newxlock:/$(basename $Newxlock):rw"
+          [ "$Newxsocket" ] && Dockercommand="$Dockercommand \\
+  -v $Newxsocket:/X$Newdisplaynumber:rw"
         ;;
       esac
       # Wayland socket will be softlinked to XDG_RUNTIME_DIR in x11docker.CMD.sh
       [ "$Sharewayland" = "yes" ] && Dockercommand="$Dockercommand \\
-  -v $XDG_RUNTIME_DIR/$Waylandsocket:$Cshare/$Waylandsocket:rw"
+  -v $XDG_RUNTIME_DIR/$Waylandsocket:/$Waylandsocket:rw"
       
       ## option --gpu : share graphics adapter device files
       [ "$Gpu" = "yes" ] && {
@@ -3507,7 +3461,8 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   -v $Cachefolder/pulseclient.conf:/etc/pulse/client.conf:rw"
       ## option --workdir
       [ "$Workdir" ] && Dockercommand="$Dockercommand \\
-  --workdir $Workdir"
+  --workdir $Workdir" || Dockercommand="$Dockercommand \\
+  --workdir /tmp"
       
       # option --env: add custom environment. Only needed here for possible 'docker exec'. Otherwise set in x11docker.CMD.sh
       IFS=$'\n'
@@ -3538,7 +3493,8 @@ DefaultEnvironment=DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie $(IFS=$'
   echo "mkdir -v -p /var/lib/dbus /var/run/dbus"
   echo "mkdir -v -p -m 1777 /tmp/.ICE-unix /tmp/.X11-unix /tmp/.font-unix"
   echo "chmod -c 1777 /tmp/.ICE-unix /tmp/.X11-unix /tmp/.font-unix"
-  echo "ln -s $Cshare/X$Newdisplaynumber $Newxsocket"
+  echo "ln -s /X$Newdisplaynumber $Newxsocket" # done again in x11docker.CMD.sh. At least x11docker/deepin needs it here already.
+  [ "$Newxlock" ] && echo "ln -s /$(basename $Newxlock) $Newxlock"
   echo "ls -l $Newxsocket"
   echo "export DISPLAY=$Newdisplay XAUTHORITY=$Cshare/Xclientcookie"
   echo ""
@@ -3669,9 +3625,9 @@ start() {
       echo "echo 'shutdown -hP 0' >> /etc/rc.local"
       echo "# disable getty in inittab" 
       echo "sed -i 's/.*getty/##getty disabled by x11docker## \0/' /etc/inittab"
-    ;;
+    ;;  
   esac
-  
+
   [ "$Langwunsch" ] && {
     echo "echo \"x11docker: Searching for language locale matching $Langwunsch\""
     echo "Locales=\"\$(locale -a)\""
@@ -3704,7 +3660,7 @@ start() {
     echo "  echo \"x11docker: Found locale in image: \$Langcontainer\""
     echo "}"
     echo "[ \"\$Langcontainer\" ] && {"
-    echo "  echo \"\$Langcontainer\" > /tmp/x11docker.LANG"
+    echo "  echo \"\$Langcontainer\" > /x11docker.LANG"
     echo "  echo \"LANG=\$Langcontainer\" > /etc/default/locale"
     echo "} || echo \"x11docker WARNING: desired locale for '--lang=$Langwunsch' not found and not created.\""
     echo "echo \"x11docker: Output of locale -a:\""
@@ -3717,7 +3673,7 @@ start() {
   }
   
   echo ""
-  echo ":> /tmp/x11docker.setupready"
+  echo ":> /x11docker.setupready"
   [ "$Switchcontaineruser" = "yes" ] && {   # if "no", x11docker.CMD.sh is executed in command line $Dockercommand
     case $Initsystem in
       tini|none)             echo "exec /bin/su - -s /bin/sh $Benutzer $Cshare/x11docker.CMD.sh" ;;
@@ -3801,8 +3757,8 @@ start() {
   
   echo "  echo '# wait for container setup script do be ready'"
   echo "  echo 'for Count in $(seq -s' ' 30); do'"
-  echo "  echo '  [ -e /tmp/x11docker.setupready ] && break'"
-  echo "  echo '  sleep 0.1'"
+  echo "  echo '  [ -e /x11docker.setupready ] && break'"
+  echo "  echo '  echo x11docker: waiting for root setup to be ready && sleep 0.1'"
   echo "  echo 'done'"
   echo "  echo ''"
   echo "} >> $Imagecommandscript"
@@ -3833,9 +3789,11 @@ start() {
 
   echo "  echo ''"
   
-  [ -n "$Newdisplay" ]           && {
+  [ -n "$Newdisplay" ] && {
     echo "  echo 'export DISPLAY=$Newdisplay'"
-    echo "  echo 'ln -s $Cshare/X$Newdisplaynumber /tmp/.X11-unix/'" 
+    # already done in setup script as needed at least by x11docker/deepin, but repeated here as some init systems clean up /tmp
+    echo "  echo 'ln -s /X$Newdisplaynumber /tmp/.X11-unix'"
+    [ "$Newxlock" ] && echo "  echo 'ln -s /$(basename $Newxlock) $Newxlock'"
   }
   [ "$Xauthentication" = "yes" ] && echo "  echo 'export XAUTHORITY=$Cshare/Xclientcookie'"
   [ "$Xserver" = "--nothing" ]   && echo "  echo 'unset DISPLAY WAYLAND_DISPLAY XAUTHORITY'"
@@ -3859,7 +3817,8 @@ start() {
     echo "  echo ''"
     echo "  echo '# Wayland environment'"
     echo "  echo 'export WAYLAND_DISPLAY=$Waylandsocket'"
-    echo "  echo 'ln -s $Cshare/$Waylandsocket \$XDG_RUNTIME_DIR/$Waylandsocket'"
+    echo "  echo 'ln -s /$Waylandsocket \$XDG_RUNTIME_DIR/$Waylandsocket'"
+    echo "  echo 'ls -la \$XDG_RUNTIME_DIR/$Waylandsocket'"
   }
   [ "$Setwaylandenv" = "yes" ] && {
     for Line in $Waylandtoolkitenv ; do echo "  echo export $Line" ; done
@@ -3879,7 +3838,7 @@ start() {
   echo "  echo 'export TERM=xterm'"
   echo "  echo ''"
 
-  echo "  echo '[ -e /tmp/x11docker.LANG ] && export LANG=\$(cat /tmp/x11docker.LANG) '"
+  echo "  echo '[ -e /x11docker.LANG ] && export LANG=\$(cat /x11docker.LANG) '"
   echo "  echo ''"
   
   [ "$Pulseaudio" = "yes" ] && echo "  echo 'export $Pulseserver'"
@@ -3921,6 +3880,7 @@ start() {
   echo "  sleep 0.2"
   echo "  docker exec $Containername sh -c : && { echo 'x11docker: container is up and running.' ; break ; } || echo \"x11docker: container not ready on \$Count. attempt, trying again.\" "
   echo "done"
+  echo "cat $Dockerlogfile | grep 'Error response from daemon'"  # repeat possible error message to make it visible in error() after verbose Count loop
   echo ""
   [ "$Initsystem" = "systemd" ] && echo "mkdir -v -p /sys/fs/cgroup/systemd   # make sure this folder exists on non-systemd hosts, too" 
   
@@ -4621,4 +4581,58 @@ $(tail $Compositorlogfile)"
     ;;
   esac
   exit 0 # trap to finish()
+}
+
+######### ToDo notes for development
+todo() {
+# work on traperror()
+#
+# --dbus-system: policykit must not have no-new-privileges. Seems to use setuid? Core issue AccountsService?
+#                starting polkitd and accounts-daemon in setupscript helps:
+#                -> cinnamon starts up with lots of (harmless?) error messages
+#                -> deepin needs --pulseaudio again
+# --wayland --dbus-system GTK3 seems to work now!?
+# check fgconsole
+# bestwu/deepin: why sh is replaced by bash?
+# BUG opensuse/arch: issues with x11docker/fluxbox, background missing, sometimes no context menu. where is the difference?
+# check echo especially in sh scripts, replace with printf if needed (#25)
+# avoid possible confusions --home --sharedir. --sharedir mounts can overlap --home folder. What about softlinks with existing target in --home? Maybe avoid /home/$USER at all
+# check out possibilities to allow 'sudo docker' directly again.
+# xpra restart on tty switch -> bug report
+# --xpra --desktop restarts client if closing desktop window
+
+# --lang: find out locale package names for several distris for documentation
+# --keymap does not work on tty with --kwin and --kwin-xwayland. No idea how to set it.
+# further check of xpra server crashes with jess/atom and chromium. --mmap=no avoids the bug: xpra bug report?
+
+# BUG check whether VT is not in use with --xorg/--xpra/--xdummy, bug if accidently using vt that is already in use
+# check all FIXME 
+# note: SYS_PTRACE allows polkit in docker
+# --systemd: try to avoid xhost +SI:localuser:$Benutzer
+# --xpra-xwayland, xdummy-xwayland: use kwin-wayland as fallback for missing weston? 
+# --xorg: getty and autologin to avoid Xwrapper.config changes?
+# gnome3 based desktop failing due to gnome bugs: pantheon budgie gnome3
+# check Xorg version for +iglx, check security implications, maybe option --iglx?
+# GTK3 in Wayland: --dbus once worked with $Dbusdaemon=yes
+# --wayland --user/--hostuser: wayland socket access denied due to XDG_RUNTIME_DIR
+# --nxagent 3.5.0: Mageia 6: seamless mode fails
+# fedora: SElinux issue: '--security-opt label=type:container_runtime_t': need more restrictive setting
+#         https://unix.stackexchange.com/questions/386767/selinux-and-docker-allow-access-to-x-unix-socket-in-tmp-x11-unix
+# multimonitor support for --scale and --size
+# check current multimonitor behaviour for weston on tty
+# --xdummy --gpu on tty allows real resolutions only
+# --xorg: check custom systemd start of X #7
+# check X in container #7
+# some tests with Xephyrglamor=no
+
+### BUG collection: non x11docker bugs
+# BUG Xwayland does not always sit at 0:0 on multiple outputs. 
+#     bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1498665
+# BUG nxagent with x11docker/lxde: segmentation fault of lxpanel with --userns-remap. bug in nxagent, lxpanel or x11docker?
+# BUG --kwin*: wrong fullscreen and crashes in gnome-wayland, strange in weston, WAYLAND_DISPLAY="" does not help, probably bug in kwin
+# BUG scale>1 Xwayland in Weston is too large (Xwayland bug), rendering issues on tty (switching scaled/unscaled Xwayland on keyboard/mouse events) 
+#     bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1498669
+# BUG x11docker-gui in weston freezes weston in combo boxes. Weston bug ? QT3/4 bug?
+# BUG debian bug report lightdm/sddm contra gdm, dm can crash on tty switch if multiple graphical sessions are running
+  :
 }
