--gpu: some NVIDIA messages.

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -795,6 +795,19 @@ rmcr() {                        # remove carriage return to translate DOS/Window
     *)  sed -i "s/$(printf "\r")//g"  "${1:-}"
   esac
 }
+download() {                    # download file at URL $1 and store it in file $2
+  # Uses wget or curl. If both are missing, returns 1. Follows redirects. 
+  # With no arguments it checks for curl/wget only.
+  local Downloader=
+  command -v wget >/dev/null && Downloader="wget"
+  command -v curl >/dev/null && Downloader="curl"
+  [ "$Downloader" ] || return 1
+  [ "${1:-}" ] || return 0
+  case $Downloader in
+    wget) wget "${1:-}" -O "${2:-}" ;;
+    curl) curl -L "${1:-}" --output "${2:-}" ;;
+  esac
+}
 
 #### file routines
 waitforfilecreation() {         # similar to inotify-wait: wait up to 15s for file $1 to be created
@@ -1048,20 +1061,20 @@ installer() {                   # --install, --update, --update-master, --remove
 
       [ -d /tmp/x11docker-install ] && rm -R /tmp/x11docker-install
       mkdir -p /tmp/x11docker-install && cd /tmp/x11docker-install || error "Could not create or cd to /tmp/x11docker-install"
-      command -v wget >/dev/null  || error "wget not found. Need 'wget' for download.
-  Please install wget."
+      download || error "Neither wget nor curl found. Need 'wget' or 'curl'for download.
+  Please install wget or curl."
       command -v unzip >/dev/null || error "Can not unpack archive. Please install 'unzip'."
 
       case ${1:-} in
         --update-master)
           note "Downloading latest x11docker master version from github"
-          wget https://github.com/mviereck/x11docker/archive/master.zip -O x11docker-update.zip || error "Could not download x11docker-master from github"
+          download "https://codeload.github.com/mviereck/x11docker/zip/master" "x11docker-update.zip" || error "Could not download x11docker-master from github"
         ;;
         --update)
-          wget https://raw.githubusercontent.com/mviereck/x11docker/master/CHANGELOG.md || error "Could not download CHANGELOG.md from github."
+          download "https://raw.githubusercontent.com/mviereck/x11docker/master/CHANGELOG.md" "CHANGELOG.md" || error "Could not download CHANGELOG.md from github."
           Releaseversion="v$(cat CHANGELOG.md | grep "## \[" | grep -v 'Unreleased' | head -n1 | cut -d[ -f2 | cut -d] -f1)"
           note "Downloading latest x11docker release $Releaseversion from github"
-          wget "https://github.com/mviereck/x11docker/archive/$Releaseversion.zip" -O x11docker-update.zip || error "Could not download latest x11docker release from github"
+          download "https://github.com/mviereck/x11docker/archive/$Releaseversion.zip" "x11docker-update.zip" || error "Could not download latest x11docker release from github"
         ;;
       esac
 
@@ -1754,6 +1767,18 @@ check_xserver() {               # check chosen X server, auto-choose X server
     [ "$Winsubsystem" = "CYGWIN" ]                               && Xserver="--xwin"
     [ "$Sharewayland" = "yes" ] && { [ -n "$Hostwaylandsocket" ] && [ "$Desktopmode" = "no" ] && Xserver="--hostwayland" || Xserver="--weston" ; }
   }
+  
+  [ -e "/proc/driver/nvidia" ] && [ "$Sharegpu" = "yes" ] && case $Xserver in
+    --hostdisplay|--xorg) ;;
+    *)
+      { [ "$Desktopmode" = "yes" ] || [ "$Windowmanager" ] ; } && Xserver="--xorg" || Xserver="--hostdisplay"
+      warning "Option --gpu: Hardware acceleration with closed source 
+  NVIDIA drivers only works for options --hostdisplay and --xorg.
+  Consider to use free open source nouveau driver instead.
+  Fallback: using X server option $Xserver."
+      Autochooseserver="no"
+    ;;
+  esac
 
   [ "$Sharegpu" = "yes" ] && case $Xserver in
     --xpra)
@@ -5655,6 +5680,12 @@ option_messages() {             # some messages depending on options, but not ch
   If application startup fails, try --weston instead."
     ;;
   esac
+  
+  # NVIDIA without --gpu
+  [ -e "/proc/driver/nvidia" ] && [ "$Sharegpu" = "no" ] && case $Xserver in
+    --hostdisplay|--xorg) note "Option $Xserver may fail with proprietary NVIDIA driver
+  on host. In that case try other X server options like --xpra or --xephyr." ;;
+  esac
 
   # --fullscreen
   [ "$Fullscreen" = "yes" ] && {
@@ -6536,7 +6567,6 @@ main "$@"
   
 #### ToDo notes for development
 todo() {
-# move containersubshell to xinitrc?
 # further checks of pam.d
 
 # --xonly: not default for empty x11docker image name?
@@ -6565,7 +6595,7 @@ todo() {
 # check xhost +localhost
 # BUG error message window in wayland fails: xterm: no display. should use konsole
 # x11docker-gui: menu entry management? persistant command storage?
-# --update: regard possible location in /opt
+# --update: regard possible location in /opt?
 # BUG?: x11docker/xwayland nested: where is the X socket ??
 
 # --weston/x: allow tty switch/option --vt if running as root?
