--backend=proot: improvements

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -5632,22 +5632,14 @@ Exec=/usr/local/bin/x11docker-xrandr
     echo "} || note 'Failed to add container user to group $Line.'"
     echo ""
   done
-
-  # HOME
-  case $Backend in
-    proot) ;;
-    *)
-      echo "# Create HOME"
-      echo '[ -e "$Containeruserhome" ] || {'
-       #echo '  mkdir -v -p "$(dirname "$Containeruserhome")"'
-      echo '  mkdir -v -p -m 777 "$Containeruserhome"'
-      echo '  chown -v "$Containeruser":"$Containerusergroup" "$Containeruserhome" && chmod -v 755 "$Containeruserhome"  # can fail depending on capabilities'
-      echo '}'
-      #echo "chown \$Containeruser:\$(id -g \$Containeruser) \"\$Containeruserhome\""
-      echo "ls -la \$Containeruserhome"
-      echo ""
-    ;;
-  esac
+  
+  echo "# Create HOME"
+  echo '[ -e "$Containeruserhome" ] || {'
+  echo '  mkdir -v -p -m 777 "$Containeruserhome"'
+  echo '  chown -v "$Containeruser":"$Containerusergroup" "$Containeruserhome" && chmod -v 755 "$Containeruserhome"  # can fail depending on capabilities'
+  echo '}'
+  echo "ls -la \$Containeruserhome"
+  echo ""
 
   # --gpu with closed source nvidia driver
   [ "$Nvidiainstallerfile" ] && nvidia_installer
@@ -6310,15 +6302,6 @@ Containeruseruid=\$(id -u \$Containeruser)
 export XDG_RUNTIME_DIR=/tmp/XDG_RUNTIME_DIR
 [ -e /run/user/\$Containeruseruid ] && ln -s /run/user/\$Containeruseruid \$XDG_RUNTIME_DIR || mkdir -p -m700 \$XDG_RUNTIME_DIR
 "
-
-
-    case $Backend in
-      proot)
-        echo "ls -l /home"
-        echo "mkdir -p -v \$HOME" 
-        echo "ls -l /home"
-      ;;
-    esac
 
     # softlinks from shared folders to HOME
     [ "$Persistanthomevolume" != "$Containeruserhosthome" ] && { # not for --home=$HOME
@@ -7421,10 +7404,12 @@ check_option_interferences() {  # check multiple option interferences, change se
   Though, these are still within nerdctl default capabilities."
     ;;
     proot)
-      warning "Option --backend=proot: Your hosts system is NOT PROTECTED at all.
+      warning "Option --backend=proot: Your host system is NOT PROTECTED.
   There is close to no isolation like a container could provide.
   Setting security related options like --cap-default might lead to
-  (wrong) x11docker messages but won't change the proot setup."
+  (wrong) x11docker messages but won't change the proot setup.
+  Effectively applications in proot have the same privileges
+  as if they would have been installed and run on the host system."
       Switchcontaineruser="yes"
       [ "$Shareipc" != "no" ] && Shareipc="host" && note "Option --backend=proot: IPC settings are not possible."
       case "$Network" in
