--password: check early before other checks #334

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -11,7 +11,7 @@
 # Run 'x11docker --help' or scroll down to read usage information.
 # More documentation at:  https://github.com/mviereck/x11docker
 
-Version="6.7.1-beta-6"
+Version="6.7.1-beta-7"
 
 # --enforce-i: Enforce running in interactive mode to allow commands tty and weston-launch in special setups.
 grep -q -- "--enforce-i" <<< "$*" && case $- in
@@ -1130,6 +1130,7 @@ mkfile() {                      # create file $1 owned by $Hostuser
   return 0
 }
 myrealpath() {                  # real path of possible symlink
+  [ -z "$@" ] && return 1
   command -v realpath >/dev/null && {
     realpath "$@"
   } || {
@@ -4023,21 +4024,6 @@ check_containeruser() {         # check container user and shared home folder (a
     Sudouser="${Sudouser:-yes}" && note "Option --user=root: Enabling option --sudouser."
   }
   
-  # --password
-  [ -n "$Containeruserpassword" ] && {
-    command -v perl >/dev/null || error "Option --password: command 'perl' not found.
-  perl is needed to generate an encrypted password."
-    [ "$Containeruserpassword" = "INTERACTIVE" ] && {
-      read -rs -p "Please type in a new container user password (chars are invisible): " Containeruserpassword
-      [ -z "$Containeruserpassword" ] && error "Empty input, password not changed."
-    }
-    Containeruserpassword="$(perl -e "print crypt(\"$Containeruserpassword\", \"salt\")")"
-    mkdir -p "$(dirname "$Passwordfile")"
-    echo "$Containeruserpassword" > "$Passwordfile"
-    chmod 600                       "$Passwordfile"
-    note "Option --password: Password changed, exiting."
-    finish
-  }
   [ -f "$Passwordfile" ] && {
     verbose "Found password file $Passwordfile"
     Containeruserpassword="$(cat "$Passwordfile")"
@@ -7545,7 +7531,6 @@ check_runmode() {               # check run/--exe/--xonly
       Runsinsnap="no"
     ;;
   esac
-  
   Codename="$(unspecialstring "$Codename" | cut -c1-40)"
   Codename="${Codename:-noname}"
   Imagebasename="$(unspecialstring "$Imagebasename")"  # must be - for backwards compatibility of --home
@@ -8836,6 +8821,22 @@ main() {
   
   declare_variables
   parse_options "$@"
+  
+  [ -n "$Containeruserpassword" ] && {                                            # --password
+    command -v perl >/dev/null || error "Option --password: command 'perl' not found.
+  perl is needed to generate an encrypted password."
+    [ "$Containeruserpassword" = "INTERACTIVE" ] && {
+      read -rs -p "Please type in a new container user password (chars are invisible): " Containeruserpassword
+      echo ""
+      [ -z "$Containeruserpassword" ] && error "Empty input, password not changed."
+    }
+    Containeruserpassword="$(perl -e "print crypt(\"$Containeruserpassword\", \"salt\")")"
+    mkdir -p "$(dirname "$Passwordfile")"
+    echo "$Containeruserpassword" > "$Passwordfile"
+    chmod 600                       "$Passwordfile"
+    note "Option --password: Password changed, exiting."
+    finish
+  }
 
   [ "$Silent" = "yes" ]    && exec {FDstderr}>/dev/null                           # --quiet
   [ "$Debugmode" = "yes" ] && {                                                   # --debug
