--install/--update: some fixes

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1487,17 +1487,10 @@ installer() {                   # --install, --update, --update-master, --remove
     --update|--update-master|--remove)
       grep -q x11docker <<< "$0" && {
         Binpath="$(dirname "$0")"
+        [ -d "$Binpath/.git" ] && Binpath="/usr/bin"
         Binpath="$(myrealpath "$Binpath")"
-        Binowner="$(stat -c '%U' "$0")"
-        Bingroup="$(stat -c '%G' "$0")"
-        [ -d "$Binpath/.git" ] && {
-          error "Option ${1:-}: It seems you are within a git directory.
-  Use 'git pull' to update your local git repository.
-  Otherwise, run 'x11docker --install' first
-  before running 'x11docker ${1:-}'
-  so to use a system installation of x11docker."
-          return 1
-        }
+        Binowner="$(stat -c '%U' "$Binpath/x11docker")"
+        Bingroup="$(stat -c '%G' "$Binpath/x11docker")"
       }
     ;;
   esac
@@ -1512,7 +1505,10 @@ installer() {                   # --install, --update, --update-master, --remove
       CYGWIN|MSYS2) ;;
       *) 
         case "$Binowner" in
-          root) error "Must run as root to install, update or remove x11docker system wide." ; return 1 ;;
+          root) 
+            error "Must run as root to install, update or remove x11docker system wide."
+            return 1 
+          ;;
           *) warning "Option ${1:-}: Not running as root.
   Installing or updating non-essential files in system wide folders might fail." ;;
         esac
@@ -1523,11 +1519,16 @@ installer() {                   # --install, --update, --update-master, --remove
   # Preparing
   case ${1:-} in
     --install)
-      [ -f "./x11docker" ]             || { error "File x11docker not found in current folder.
-  Try 'x11docker --update' instead." ; return 1 ; }
-      command -v x11docker > /dev/null && { warning "x11docker seems to be installed already.
+      [ -f "./x11docker" ]             || {
+        error "File x11docker not found in current folder.
+  Try 'x11docker --update' instead."
+        return 1
+      }
+      command -v x11docker > /dev/null && { 
+        warning "x11docker seems to be installed already.
   Will overwrite existing installation.
-  Consider to use option '--update' or '--update-master' instead." ; }
+  Consider to use option '--update' or '--update-master' instead." 
+      }
     ;;
     --update|--update-master)
       grep -q x11docker <<< "$0" && {
@@ -1538,23 +1539,41 @@ installer() {                   # --install, --update, --update-master, --remove
       }
 
       [ -d /tmp/x11docker-install ] && rm -R /tmp/x11docker-install
-      mkdir -p /tmp/x11docker-install && cd /tmp/x11docker-install || { error "Could not create or cd to /tmp/x11docker-install." ; return 1 ; }
-      download || error "Neither wget nor curl found. Need 'wget' or 'curl' for download.
+      mkdir -p /tmp/x11docker-install && cd /tmp/x11docker-install || { 
+        error "Could not create or cd to /tmp/x11docker-install."
+        return 1
+      }
+      download || {
+        error "Neither wget nor curl found. Need 'wget' or 'curl' for download.
   Please install wget or curl."
+        return 1
+      }
       command -v unzip >/dev/null && Format="zip"
       command -v tar >/dev/null   && Format="tar.gz"
-      [ "$Format" ] || { error "Cannot extract archive. Please install 'unzip' or 'tar'." ; return 1 }
+      [ "$Format" ] || { 
+        error "Cannot extract archive. Please install 'unzip' or 'tar'."
+        return 1
+      }
 
       case ${1:-} in
         --update-master)
           note "Downloading latest x11docker master version from github."
-          download "https://codeload.github.com/mviereck/x11docker/$Format/master" "x11docker-update.$Format"           || error "Failed to download x11docker from github."
+          download "https://codeload.github.com/mviereck/x11docker/$Format/master" "x11docker-update.$Format"           || {
+            error "Failed to download x11docker from github."
+            return 1
+          }
         ;;
         --update)
-          download "https://raw.githubusercontent.com/mviereck/x11docker/master/CHANGELOG.md" "CHANGELOG.md"            || error "Failed to download CHANGELOG.md from github."
+          download "https://raw.githubusercontent.com/mviereck/x11docker/master/CHANGELOG.md" "CHANGELOG.md"            || {
+            error "Failed to download CHANGELOG.md from github."
+            return 1
+          }
           Releaseversion="v$(cat CHANGELOG.md | grep "## \[" | grep -v 'Unreleased' | head -n1 | cut -d[ -f2 | cut -d] -f1)"
           note "Downloading latest x11docker release $Releaseversion from github."
-          download "https://codeload.github.com/mviereck/x11docker/$Format/$Releaseversion" "x11docker-update.$Format"  || error "Failed to download x11docker from github."
+          download "https://codeload.github.com/mviereck/x11docker/$Format/$Releaseversion" "x11docker-update.$Format"  || {
+            error "Failed to download x11docker from github."
+            return 1
+          }
         ;;
       esac
 
@@ -1562,9 +1581,15 @@ installer() {                   # --install, --update, --update-master, --remove
       case $Format in
         zip)    unzip   "x11docker-update.$Format" ;;
         tar.gz) tar xzf "x11docker-update.$Format" ;;
-      esac || error "Failed to extract $Format archive."
+      esac || {
+        error "Failed to extract $Format archive."
+        return 1
+      }
       echo ""
-      cd /tmp/x11docker-install/$(ls -l | grep drwx | rev | cut -d' ' -f1 | rev) || error "Could not cd to /tmp/x11docker-update/$(ls -l | grep drwx | rev | cut -d' ' -f1 | rev)"
+      cd /tmp/x11docker-install/$(ls -l | grep drwx | rev | cut -d' ' -f1 | rev) || {
+        error "Could not cd to /tmp/x11docker-update/$(ls -l | grep drwx | rev | cut -d' ' -f1 | rev)"
+        return 1
+      }
     ;;
   esac
 
@@ -1572,8 +1597,14 @@ installer() {                   # --install, --update, --update-master, --remove
   case ${1:-} in
     --install|--update|--update-master)
       note "Installing x11docker in $Binpath"
-      cp x11docker "$Binpath/"                                                || error "Could not copy x11docker to $Binpath"
-      chmod 755 "$Binpath/x11docker"                                          || error "Could not set executable bit on x11docker"
+      cp x11docker "$Binpath/"                                                || {
+        error "Could not copy x11docker to $Binpath"
+        return 1
+      }
+      chmod 755 "$Binpath/x11docker"                                          || {
+        error "Could not set executable bit on x11docker"
+        return 1
+      }
       chown "$Binowner:$Bingroup" "$Binpath/x11docker"                        || warning "Could not set ownership '$Binowner:$Bingroup' to '$Binpath/x11docker'"
 
       note "Installing icon for x11docker with xdg-icon-resource"
@@ -2232,12 +2263,18 @@ set_password() {                # option --password: set container user password
   
   Password="${1:-}"
 
-  command -v perl >/dev/null || error "Option --password: command 'perl' not found.
+  command -v perl >/dev/null || {
+    error "Option --password: command 'perl' not found.
   perl is needed to generate an encrypted password."
+    return 1
+  }
   [ "$Password" = "INTERACTIVE" ] && {
     read -rs -p "Please type in a new container user password (chars are invisible): " Password
     echo ""
-    [ -z "$Password" ] && error "Empty input, password not changed."
+    [ -z "$Password" ] && {
+      error "Empty input, password not changed."
+      return 1
+    }
   }
   Password="$(perl -e "print crypt(\"$Password\", \"salt\")")"
   mkdir -p "$(dirname "$Passwordfile")"
