V3.5.11 pull image if not available before calling 'docker run'
# 12.07.2017 V3.5.11 pull image if not available before calling 'docker run'

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -7,7 +7,7 @@
 # Type 'x11docker --help' or scroll down to read usage information.
 # https://github.com/mviereck/x11docker
 
-Version="3.5.10"
+Version="3.5.11"
 
 changelog() {
 ### ToDo:
@@ -32,6 +32,7 @@ changelog() {
 # BUG debian bug report lightdm/sddm contra gdm, dm can crash on tty switch if multiple graphical sessions are running
 
 # x11docker changelog
+# 12.07.2017 V3.5.11 pull image if not available before calling 'docker run'
 # 12.07.2017 V3.5.10 regard ENTRYPOINT in dockerrc
 # 09.07.2017 V3.5.9  --user: bugfix parsing custom gid, gid was set to username
 #                    --home with --user=(unknown): only show warning (instead of error) not creating persistent home
@@ -2306,7 +2307,12 @@ esac
   echo "#! /bin/bash"
   declare -f warning
   echo "Imagecommand='$Imagecommand'"
-  echo "[ -z \"\$Imagecommand\" ] && {"
+  echo "Imagename='$Imagename'"
+  echo "# check if image is available locally"
+  echo "docker inspect --type=image $Imagename > /dev/null || {"
+  echo "  warning 'Image $Imagename not found locally. Will try to pull it'"
+  echo "  docker pull $Imagename"
+  echo "}"  echo "[ -z \"\$Imagecommand\" ] && {"
   echo "  # extract image command from image if not given on cli"
   echo "  Imagecommand=\$(docker inspect --format='{{.Config.Cmd}}' $Imagename)"
   echo "  Imagecommand=\${Imagecommand#[}"
