fix for /etc/localtime if missing in container

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1073,7 +1073,7 @@ waitforlogentry() {             # wait for entry $3 in logfile $2 of application
   Startzeit="${Startzeit:-0}"
   [ "$Warten" = "infinity" ] && Warten=32000
 
-  debugnote "waitforlogentry(): ${1:-}: Waiting for logentry \"${3:-}\" in $(basename ${2:-})."
+  debugnote "waitforlogentry(): ${1:-}: Waiting for logentry \"${3:-}\" in $(basename ${2:-})"
   
   while ! grep -q "${3:-}" <"${2:-}" ; do
     Count="$(( $Count + 1 ))"
@@ -1084,15 +1084,15 @@ waitforlogentry() {             # wait for entry $3 in logfile $2 of application
     [ "$Schlaf" = "0" ] && Schlaf="0.5"
     mysleep "$Schlaf"
     
-    [ "$Dauer" -gt "10" ] && debugnote "waitforlogentry(): ${1:-}: Waiting since ${Dauer}s for log entry \"${3:-}\" in $(basename ${2:-})."
+    [ "$Dauer" -gt "10" ] && debugnote "waitforlogentry(): ${1:-}: Waiting since ${Dauer}s for log entry \"${3:-}\" in $(basename ${2:-})"
     
-    [ "$Dauer" -gt "$Warten" ] && error "waitforlogentry(): ${1:-}: Timeout waiting for log entry \"${3:-}\" in $(basename ${2:-}).
+    [ "$Dauer" -gt "$Warten" ] && error "waitforlogentry(): ${1:-}: Timeout waiting for log entry \"${3:-}\" in $(basename ${2:-})
   Last lines of logfile $(basename ${2:-}):
 $(tail "${2:-}")"
     
 #    grep -i -q -E 'xinit: giving up|unable to connect to X server|Connection refused|server error|Only console users are allowed|Failed to process Wayland|failed to create display|] fatal:' <"${2:-}" && \
     [ "$Errorkeys" ] && grep -i -q -E "$Errorkeys" <"${2:-}" && \
-      error "waitforlogentry(): ${1:-}: Found error message in logfile:
+      error "waitforlogentry(): ${1:-}: Found error message in logfile.
   Last lines of logfile $(basename ${2:-}):
 $(tail "${2:-}")"
 
@@ -3300,7 +3300,6 @@ create_xinitrc() {              # create xinitrc: set up X environment, create c
 
       [ "$Xauthentication" = "yes" ] && {
         echo         "# create new XAUTHORITY cookies"
-        echo         "cd $Sharefolder"
         echo         ":> $Xclientcookie"
         echo         ""
         [ "$Xserver" = "--nxagent" ] && {
@@ -3580,7 +3579,7 @@ check_containerhome() {         # options --home, --homedir, --homebasedir: chec
   ## option '--homebasedir': Specify base folder here to store container home folders for --home
   
   # base home folder
-  [ "$Homebasefolder" ] && {
+  [ "$Homebasefolder" ] && {                # --homebasedir
     Homebasefolder="$(convertpath subsystem "$Homebasefolder")"
     [ -e "$Homebasefolder" ] || {
       warning "Option --homebasedir: Specified path does not exist:
@@ -3591,7 +3590,7 @@ check_containerhome() {         # options --home, --homedir, --homebasedir: chec
   }
   [ "$Homebasefolder" ] || case $Winsubsystem in
     "") Homebasefolder="$Containeruserhome/.local/share/x11docker" ;;
-    *)  Homebasefolder="$(convertpath subsystem "$(wincmd '/C "echo %userprofile%"' | rmcr)")/x11docker/home" ;;
+    *)  Homebasefolder="$(convertpath subsystem "$(wincmd '/C "echo %userprofile%"') ")/x11docker/home" ;;
   esac
   
   [ "$Sharehosthome" = "yes" ] && {
@@ -4282,12 +4281,12 @@ create_containerrootrc() {      ### create containerrootrc: This script runs as 
   echo ""
 
   echo "# Time zone"
-  [ "$Hostlocaltime" ] && {
+  [ "$Hostlocaltimefile" ] && {
     echo '[ ! -d /usr/share/zoneinfo ] && [ "$Containerlibc" = "'$Hostlibc'" ] && {'
-    echo "  mkdir -p $(dirname $Hostlocaltime)"
-    echo "  cp '$Cshare/timezone'  '$Hostlocaltime'"
+    echo "  mkdir -p $(dirname $Hostlocaltimefile)"
+    echo "  cp '$(convertpath share $Containerlocaltimefile)' '$Hostlocaltimefile'"
     echo "}"
-    echo "[ -e '$Hostlocaltime' ] && ln -f -s '$Hostlocaltime' /etc/localtime"
+    echo "[ -e '$Hostlocaltimefile' ] && ln -f -s '$Hostlocaltimefile' /etc/localtime"
     echo ""
   }
 
@@ -5381,7 +5380,7 @@ create_dockerrc() {             ### create dockerrc: This script runs as root (o
 
   echo     "  echo 'storeinfo test locale && export LANG=\"\$(storeinfo dump locale)\"'"
 
-  echo     "  echo '[ -e \"$Hostlocaltime\" ] || export TZ=$Hostutctime'"
+  echo     "  echo '[ -e \"$Hostlocaltimefile\" ] || export TZ=$Hostutctime'"
   echo     "  echo '[ \"\$(date -Ihours)\" != \"$(date -Ihours)\" ] && export TZ=$Hostutctime'"
 
   echo     "  echo '[ \"\$DEBIAN_FRONTEND\" = noninteractive ] && unset DEBIAN_FRONTEND && export DEBIAN_FRONTEND'"
@@ -5735,7 +5734,6 @@ start_hostexe() {               # options --exe, --xonly: Run host executeable i
     done < <(store_runoption dump env | grep -v XAUTHORITY | grep -v XDG_RUNTIME_DIR)
     echo ""
     
-    
     echo "env >> $Containerenvironmentfile"
     echo "verbose \"Container environment:"
     echo "\$(env | sort)\""
@@ -5748,6 +5746,7 @@ start_hostexe() {               # options --exe, --xonly: Run host executeable i
     echo ""
     
     echo "storeinfo test tini && Tini=\"\$(storeinfo dump tini) -s --\" || Tini=''"
+    echo ""
     
     echo "# close additional file descriptors"
     echo "for i in 3 4 6 7 8 9; do"
@@ -5785,30 +5784,28 @@ start_xpra() {                  # options --xpra / --xpra-xwayland: start and wa
   Xpraserverpid=$!
   storepid $! xpraserver
   verlt "$Xprarelease" "r23060" && waitforlogentry "xpra server" $Xpraserverlogfile 'xpra is ready' 
-  rocknroll || return 1
+  rocknroll || return 64
   
   debugnote "Running Xpra client"
   
   echo "x11docker [$(timestamp)]: Starting Xpra client" >> $Xpraclientlogfile
-  #  
-  unpriv "env $Hostxenv NO_AT_BRIDGE=1 XPRA_EXPORT_ICON_DATA=0 XPRA_ICON_OVERLAY=0 XPRA_MENU_ICONS=0 $(verlt $Xpraversion v2.1 && echo XPRA_OPENGL_DOUBLE_BUFFERED=1)   $Xpraclientcommand" >> $Xpraclientlogfile 2>&1 & 
+  unpriv "env $Hostxenv NO_AT_BRIDGE=1 XPRA_EXPORT_ICON_DATA=0 XPRA_ICON_OVERLAY=0 XPRA_MENU_ICONS=0 $(verlt $Xpraversion v2.1 && echo XPRA_OPENGL_DOUBLE_BUFFERED=1) $Xpraclientcommand" >> $Xpraclientlogfile 2>&1 & 
   Xpraclientpid=$!
   storepid $! xpraclient
 
-  { # catch possible xpra crashes
-    while rocknroll; do
-      ps -p $Xpraserverpid >/dev/null || break
-      ps -p $Xpraclientpid >/dev/null || break
-      sleep 1
-    done
-    sleep 1 && rocknroll && note "Option $Xserver: xpra terminated unexpectedly.
+  # catch possible xpra crashes
+  while rocknroll; do
+    ps -p $Xpraserverpid >/dev/null || break
+    ps -p $Xpraclientpid >/dev/null || break
+    sleep 1
+  done
+  sleep 1 && rocknroll && note "Option $Xserver: xpra terminated unexpectedly.
   Last lines of xpra server log:
 $(tail $Xpraserverlogfile)
 ---------------------------------
   Last lines of xpra client log:
 $(tail $Xpraclientlogfile)"
-    saygoodbye xpra
-  }
+  saygoodbye xpra
   
   return 0
 }
@@ -5849,7 +5846,8 @@ check_host() {                  # check host environment
   ldd --version 2>&1 | grep -q -E 'GLIBC|GNU libc'  && Hostlibc='glibc'
   
   # Check host time zone
-  Hostlocaltime="$(myrealpath /etc/localtime)"      # Find time zone file in /usr/share/zoneinfo
+  Hostlocaltimefile="$(myrealpath /etc/localtime)"      # Find time zone file in /usr/share/zoneinfo
+  [ -e "$Hostlocaltimefile" ] || Hostlocaltimefile=""
   Hostutctime=$(date +%:::z)                        # Offset of UTC. Used if time zone file cannot be provided
   [ "$(cut -c1 <<< "$Hostutctime")" = "+" ] && {
     Hostutctime="UTC-$(cut -c2- <<< "$Hostutctime")"
@@ -6881,6 +6879,7 @@ create_cachefiles() {           # create empty cache files owned by unprivileged
   Cmdstdoutlogfile="$Sharefolder/$Cmdstdoutlogfile"                 && mkfile $Cmdstdoutlogfile 666
   Containerrc="$Sharefolder/$Containerrc"                           && mkfile $Containerrc
   Containerenvironmentfile="$Sharefolder/$Containerenvironmentfile" && mkfile $Containerenvironmentfile 666
+  Containerlocaltimefile="$Sharefolder/$Containerlocaltimefile"
   Containerlogfile="$Sharefolder/$Containerlogfile"                 && mkfile $Containerlogfile 666
   Containerrootrc="$Sharefolder/$Containerrootrc"                   && mkfile $Containerrootrc
   Logfile="$Sharefolder/x11docker.log"                              && mkfile $Logfile
@@ -6903,6 +6902,9 @@ create_cachefiles() {           # create empty cache files owned by unprivileged
     [ "$Line" != "$Numbersinusefile" ] && rm "$Line"
   done
   [ -e "$Numbersinusefile" ] || mkfile "$Numbersinusefile"
+  
+  # libc timezone file
+  [ -e "$Hostlocaltimefile" ] && cp "$Hostlocaltimefile" "$Containerlocaltimefile"
   
   storeinfo "cache=$Cachefolder"
   
@@ -7368,7 +7370,7 @@ declare_variables() {           # declare global variables
   Hosthidepid=""                                  # /proc is mounted with hidepid=2 yes/no. Seen on NixOS.
   Hostip=""                                       # An IP address to access host. Preferred: IP of docker daemon
   Hostlibc=""                                     # glibc or musl. Can be important for locale and timezone.
-  Hostlocaltime=""                                # Time zone from host, myrealpath /etc/localtime
+  Hostlocaltimefile=""                            # Time zone from host, myrealpath /etc/localtime
   Hostmitshm="yes"                                # X on host has extension MIT-SHM enabled yes/no. Assume yes, check later
   Hostsystem=""                                   # $ID from /etc/os-release
   Hostutctime=""                                  # Time zone from host as offset to UTC
@@ -7494,6 +7496,7 @@ declare_variables() {           # declare global variables
   Containerenvironment=""                         # --env: Environment variables
   Containerenvironmentcount="0"
   Containerenvironmentfile="container.environment" # file to store final container environment
+  Containerlocaltimefile="libc.localtime"         # localtime file from host shared to container
   Containername=""                                # --name: Container name
   Customdockeroptions=""                          # -- [...] -- : Custom options for "docker run".
   Imagename=""                                    # Image to run
@@ -8102,15 +8105,15 @@ main "$@"
   
 #### ToDo notes for development
 todo() {
-  # BUG Cshare/timezone, something is wrong, no timezone file
   # replace find in containerrootrc, missing in fedora images
   # cleanup(): avoid hardcoded pathes
 
   # how to trigger elogind in alpine, su does not take effect. missing policykit?
   # support --exe --user ?
   # avoid loosing dockerstopshell from process tree
+  # avoid loosing hostexe from process tree
   # dockerstopshell does not react if fifofile is deleted.
-  # reduce number of variables with storeinfo() ?
+  # reduce number of variables with storeinfo()
   # check systemd warnings on x11docker services
     
   # bug report startplasmacompositor: --libinput
