finish(): remove container with docker rm instead of option --rm

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -603,6 +603,12 @@ finish() {                      # trap EXIT routine to clean up background proce
     } || debugnote "finish(): Container terminated successfully"
   }
   
+  # remove container
+  [ "$Preservecachefiles" = "no" ] && [ "$Containername" ] && {
+    debugnote "Removing container $Containername"
+    $Dockerexe rm -f "$Containername" || error "Failed to remove container $Containername"
+  }
+
   # Check if 'docker logs' is still running
   [ "$FDdockerstop" ] && {
     checkpid $Dockerlogspid      && echo "stop" >&${FDdockerstop}
@@ -3970,8 +3976,8 @@ create_dockercommand() {        ### create command to run docker
   local Line= Memory Tini=
   
   Dockercommand="$Dockerexe run --tty"
-  Wmdockercommand="$Dockerexe run --rm --detach"
-  [ "$Preservecachefiles" = "no" ] && Dockercommand="$Dockercommand --rm"
+  Wmdockercommand="$Dockerexe run --detach"
+  #[ "$Preservecachefiles" = "no" ] && Dockercommand="$Dockercommand --rm"
   case $Interactive in
     yes) Dockercommand="$Dockercommand --interactive" ;;
     no)  Dockercommand="$Dockercommand --detach" ;;
@@ -6783,7 +6789,7 @@ check_option_interferences() {  # check multiple option interferences, change se
         none|tini) ;;
         *) note "Option --no-setup: Option --init is not supported" ;;
       esac
-      Initsystem=""
+      Initsystem="none"
       Dbusrunsession="no"
       #Createcontaineruser="no"
       Langwunsch=""
@@ -8692,9 +8698,11 @@ $(nl -ba <$Dockerrc)"
     ## containerrootrc runs as root in container.
     # Main jobs: create unprivileged container user, disable possible privilege leaks, set local time.
     # Optional jobs: run init system, run DBus daemon, install nvidia driver, create language locale.
-    create_containerrootrc
-    verbose "Generated containerrootrc:
+    [ "$Containersetup" = "yes" ] && {
+      create_containerrootrc
+      verbose "Generated containerrootrc:
 $(nl -ba <$Containerrootrc)"
+    }
     create_xtermrc              # xtermrc to prompt for password if needed.
   }
   
